### ISSUE TITLE
jconfig not warning about same ipv6 address being used

### ISSUE THREAD

**Issue by palica** [cbsd/cbsd#104]
When I change configuration of a jail it warns me if the same ipv4 address is in use or on the network, but doesn't do it for ipv6 addresses. Would be nice to have.

Thanks

**Comment by olevole** [comment]
totally agree with you)

**Comment by olevole** [comment]
Fixed fix external ping6 utility: https://github.com/cbsd/cbsd/commit/369c54586aedeee7f71089f8ab817ad92a391d44

But i hope someday wrote *ndp* support to check via discovery protocol, due to ICMPv6 can blocked. 
It will be available in CBSD 11.0.5
