### ISSUE TITLE
Preferred method to proxy external traffic to different jails?

### ISSUE THREAD

**Issue by priyadarshan** [cbsd/cbsd#105]
I have successfully setup a jail with `cbsd`

```
root@kavi:~ # cbsd jls
JNAME  JID  IP4_ADDR     HOST_HOSTNAME    PATH                    STATUS
jail1  1    10.0.0.1/16  jail1.kavi.it  /usr/jails/jails/jail1  On
```

I have installed and started `nginx` in `jail1`, and I can see it working from outside the jail:
 
```
root@kavi:~ # fetch -o - http://10.0.0.1
-                                               0% of  612  B    0  Bps<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
-                                             100% of  612  B   10 MBps 00m00s
```

Now, I would like to connect to the `nginx` server inside jail1 from the internet.

I could perhaps do it by using another nginx install on the host, as a proxy.

But is there a `cbsd` preferred way to do that?

Would you advice for a more general proxy, like [haproxy](http://www.freshports.org/net/haproxy/)?

Also, what if one install a different service (ie, not port 80/443), that he needs to be reachable from the internet, like irc, postgresql, syncthing, etc.

Which would be the preferred way to do that?

Could you share some configuration one could customise?

Thank you so much for `cbsd`, it is a great tool.

**Comment by nopainnogainjoe** [comment]
I would recommend redirecting the traffic with PF.

**Comment by olevole** [comment]
in fact, I do not have great advice that it is better to use. Personally, I like to install nginx on hoster as belenser. But you can use haproxy or any other similar solution.

Regards CBSD features, you can use 

~~~
cbsd expose
~~~

For port forwarding from nodeip (usual external IP) into jail.

https://www.bsdstore.ru/en/11.0/wf_expose_ssi.html

For example, if you wish to forward http/https into nginx jail, use:
~~~
cbsd expose jname=nginx in=80
cbsd expose jname=nginx in=443
~~~

If destination port not same, add 'out=':

~~~
cbsd expose jname=nginx in=80 out=81
~~~


cbsd expose used **ipfw fwd** . As you pointed out, PF also good solution. But i not realized PF support for port forwarding at the moment

**Comment by srichinmoyarchivist** [comment]
@nopainnogainjoe Could you please show some examples using `pf` syntax?

For example, how to direct traffic from internet entering `em0` (for example, listening on 192.168.178.20), to jail1 listening on 10.0.0.1:

- for domain name `domain.com`
- for domain name 'domain.com:443' (https)
- for IRC server listening on port 6667/TCP, for domain irc.domain.com
- for a second IRC server listening on port 6668/TCP, for domain irc.domain2.com

Thank you!

**Comment by olevole** [comment]
I think, depending on the selected NAT framework ( ipfw, pf, ipfilter ) is good idea in **cbsd expose** create rule by corresponding framework. So, pf/ipfilter sample  interesting for me too ;)

**Comment by priyadarshan** [comment]
Thank you @olevole, I think PF does port forwarding (http://www.openbsd.org/faq/pf/rdr.html).

But how could one deal with domain names? Does  ipfw allow rules based on domain names?

As @srichinmoyarchivist mentioned, how could one redirect incoming traffic on port 80, but only the packets related to domain.net?

**Comment by olevole** [comment]
@priyadarshan  for domain-based redirect, only HTTP-balancer (haproxy, nginx, apache, lighthttp) can do this.

**Comment by priyadarshan** [comment]
Thanks, that helps. Then, to make things tidier, it would perhaps be better to use a general proxy server.
I would still be interested in `pf` rules, though, for those case were a jail ip:port would be enough.

Thank you. `cbsd` rocks.

**Comment by nopainnogainjoe** [comment]
pf.conf:

if="em0"
web="10.0.0.1"
www_port="80" # or www_ports="{ 80, 443}"
rdr pass on $if proto tcp from any to any port $www_port -> $web

**Comment by olevole** [comment]
@nopainnogainjoe  i've add this Issue in open state - sometimes i've add pf support for port forwarding via cbsd expose. At the moment, users can use 'expose' to create redirect by jail name:
~~~
% cbsd jexec jname=redis sockstat -4l |grep redis
redis    redis-serv 10652 5  tcp4   10.0.0.4:6379         *:*
~~~

~~~
% cbsd expose --help
[jail] Exposing a port to jail from master host
require: 
opt: jname mode proto in out inaddr outaddr
mode - add,delete,apply,clear,flush,list
  - add : add and apply one rule, e.g: in=222 out=22 proto=tcp
  - delete : delete and clear one rule, e.g: in=222 out=22
  - apply : apply all rules from database
  - clear : clear all rules from database
  - flush : clear and remove all rules
proto = udp, tcp. default: tcp
in - master port for incoming connection
out - (optional) destination port inside jail
inaddr - use IP as nodeip (for incoming connection). Default is 138.201.18.134
outaddr - use IP as destination address, do not use jail IPs
~~~

~~~
% cbsd expose jname=redis in=6379 mode=add
CBSD Expose for redis: 6379 -> 6379 (tcp)
~~~

Result:
~~~
% ipfw list 2004
02004 fwd 10.0.0.4,6379 tcp from any to 138.201.18.134 dst-port 6379 in // Setup by CBSD expose: redis
~~~

**Comment by priyadarshan** [comment]
So, just to be clear, `cbsd expose` works only for machines with IPFW, right?

PS: I have started experimenting with HAProxy. I am finding it very flexible.

**Comment by olevole** [comment]
> So, just to be clear, cbsd expose works only for machines with IPFW, right?

Exactly

**Comment by cleverfox** [comment]
With proxy you see hosts's address as remote address of connection inside jail. It is inacceptable in some cases.

**Comment by nopainnogainjoe** [comment]
most of the proxies have X-Forwared-For nowadays

**Comment by cleverfox** [comment]
You can add header only if it HTTP and few other protocols. In generic TCP proxy you can't add header. Forwarding with firewall can be used in any case. 
IMHO there is one case when proxy is really better - if you have many jails with http, you can share one IP for they all based on hostname.

**Comment by olevole** [comment]
pf support via `cbsd expose` added in https://github.com/cbsd/cbsd/commit/d136f5cfbaaf425f3ce4d7b70c0a294c8074a9e6

**Comment by priyadarshan** [comment]
Thank you, this is wonderful. I will test it as soon as available on FreshPorts.
