### ISSUE TITLE
cbsd geli with device end with an error

### ISSUE THREAD

**Issue by palica** [cbsd/cbsd#106]
When trying to initialize geli encryption on a device (zvol) it ends with an error.

```
 cbsd geli mode=init device=/dev/zvol/storage/usr/jails/enc-www
Enter passphrase for /dev/zvol/storage/usr/jails/enc-www:
New Password:
Retype New Password:
Metadata backup can be found in /var/backups/zvol_storage_usr_jails_enc-www.eli and
can be restored with the following command:

# geli restore /var/backups/zvol_storage_usr_jails_enc-www.eli /dev/zvol/storage/usr/jails/enc-www

mdconfig: option requires an argument -- f
usage: mdconfig -a -t type [-n] [-o [no]option] ... [-f file]
                [-s size] [-S sectorsize] [-u unit]
                [-x sectors/track] [-y heads/cylinder]
       mdconfig -d -u unit [-o [no]force]
       mdconfig -r -u unit -s size [-o [no]force]
       mdconfig -l [-v] [-n] [-f file] [-u unit]
       mdconfig file
                type = {malloc, vnode, swap}
                option = {cluster, compress, reserve}
                size = %d (512 byte blocks), %db (B),
                       %dk (kB), %dm (MB), %dg (GB),
                       %dt (TB), or %dp (PB)
error: geli: Invalid number of arguments.
```

**Comment by olevole** [comment]
At the moment, CBSD not tested/works with ZVOL, only with mdconfig/vnode-based backend: https://www.bsdstore.ru/en/cbsd_geli.html

Let this report will stay as todo/request features.

**Comment by palica** [comment]
I can help you test it and debug it. I am able to mount the device manualy and use it.

**Comment by olevole** [comment]
note to self:

Looks like native encryption coming soon to upstream:

http://open-zfs.org/wiki/ZFS-Native_Encryption
https://drive.google.com/file/d/0B5hUzsxe4cdmU3ZTRXNxa2JIaDQ/view

So, CBSD must have option/must be able to choosing encryption method: GELI and ZFS-based.

Also, GELI-based (and ZFS) encryption good not only for bhyve. Here is XEN and jail also can use it for separated secured place

**Comment by olevole** [comment]
fixed, thanks!
