### ISSUE TITLE
use zfs send to move/copy jails between zfs hosts instead of rsync

### ISSUE THREAD

**Issue by palica** [cbsd/cbsd#118]
would make copying even faster between host

**Comment by nopainnogainjoe** [comment]
I second that!

**Comment by olevole** [comment]
I have 'cbsd zrep' for this, but I planned to adapt a more suitable solution. Still in r&d

**Comment by olevole** [comment]
Done via zfs-migrator script. Unfortunately, the current implementation requires access from the root user by ssh keys, for this reason it is now a separate script (not executed from j2slave). But it works.
