### ISSUE TITLE
Need compression options on jexport command

### ISSUE THREAD

**Issue by Dorlas** [cbsd/cbsd#131]
Greetings!
I have a weak processors on servers, but a lot of disk space.

Is it possible to introduce the possibility to specify compression options (in particular - with no compression) when creating the jail image with command: cbsd jexport ?

**Comment by olevole** [comment]
jexport: add compress=X args.

Test1, default value ( compress=6 ):
~~~
% time cbsd jexport jname=localj
Images size for localj.img: 16m
34.490u 0.409s 0:15.47 225.5%   86+192k 2797+2276io 1pf+0w
~~~

Test2, minimal compress ratio:
~~~
% time cbsd jexport jname=localj compress=1
Images size for localj.img: 19m
38.884u 0.353s 0:06.01 652.7%   87+193k 2815+2623io 1pf+0w
~~~

Test3, maximum compress ratio:
~~~
% time cbsd jexport jname=localj compress=9
Images size for localj.img: 14m
36.954u 0.496s 0:37.45 99.9%    86+192k 2815+2059io 1pf+0w
~~~

Test4, compress disabled:
~~~
% time cbsd jexport jname=localj compress=0
Images size for localj.img: 63m
0.183u 0.213s 0:00.54 72.2%     168+191k 2808+7024io 1pf+0w
~~~
