### ISSUE TITLE
jrctl-tui or jrctl apply only one last parameters on jails

### ISSUE THREAD

**Issue by Dorlas** [cbsd/cbsd#139]
Hello!

When i try limit jail resources using jrctl-tui with multiple limit characters, i see, what applyed only last value.

For example, i try add limit on my jail with two parameters (memoryuse and maxproc), i see, what applyed only maxproc.

And when i test it with rctl - i see:
```
rctl
jail:ftpbackup:maxproc:deny=50

```
If i manualy write file jail.limits on jails-system/<jail name> and restart jail, all applyed well.

**Comment by olevole** [comment]
note to self:
it will be part of refactoring with migration dialogs to 'cbsd forms'

**Comment by olevole** [comment]
migrated to 'forms' functional, will available in 11.0.10-R
