### ISSUE TITLE
bhyve ubuntu guest/network interface not working

### ISSUE THREAD

**Issue by matthewearl00** [cbsd/cbsd#140]
I created an ubuntu 16.04 guest using the existing template and was able to vnc in. 
The start of the install shown an error that said "The BIOS has corrupted hw-PMU resources" but I ignored it and after 5 minutes it proceeded.  
During the phase of getting a DHCP assignment I noticed it was taking long. 
At the end it stated it could not get a number so I put in a static address. 
When it needed to download it could not. 
I logged into the box and notice the interface enp0s4 was there and set correctly. 
It just will not see any network I{ besides it's own. 
I have another windows machine running and it works fine. 
using nic of type vnet and on auto. 
No matter what I do I cannot get this virtio network device to route.
 I will try running a machine using bhyve's native commands and see if I can get it to work. 
BTW i LOVE CBSD. 
I have used it for years and in production but this is my first bhyve attempt. Thanks

**Comment by olevole** [comment]
Thanks for feedback. let's try to understand )

1) Can you share CBSD version:
~~~
cbsd -c version
~~~

2) 

Also what is method for NIC parent ? If 'auto' - this mean CBSD will use bridge interface.
And when 'disable' - no bridge, tap use is point-to-point interfaces.

3)
Also, can you try clear arp cache from hoster via:
~~~
arp -ad
~~~

than try to ping static address of Ubuntu guest. It something change?

Also make sure interface is guest if up'et:

~~~
ifconfig enp0s4 up
~~~

**Comment by matthewearl00** [comment]
Thanks. Here is the info:

1.
>root@freebsd1:/ # cbsd -c version
>11.0.9

2.
NIC Parent is set to auto. I need it to bridge and use same IP's as host. Also windows vm is like this.

3.
>root@freebsd1:/ # arp -ad
>arp: writing to routing socket: No such file or directory
>10.0.0.222 (10.0.0.222) deleted
>10.0.0.254 (10.0.0.254) deleted
>root@freebsd1:/ # ping 10.0.0.31
>PING 10.0.0.31 (10.0.0.31): 56 data bytes
>ping: sendto: Host is down
>ping: sendto: Host is down

4.
Interface is up.

**Comment by matthewearl00** [comment]
To add, I manually did this and it still did not work.

> grub-bhyve -r cd0 -m ./vm1-device.map -M 2048 vm1

> bhyve -c 2 -m 2048M -H -P -A -l com1,stdio -s 0:0,hostbridge -s 1:0,lpc -s 2:0,virtio-net,tap1 -s 3,ahci-cd,./ubuntu-16.04-server-amd64.iso -s 4,virtio-blk,./vm1.img vm1

Same issue with network card.

**Comment by olevole** [comment]
two more questions:

1) Can you share full output for this command:
~~~
a) ifconfig
b) netstat -rn
~~~

from hoster system when guest is booted via CBSD ?


2)  do you enable ip.forwarding on hoster ?
~~~
sysctl -nq net.inet.ip.forwarding
~~~

---------------------

You very much will help me with diagnostics if you try to carry out the experiment at whom the bridge won't be used (perhaps, problems with bridge configuration). To do this:

1) stop guest
% cbsd bstop <jname>
2) change default network mode from bridge to p-2-p:
% cbsd bconfig <jname>

    --> bhyvenic -->
    --> nic1 -->
    --> nic_parent --> change **auto** to **disabled**

3) start guest
% cbsd bstart <jname>

4) search if 'ifconfig' output on hoster tap interfaces with "cbsd-<jname>" value in **description**

5) add any not routed IP  address on this interfaces, e.g:
~~~
ifconfig tap2 10.0.1.1/24
~~~

6) login into guest via VNC and set next free IP address with network from step5, e.g:
~~~
ifconfig enp0s4 10.0.1.2/24
~~~

And try to ping hoster from guest:
~~~
ping 10.0.1.1
~~~

( of try to ping guest from hoster: 10.0.1.2 )

**Comment by matthewearl00** [comment]
I will do all those things you say. I love this product and will help any way I can. Here is the output of the host (I have 2 VM's. A windows on tap1 and I believe the ubuntu is tap2. Also sorry in advanced. I don't know how to properly format on gitub reponses.
 These are the two answers and I am gonna try the rest of the suggestions now.

> root@freebsd1:~ # ifconfig
re0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=82099<RXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>
        ether 78:24:af:42:08:64
        inet 10.0.0.39 netmask 0xffffff00 broadcast 10.0.0.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex,master>)
        status: active

>lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo

>bridge1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: re0
        ether 02:f4:72:36:85:01
        nd6 options=1<PERFORMNUD>
        groups: bridge
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: tap2 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 5 priority 128 path cost 2000000
        member: tap1 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 4 priority 128 path cost 2000000
        member: re0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 1 priority 128 path cost 20000

>tap1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: exiles-nic0
        options=80000<LINKSTATE>
        ether 00:bd:74:f5:f6:01
        inet6 fe80::2bd:74ff:fef5:f601%tap1 prefixlen 64 scopeid 0x4
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: active
        groups: tap
        Opened by PID 1109

>tap2: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: openstack-nic0
        options=80000<LINKSTATE>
        ether 00:bd:3a:28:f7:02
        inet6 fe80::2bd:3aff:fe28:f702%tap2 prefixlen 64 scopeid 0x5
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: active
        groups: tap
        Opened by PID 1305

> root@freebsd1:~ # netstat -rn
Routing tables

> Internet:

>Destination        Gateway            Flags     Netif Expire
default            10.0.0.254         UGS         re0
10.0.0.0/24        link#1             U           re0
10.0.0.39          link#1             UHS         lo0
127.0.0.1          link#2             UH          lo0

>Internet6:
Destination                       Gateway                       Flags     Netif Expire
::/96                             ::1                           UGRS        lo0
::1                               link#2                        UH          lo0
::ffff:0.0.0.0/96                 ::1                           UGRS        lo0
fe80::/10                         ::1                           UGRS        lo0
fe80::%lo0/64                     link#2                        U           lo0
fe80::1%lo0                       link#2                        UHS         lo0
fe80::%tap1/64                    link#4                        U          tap1
fe80::2bd:74ff:fef5:f601%tap1     link#4                        UHS         lo0
fe80::%tap2/64                    link#5                        U          tap2
fe80::2bd:3aff:fe28:f702%tap2     link#5                        UHS         lo0
ff02::/16                         ::1                           UGRS        lo0

**Comment by matthewearl00** [comment]
the test you want me to do I am assuming you want me to set the ubuntu guest as dhcp?

**Comment by matthewearl00** [comment]
Ok I tried the suggestions about turning off the NIC and adding the IP's above. I cannot ping from one to the other in either direction.

**Comment by matthewearl00** [comment]
Also, to let you know I just installed Freebsd 11 and it worked with no problems.

**Comment by Dorlas** [comment]
Hello All!

I try to install Ubuntu 16.04 too.

I capture on physical network interface (re0 too) pachets with tshark - and when VM use DHCP protocol, i see first two initial packets:
1) Broadcast DHCP Discover from VM with Ubuntu (MAC Address: Netapp_e8:94:db (00:a0:98:e8:94:db)
2) Broadcase DHCP Offer from my LAN DHCP server

And nothing else...

it turns out that VM is not getting the answers - they do not pass over the bridge.

May be this information help too ;)

**Comment by Dorlas** [comment]
Very strange....

With command:
`tcpdump -n -p -i tap1 `
i see multiple packets from my network...
BUT - on syslog on Ubuntu Installation (alt+F2 mode) i see:
```
netcfg
ARPING to 192.168.10.1 from 192.168.10.25 via enp0s4
Sent 1 probe(s) (1 broadcast(s))
Received 0 reply
```
I think - problems in Ubuntu, not in Bhyve...

**Comment by Dorlas** [comment]
Deeper.....

Problem on ARP protocol.

On my physical network adaper MAC address is: 30:85:a9:af:37:c2
```
re0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=82099<RXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>
        ether 30:85:a9:af:37:c2
        inet 192.168.10.204 netmask 0xffffff00 broadcast 192.168.10.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
```
When i capture packets on tap1 with tcpdump i see:
```
06:34:58.810847 ARP, Request who-has 192.168.10.204 tell 192.168.10.25, length 46
06:34:58.810892 ARP, Reply 192.168.10.204 is-at 00:bd:39:fb:e2:01, length 28
```
00:bd:39:fb:e2:01 is not 30:85:a9:af:37:c2 ;)

Next - i try to write static MAC address on Ubuntu with arp -s
Write it successfull..
When i try to PING to my HOST.
AND when - i see ICMP Request on tap1, but no request on bridge1 and re0.

My brains is crash now ;))))

**Comment by matthewearl00** [comment]
Dorlas great efforts. As I had mentioned before that it also does this in Debian 8. I have tried Ubuntu 16.04, 15.04 and debian Jessie. They all failed. Freebsd and Windows 10 had worked. I should try Centos.

**Comment by olevole** [comment]
Thank you very much, guys! But for me there were even more unclear things ;-)

I assume that it is feature of virtio behavior , because settings with tap/bridge is correct.

Also, thanks to @Dorlas   for accessing as root on FreeBSD 11 where problem is appear.
After one hour of ex-recops, I couldn't find out problems and with a permission of Dorlas, just upgrade FreeBSD 11 to FreeBSD 12 aka (HEAD/Current) and now, Ubuntu work fine:

From hoster:
~~~
% arp -an |grep 10.25
? (192.168.10.25) at 00:a0:98:e8:94:db on re0 expires in 1197 seconds [ethernet]
~~~

<< on FreeBSD hoster, where 192.168.10.25 is IP of Linux Guest

And ping from Ubuntu guest is fine.

Also, on FreeBSD 11 such command:
~~~
arp -an |grep 10.25
~~~

will return arp on 'tap' interfaces. I have only seen this difference.

So, @matthewearl00 if it is not critical - can you try to update FreeBSD on HEAD ?
I believe, in there are some fixes solving this behavior.

**Comment by matthewearl00** [comment]
I would hate to take a production machine and put it on 12-current. I wonder if 11-stable has ingested the changes.

**Comment by olevole** [comment]
Yes, it would be interesting to find the associated commit and make patch. 
Unfortunately, I do not have resources to test RELENG_11 instead of HEAD. 
I have only one FreeBSD on the bare metal and now FreeBSD 12-CURRENT there ;-(

**Comment by matthewearl00** [comment]
@olevole I have plenty of hardware I could let you use to develop on if you need. That is if you have the time or want to. I'm just trying t donate what I can. If I can patch 11-release with the correct virtio I would rather do that than go to current. Maybe I will send this to Michael Dexter and see what he thinks.

**Comment by Dorlas** [comment]
Have i nice day!

I'm download CURRENT SRC of FreeBSD_12 and trying searching differencing...
I am not programmer, but can read and think ;)))) Not writer, but reader...

Now - i got differ between virtio, vmm, if_bridge and if_tap.
You can download it from my Server:
`https://847851.dyn.ufanet.ru/owncloud/index.php/s/Y3Z9kcCMWMZoUqG`

Compare forlders with command: diff -bur 11/ 12/

May be later i try to test it on clean 11 version installation.
If some one try test patch to virio - you need to recompile your kernel - because it is in main:

```
root@clonebsd1:/usr/src/sys/amd64/conf # grep -i "virt" NOTES
# VirtIO support
# The virtio entry provides a generic bus for use by the device drivers.
# Multiple such interfaces are defined by the VirtIO specification. FreeBSD
# only has support for PCI. Therefore, virtio_pci must be statically
device          virtio          # Generic VirtIO bus (required)
device          virtio_pci      # VirtIO PCI Interface
device          vtnet           # VirtIO Ethernet device
device          virtio_blk      # VirtIO Block device
device          virtio_scsi     # VirtIO SCSI device
device          virtio_balloon  # VirtIO Memory Balloon device
device          virtio_random   # VirtIO Entropy device
device          virtio_console  # VirtIO Console device
```
Other modules can recompile with local Makefiles (without recompile kernel).

After read difference on virtio, vmm, if_bridge and if_tap i don't see more change, what can touch our problem. But - who knows....need tests.

**Comment by Dorlas** [comment]
Hey guys!
I setup new FreeBSD 11-RELEASE system, install CBSD and activate Bhyve on same PC (identical HW - i have a middle work class on same hardware).

Download laterst CentOS Image from URL:
`http://mirror.yandex.ru/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1611.iso`
place is on /CBSD/src/iso/ and create link:
`ln -sf CentOS-7-x86_64-Minimal-1611.iso cbsd-iso-CentOS-7-x86_64-Minimal-1511.iso`

Create VM and install. 
Network is running during setup and after install on working system.
Without any patches/changes...

It is cool!

**Comment by matthewearl00** [comment]
But ubuntu still doesn't work right?

**Comment by Dorlas** [comment]
No, it doesn't work now.

And problem not only in virtio i think.

I take latest version on it from
`https://svnweb.freebsd.org/base/head/sys/dev/virtio/`

Place on my 11-RELEASE (/usr/src/sys/dev/virtio) and recompile kerbel with modules.
I know, what it durty experiments, but i try do it ))))

AND - nothing changes! CentOS network works well, Debian-like - no.

Later i try to update all world from 11-RELEASE to 11-STABLE.

**Comment by Dorlas** [comment]
Damned...

I update my test system from 11-RELEASE to 11-STABLE. Use make package:
`https://wiki.freebsd.org/PkgBase`

Nothing changes...

Any ideas ?

**Comment by Dorlas** [comment]
Last shoot...
Update this system from 11-STABLE to 12-HEAD (with package too) - and now VM network is words well (Ubuntu and Debian).

Need developers attach for this problems...
My knowledge is not enough i think.

**Comment by matthewearl00** [comment]
You did amazing. Thanks @Dorlas. Let me try to bring Michael Dexter into this.

**Comment by matthewearl00** [comment]
Ok I sent him an email. Hopefully he can shine some light on this.

**Comment by matthewearl00** [comment]
Ok Michael had said he will ask around and try to fit in a test. Thanks everyone for your efforts and lets see what happens.

**Comment by olevole** [comment]
@matthewearl00 Thank you for report! I hope this is not the end ;-)

**Comment by olevole** [comment]
Looks like FreeBSD-CURRENT doesn't help here - today I got the same situation on my 12.0-CURRENT FreeBSD 12.0-CURRENT #2 r314329 after couple of bhyve stop/start cycle.

The problem is gone when I stopped all jails (and they remove the IP from the same subnet from uplink interface). When i restored alias on interface - problem is back ;). After rebooting all has returned to normal state. Possible IP order initialization order affected when IP on the same subnet.

**Comment by olevole** [comment]
Good news ;-) This behavior was due to '-W' args in some of profiles. To fix it by hand on already installed system:
~~~
sqlite3 ~cbsd/var/db/local.sqlite "UPDATE bhyve SET bhyve_flags='0'"
~~~

I've update bad profiles and send PR to update CBSD port today: CBSD 11.0.14

**Comment by matthewearl00** [comment]
OMG you are the man!!! Oleg we need to chat about some stuff later. I will
be out in the field for a little bit but I will email you.
