### ISSUE TITLE
Having an issue creating the Tap connection

### ISSUE THREAD

**Issue by m2freem** [cbsd/cbsd#151]
I have to admit that I am new with the software, but I really like what I see.  I am sure it is a setting somewhere or something I have done, but I am at a loss where to find it.  If there is a better place to put this, please let me know.  So on with the issue...

I am having an issue with the system creating the tap connection for a new bhyve/Ubunutu 16.04 server guest.  It seems to create the bridge, but not the tap.   

On start, the system creates tap 0 and bridge 0.  When my first test guest is bconstruct, bstart, and blogin.  The installation of the ISO fails on "interface tap1 does not exist"  

ifconfig shows tap0, bridge0, and bridge 1, however tap1 truly does not exist.

I would really appreciate some guidance here. 

Host: FreeBSD 11.0 Stable-HBSD (0)
CBSD Version : 11.0.9

/etc/sysctl.conf:
net.link.tap.up_on_open=1

/boot/loader.conf:
vmm_load="YES"
nmdm_load="YES"
if_tap_load="YES"
if_bridge_load="YES"

/etc/rc.conf:
cloned_interfaces="bridge0 tap 0"
ifconfig_bridge0="addm igb0 addm tap0"
cbsd_workdir='/usr/jails"
cbsdd_enable="YES"
rcshutdown_timeout="900"
kld_list="if_bridge if_tap nmdm"

**Comment by will666** [comment]
cloned_interfaces="bridge0 tap 0" show be: cloned_interfaces="bridge0 **tap0**"

**Comment by m2freem** [comment]
William,


How you have indicated, is how it is in rc.conf on the server.  It was a typo on my part putting it on the forum.


________________________________

**Comment by will666** [comment]
my setup brings up bridge1 and tap1 with 172.16.0.1/24 IP set on bridge1, i do not use DHCP, so my bhyve guest uses 172.16.0.2/16

**Comment by m2freem** [comment]
`bce0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=c01bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,VLAN_HWTSO,LINKSTATE>
	ether 00:26:b9:3d:3c:99
	inet 192.168.200.152 netmask 0xffffff00 broadcast 192.168.200.255 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect (100baseTX <full-duplex>)
	status: active
bce1: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=c01bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,VLAN_HWTSO,LINKSTATE>
	ether 00:26:b9:3d:3c:9a
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 02:78:41:28:a2:00
	nd6 options=9<PERFORMNUD,IFDISABLED>
	groups: bridge 
	id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
	maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
	root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
tap0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=80000<LINKSTATE>
	ether 00:bd:ae:48:f7:00
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: no carrier
	groups: tap 
bridge1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	description: bce0
	ether 02:78:41:28:a2:01
	nd6 options=1<PERFORMNUD>
	groups: bridge 
	id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
	maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
	root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
	member: bce0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 1 priority 128 path cost 200000`

**Comment by will666** [comment]
I remember struggling as well on this part, i ended by deleting the interfaces like so:
`ifconfig tap0 destroy && ifconfig bridge0 destroy`, then try to run/create the bhyve VM.

**Comment by m2freem** [comment]
Will, 

Done as recommended.

Bstart, 
ifconfig, shows tap1 and bridge 1
blogin, gives tap 1 does note exist
ifconfig, shows bridge 1

**Comment by m2freem** [comment]
dmesg|tail

[239472] tap1: Ethernet address: 00:bd:c6:e5:3c:01
[239472] tap1: promiscuous mode enabled
[239473] tap1: link state changed to UP
[239473] pid 24876 (bhyve), uid 0: exited on signal 6
[239473] tap1: link state changed to DOWN

**Comment by will666** [comment]
hum i would investigate on the network adapter driver of the VM, did you try to reconfigure the cbsd env?
`cbsd initenv`

**Comment by m2freem** [comment]
ok, so tap1 drops out after a few seconds after bstart.  It is not blogin dependent. 

Is there a CBSD specific log where I can get a little more info as to why tap1 fails?
/usr/jails/var/log is empty

I am not sure what I would need to change with "cbsd initenv"

**Comment by will666** [comment]
`cbsd initenv` does some cleaning and re-init cbsd env, don't change stuff if not necessary, just run the command and try again (like you would do after a cbsd update). I had the same problem as you but i don't remember what i did at the time...

**Comment by olevole** [comment]
Hi. Best way to debug at the moment  - trying to run bhyverun.sh script by hand:

~~~
ifconfig tapX create 
cd ~cbsd/jails-system/<vm>-system/<vm>
sh ~cbsd/share/bhyverun.sh -c ./bhyve.conf
~~~
E.g, if vm have name ubuntu1, in ~cbsd/jails-system/ubuntu1/ directory you can find bhyve.conf.

% grep mytap ~cbsd/jails-system/ubuntu1/bhyve.conf    
% ifconfig tap1 create        // if mytap="tap1" from previous step
% sh ~cbsd/share/bhyverun.sh -c ./bhyve..conf
~~~

and access to VM from VNC:
~~~
vncviewer <ip>:5900
~~~

If you not change default ubuntu settings,'cbsd blogin'  will not work, because the graphics console is expected and the server will start after first accessing to VNC port.

Becouse judging by the message:

[239473] pid 24876 (bhyve), uid 0: exited on signal 6

bhyve for some reason finished and executing bhyve from console can clarify the reason

**Comment by m2freem** [comment]
Ok,  I found the problem.   My old Xeon processor does not support UG, which makes Bhyve not work properly.   I appreciate your help @will666.

Please close this Issue

**Comment by olevole** [comment]
Also thanks to @will666  ;)

**Comment by m2freem** [comment]
Oleg,


Thanks for the input.  I think what I have is a hardware issue.  The issue being that my processor/motherboard do not support UG.  Which, it seems, is causing the fail at VM start.


I am currently updating the bios of my system, but I am not really expecting it to fix it.  Limitations of old hardware. I am positive that I can get everything I want to do done in a couple of jails, so it's not a real big deal.  I just wanted to get my hands on and around a hypervisor.  Maybe the next time around.



________________________________
