### ISSUE TITLE
Docker application in a jail

### ISSUE THREAD

**Issue by PECgeo** [cbsd/cbsd#169]
Hi
Just curious if this is possible and if so  is there a howto somewhere. As a side note i have read  that some Freebsd  docker projects are dead or not being developed and some are experimental. Bhyve is not usable on the machine that I experiment on so running a VM is not possible

**Comment by olevole** [comment]
Hi. Unfortunately, I do not know the options for using the docker without the bhyve on FreeBSD ;-(
