### ISSUE TITLE
Устанавливая cbsd из github невозможно узнать версию cbsd

### ISSUE THREAD

**Issue by click0** [cbsd/cbsd#173]
Устанавливая cbsd из github невозможно узнать версию cbsd. В портах и пакетах - более-менее отображается версия. И не мешало бы показывать help до инициализации (установки переменных окружения) cbsd.

[19:59]core:root-> /root# /usr/local/bin/cbsd -v
cbsd: No workdir defined
[19:59]core:root-> /root# /usr/local/bin/cbsd -V
cbsd: No workdir defined
[19:59]core:root-> /root# /usr/local/bin/cbsd -h
cbsd: No workdir defined
[19:59]core:root-> /root# file /usr/local/bin/cbsd
/usr/local/bin/cbsd: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.0 (1100513), FreeBSD-style, stripped
[19:59]core:root-> /root# /usr/local/bin/cbsd --version
cbsd: No workdir defined
[19:59]core:root-> /root# /usr/local/bin/cbsd -version
cbsd: No workdir defined
[20:00]core:root-> /root# /usr/local/bin/cbsd --help
cbsd: No workdir defined

**Comment by olevole** [comment]
Да, согласен.
Нотес для себя: обработать аргумент до проверки наличия https://github.com/cbsd/cbsd/blob/master/bin/cbsdsh/main.c#L181

**Comment by olevole** [comment]
Должна показывать по 
cbsd -c version

**Comment by olevole** [comment]
Поправлено в рамках коммита: https://github.com/cbsd/cbsd/commit/26c9e6f4d2181d8da9fb602d8a427df1deb5e4f7

**Comment by click0** [comment]
Все по-прежнему

# ll /usr/local/bin/cbsd
-r-x------  1 root  wheel  174288 13 июля  00:46 /usr/local/bin/cbsd*
# /usr/local/bin/cbsd -c version
cbsd: no workdir defined
# /usr/local/bin/cbsd --help
cbsd: no workdir defined

**Comment by olevole** [comment]
Эти изменения сейчас только в GIT (в develop ветке и смержено в master), релиза на базе этих правок еще небыло - будут в CBSD 11.1.0 (планирую в течении месяца отрелизить).

Соотв, увидеть можно только в GIT версии:

~~~
root@gizmo:~ # git clone https://github.com/cbsd/cbsd.git /tmp/cbsd
Cloning into '/tmp/cbsd'...

root@gizmo:~ # cd /tmp/cbsd
root@gizmo:/tmp/cbsd # make
cc bin/cbsdsftp.c -o bin/cbsdsftp -lssh2 -L/usr/local/lib -I/usr/local/include && "/usr/bin/strip" bin/cbsdsftp
...

root@gizmo:/tmp/cbsd # bin/cbsdsh/cbsd version
11.1.0a
~~~

**Comment by click0** [comment]
Я качал ветку mster - https://github.com/olevole/cbsd/archive/master.zip

**Comment by olevole** [comment]
Пардон, теперь стало:
~~~
cbsd version
~~~

вместо cbsd -c.

Надо будет в доку внести.

PS: по cbsd help также выводится версия, спасибо за наводку, you are welcome ;-)

**Comment by click0** [comment]
Тогда работает :)
# /usr/local/bin/cbsd version
11.1.0a

**Comment by click0** [comment]
Но вывод help подправьте.

# /usr/local/bin/cbsd --help
cbsd: no workdir defined
# /usr/local/bin/cbsd help
cbsd: no workdir defined
# /usr/local/bin/cbsd -c help
cbsd: no workdir defined

**Comment by olevole** [comment]
тут сложнее, но я подумаю, пока оставлю открытым таску.

**Comment by olevole** [comment]
Посмотрел, сейчас пока никак, поскольку help является командой cbsd, а все команды работают уже после успешной инициализации/setup-а.
