### ISSUE TITLE
Не определяет наличие модуля PF в ядре

### ISSUE THREAD

**Issue by click0** [cbsd/cbsd#176]
# env workdir="/usr/jails" /usr/local/cbsd/sudoexec/initenv
...
Do you want to modify /boot/loader.conf to set pf_load=YES ?
[yes(1) or no(0)]
n
grep: /usr/jails/etc/pfnat.conf: No such file or directory
...

Причем:
# kldstat -v | grep ' pf$'
                408 pf

**Comment by olevole** [comment]
Тут только про grep надо будет поправить поведение ( No such file or directory ). В остальном, здесь не проверяется есть модуль или нет, поскольку это инициализация CBSD и в этом диалог-ответе она готовит и конфигурирует параметры, которые требуются для работы. То что модуль уже загружен, может быть результат ручной загрузки pf, что не гарантирует загрузку модуля при перезагрузки сервера и таким образом, повлечет неработоспособность CBSD. Поэтому, вопрос о правке конфига здесь подразумевает только правку конфига, чтобы пользователь знал, что меняется в его системе и что без спроса, менять в системных настройках система ничего не будет.

**Comment by olevole** [comment]
Corrected, thanks!
