### ISSUE TITLE
Не корректно определяется ветка FreeBSD 10 - RELENG_10 

### ISSUE THREAD

**Issue by click0** [cbsd/cbsd#177]
# env workdir="/usr/jails" /usr/local/cbsd/sudoexec/initenv
...
stable: Use STABLE branch (RELENG_10 (ver = 10) instead of RELEASE_10.x (ver = 10.x) ). Only CBSD repository have binary base for STABLE branch ?
(STABLE_X instead of RELEASE_X_Y branch for base/kernel will be used), e.g.: 0 (use release)
...

# uname -a
FreeBSD core.domain.com 11.1-PRERELEASE FreeBSD 11.1-PRERELEASE #0 r318606: Mon May 22 14:28:27 EEST 2017     root@core.domain.com:/usr/obj/usr/src/sys/core.domain.com.1  amd64

**Comment by olevole** [comment]
Это не баг, в этом месте никакого определения нет и надпись является чисто информативным текстом. Добавлю в текст 'e.g / for example', чтобы путаниц таких небыло

**Comment by olevole** [comment]
Corrected, thanks!
