### ISSUE TITLE
Specify bridge/nic

### ISSUE THREAD

**Issue by Fazik** [cbsd/cbsd#180]
Hello,
First of all thanks for such great software. It is really useful.
As for problem.
I was not able to find any documentation regarding choosing interface/bridge for vnet based jail.
By default cbsd will use first interface(in my case igb0).
Is it possible to configure which interface should be attached to bridge or to specify already existing bridge, which should be used?

**Comment by olevole** [comment]
Hi,

Yeah, I like CBSD too ;-)

I have not used for a very long time vnet-based jails, but It seems that the interface choice should work in the same way as for non-vnet jails or bhyve, via 'interface' params in 'cbsd jconstruct-tui' or 'cbsd jconfig':

cbsd jconfig -> [your_jail] -> 'interfaces' -> SELECT/Specify uplink

or via CLI:

~~~
% ifconfig vlan100 create
~~~

~~~
% cbsd jls display=jname,vnet,interface

JNAME  VNET  INTERFACE
jail1  1     auto

% cbsd jset jname=jail1 interface=vlan100
interface: vlan100

% cbsd jstart jail1
...

% ifconfig
...
vlan100: flags=8102<BROADCAST,PROMISC,MULTICAST> metric 0 mtu 1500
        ether 00:00:00:00:00:00
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        vlan: 0 vlanpcp: 0 parent interface: <none>
        groups: vlan 
bridge2: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: vlan100
        ether 02:0c:86:ea:bd:02
        nd6 options=1<PERFORMNUD>
        groups: bridge 
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: epair1a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 11 priority 128 path cost 2000
        member: vlan100 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 9 priority 128 path cost 55
epair1a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: jail1
        options=8<VLAN_MTU>
        ether 02:ff:40:00:0b:0a
        hwaddr 02:ff:40:00:0b:0a
        inet6 fe80::ff:40ff:fe00:b0a%epair1a prefixlen 64 scopeid 0xb 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
        groups: epair
~~~

It is not possible to indicate to use existing bridge now, but I add it to my TODO
Also in my todo is ability to add multi-interface for vnet, in the same way as it is done in 'cbsd bconfig' -> 'bhyvenic' -> ...   (for bhyve)

Can you check the ability to explicitly specify the interface via 'cbsd jconfig' or 'cbsd jset' ?

Also I will leave this issue in open state as reminder for TODO with choosing of existing bridge.

**Comment by Fazik** [comment]
Thanks,
It worked.
Seems that I previously done in some wrong way)

**Comment by olevole** [comment]
Cleanup
