### ISSUE TITLE
interface alias error

### ISSUE THREAD

**Issue by sturican** [cbsd/cbsd#221]
Приветствую! 

Замечено, что при небольшом количестве ждейлов (5 штук). Периодически (далеко не всегда), некоторые из джейлов при старте не навешивают алиасы на интерфейс. При перезапуске cbsd jrestart jname  - соответственно ругается, что алиас удалить не может и заново уже вешает нормально. 
Что попробовать сделать?

FreeBSD version ( uname -a ): 
FreeBSD 10.3-STABLE #2 r310624M

CBSD version ( cbsd version ): 
cbsd-10.3.2,1

**Comment by Dorlas** [comment]
Что-то версия CBSD у Вас какая то бородатая...очень устарела.
Есть возможность обновить до последней ? (11.1.10)

**Comment by sturican** [comment]
да там фрибзд 10.3 через pkg более свежей cbsd не показывает. С портов сейчас гляну, может свежее текущей, не обратил внимания.

**Comment by Dorlas** [comment]
Три месяца назад обновлял один из серверов с FreeBSD 10.3 на 10.4 - обновился без проблем (с помощью freebsd-update). Софт пересобирать из портов не пришлось. Рекомендую.

**Comment by sturican** [comment]
Угу, спасибо. Мне бы причину понять почему алиасы не создаются главное. Софт да, обновить пора бы там. Возможно порядок включения задать разный стоит для нескольких джейлов, что-то не успевает где-то отработать одновременно, хз.

**Comment by olevole** [comment]
Да, всегда желательно репортить будучи на последней версии. Я что-то связанное с удалением алиазов фиксил именно в последней версии, https://www.bsdstore.ru/ru/news.html, вот тут фраза хромающая грамматикой "bugfix: jstop: fix ip4_addr list for removeing, " :-), но конечно же, могут и другие неизвестные баги выползать. Бекап на забудь :-) тк прыжки с 10.3.x до 11.1.11 версий я не тестил, физически это с моими ресурсами сложно, большая пропастьмежду ними:-)

**Comment by sturican** [comment]
понял, обновлюсь, если повторится - напишу, сори за беспокойство :)

**Comment by olevole** [comment]
Ok, просьба переоткрыть, если траблы остануться
