### ISSUE TITLE
jconstruct-tui: profile selection does not work

### ISSUE THREAD

**Issue by uropro** [cbsd/cbsd#240]
When I start 'cbsd jconstruct-tui ' as root, I get the nice window, but I cannot change the profile 'default': Hitting the 'enter' key does not open the dialog for selection the profiles, instead the screen is redrawn.
pkglist etc. works as intended.
I have not changed anything in /usr/jails/etc/ etc.
What could be wrong? I am working on freshly installed FreeBSD 11.1 with CBSD v11.1.12
Thanks for any help!

**Comment by olevole** [comment]
Thanks for reports, you are the second who has noticed about this ;-)

This error appeared in 11.1.12 and already fixed in 11.1.13 ( bugfix release)
After a short check, it will be commited into a port tree:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225401

I'm also waiting)

**Comment by uropro** [comment]
11.1.13 fixes the issue. Thanks a lot!
