### ISSUE TITLE
Feature Request Ability to add multiple VNET type interfaces to jail

### ISSUE THREAD

**Issue by gizahNL** [cbsd/cbsd#243]
Currently it is impossible via the interface to have cbsd create multiple VNET interfaces (eth0, eth1 etc.) and assign them to a jail. 
There are no kernel limitations (vanilla FreeBSD allows multiple vnet interfaces in jail.conf via comma seperation).

Purpose is to allow stricter network  seperation of jails that need to be externally available (say webnode) but also need access  to private networks (say mysql node)

**Comment by olevole** [comment]
I agree with you, this task in my TODO's long enough time ;-) I've plan to implement it in next CBSD release.
Just in case, I want to say that you can create jail on different interfaces, however, when VNET=0 (by interface='0' or disable and specify real IP from physical NIC).

Thank you for reminding!

**Comment by olevole** [comment]
Support for multiple VNET was added as part of the https://github.com/cbsd/cbsd/commit/eefe9e958dcc641904ee48b51b22ee06185847ee

BTW,
> vanilla FreeBSD allows multiple vnet interfaces in jail.conf via comma seperation

this is not true), we can not write in jail.conf something like:
~~~
vnet.interfaces="epair1b epair2b .."
~~~
such an entry is not supported (at least for FreeBSD 12-CURRENT rev 329454 from 2018-02-17)
Multi-NIC support requires post-jail-creation actions:

~~~
ifconfig epair1b **vnet** jailX
~~~
upon jail create and
~~~
ifconfig epair1b **-vnet** jailX
~~~
before jail stop.

Will be available in CBSD 11.1.16

**Comment by olevole** [comment]
**Notes for myself**:

Todo:
   - document jail network options on the site;
   - add support for on-the-fly operation (or hide jailnic submenu for active jail)
   - manage NIC/epair without TUI, via CLI

**Comment by olevole** [comment]
commited to ports tree

**Comment by gizahNL** [comment]
great! thanks!
