### ISSUE TITLE
Не получается добавить ноду

### ISSUE THREAD

**Issue by sturican** [cbsd/cbsd#260]
Добрый день! 

Mandatory info for bug reports:
При попытке добавить ноду:

```
cbsd node mode=add node=xx.xx.xx.xx
Connecting to xx.xx.xx.xx via IPv4...
xx.xx.xx.xx has nodename: hostname
Added successfull: xx.xx.xx.xx
Already exist in database, updating: xx.xx.xx.xx
**rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.2]
CBSD: Fetching inventory failed: hostname**
```

На слейв ноде запущен cbsdrsync, telnet с мастер ноды до слейв на порт 1873 ходит.
На всякий случай, запустил на мастер ноде тоже cbsdrsync правда не уверен, что это необходимо. Со слейва тоже телнет до мастера на 1873 порт ходит.

Как правильно отдебужить почему rsync не отрабатывает?

p.s. нашёл мало информации по работе с нодами, возник дополнительно вопрос, как организовать распределение нагрузки между нодами (кластер, автоперенос тюрьм в случае падения одной из нод?), если такое возможно? Или с мастера можно только управлять + мигрировать джейлы? Где можно почитать на эту тему?

Заранее спасибо! 

FreeBSD version ( uname -a ): 
Мастер нода: FreeBSD 11.1-RELEASE-p4
Слейв нода: FreeBSD 11.1-RELEASE-p4

CBSD version ( cbsd version ): 
мастер: 11.1.16
слейв: 11.1.13

**Comment by olevole** [comment]
cbsdrsyncd  ( rsync daemon ) в этом месте не используется - по 1873 бегает трафик только при миграции/клонировании jail.

При добавлении node, rsync работает в режиме rsync over ssh и судя по всему, он в твоем случае не отрабатывает на этапе скрипта nodescp.

А по команде

~~~
cbsd node mode=list
~~~

удаленная нода каком статусе, Connected ?

Я до сих пор не добавил глобального ключа debug=1, но можно легко увидеть, какую команду с rsync выполняет скрипт в nodescp, вставив трейс шелла, для этого открыть

/usr/local/cbsd/nodectl/nodescp 

скрипт любым редактором и после строчки

init $*

( это примерно 24-я строчка) добавить строчку:

set -o xtrace

Те, будет примерно такой кусок:
~~~
..
. ${strings}
. ${nodes}

init $*

**set -o xtrace**

getnode()
{
~~~

после чего запустить `cbsd initenv` и еще раз попробовать вызвать обновление удаленной ноды:

cbsd retrinv node=hostname tryoffline=1

Если я правильно угадал место где rsync работает, то должно быть побольше вывода, в том числе строчка с ssh .. rsync ..

Распределения нагрузки в автоматическом режиме ( DRS,  Distributed Resource Scheduler ) сейчас нет - только вручную мигрировать окружения ориентируясь на мониторинг. HA, high availability тоже в коробке нет, но касательно jail - это можно легко достичь через carp хук и внешний скрипт, который сделает takeover на резервную ноду. Хорошая практика ставить попрано ноды, master-slave крест-на-крест, когда оба сервера хостят _часть_ контейнеров и при этом являются slave-ом для соседа - ресурсы не простаивают как при полном master-slave кейсе. Кто-то в CBSD чатике подобные схемы с фейловеров организовывал (с использованием NFS и glusterfs), но у меня и в CBSD такого функционала еще нет.

Добавленную ноду понимают эти команды, остальные (например, jconstruct-tui - пока нет):

jlogin, jstop, jstart, jremove (осторожнее с ней) + jcoldmigrate

**Comment by sturican** [comment]
в tools/retrinv вывел команду с nodescp, при запуске её напрямую xtrace сработал, там ошибка  Permission denied (publickey,password).
разбираюсь.

**Comment by sturican** [comment]
Всё оказалось, как обычно просто, зря только спокойствие возмущал :)
у меня в sshd.conf изменено стандартное имя файла где ключ искать. Всё работает, nodа подключилась и в статусе connected теперь.

Спасибо за помощь!

**Comment by olevole** [comment]
Аа, тогда гуд:-) функционал с межнодовым взаимодействием заморожен и не развивается, поскольку тут надо использовать AMQP-like брокер, задачи процессить через очередь, тк напрямую дергать ssh не очень надежно. Поэтому, профита от добавленных нод особо пока нет, разве что jcoldmigration и j2slave. Еще, есть команда zfs-migrator, но она требует рутового ключа и пока не документирована

**Comment by sturican** [comment]
ну да, мне собственно для удобства миграции джейлов и нужно было, сейчас jcoldmigrate юзаю, спасибо!

а zfs-migrator где посмотреть? мне всё-равно скорее разово это потребуется

**Comment by olevole** [comment]
zfs-migrator пока недокументирована, тк я хочу ее избавить от root доступа. Так что весь хелп пока тут:

cbsd zfs-migrator --help

;)

у нее два режима работы - full и incremental, в первом случае она снапшот отправляет и переносит jail целиком. Во втором - инкрементальные снапшоты, дискретная репликация по сути. Удобно, если нужно перелить постоянно модифицирующийся на файловой системе jail.

**Comment by sturican** [comment]
то что нужно! буду пробовать.

**Comment by sturican** [comment]
Олег, доброго дня!

Подскажите, с zfs-migrator  ситуация не изменилась, так и нужен root овый доступ? 

Опять переезжаю сервер и снова те же проблемы :) Забывается всё, если не используешь часто :)

Тут вот что получилось:

На сервере откуда переношу: 
**sudo cbsd version
12.0.3**

На сервере куда: 
**cbsd version
12.0.7**

На сервере источнике делаю: 

- cbsd j2prepare node=node1 jname=erp --verbose
- cbsd j2slave node=node1 jname=erp

На node1 появляются джейлы:
cbsd jls
node1  erp          0    10.0.0.3     erp.node1.ru          /zjails/jails/erp          Unregister

Данные переносятся. Но самих джейлов не видно по всей видимости, любые команды на запуск или смену статуса slave/master пишут:
**No such jail: erp**

В /zjails/jails/ - пусто. 
В /zjails/jails-data - всё есть.

Как их инициализировать правильно?

**Comment by olevole** [comment]
Это либо rsync не запущен в виде сервиса cbsdrsync либо его порт фильтруется, 1873 кажется.
Хорошо бы было еще обновиться до последней версии и иметь однаковые версии, я там что то исправлял еще

**Comment by sturican** [comment]
гм... как это может быть, если данные по ноде передаются? и в /zjails/jails-data/erp-data целиком джей лежит? т.е. слайсы на zfs делаются, данные переносятся. Именно действий с нодой сделать не могу потом никаких..

**Comment by olevole** [comment]
А, действительно. Тогда я бы посоветовл обновится. Не хватает финальной стадии на конечной ноде в виде

cbsd jswmode jname=xxx mode=master

Она регистрирует клетку из режима unregister

**Comment by olevole** [comment]
А по размеру объем данных совпадает, через zfs get used например? Непонятно почему не дошло до этого

**Comment by sturican** [comment]
ага, это пробовал, в том то и дело, что ноды как будто в новой cbsd не зарегистрированы.

cbsd jswmode jname=erp mode=master
No such jail: erp

**Comment by sturican** [comment]
по размеру почему-то на приемнике даже больше... странно :)

**Comment by sturican** [comment]
хотя может из-за разного кол-ва дисков, на источнике raidz2 из 6ти, на приемнике raidz3 - из 8

**Comment by olevole** [comment]
кстати да, это вполне может быть из-за рассинхрона версий, схемы SQL могут быть разные.
Попробуй все таки обновиться из портов. Может cbsd initenv разрулит. Если на свежаке тоже проблемы, надо тогда дебажить) Я попробую у себя вопроизвести если не алё

**Comment by sturican** [comment]
ага, щас попробую. 
Я пока один джейл попробовал сначала создать, потом закинуть, правда они двоятся тогда в списке:

cbsd jls
NODENAME           JNAME        JID  IP4_ADDR     HOST_HOSTNAME           PATH                       STATUS
node1  erp          0    10.0.0.3/32  erp.local          /zjails/jails/erp          Off         
node1  erp          0    10.0.0.3     erp.local          /zjails/jails/erp          Unregister 

сейчас обновиться попробую

**Comment by olevole** [comment]
если чё (объемы небольшие), то есть еще jimport/jexport ;) должно быть надежнее  (и еще jrclone ). Я 100 лет не проверял команды которые между нодами что-то делают( надо переделывать эти механизмы на брокер какой-нибудь

**Comment by sturican** [comment]
объёмы как раз большие...

jrclone с ноды на ноду как раз умеет? что-то упустил этот момент...
тут как раз нужно без остановки клетки действовать, клон вроде стоп клетки требует, нет?

**Comment by olevole** [comment]
кажется не требует, в любом случае это закомментить можно)

**Comment by sturican** [comment]
ещё вопрос sharedfs это что за зверь при клоне? Типа общий раздел для обоих джейлов, это в случае СХД если используется и джейлы имеют общий zfs zvol, такое что-то?

CBSD обновил, сейчас пробую по старой схеме, отпишусь если не выйдет jrclone попробую.

**Comment by sturican** [comment]
аааа, так вот видимо в чём дело :)
посмотрел в jrclone он там тоже делает препар и 2slave, а вот затем, то что мне и не хватало видимо, jregister! :) попробую

**Comment by olevole** [comment]
sharedfs да, это например когда данные на NFS/GlusterFS/Ceph и тд - ниче копировать не будет, только разрегистрирует на первой и зарегает на второй. Я кажется делал, чтобы этот признак детектился CBSD автоматом - в data каталоге теперь есть файлик 'dir.id' который показывает некий UUID датасета. И если он совпадает, CBSD считает что файловай система единая. А этот ключ чтобы руками заставить так думать

**Comment by sturican** [comment]
блин, да всё нормально, надо было  cbsd jregister jname= делать и всё норм.
Спасибо!

**Comment by olevole** [comment]
гы, я видимо ее спутал с jswmode. гуд

**Comment by sturican** [comment]
ага :)
кстати, для справки ещё, а slave/master это просто флаги? Если ноду перевести в slave она тушится? или продолжает работать как было и это чисто для настройки файловера, чтобы понимать кто мастер, кто слейв? и тушить/зажигать нужные джейлы, если надо.

**Comment by olevole** [comment]
Slave или maitenance статус это асего лишь логический признак, который мешает всяким start/stop что то делать над контейнером, чтобы дубляжа например не оказалось когда две клетки запустились

**Comment by sturican** [comment]
Олег, добрый вечер!

Мигрировал почти все клетки через ноды по cbsd j2prepare & cbsd j2slave & cbsd jregister
Всё прошло отлично. На последней клетке (ну а как же ещё могло быть  :) )
Отвалилась нода приемник в статус disconected.

cbsd node mode=list
.....id_rsa  Disconnected  7353

cbsd cbsdssh 10.0.0.28 22222 ls
не работает висит пока error не отдаст.

Порты открыты телнетом всё нормально в обе стороны.

На ноде где disconected - 
sudo ps -aux | grep cbsd  | grep sock 
есть сокеты до других нод, но пропал до желаемой...
Как бы это мягко перезапустить? Нашёл старый тред, там reload советовали сделать (хотя он вроде и не помог), но в текущей версии cbsd reload - а нет, только restart...

Как починить без перезапуска клеток, есть идеи?

**Comment by olevole** [comment]
попробуй магический ключ tryoffline=1 у j2prepare и j2slave. она заставляет скипать проверку статуса ноды

**Comment by sturican** [comment]
cbsd j2prepare node=node1 jname=bitrix --verbose --tryoffline=1
Preparing..Error in rexe
Guru meditaion: 
Node is offline: node1

не хотит...

**Comment by sturican** [comment]
ещё на node1 весь лог загажен:
Jun  5 17:31:24 node1 cbsd[56857]: cbsdd: update remote inventory for 192.168.0.20 via loop_per_retrinv [10] 

может поэтому чего?

**Comment by olevole** [comment]
эти параметры надо писать также как все аргументы в cbsd, те без --

cbsd j2prepare node=node1 jname=bitrix tryoffline=1

**Comment by sturican** [comment]
а, понял :)

```
Preparing..Error in rexe
Guru meditaion: 

```

тогда такая вот ошибка...

**Comment by sturican** [comment]
уууу, в логах приемника увидел: 

Jun  5 00:00:20 taishi sshd[71083]: Failed unknown for cbsd from 192.168.0.20 port 54757 ssh2
Jun  5 00:00:20 taishi sshd[71083]: Failed publickey for cbsd from ............

бред, как же оно раньше работало... может заново ноду добавить попробовать на источнике?

**Comment by sturican** [comment]
всё решено, не знаю каким образом, но ключ не там искал при авторизации, хотя не менял ничего вроде. Старнно. Включил дебуг sshd на приемнике и нашёл проблему.

Извиняюсь, что опять возмущал спокойствие :)

**Comment by olevole** [comment]
:-)

**Comment by sturican** [comment]
Олег, день добрый!

Мини хотелка родилась при переносе джейлов, подумайте, может будет возможность сделать, если это имеет смысл:

В j2slave добавить возможность exclude (мне понадобилось для исключения левых постоянно меняющихся файлов, логи, сессии и тд).

Для себя добавил в j2slave:

```
# sync for data
rsync_add_params=""
rsync_exclude_file="${jailsysdir}/${jname}/rsync.exclude"
if [ -f $rsync_exclude_file ];
then
	rsync_add_params="${rsync_add_params} --exclude-from ${rsync_exclude_file}"
fi

/usr/local/bin/rsync --port=1873 -arzz --partial ${_rs_progress} --devices --numeric-ids --delete --recursive --partial ${rsync_add_params} --password-file=${etcdir}/${jname}.secrets ${data}/ rsync://${jname}@${ip}/${jname}/ 2>${DEBLOG}

```

**Comment by olevole** [comment]
Я такое года два уже хочу сам :-) для jexport в тч. Пока времени нет сесть за это

**Comment by sturican** [comment]
Олег, ещё вопрос... не могу понять дело в cbsd rexe или в curve hands :)

Делаю скрипт собираю инфу с удалённых нод, заткнулся на простейшей вещи:

shник:

```
serverCmd="cbsd rexe node=node1"
echo $($serverCmd "echo $NGINX_JAILS/$type/")
echo $($serverCmd "ls $NGINX_JAILS/$type/")
echo $($serverCmd "ls $NGINX_JAILS/$type/$site")
```

В оутпуте получаем:

первая - путь до конфигов сайтов - ок: /usr/local/etc/nginx/confs/jails/wordpress/
вторая - ls тоже ок. off.site1.ru off.site2-test.ru
третья - при любом раскладе, как добавляется к команде имя конфига сайта все команды дальше затыкаются... вида: : No such file or **directorynfs**/jails/wordpress/on.site-test.ru

как будто отрезает куски какие-то...
Там может ограничение какое-то срабатывает на длину команды или фиг знает, что ещё может быть... Хотя нет, ограничение не похоже, если вместо переменной $site указать имя файла руками, он его нормально lsит или катит, бред... может из-за /bin/sh на удалённой ноде что-то не так экранирую? голову сломал уже

**Comment by olevole** [comment]
Я думаю, что echo это плохой инструмент для получения инфо, проблема с экранами, всякими спецсимволами '*' и \r\n. Не проще сделать как-нибудь так:
```
serverCmd="cbsd rexe node=node1"

${serverCmd} /bin/sh <<EOF
hostname
date
echo $NGINX_JAILS/$type/
ls $NGINX_JAILS/$type/
ls $NGINX_JAILS/$type/$site
EOF
```

тут по крайней мере не будет траблов со * и \r\n

**Comment by sturican** [comment]
да я уже и так и так пробовал, в тот то и дело, что результат один:

```
for site in $(${serverCmd} "ls $NGINX_JAILS/$type | sort | grep -e \"^on\"")
    do
		echo "$site"

		${serverCmd} /bin/sh <<EOF
		cat "${NGINX_JAILS}/${type}/${site}"
EOF

done
```
вывод:
```
on.sitetest.ru
: No such file or directoryonfs/jails/wordpress/on.sitetest.ru
on.sitetest2.ru
: No such file or directoryonfs/jails/wordpress/on.sitetest2.ru
```

всё равно как будто часть строки срезана, поэтому и подумал может rexe что-то может делать такое....

Хотя rexe не причём похоже... если /bin/sh просто сделать такая же песня. Фигня какая-то :(

**Comment by sturican** [comment]
Дальше больше.

Такая фигня происходит при повторном соединении с нодой. Если видоизменить скрипт и изначально считывать оглавление с локали, вот так:

```
for site in $(ls $NGINX_JAILS/$type | sort | grep -ve "^off")
    do
		jPath="${NGINX_JAILS}/${type}/${site}"
		echo $jPath

${serverCmd} /bin/sh <<EOF
		ls "$jPath"
EOF

done

```
то обращение к ноде внутри цикла отрабатывают уже отлично.

**Comment by olevole** [comment]
без дебага, идей, увы - больше нет

**Comment by sturican** [comment]
ещё немного покрутив, в конце-концов сделал всё что хочу собирать на удалённой ноде в файл и уже этот скрипт дёргаю с ноды-источника, где уже с файлом работаю.
Х.З. может оно так и даже лучше будет, меньше туда-сюда ссх команды гонять.
