### ISSUE TITLE
An option to not add egress to bridge

### ISSUE THREAD

**Issue by mekanix** [cbsd/cbsd#270]
In short, I would like to make `addm ${interface}` part of https://github.com/cbsd/cbsd/blob/develop/bhyve.subr#L274 optional, but on by default to retain compatibility. The problem I have is setting up DHCP jail on bridge interface which does not listen on egress by default. As DHCP is using BPF directly (just like PF), PF can not block that. I was thinking about one more bconstruct-tui option and bconstruct cli option. Did I forget something?

**Comment by olevole** [comment]
Yes, a similar task is in my TODO very long time - some users want to create their own bridge and have the ability to specify for virtual machines. Or, you want configure only tap ifaces, without link to any bridge/uplink ?
