### ISSUE TITLE
Feature Request: Allow CBSD to work on machines without Virtualization support.

### ISSUE THREAD

**Issue by sn3ak** [cbsd/cbsd#275]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD host.mydomain.com 11.1-RELEASE-p9 FreeBSD 11.1-RELEASE-p9 #0: Tue Apr  3 16:59:16 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

CBSD version ( cbsd version ): 
pkg info | grep cbsd : cbsd-11.1.16

# cbsd bconstruct-tui
No kldloaded module: vmm
Please add vmm_load="YES" into /boot/loader.conf and
put kld_list="if_bridge if_tap nmdm" into your /etc/rc.conf then reboot host.
Press any key...

from dmesg on this specific machine:
module_register_init: MOD_LOAD (vmm, 0xffffffff82657620, 0) error 22

We are using CBSD in other machines that do support Bhyve, it would be ideal if we could use the same tool(s) for our dedicated jail machine.

Thanks for the good work.

**Comment by olevole** [comment]
Not very clear to me. If your hoster does not support virtualization then commands related to the bhyve ( bconstruct-tui, bstart, bremove ) are useless for you.

if you want to work with jail, use jail-related command which are the same, just start with the 'j' letter:

cbsd jconstruct-tui
cbsd jremove
cbsd jstart
cbsd jconfig
...

**Comment by sn3ak** [comment]
*slaps head*...
This is what you get, when you follow documentation too closely (following Clonos install for FreeBSD), without the proper understanding.

Sorry for wasting your time.
