### ISSUE TITLE
cbsd expose with pf fails to add udp rules

### ISSUE THREAD

**Issue by sn3ak** [cbsd/cbsd#280]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD private 11.1-RELEASE-p9 FreeBSD 11.1-RELEASE-p9 #0: Tue Apr  3 16:59:16 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

CBSD version ( cbsd version ): 11.1.16

It appears due to line 101 in tools/expose that it is impossible to add udp rules when using pf. Recommend replacing tcp with ${proto}

**Comment by olevole** [comment]
Thank you very much! I will soon fix this.

**Comment by olevole** [comment]
Commited, will be available in next release (11.1.18 or 11.2.0).

**Comment by olevole** [comment]
Commited into ports tree via 11.1.19 release
