### ISSUE TITLE
cbsd expose fails to add tcp and udp rules when the port is the same

### ISSUE THREAD

**Issue by sn3ak** [cbsd/cbsd#281]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD private 11.1-RELEASE-p9 FreeBSD 11.1-RELEASE-p9 #0: Tue Apr  3 16:59:16 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

CBSD version ( cbsd version ): 11.1.16

root@host:/usr/jails/etc # cbsd expose jname=dns proto=udp in=53 out=53 mode=add
CBSD Expose for dns: 53 -> 53 (udp)
CBSD: Enable IP forwarding for NAT service
pfctl: pf already enabled

root@host:/usr/jails/etc # cbsd expose jname=dns proto=tcp in=53 out=53 mode=add
CBSD Expose for dns: 53 -> 53 (tcp)
CBSD: Enable IP forwarding for NAT service
pfctl: pf already enabled

The rules do get added to pfnat.conf, however:
root@host:/usr/jails/etc # cbsd expose jname=dns mode=list
53 -> 53 (via 138.197.195.201 tcp)

and cbsd expose mode=flush only restores the tcp rule.

**Comment by olevole** [comment]
Hmm, perhaps it's a bug in the list/show only. Can you check pfnat.conf file (or active rules in pf):
```cat ~cbsd/etc/pfnat.conf```
or
```pfctl -sn```
after both expose rule ?

**Comment by olevole** [comment]
I apologize, it was a hasty conclusion. I found the reason for this behavior - ```port in``` in SQLite3 is UNIQUE:

https://github.com/cbsd/cbsd/blob/develop/share/system-expose.schema#L5

We need to change it. I will prepare a patch for this soon

**Comment by olevole** [comment]
Well, looks like there were a few problems ;-)

First and second: for some reason pin (port in) was UNIQUE and PRIMARY KEY ( both do not allow dubbing )
The third ( it did not affect your problem ): pout (port out) for some reason was TEXT(!?), most likely it's a typo.

Patch for migrate old tables was created: https://github.com/cbsd/cbsd/blob/develop/upgrade/pre-patch-11.1.19.0

You can apply all changes via:
~~~
fetch -o /usr/local/cbsd/upgrade/pre-patch-11.1.19.0 https://github.com/cbsd/cbsd/blob/develop/upgrade/pre-patch-11.1.19.0
~~~
~~~
chmod +x /usr/local/cbsd/upgrade/pre-patch-11.1.19.0
~~~
~~~
fetch -o /usr/local/cbsd/share/system-expose.schema https://github.com/cbsd/cbsd/blob/develop/share/system-expose.schema
~~~

And re-run: `cbsd initenv`

Before this, it is advisable to update the CBSD to the latest available version from the ports (11.1.18)

**Comment by olevole** [comment]
I expect this problem to be corrected with this patch. Can you test this and give feedback ? I will be very grateful!

**Comment by olevole** [comment]
I assume that everything is ok, pls reopen if not

**Comment by olevole** [comment]
Commited into ports tree via 11.1.19 release
