### ISSUE TITLE
No sane way to set bhyve_flags

### ISSUE THREAD

**Issue by davisjc** [cbsd/cbsd#282]
FreeBSD 11.1-RELEASE-p4
cbsd 11.1.11

I'm really enjoying cbsd so far.  However, sometimes simple things are incredibly painful to modify.

In particular, I want to add the '-p' option to the bhyve command line to pin the vcpus to certain cores.  Is there anyway I can set this without hacking up the cbsd scripts...?   I'd really expect this to be configurable via bconfig.  I tried to read the bstart script for a little while to understand where ${bhyve_flags} is set, but it's hard to understand what where magic variable came from without reading more of the source.

There's a file rc.conf_<VM_NAME> in jails-system/<VM_NAME> that has a line for bhyve_flags, but modifying this appears to do absolutely nothing.  The same file also has mention of another rcconf setting, pointing to a path in jails-rcconf, but adding a file there with same syntax also does nothing.

Please make this easier to hack.

Thank you very much for your work on the project.

**Comment by olevole** [comment]
Thanks for the feedback!

CBSD has few users. And very few of them very use bhyve via CBSD ;)
A similar need (in arbitrary extra arguments for bhyve) is very long overdue, I absolutely agree with you. Although this is a simple task. 
I think we can provide several options to add extra parameters at the same time:

- via classic inputbox in dialog ( not very comfortable for long lines and editing )
- via extra **bhyve_args=** in vm profiles
- via additional extra file in system dir, e.g ~cbsd/jails-system/<VM_NAME>/bhyve_extra_params.conf

I'll try to do it on the weekend. 
CBSD 11.1.11 already a little outdated on the part of the support code bhyve (all recent changes are generally  related to bhyve). 
So, I would be very grateful if you could test changes in your install (for this you need to upgrade to the latest version), when they will be ready.

Apart from extra bhyve args, I'm interested to cover bhyve cpu pinning in CBSD. In latest version I implemented bhyve cpu topology (  https://www.bsdstore.ru/en/11.1.x/wf_bcpu_topology_ssi.html ), but this will work on recent FreeBSD-current only. So next step is CPU pinning.

Do you have any idea how this might look like? You can write the configurations that you write for CPU pinning? I still have not tried it.

**Comment by davisjc** [comment]
Thanks for the quick response!

I just pulled 11.1.18.  The cpu topology stuff you're working on looks interesting.  I'm curious to see how that progresses.

Given the current way cbsd operates, I'd expect there to be a field in the bconfig dialog for "additional bhyve parameters" where you could put arbitrary text.

A single flat text file that contains the entirety of the config for a vm/jail would be ideal, but I understand that cbsd uses sqlite here and there to store some state.  Earlier, I thought I could tweak the vm settings with jails-system/<VM_NAME>/bhyve.conf.  I tried modifying that file as mentioned above and then quickly learned that the bstart script actually dumps its own state into this file every start...  Which is not at all what I would expect.  The file seems more of a log than an actual config.

Another instance of config confusion I had was how to add additional mounts for FreeBSD jails.  It took a bit of experimentation to understand that I needed to create a new text file in jails-fstab/ named "fstab.<JAIL_NAME>.local".  The existing file, "fstab.<JAIL_NAME>" gave the hint of "Use /home/cbsd/jails-fstab/fstab.local instead", which isn't literal advice, I found out.  In that case, it would have been nice if an empty "fstab.<JAIL_NAME>.local" file was generated to point the user in the right direction.

As for CPU pinning, I'm currently running a 4 core / 8 thread host with a 4 vcpu Windows 10 vm.  I can achieve the pinning I want with "-p 0:4 -p 1:5 -p 2:6 -p 3:7", which pins all 4 vcpus to the back half of my physical cores.

Again, thanks again for your work on cbsd!  Very cool project.

**Comment by olevole** [comment]
@davisjc I made several changes for this task. It will be nice if you can check it out. 

Changes have touched several files, so I think the easiest way to check is to copy the current code from the development branch ;). E.g:

Backup old dir (or you can just reinstall the port):
~~~
mv /usr/local/cbsd /usr/local/cbsd-orig
~~~

Checkout new code:
~~~
git clone https://github.com/cbsd/cbsd.git /usr/local/cbsd
~~~

Run initenv (make sure you have pkgconf package before):
~~~
cbsd initenv
~~~

And try to use **bhyve_flags** menu via **bconstruct-tui** and **bconfig**.

Also, I added the ability to reassign any parameters through $systemdir/<JAIL_NAME>/etc/rc.conf, e.g. when workdir=/usr/jails and domain name is 'vm1', just create

/usr/jails/jails-system/vm1/etc/rc.conf with follow content (for example):

~~~
bhyve_flags=-p 0:4 -p 1:5 -p 2:6 -p 3:7
~~~

**Comment by davisjc** [comment]
Heh, nice!  Yeah, both the dialog menu and the rc.conf option work for me.  Thank you for taking the time to look at this! =]

**Comment by olevole** [comment]
You're welcome! Will be available in the next release.

**Comment by olevole** [comment]
Commited into ports tree via 11.1.19 release
