### ISSUE TITLE
Can't unset protected flag from jail

### ISSUE THREAD

**Issue by Dorlas** [cbsd/cbsd#290]
Mandatory info for bug reports:

Try to unset protected flag from jail and flag never changed.
Try to use CLI: cbsd jset mode=quiet jname=dokuwiki protected="0" and try to use cbsd jconfig.

FreeBSD version ( uname -a ): 11.1-RELEASE-p7

CBSD version ( cbsd version ): 11.1.19

**Comment by olevole** [comment]
Thanks! I'll try to update in the ports ASAP

**Comment by olevole** [comment]
Commited into ports tree, v11.20, Thanks!
