### ISSUE TITLE
Interest for completion? (zsh)

### ISSUE THREAD

**Issue by moviuro** [cbsd/cbsd#297]
Hi,

I'm trying my hand at zsh completion. Would it be interesting for the cbsd project to ship a zsh completion script?

It won't be ready to ship right now, though, I'm guessing some weeks of work on my end will be necessary.

Cheers,

**Comment by olevole** [comment]
Hi,
Yes,  it would be nice to put these files in the CBSD code base (e.g in share directory), and/or update README. 

Hhm, some time ago I enjoyed with bash completion. However, I can not find how I did it ;) 
I think, together with yours zsh completion i've restore and put bash completion.

By the way, I saw some interesting solutions for popup/tooltip completion. E.g:

https://github.com/cloudnativelabs/kube-shell  ( uses https://github.com/jonathanslenders/python-prompt-toolkit )

or there is a more suitable solution for CBSD: 

https://github.com/jhawthorn/fzy
https://github.com/garybernhardt/selecta

I have been thinking for a long time to build them in cbsd shell ( /usr/local/bin/cbsd )
But I'm not sure that everyone will like it ;-)

So, fill free to add zsh completion script, this is very useful!

**Comment by moviuro** [comment]
:+1:

Though I was thinking of some more "usual" behavior, using http://zsh.sourceforge.net/Doc/Release/Completion-System.html (which is not trivial)

```
# cbsd <TAB>
completing command
jexec          -- [jail] execute command in jail
jconstruct-tui -- [jail] dialog to configure a jail
[...]
```

```
# cbsd jexec <TAB>
completing jexec options
jname=   -- in which jail to jexec
user=    -- whom to impersonate
completing command
at ls dd [...]
cp rm xz
```

```
# cbsd jexec jname=<TAB>
completing jname
*       haproxy    [...]
unbound nextcloud
```

I'll be publishing my completion when at least jexec works correctly.

**Comment by olevole** [comment]
Wow! this requires some modification from the CBSD side ? Each cbsd script (except --help)  can display the available parameters via 'cbsd <script> --args'. Maybe it can be adapted somehow. I will try to read about zsh completion on the weekend

**Comment by moviuro** [comment]
No, it requires no modification to the cbsd code (so far).

However, I do parse cbsd's output. For example, for the `jname=` part, I use the following code:

```sh
__cbsd-jls-for-jexec() {
  cbsd jls display=status,jname | awk '{ if ( $1 ~ "On" ) print $2 }'
  printf '%s\n' '\\\*'
}
```

**Comment by moviuro** [comment]
I have the following code ATM, http://ix.io/1biJ .

It:

* Completes the subcommand, and displays it with a short help text.
* Completes `cbsd jexec` with `--help` or `jname=` and helps select the jail
* Displays `cbsd jexec --help` if you try to tab your way through it
* Completes `user=` with users from the selected jail (unless you chose `jname=\*` in which case it's broken)
* Breaks when you try to append the command after that

**This is absolutely not production-ready, and if it destroys your home, it's not my fault**

**Comment by olevole** [comment]
Cool, this works for me.
I'm not sure that this will not change, 
but for now I added this into _/usr/local/cbsd//share/autocompletion/zsh_

Maybe someday we will be able to make _cbsd_subcmd dynamic (e.g. via Jenkins when new CBSD release is being prepared).

As far as I understand, we can write about ZSH completion activating something like:

1) create ~/.zshrc for root:
~~~
# COMPLETION SETTINGS
# add custom completion scripts
fpath=(~/.zsh/completion $fpath) 

# compsys initialization
autoload -U compinit
compinit

# show completion menu when number of options is at least 2
zstyle ':completion:*' menu select=2
~~~


2) create directory: 
~~~
mkdir -p ~root/.zsh/completion/
~~~

3) copy helper:
~~~
cp -a /usr/local/cbsd/share/autocompletion/zsh/_cbsd ~root/.zsh/completion/
~~~

4) Have fun!

?

**Comment by mekanix** [comment]
Sorry to be late to the party, I didn't have notifications turned on. As I'm working on socket based communication between CBSD daemon and CBSD shell (command, call it what you will), the CBSD CLI will probably slightly change. So, on the shell side of things, I intend to port https://github.com/AmokHuginnsson/replxx and try to use it for our purposes. Once I have that, we can probably "export" in a way that is convenient for ZSH (and Fish, as I use it) to consume it and write completion.

**Comment by olevole** [comment]
@mekanix repplx - nice project. But before we finish the CBSD daemon, we will go a very long and long way)

@moviuro I added your scripts into CBSD 11.2.0 ( commited into ports tree today).
If you plan on continuing to work on this, please create a Pull Request into develop branch. And if there is a lot of work, I can give you a commit to a dev branch. Thanks you!

**Comment by moviuro** [comment]
@olevole I'll continue working on my own fork, no need to give me commit rights on upstream :wink: thanks though!

**Comment by mekanix** [comment]
I'm sorry if I made an impression that my work on sockets and new shell is coming soon, that's not true. I expect first version around Autumn, just to make it clear.

**Comment by olevole** [comment]
CBSD contribution now has zfs completion scripts, so I will close this issue. Thanks you very much @moviuro !

**Comment by ntinti** [comment]
Great supplement, I like it. But I'm wondering why zsh completion for poudriere is automatically there without any personal configuration in .zshrc

They installed it in a shared zfs directory

```
post-install-ZSH-on:
   @${MKDIR} ${STAGEDIR}${PREFIX}/share/zsh/site-functions/
   ${INSTALL_DATA} ${WRKSRC}/completions/zsh/_poudriere \
       ${STAGEDIR}${PREFIX}/share/zsh/site-functions/
```
curl and pkg also reside there, I think cbsd also can do it:

```
ls -la /usr/local/share/zsh/site-functions/
total 31
-rw-r--r--  1 root  wheel  13098 16 Juni 17:22 _curl
-rw-r--r--  1 root  wheel  31391 10 Mai  01:18 _pkg
-r--r--r--  1 root  wheel   9051  5 Apr. 21:52 _pkgtools
-rw-r--r--  1 root  wheel   7283 16 Juni 17:22 _poudriere
```

**Comment by olevole** [comment]
@ntinti Got it. Unfortunately I do not use **zsh** [yet ;-)], so I'm not very good at this issue. Well, I'll add this configuration to the next release into sysutils/cbsd port.

As for comment from https://github.com/cbsd/cbsd/issues/309#issuecomment-405111926:

> not only the first level, but following the whole tree of all options cbsd has would be nice for completion. Poudriere e.g. has it:

As I understand it, the work is not yet complete. Personally, I'm currently not working on this, maybe someone will be able to finish work sooner or later.
