### ISSUE TITLE
Socket communication between daemon and shell

### ISSUE THREAD

**Issue by mekanix** [cbsd/cbsd#300]
This is a ticket to follow the progress of sockets implementation and surrounding libraries, like replxx (https://github.com/AmokHuginnsson/replxx/issues/18).

**Comment by olevole** [comment]
I'm just patrolling CBSD Issues.
@mekanix can we close this Issue? If work on socket communication still in progress or still in todo, I suggest adding this to CBSD roadmap ( https://www.bsdstore.ru/en/roadmap.html ) as long-term task.

**Comment by mekanix** [comment]
We can. Sockets will get their own project as we discussed earlier.
