### ISSUE TITLE
sqlite problem after upgrade

### ISSUE THREAD

**Issue by reablaz** [cbsd/cbsd#302]
Mandatory info for bug reports:
We have cbsd on hosts with both bhyve and jail instances. after upgrade from 11.0 to 11.1 (or 11.1 to 11.2 on another server) we got problem to launch bhyve instances. 

> Unable to fetch vm data from: /path/to/cbsdworkdir/var/db/ivn.hostname.sqlite

It is possible to restore cbsd functioning, if make a downgrade to cbsd 11.1.11.

FreeBSD version ( uname -a ): 11.1, 11.2

CBSD version ( cbsd version ): cbsd 11.1.11<

**Comment by mekanix** [comment]
I upgraded all my boxes to FreeBSD/CBSD 11.2 and I don't have such a problem, so I have a problem replicating this error. Can you help me with that, please? First, is the `/path/to/cbsdworkdir/var/db/ivn.hostname.sqlite` real path or you obfuscated it? Also, when you say "uypgrade from 11.0 to 11.1" is it CBSD or FreeBSD version?

**Comment by olevole** [comment]
did you do `cbsd initenv` ?

Also, hostname of node remained unchanged during the update ?
CBSD use ~cbsd/var/db/local.sqlite as DB which is symlink to ~cbsd/var/db/inv.<hostname>.sqlite

Can you list ~cbsd/var/db/ directory for *.sqlite file ?

**Comment by reablaz** [comment]
Path of /var/db was obfuscated, below is more correct paths (with obfuscation as well).
After recreating problem it dissapeared and cbsd updated successfully (locked cbsd in pkg when updated other packages)
Initial problem occured during freebsd-update procedure.
cbsd initenv was launched after update.
Below is last cbsd upgrade procedure which succeeded.
I said about upgrading FreeBSD version from 11.0 to 11.1 , not CBSD.

> root@charizard:/usr/home/user # uname -a
> FreeBSD charizard.hostname.com 11.2-RELEASE FreeBSD 11.2-RELEASE #0 r335510: Fri Jun 22 04:32:14 UTC 2018     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
> 
> root@charizard:/usr/home/user # pkg info cbsd
> cbsd-11.1.11
> Name           : cbsd
> Version        : 11.1.11
> Installed on   : Tue Jul  3 14:37:17 2018 EEST
> Origin         : sysutils/cbsd
> Architecture   : FreeBSD:11:amd64
> Prefix         : /usr/local
> Categories     : sysutils
> Licenses       : BSD2CLAUSE
> Maintainer     : olevole@olevole.ru
> WWW            : https://www.bsdstore.ru
> Comment        : Yet another FreeBSD Jail and Bhyve Management Utility
> Shared Libs required:
> 	libssh2.so.1
> 	libsqlite3.so.0
> Annotations    :
> Flat size      : 22.5MiB
> Description    :
> Yet another FreeBSD jail and bhyve management tool.
> 
> WWW: https://www.bsdstore.ru
> 
> 
> root@charizard:~ # ls -la /sroot/jails/var/db/
> total 894
> drwxrwx---  2 cbsd  cbsd      12 Jul  3 17:08 .
> drwxr-xr-x  8 cbsd  cbsd       8 Jul 19  2017 ..
> -rw-rw----  1 cbsd  cbsd   16384 Jul 19  2017 authkey.sqlite
> -rw-rw----  1 cbsd  cbsd   12288 Jul  3 14:41 cbsdtaskd.sqlite
> -rw-rw----  1 cbsd  cbsd  143360 Jul  3 17:08 inv.charizard.hostname.com.sqlite
> -rw-r-----  1 root  cbsd  139264 Aug  2  2017 inv.charizard.hostname.com.sqlite-bck
> -rw-r-----  1 root  cbsd  139264 Aug 29  2017 inv.charizard.hostname.com.sqlite-bck2
> lrwxrwxr-x  1 root  cbsd      51 Jul  3 14:37 local.sqlite -> /sroot/jails/var/db/inv.charizard.hostname.com.sqlite
> -rw-rw----  1 cbsd  cbsd   12288 Jul 19  2017 nodes.sqlite
> -rw-rw----  1 cbsd  cbsd   12288 Jun  8 13:52 storage_media.sqlite
> -rw-rw----  1 cbsd  cbsd   16384 Jul 19  2017 vpnet.sqlite
> -rw-rw----  1 cbsd  cbsd   12288 Jul 19  2017 zrepd.sqlite
> 
> 
> root@charizard:~ # pkg update
> Updating FreeBSD repository catalogue...
> FreeBSD repository is up to date.
> All repositories are up to date.
> root@charizard:~ # pkg upgrade
> Updating FreeBSD repository catalogue...
> FreeBSD repository is up to date.
> All repositories are up to date.
> Updating database digests format: 100%
> Checking for upgrades (1 candidates): 100%
> Processing candidates (1 candidates): 100%
> Checking integrity... done (0 conflicting)
> The following 1 package(s) will be affected (of 0 checked):
> 
> Installed packages to be UPGRADED:
>         cbsd: 11.1.11 -> 11.1.16
> 
> Number of packages to be upgraded: 1
> 
> Proceed with this action? [y/N]: y
> [1/1] Upgrading cbsd from 11.1.11 to 11.1.16...
> ===> Creating groups.
> Using existing group 'cbsd'.
> ===> Creating users
> Using existing user 'cbsd'.
> [1/1] Extracting cbsd-11.1.16: 100%
> Message from cbsd-11.1.16:
> 
> ===============================================================================
> 
> cbsd is now installed, but requires additional setup steps:
> 
> Upon initial installation, run:
> 
>   env workdir="/path" /usr/local/cbsd/sudoexec/initenv
> 
> Where /path is the path to the cbsd workdir, e.g.: /usr/jails
> 
> For upgrading an existing installation, run:
> 
>   cbsd initenv
> 
> ===============================================================================
> 
> 
> root@charizard:~ # cbsd initenv
> -------[CBSD v.11.1.16]-------
>  This is install/upgrade scripts for CBSD.
>  Don't forget to backup.
> -----------------------------
> Do you want prepare or upgrade hier environment for CBSD now?
> [yes(1) or no(0)]
> 1
> >>> Installing or upgrading
> [Stage 0: upgrading and migration data from 11.1.11 to 11.1.16]
>   * Xen tables re-created
>   * Update bhyve settings tables for openproject
>    * moving:  vm_cpus vm_ram vm_os_type vm_boot virtio_type vm_hostbridge vm_os_profile vm_iso_path vm_console vm_efi vm_vnc_port protected hidden bhyve_generate_acpi bhyve_wire_memory bhyve_rts_keeps_utc bhyve_force_msi_irq bhyve_x2apic_mode bhyve_mptable_gen bhyve_ignore_msr_acc cd_vnc_wait bhyve_vnc_resolution bhyve_vnc_tcp_bind ip4_addr vnc_password bhyve_vnc_vgaconf
>   * Update bhyve settings tables for ossec
>    * moving:  vm_cpus vm_ram vm_os_type vm_boot virtio_type vm_hostbridge vm_os_profile vm_iso_path vm_console vm_efi vm_vnc_port protected hidden bhyve_generate_acpi bhyve_wire_memory bhyve_rts_keeps_utc bhyve_force_msi_irq bhyve_x2apic_mode bhyve_mptable_gen bhyve_ignore_msr_acc cd_vnc_wait bhyve_vnc_resolution bhyve_vnc_tcp_bind ip4_addr vnc_password bhyve_vnc_vgaconf
> [Stage 1: account & dir hier]
>  * Check hier and permission...
> [Stage 2: build tools]
> [Stage 3: local settings]
> [Stage 4: update default skel resolv.conf]
> [Stage 5: refreshing inventory]
> [Stage 6: authentication keys]
> [Stage 7: modules]
> [Stage 9: cleanup]
>  * Remove obsolete files...
> \tRemoving obsolete file: /sroot/jails/etc/defaults/vm-linux-ubuntuserver-x86-17.04.conf
> \tRemoving obsolete file: /sroot/jails/etc/defaults/vm-linux-ArchLinux-x86-2017.conf
> \tRemoving obsolete file: /sroot/jails/etc/defaults/vm-linux-Kali-2017-amd64.conf
> \tRemoving obsolete file: /sroot/jails/etc/defaults/vm-linux-Tails-3.0.1.conf
> [Stage X: upgrading]
> >>> Done

> Unable to fetch vm data from: /path/to/cbsdworkdir/var/db/ivn.hostname.sqlite
In previous message I was wrong about sqlite file name, it was named as BHYVE VM name. Unfortunately, I do not remember exact path and name.
P.S. Pretty sure problem occured because of our setup, it was on two different servers which was upgraded with two different admins. 
On the second host manual upgrade with pkg succeeded as well.

**Comment by olevole** [comment]
Got it. Just in case - if for some reason the CBSD lost jail/bhyve, the first thing to check is where the symbolic link **~cbsd/var/db/local.sqlite** points to.

PS: BTW, I recommend upgrading to the latest version of CBSD (e.g from the ports) - **11.2.0**, because older CBSD (and bhyve-firmware) versions may have problems with booting new Linux kernels (bug in bhyve uefi firmware). As I understand it, you use a quarterly repository. It still has a broken CBSD version.

**Comment by reablaz** [comment]
Thank you for your recommendation.
Yes, we are using default repo, provided by freebsd installer.

Much thanks for your great project. it rocks! we've used cbsd for almost two years and are so excited about the possibilities cbsd gives. It seems the best (and maybe the only) wrapper/framework for both jails and bhyve, which works as expected.

Do you accept donations in crypto? Bitcoins/Litecoins/Monero? if not, we can help you to establish such possibility (and describe how can you cash-out easy) and would like to donate a bit of crypto for your huge contribution. we are working in crypto-space and can provide you free payment processing service and crypto advices for sure. It can be useful also for your hosting project, as payment methond which one do not require any banking or contracts.

**Comment by olevole** [comment]
@reablaz Thank you, these are very motivating words.) Yes, we accept donations and are happy with any help. Unfortunately, I've never worked with crypto/coins. I hope we will fix it soon))

**Comment by reablaz** [comment]
Yesterday we reproduced problem on the third server. After freebsd-update procedure, after restarts error appeared. All three servers were installed in different ways, with different hardware configuration. Upgrades FreeBSD 11.1 -> 11.2. Jails wont start in auto, bhyve VMs dissapeared at all. Exact situation as with other hosts. After manual cbsd upgrade via pkg everything went OK. But issue definetely persists, maybe only on some speciic freebsd/cbsd versions only. Screenshot attached
![vzqsijt](https://user-images.githubusercontent.com/3844596/42408464-b9853950-81d5-11e8-8819-72ec0bd0af54.png)

**Comment by reablaz** [comment]
I'll re-open the issue. Please close if you think that problem is not related to cbsd itself

**Comment by olevole** [comment]
Hints for yourself:

Error occurs here:

https://github.com/cbsd/cbsd/blob/develop/rcconf.subr#L15-L52

This can occur in two cases:

1.  cbsdsql ( /usr/local/bin/cbsd ) compiled dynamically with SQLite3 and for some reason SQL library was broken.
2. For some reason CBSD scripts was updated and expect a new SQL scheme ( what is corrected through migration scripts in `cbsd initenv` procedure ).

@reablaz Unfortunately, I can not reproduce the problem. if you have a broken host, you can check and confirm my suspicions via:

a) try out  for SELECT via sqlite3:

~~~
sqlite3 ~cbsd/jails-system/<jname>/local.sqlite "SELECT astart,vm_cpus,vm_ram,vm_os_type,vm_boot,vm_os_profile,vm_vnc_port,virtio_type,bhyve_vnc_tcp_bind,bhyve_vnc_resolution,cd_vnc_wait,protected,hidden,maintenance,ip4_addr,vnc_password,vm_hostbridge,vm_iso_path,vm_console,vm_efi,bhyve_generate_acpi,bhyve_wire_memory,bhyve_rts_keeps_utc,bhyve_force_msi_irq,bhyve_x2apic_mode,bhyve_mptable_gen,bhyve_ignore_msr_acc,bhyve_vnc_vgaconf,vm_cpu_topology FROM settings ORDER BY (created) DESC LIMIT 1;"
~~~

where <jname> - vm name.

b) try out  for SELECT via cbsdsh and cbsdsql:
~~~
cbsd (run cbsdsh)
cbsdsql ~cbsd/jails-system/debpup1/local.sqlite "SELECT astart,vm_cpus,vm_ram,vm_os_type,vm_boot,vm_os_profile,vm_vnc_port,virtio_type,bhyve_vnc_tcp_bind,bhyve_vnc_resolution,cd_vnc_wait,protected,hidden,maintenance,ip4_addr,vnc_password,vm_hostbridge,vm_iso_path,vm_console,vm_efi,bhyve_generate_acpi,bhyve_wire_memory,bhyve_rts_keeps_utc,bhyve_force_msi_irq,bhyve_x2apic_mode,bhyve_mptable_gen,bhyve_ignore_msr_acc,bhyve_vnc_vgaconf,vm_cpu_topology FROM settings ORDER BY (created) DESC LIMIT 1;"
~~~

**Comment by reablaz** [comment]
We have no more hosts with bhyve (hosts with jails only upgrades OK), ill try to reproduce problem in test enviroment. Will respond after that

**Comment by reablaz** [comment]
upgrade from 11.1.11 to cbsd 11.2.0 went OK. 
thank you for fast responses
