### ISSUE TITLE
feature request: jail import to zpool with different name

### ISSUE THREAD

**Issue by reablaz** [cbsd/cbsd#305]
FreeBSD version ( uname -a ):  all

CBSD version ( cbsd version ): <11.11.0, didnt tested on newer versions

So we are using cbsd on servers with separate zpool for jails/bhyve. I can share as well our experience, it may be useful for somebody, especially in case when freebsd host is hosted in third-party DC. So we are installing freebsd base system on unencrypted disk/slice, so it can (re)boot without intervention and after the base system boot it is possible to ssh to the host remotely via network. After remote connection (manual or automated), we are launching decryption procedure (usually script, where you need to pass passphrase and/or key for geli) for data disks/slices (in such way creating secure, encrypted zpool for data - in our case for cbsd jails/bhyves).after that we are importing zpool from decrypted storage and starting cbsdd.

In our enviroment data zpools where cbsd is initialized on each host has different name. for example two hosts A and B, each in separate DC without any cluster/interconnection need.
Host A: zsystem - zpool for zfs root, zdataA - zpool for jails/bhyve;
Host B: zsystem - zpool for zfs root, zstorageB - zpool for jails/bhyve;

when there is a need to migrate jail form host A to host B, we are exporting jail from host A with jexport, transferring .img to host B, and after that importing .img with jimport on host B.

The problem: while jails imported successfully, jail wont start, because cbsd cant locate jail with path /zdataA/path/to/cbsd/ on host B, because actual path of jail on host B is /zstorageB/path/to/cbsd.

Workaround: we are changing four entries in inv.hostname.sqlite db (just prefix /zdataA -> /zstorageB)

I have not tested this with bhyve, because bhyve instances we are migrating on zfs layer (zfs send / recv), transferring raw vhd zpool.

It would be great to make such migration path-independet or with possibility to provide custom path while importing

p.s. i do not feel strong enough in coding to make a pull request, maybe can contribute in any way with some advices.

**Comment by olevole** [comment]
It will be interesting to implement. Part of this overlaps with the old task of having several independent $workdir environments, where each $workdir can have an independent copy of basejail, independent resource/quota's limit and use use independent ZFS pools/storage.

This features requires some r&d especially in the case when bhyve VM may have several dsk

**Comment by reablaz** [comment]
works as expected on newer cbsd version
