### ISSUE TITLE
multiple ip adresses can't be configured separately on interfaces without hosts config

### ISSUE THREAD

**Issue by ntinti** [cbsd/cbsd#306]
FreeBSD version ( uname -a ): 11.2 Release
CBSD version ( cbsd version ): 11.2.0

Since a few years it is possible on FreeBSD to create dynamic created ip numbers in a jail per interface like
`ip4.addr = re0|172.20.20.233/24,re1|10.0.0.1/8;`
It would be nice if it can be set in CBSD also.

Also IPV6 should be possible, eg.
`ip6.addr  =  igb0.16|::3;`

```
     ip4.addr
	     In	addition to the	IP addresses that are passed to	the kernel, an
	     interface,	netmask	and additional parameters (as supported	by
	     ifconfig(8)) may also be specified, in the	form
	     ``interface|ip-address/netmask param ...''.  If an	interface is
	     given before the IP address, an alias for the address will	be
	     added to that interface, as it is with the	interface parameter.
	     If	a netmask in either dotted-quad	or CIDR	form is	given after an
	     IP	address, it will be used when adding the IP alias.  If addi-
	     tional parameters are specified then they will also be used when
	     adding the	IP alias.

     ip6.addr
	     In	addition to the	IP addresses that are passed to	the kernel, an
	     interface,	prefix and additional parameters (as supported by
	     ifconfig(8)) may also be specified, in the	form
	     ``interface|ip-address/prefix param ...''.
```

**Comment by olevole** [comment]
Now everything should work.

CBSD use SQLite3 where '|' is default delimer. Thus we are forced to convert (and accept by default) records in <iface>#ip-addr.  But in order for users to feel comfortable, we also allow a record of the <iface>|ip-addr form.

Thanks! will be available in the next release
