### ISSUE TITLE
raw sockets can't be disabled

### ISSUE THREAD

**Issue by ntinti** [cbsd/cbsd#307]
FreeBSD version ( uname -a ):  11.2 Release
CBSD version ( cbsd version ): 11.2.0

Per default on FreeBSD allow.raw_sockets is disabled. CBSD enable it as default without the possibility to switch it off, there is no config setting, only "cbsd makeconf" shows that it is there.

```
     allow.raw_sockets
		     The jail root is allowed to create	raw sockets.  Setting
		     this parameter allows utilities like ping(8) and
		     traceroute(8) to operate inside the jail.	If this	is
		     set, the source IP	addresses are enforced to comply with
		     the IP address bound to the jail, regardless of whether
		     or	not the	IP_HDRINCL flag	has been set on	the socket.
		     Since raw sockets can be used to configure	and interact
		     with various network subsystems, extra caution should be
		     used where	privileged access to jails is given out	to
		     untrusted parties.
```

**Comment by olevole** [comment]
https://github.com/cbsd/cbsd/commit/373735113a796e5f9ff1fa1ed465bd7b13ce3d70
https://github.com/cbsd/cbsd/commit/e28c28f238a9b912a89330b3d9d173f7c4a77863

open question: we need to select the default value

**Comment by ntinti** [comment]
Top :-)

**Comment by olevole** [comment]
commited to ports as 11.2.1
