### ISSUE TITLE
Missing IPv6 option

### ISSUE THREAD

**Issue by ntinti** [cbsd/cbsd#308]
Found only possibility to configure IPv4. What about IPv6 ? Therefore the freebsd  jail option "ip6.addr" exist
e.g.
	`ip6.addr = "2001:db8::2";`
analog to
	`ip4.addr = "192.0.2.3";`

**Comment by olevole** [comment]
IPv6 must work, use ip4_addr params for this, e.g:

~~~
cbsd jset jname=XXX ip4_addr="4f8:171:2985::5"
cbsd jset jname=XXX ip4_addr="10.0.0.29/24,2a01:4f8:171:2985::3/64,192.168.0.2,4f8:171:2985::9"
~~~

PS: Yes, I know the name of the parameter **ip4_addr** not the best for IPv6 ;-) This is a legacy from 2012y when CBSD only started and used only IPv6. It will be necessary to add one day **ip6_addr** or rename **ip4_addr** to **ip_addr** and do not break the compatibility
