### ISSUE TITLE
strange output with racct ctrl (jrctl-tui)

### ISSUE THREAD

**Issue by reablaz** [cbsd/cbsd#310]
Mandatory info for bug reports:

when setting resource limit for first time for jail, error message appears, while jail is saving config as expected. when "save changes" for second time (without changing anything) error message dissapears

root@host:/home/eb # cbsd jrctl-tui jname=matrix
jrctl formfile for matrix: updated
Set new quota for matrix:/zdata/jails/jails-data/matrix-data: 
cannot set property for 'zdata/jails/matrix': bad numeric value ''
set resource limit: [ ]
root@host:/home/eb # cbsd jrctl-tui jname=matrix
jrctl formfile for matrix: updated
set resource limit: [ ]
root@host:/home/eb #

FreeBSD version ( uname -a ): 11.2

CBSD version ( cbsd version ): 11.2.0

**Comment by olevole** [comment]
Fixed in GH, Thanks!
