### ISSUE TITLE
bhyve dhcp

### ISSUE THREAD

**Issue by sturican** [cbsd/cbsd#322]
Доброго дня!

Добрался наконец попробовать виртуалки через cbsd.
Поставил centos, проблема с сетью в гостевой ос.
Прошу помощи, из коробки не должно работать? Выставлено auto и dhcp. 
При старте вижу ошибку: IP DHCP not identified

cbsd@bi> version
version
11.2.1

С запущенной гостевой ос ifconfig:
bridge1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: nfe1
        ether 02:14:9b:5b:e1:01
        nd6 options=1<PERFORMNUD>
        groups: bridge 
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: tap2 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 7 priority 128 path cost 2000000
        member: tap1 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 6 priority 128 path cost 2000000
        member: nfe1 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 2 priority 128 path cost 20000
tap1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: CBSDSYSTEM0
        options=80000<LINKSTATE>
        ether 00:bd:0a:00:2c:01
        hwaddr 00:bd:0a:00:2c:01
        inet6 fe80::2bd:aff:fe00:2c01%tap1 prefixlen 64 scopeid 0x6 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: no carrier
        groups: tap 
tap2: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: dev-nic0
        options=80000<LINKSTATE>
        ether 00:bd:71:d6:6f:02
        hwaddr 00:bd:71:d6:6f:02
        inet6 fe80::2bd:71ff:fed6:6f02%tap2 prefixlen 64 scopeid 0x7 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: active
        groups: tap 
        Opened by PID 43144

**Comment by olevole** [comment]
А сам dhcpd сервер поднят? CBSD не в состоянии рулить настройками внутри гвеста (без модификаций гвеста/ISO или без выключенного какого-нибудь cloud-init  который мало где включен по-умолчанию). Те, параметр ip4_addr в настройках виртуальной машины не играет роли без дополнительных телодвижений. Поскольку CBSD может и управляем MAC-адресом, пользоваться этим полем можно, но нужна ручная донастройка в виде подъема dhcpd сервиса:
https://www.bsdstore.ru/ru/articles/cbsd_vm_hook_dhcpd.html

**Comment by sturican** [comment]
Олег, спасибо! за ссылку, попробую.

**Comment by olevole** [comment]
Если по ссылке что непонятно - можно писать, поясню по мере возможностей)
