### ISSUE TITLE
Feature-Request NoVNC

### ISSUE THREAD

**Issue by ntinti** [cbsd/cbsd#328]
Integration of NoVNC to have  VNC access with a browser
https://novnc.com/info.html

**Comment by olevole** [comment]
In what form do you imagine integration noVNC with CBSD ? This applies to the WEB interface for CBSD and this has already been done two years ago with ClonOS project ( https://clonos.tekroutine.com/ )
Formally, ClonOS is WEB UI for CBSD (with noVNC for bhyve and for jail)

**Comment by ntinti** [comment]
Hi Ole

As a seperat feature? On MacOS I tried half a dozen VNC viewers before I found that the old „chicken <https://sourceforge.net/projects/chicken/files/>“ works.

I don't need ClonOS to administrate the option for jails and VMs with cbsd - cbsd does all the things very very well without a gui. but I need a working VNC to admisntrate the bhyve VMs themselves. Also it would be fine to have a independent VNC rescue interface if you build a vm for friends or customers.

Nicola

**Comment by olevole** [comment]
I still can not imagine integration. What exactly should we get from **CBSD** ? NoVNC is js-based script for proxy VNC <-> HTML5.  CBSD launch bhyve/XEN/jail and got VNC port for environment (this port available for user script via exported variables ( https://www.bsdstore.ru/en/12.0.x/wf_cbsd_variables_ssi.html ) and can be used via stop/start hooks ( https://www.bsdstore.ru/en/12.0.x/wf_jconfig_ssi.html#execscript ). In this regard, I believe the CDCS is flexible enough to expand the possibilities ( you can put script for launch/destroy novnc script in **master_poststart.d** / **master_prestop.d** directories, for example.

if you want something more - dashboard page with list of XEN/bhyve/jail with link to VNC for browser, then the integration of all this in the CBSD is quite difficult - we need manage WEB server (with secured access via basic auth or access/deny list), we need some kind of supervisor to manage noVNC process and we need some code for WEB. In other words, it is ClonOS ;)
Maybe I do not understand something, as it should be.

**Comment by ntinti** [comment]
OK - I understand - I will try the NoVNC Script.
