### ISSUE TITLE
При настройки сети не сохраняется значение

### ISSUE THREAD

**Issue by pautiina** [cbsd/cbsd#347]
При настройке сети виртуальной машины **bhyve** не сохраняется IP-адрес установленный в значение 0.
Визуально отображается, что значение установлено в 0, но когда запускаем команду: cbsd bls значение `IP4_ADDR` показывает **DHCP**. Если также в настройках зайти в IP-адрес там тоже стоит **DHCP**
Вчера до обновления все работало :)

FreeBSD version ( uname -a ):` FreeBSD cbsd 11.2-STABLE FreeBSD 11.2-STABLE #0 r338467: Tue Oct 16 10:11:02 EEST 2018     pautina@cbsd:/usr/obj/usr/src/sys/CBSD  amd64`

CBSD version ( cbsd version ): 12.0.0

**Comment by pautiina** [comment]
И так опытным путем была получена информация, что файл `~cbsd/var/db/local.sqlite` и файлы  `~cbsd/jails-system/$jname/local.sqlite` имеют разные значения при сохранении. Теперь вопрос, кому верить и как исправить?

**Comment by olevole** [comment]
надо проверить. Исторически данные были в ~cbsd/var/db/local.sqlite, но при миграции машин тяжело делать какой-то dump / restore данных чисто для мигрируемой (или клонируемой) машины из общей БД. Поэтому теперь ~cbsd/jails-system/$jname каталог, который хранит только данные конкретной виртуалки, хранит и настройки. Те, первоисточник теперь там, а в старый ~cbsd/var/db/local.sqlite пока что идет дубляж для back-compatible. 

Те, проблема в том что 'cbsd bls' ? Если стоит 0, она DHCP и должна показать. Правда, DHCP должна в итоге получать какой-то IP и реплейсить.

Можно еще попросить - зайти в 'cbsd bconfig' и там зайдя в ip4_addr посмотреть - что там? Если DHCP и ткнуть 'OK', он должен вписать вместо DHCP какой-то IP.

PS: при этом ip4_addr в bhyve бессмысленно без хуков типа такого ( https://www.bsdstore.ru/ru/articles/cbsd_vm_hook_dhcpd.html ), тк bhyve не в состоянии контекстуализировать настройки внутри виртуалки, может только по MAC адресу таким вот образом что-то дать. Впрочем, есть еще возможность сделать поддержку cloud-init, но его не все дистрибутивы by default имеют

**Comment by pautiina** [comment]
Меня тут научили одной штуке сейчас попробую показать. 
Вот первая часть, когда изначально стоял 0, потом через настройки я указал DHCP. IP-адрес назначился, но при повторном конфигурировании в нстройках стоял 0. Лучше раз увидеть.
![cbsd](https://user-images.githubusercontent.com/11805503/47315814-39c7f900-d64e-11e8-9356-2ee594691e50.gif)
И вот обратная сторона, когда сначала стояло DHCP, а потом на интерфейсе я решил назначить 0 на самом виртуальном сетевом интерфейсе. И тут я заметил, что настройки прекрасно применяются, когда я меняю ip4_addr в общих настройках виртуалки. а не в самом сетевом интерфейсе. 
![cbsd2](https://user-images.githubusercontent.com/11805503/47316503-f53d5d00-d64f-11e8-8347-253619007f1d.gif)

Вот посмотрел на свои тесты и сам теперь думаю, баг это или все-таки продуманная логика ?!

**Comment by olevole** [comment]
Вот бы все так issue оформляли, все сразу понятно с фильмом :-) значение 0 у bhyve неактуально, я уберу описание про 0 и валидацию добавлю. А по остальной части - это бага таки. Возьму таймаут на подумать-поправить, спс!

**Comment by olevole** [comment]
Так, со времени последнего апдейта по этой таске - cloud-init появился. Описание только что подправил. Рассинхрон при bset ip4_addr в разных SQLite3 я правил не очень давно, но искать лень. Верю, что в версии которая сейчас в портах - этот фикс имеется. Соотв, закрываю issue, спасибо!
