### ISSUE TITLE
Проблема с freebsd-update

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#351]
FreeBSD version ( uname -a ): FreeBSD 11.2-RELEASE-p4
CBSD version ( cbsd version ): 11.2.1

Имеется jail c baserw=1 и версией 11.0-RELEASE-p1.
Следую процедуре https://www.bsdstore.ru/en/12.0.x/wf_jupgrade_ssi.html, захожу в jail и пытаюсь сделать freebsd-update fetch
С удивлением вижу, что программа пытается обновить не 11.0, а 11.2 :
# freebsd-update fetch
src component not installed, skipped
Looking up update.FreeBSD.org mirrors... 2 mirrors found.
Fetching metadata signature for 11.2-RELEASE from update4.freebsd.org... done.
Fetching metadata index... done.
Inspecting system... done.
Preparing to download files... done.

The following files will be updated as part of updating to 11.2-RELEASE-p4:
/bin/freebsd-version
/usr/include/netinet6/in6.h
/usr/include/netinet6/ip6_var.h
/usr/include/x86/specialreg.h
/usr/sbin/wpa_supplicant
/usr/share/man/man4/inet.4.gz
/usr/share/man/man4/inet6.4.gz
/usr/share/man/man4/tcp.4.gz
/usr/share/man/mandoc.db

Аналогичная ситуация в случае запуска  freebsd-update -b /cbsd/jails-data/jail1-data ...
Кто виноват и что делать?

**Comment by olevole** [comment]
видимо утилита freebsd-update ориентируется на uname, что нехорошо для jail ;-( Надо подумать, можно ли тут что-то сделать, кроме как написать об этом на страничке про обновления.

**Comment by Peter2121** [comment]
И как же теперь обновлять jails c baserw=1? У меня их десятка полтора...
:(

**Comment by Peter2121** [comment]
А не исчезла ли в jails переменная окружения UNAME_r?
[https://www.freebsd.org/cgi/man.cgi?query=uname&sektion=3&n=1](url)
Логично было бы устанавливать ее при старте в значение, соответствующее версии базы jail...

**Comment by olevole** [comment]
1)
https://github.com/cbsd/cbsd/blob/develop/sudoexec/jstart#L604-L605

2)
https://github.com/cbsd/cbsd/blob/develop/sudoexec/jstart#L147-L224

**Comment by Peter2121** [comment]
[root@bsdjail ~]# uname -a
FreeBSD bsdjail.bimp.fr 11.2-RELEASE-p4 FreeBSD 11.2-RELEASE-p4 #0: Thu Sep 27 08:16:24 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
[root@bsdjail ~]# cbsd jlogin jail1
Last login: Mon Nov 12 18:01:14 on pts/3
FreeBSD 11.2-RELEASE-p4 (GENERIC) #0: Thu Sep 27 08:16:24 UTC 2018
jail1:/root@[10:31] # uname -a
FreeBSD jail1.domain.local 11.2-RELEASE-p4 FreeBSD 11.2-RELEASE-p4 #0: Thu Sep 27 08:16:24 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
jail1:/root@[10:31] # freebsd-version
11.0-RELEASE-p1
jail1:/root@[10:31] # cat /etc/make.conf
WRKDIRPREFIX=/tmp

**Comment by Peter2121** [comment]
[root@bsdjail ~]# cbsd version
11.2.1

**Comment by olevole** [comment]
@Peter2121 а есть клетки с baserw=0 ?

Дай, плз,вывод этих команд:

1) cbsd jls display=jname,baserw,ver,applytpl

2) cbsd jexec jname='*' file -s /bin/sh

3) cbsd jexec jname='*' uname -r

**Comment by olevole** [comment]
есть подозрение, что это baserw=1 специфик, тк там не менеджерится база и надо по ELF version анализировать, например с /bin/sh

**Comment by Peter2121** [comment]
Все те которые baserw=0 имеют одинаковые версии с хостами, они на других серверах.
1. JNAME   BASERW  VER   APPLYTPL
jail1  1       11.0  1
2. /bin/sh: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.0 (1100122), FreeBSD-style, stripped
3.11.2-RELEASE-p4

Корректно показывает версию /bin/freebsd-version : 
11.0-RELEASE-p1

**Comment by Peter2121** [comment]
Ну пока что обхожу проблему с помощью
freebsd-update -b /iocage/tags/rmailclone/root --currently-running 11.1-RELEASE-p15 -r 11.2-RELEASE upgrade

**Comment by olevole** [comment]
Я так-то понял что можно сделать, нужно ориентироваться по $data/bin/sh у клеток с baserw=1, иначе не понять что там за версия базы. И прыгать от нее. Поправлю наверное  в районе выхов, пока руки не доходят

**Comment by olevole** [comment]
Что-то типа

% file -s ~cbsd/jails-data/jail1-data/bin/sh
`/bin/sh: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 13.0 (1300002), FreeBSD-style, stripped`

вот 1300002 - это ELF версия. Или по-CBSD-шному:

> ~cbsd/misc/elf_tables --ver ~cbsd/jails-data/jail1-data/bin/sh
> ~cbsd/misc/elf_tables --freebsdver ~cbsd/jails-data/jail1-data/bin/sh

соотв, если ELF != хостер версии, значит внутри baserw базы контейнер по мажорной версии не совпадает с ядром и надо применять правку в make.conf

**Comment by olevole** [comment]
@Peter2121 оказывается, все так и работало, через elf. Единственное, что у меня проверялась мажорная версия. Учитывая что у вас хостер 11 версии и клетка, этот код делал return:

https://github.com/cbsd/cbsd/blob/develop/sudoexec/jstart#L154-L155

Попробуй проверить изменение по 
https://github.com/cbsd/cbsd/commit/943fd4d3d5fb8d6ab308ab8f5e1ab36927263223

Это файл /usr/local/cbsd/misc/src/elf_tables.c

после изменения, сделать `cbsd initenv`

и попробовать зарестартить какой-нибудь jail

**Comment by olevole** [comment]
Впрочем я уже сам проверил, работает. Засабмитил в порты как 12.0.1, https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233271 . Надо ждать пока подхватят.

**Comment by olevole** [comment]
доступно в портах

**Comment by Peter2121** [comment]
Супер, спасибо, буду проверять на неделе.
Остался один вопрос - почему версия проверяется по /bin/sh хотя есть как бы специально на это заточенная /bin/freebsd-version?

**Comment by olevole** [comment]
sh есть везде и всегда, даже если там linux или любое другое окружение. А freebsd-version - не факт, возможно какие-то KNOBS или freebsd-in-package могут и не приносить. Впрочем, я не изучал - этот код писался в 2014 году, freebsd-version появилась позже, в F10
