### ISSUE TITLE
jail construct: /var/run is not created inside jail

### ISSUE THREAD

**Issue by uropro** [cbsd/cbsd#361]
FreeBSD 12.0-RC3, CBSD 12.0.3

Jail creation does not create and populate /var/run of the jail. Am I doing something wrong in jconstruct-tui or is this a bug? It used to work on FreeBSD 11.2

**Comment by olevole** [comment]
can tell in more detail what are you waiting for ?

On my host:
~~~
% cbsd jconstruct-tui
% cbsd jstart jail1
% cbsd jexec jname=jail11 ls -la /var/run

total 24
drwxr-xr-x   5 root  wheel     15 Dec  5 12:36 .
drwxr-xr-x  24 root  wheel     24 Dec  5 12:36 ..
-rw-rw-r--   1 root  wheel      0 Dec  5 12:36 clean_var
-rw-------   1 root  wheel      5 Dec  5 12:36 cron.pid
drwxr-xr-x   2 root  wheel      2 Dec  5 12:36 dhclient
-r--r--r--   1 root  wheel    173 Dec  5 12:36 ld-elf.so.hints
-r--r--r--   1 root  wheel    139 Dec  5 12:36 ld-elf32.so.hints
srw-rw-rw-   1 root  wheel      0 Dec  5 12:36 log
srw-------   1 root  wheel      0 Dec  5 12:36 logpriv
drwxrwx---   2 root  network    2 Dec  5 12:36 ppp
-rw-------   1 root  wheel     80 Dec  5 12:36 sendmail.pid
-rw-------   1 root  wheel      5 Dec  5 12:36 syslog.pid
-rw-r--r--   1 root  wheel      0 Dec  5 12:36 syslogd.sockets
-rw-r--r--   1 root  wheel    197 Dec  5 12:36 utx.active
drwxr-xr-x   2 root  wheel      2 Dec  5 12:36 wpa_supplicant
~~~

**Comment by uropro** [comment]
When I do this, there is no /var/run at all. Actually, also in the first place: So the subject line should read: "no /var/run". The directory does not exist. When I manually create /var/run and restart the jail, then it works. But this is, of course, not the intended behaviour.

**Comment by uropro** [comment]
in jconstruct-tui I have set the OS version to "12.0-RC3", i.e. not "12.0". Could this make a difference?

**Comment by olevole** [comment]
![tty](https://user-images.githubusercontent.com/926409/49542190-efd96080-f8e5-11e8-8f57-524a93e6d34a.gif)

**Comment by olevole** [comment]
12.0-XXX is invalid for **ver** field. Just version, e.g:

11.2
12.0

or for stable:
11
12

as far as I know, 12.0 still not released yet, so base 12.0 still not exist on FTP.
you must use '12' as ver at the moment (2018-12-05)

probably because of this you are seeing problems

**Comment by olevole** [comment]
https://www.bsdstore.ru/en/12.0.x/wf_jcreate_ssi.html
> ver - FreeBSD version for the base (10.1, 11.0 for RELEASE or 10, 11 for STABLE)

**Comment by uropro** [comment]
Nice video, many thanks. I did exactly as you, for the base.txz I have used 12.0-RC3. But /var/run is still not created.

**Comment by olevole** [comment]
Well, still unclear for me. Looks like your base is broken. According to https://github.com/cbsd/cbsd/blob/develop/freebsd_world.subr , CBSD populate hier in jail by mtree(8) on <basejail>/etc/mtree/

For example when cbsd workdir = **/usr/jails** and arch/target_arch=**amd64** and ver=12, full path to var mtree:

/usr/jails/basejail/base_amd64_amd64_12/etc/mtree/BSD.var.dist

Can you checn this file for 'run' directory availability. For example, compare with hoster file: /etc/mtree/BSD.var.dist

Also, we can debug all CBSD action via sh xtrace. To do this, please execute as usual:

cbsd jconstruct-tui
> enter jname
> enter ver (12)
GO for process

**BUT** choose 'NO' for 'Do you want to create jail immediately?' 

In this case, jconstruct-tui only will only save the configuration for 'jcreate' command.

Use full path to this file and execute jcreate with CBSD_DEBUG=1 flags to enable xtrace:

sh -c "env CBSD_DEBUG=1 cbsd jcreate jconf=/usr/jails/ftmp/jail22.55962.jconf > /tmp/out.txt 2>&1"

where /usr/jails/ftmp/jail22.55962.jconf  - path from jconstruct-tui

After this command, please post content of /tmp/out.txt (or send privately to my email: olevole at olevole dot ru)

Also, maybe also deletion/ re-creation of FreeBSD bases will help you:

cbsd removebase ver=12
cbsd repo action=get sources=base ver=12 

and try to create jail again

**Comment by olevole** [comment]
For example part from /etc/mtree/BSD.var.dist:

```
   preserve
    ..
    run
        dhclient
        ..
        ppp             gname=network mode=0770
        ..
        wpa_supplicant
        ..
    ..
    rwho            gname=daemon mode=0775
    ..
    spool
~~~

by the way. problem only with /var/run ? Other directory in /var ( for example /var/spool) - ok ?

**Comment by uropro** [comment]
spool is also not complete. 
mtree looks the same as yours.
I have sent you email with the trace output,
will try the base recreation...

**Comment by uropro** [comment]
I did execute "cbsd repo action=get sources=base ver=12", it loaded the base from your server since there is no 12-RELEASE on the freebsd-mirros. But the jail created with "ver=12" looks the same: /var/run inexistent, /var/spool incomplete etc.

**Comment by olevole** [comment]
lol:

```
+ /usr/sbin/mtree -deU -f /usr/jails/basejail/base_amd64_amd64_12.0/etc/mtree/BSD.var.dist -p /usr/jails/jails-data/testjail-data/var
mtree: unknown user `ntpd'
mtree: failed at line 49 of the specification
+ [ -f /usr/jails/basejail/base_amd64_amd64_12.0/etc/mtree/BIND.chroot.dist ]

```

your mtree failed due to no such **ntpd** user

I guess you upgrade from FreeBSD 11 (or any other but not 12.x ) to 12-RC3 ? if it is true, you forget to
```
20180719:
        New uid:gid added, ntpd:ntpd (123:123).  Be sure to run mergemaster
        or take steps to update /etc/passwd
```

from /usr/src/UPDATING

Please check this on the hoster:
~~~
% grep ntp /etc/master.passwd
~~~

you need to add:

ntpd:*:123:123::0:0:NTP Daemon:/var/db/ntp:/usr/sbin/nologin

via 'vipw' or by 'mergemaster' and add:

 ntpd:*:123:

into /etc/group.

**Comment by olevole** [comment]
notes for myself: hmm, a similar problem can also occur when hoster major version < major version of the jail, e.g on FreeBSD 11.2 somebody try to create 12.0 jail.

Probably **CBSD** should forbid it

**Comment by uropro** [comment]
host is FreeBSD 12.0-RC3. user ntpd exists exactly as shown above, also in /etc/group. (I did indeed do the merging of freebsd-update).
However, the user ntpd does not exist in the jail's /etc/master.passwd. But it exists in the base image...
Does CBSD use a differnt (old) master.passwd?

**Comment by olevole** [comment]
Can you check mtree without CBSD ? e.g:

mkdir /tmp/xxx
mtree -deU -f /usr/jails/basejail/base_amd64_amd64_12.0/etc/mtree/BSD.var.dist -p /tmp/xxx

**Comment by uropro** [comment]
Found the problem: The user ntpd existed in /etc/passwd and /etc/master.pwd, but not in the pwd.db / spwd.db files. Running 'vipw' and saving fixed it.  Now /var/run etc. gets populated and everything is fine.
Many thanks to Oleg for his help!

**Comment by olevole** [comment]
Cool! You are welcome ;)
