### ISSUE TITLE
pkgconf needed during initenv

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#362]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 11.2-RELEASE

CBSD version ( cbsd version ): 12.0.3

CBSD установлен из пакетов - пакет pkgconf не установлен (в порте sysutils/cbsd заявлен как build dependency).
При инициализации с использованием файла (`/usr/local/cbsd/sudoexec/initenv inter=0`) на Stage 2 пытается собрать cbsdsh с библиотеками sqlite3, но не может их найти так как `pkg-config: not found`. После ручной установки devel/pkgconf всё проинициализировалось корректно.

**Comment by Peter2121** [comment]
[https://www.freshports.org/sysutils/cbsd/](https://www.freshports.org/sysutils/cbsd/)
В Runtime dependencies отсутствует pkgconfig

**Comment by olevole** [comment]
Да, я так первым делом и делал, но коммитер порта не пропустил сославшись на uses. Надо посмотреть что не так с uses если она реально тру-вэй

**Comment by Peter2121** [comment]
Я подозреваю что USES предполагает вполне определённые виды зависимостей в зависимости от типа пакета. Поскольку обычно pkgconfig используется именно при сборке - он его туда по умолчанию и отправляет. Думаю должен быть какой-то способ сказать что USES именно для runtime.

**Comment by olevole** [comment]
Попробую при следующем обновлении протащить опять runtime_deps, может коммитер попадется лояльный) На самом деле, без pkgconfig жилось вполне неплохо и pkg-conf появился только вот по этой причине: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214551

Те, он нужен только чтобы узнать флаги компиляции/линковки sqlite3 чтобы использовать их в одной строчке, не более того. Оверхедно, но пока не нашлось лучшего решения чем предложение Pavel Volkov. Осталось накопить какие-нибудь изменения чтобы забампить следующий релиз. Спасибо за инфо

**Comment by olevole** [comment]
Ушло в порты с версией 12.0.4
