### ISSUE TITLE
Update jail with baserw=0

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#363]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 11.2-RELEASE-p5

CBSD version ( cbsd version ): 12.0.3

В соответствии с инструкцией [https://www.bsdstore.ru/en/12.0.x/wf_jupgrade_ssi.html](https://www.bsdstore.ru/en/12.0.x/wf_jupgrade_ssi.html) пытаюсь обновить 11.2 jail с baserw=0. Базу изначально скачал с официального репозитория:
`cbsd repo inter=0 action=get sources=base ver=11.2`
Получил world 11.2-RELEASE.
Пытаюсь обновить по инструкции:
`cbsd repo action=get sources=base mode=upgrade`
Снова скачивается и разархивируется тот же world.
На хосте 11.2-RELEASE-p5.
Как получить 11.2-RELEASE-p5 в базе jail'а?

**Comment by olevole** [comment]
Я не слышал/не знаю, выкладывают ли release engineer  архивы base.txz именно с path-level, -p1, -p2. Все что доступно cbsd  - это официальный ftp.freebsd.org, оттуда и тащит.

http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/11.2-RELEASE/

Я предполагаю, что это base.txz на момент среза/релиза и больше его не трогают.

Учитывая, что basejail это просто chroot/rootfs каталог с полной иерархией, один из вариантов сопровождать патчи - это пользоваться freebsd-update. Тут я описывал пример ( https://www.bsdstore.ru/en/12.0.x/wf_jupgrade_ssi.html#freebsd-upgrade ).

Ну и  вариант, который в cbsd по-дефолту с самого начала - это компиляция из сырцов:

cbsd srcup   ( счекаутит к ~cbsd/src/ дерево сырцов )
cbsd world ( по сути это cbsd buildworld + cbsd installworld )

**Comment by olevole** [comment]
upd: у меня в планах ввести поддержку обновления base-in-packages, я с этим уже 4 года живу и успешно обновляю базовую систему, но пока нет времени чтобы сделать

**Comment by Peter2121** [comment]
Ну, то что base.txz может быть с обновлениями - на эту мысль меня натолкнул тот факт что при установке новой системы она уже со всеми патчами базы сразу. Но не исключено что во время установки там вызывается апдейт.

> Учитывая, что basejail это просто chroot/rootfs каталог с полной иерархией, один из вариантов сопровождать патчи - это пользоваться freebsd-update.

Было бы круто обернуть это в cbsd ;)

> если инфраструктура больше чем 1 локалхост, то вполне разумно выделить какую-то машинку на сборку своих base.txz

Это в планах :)

**Comment by olevole** [comment]
Кстати да, дельная мысль после фетча применить  fetch-update :-)

**Comment by Peter2121** [comment]
Не, ну это тоже неплохо, но я имел в виду что можно предусмотреть команду cbsd для апдейта базы, со всеми необходимыми отмонированиями и примонтированиями.

**Comment by olevole** [comment]
Кажется, Goran Mekić это делал - он вливал https://github.com/cbsd/cbsd/blob/develop/tools/baseupdate скрипт. Но я не пользовался этим и вроде Горан говорил что там есть что доделывать.
Но спс за предложение - посмотрю что можно улучшить, такие брейнштормы оч полезны проекту)

**Comment by olevole** [comment]
Добавлена конфига в etc/defaults/FreeBSD-bases.conf: https://github.com/cbsd/cbsd/blob/develop/etc/defaults/FreeBSD-bases.conf

в которой имеется регулятор желаемого поведения:

auto_baseupdate=[0|1] , которую можно переназначить через etc/FreeBSD-bases.conf.

По ряду причин, это выключено по-умолчанию (не все имеют интернет, люди могут предпочесть обновлять со своих репозиториев собранные ими же бинари (на которые патчи не встанут) или обновляют через .txz на файловой системе. Да и вообще, когда система слишком много делает и лезет куда-то в интернет - не очень хорошо по-дефолту).

+ немного переработана обработка источников для забора base.txz в рамках этой таски: https://github.com/cbsd/cbsd/issues/367

+ baseupdate я проверил и немного запатчил как надо. В 12.0.4 будет входить

**Comment by olevole** [comment]
commited to ports tree: 12.0.4

**Comment by Peter2121** [comment]
Случайно заметил что `cbsd --help` не знает о существовании `cbsd baseupdate` ;)

**Comment by olevole** [comment]
> Случайно заметил что `cbsd --help` не знает о существовании `cbsd baseupdate` ;)

Ога: https://github.com/cbsd/cbsd/commit/df7e11dc7aa00f2a7bc0697f4f1fc6495316eb00
