### ISSUE TITLE
Featurerequest: Importing small VM's from img or iso disk image

### ISSUE THREAD

**Issue by Doralitze** [cbsd/cbsd#365]
Mandatory info for bug reports:
It would be a nice feature if one would be able to create / import VM's giving a hard drive dump (as .img of .iso file for example) in order to test firmware images.

FreeBSD version ( uname -a ):
FreeBSD case.nobreakspace.org 11.2-RELEASE-p4 FreeBSD 11.2-RELEASE-p4 #0: Thu Sep 27 08:16:24 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

CBSD version ( cbsd version ): 
11.2.1

**Comment by olevole** [comment]
Can you explain what “hard drive dump” means? what exactly is it created and what is the format?   maybe some real life example of this case?

**Comment by Doralitze** [comment]
Hard drive dump means a file of the follwing format (a real live firmware build): https://luebeck.freifunk.net/firmware/0.9.5/sysupgrade/gluon-ffhl-0.9.5-x86-generic-sysupgrade.img.gz

It is created by a couple of automatic build scripts but could be obtained by attaching the flash of a device and using dd. For example (after flashing the device) the following command would result in the same file:

    # dd if=/dev/sda of=/tmp/ff-image.img

A different use case (not required by us but by many others) of such a feature would be downloading an disk image on any popular distribution website and using that specific image in order to not being required to execute the installer before testing or creating a VM from a real machine.

**Comment by T-X** [comment]
Commonly, the format would be a Master Boot Record (MBR). So executing the loader in the according section in an MBR of an image. Ideally, even UEFI booting would be supported.

By skimming some webpages briefly it seems that bhyve is supposed to be able to boot a UEFI image? At least here seems to be an example which uses and selects a UEFI bootrom capable of booting an image in UEFI format: https://wiki.freebsd.org/bhyve/UEFI

Could cbsd make use of this? (Or is this maybe supported already and we only have a misunderstanding? Booting an image file seems like a quite common usage for virtualization?)

**Comment by olevole** [comment]
> By skimming some webpages briefly it seems that bhyve is supposed to be able to boot a UEFI image? At least here seems to be an example which uses and selects a UEFI bootrom capable of booting an image in UEFI format: https://wiki.freebsd.org/bhyve/UEFI
> 
> Could cbsd make use of this?

Currently, CBSD supports UEFI- **_ONLY_** boot method for some reason.
Details: https://github.com/cbsd/cbsd/issues/323

**Comment by olevole** [comment]
Take a look on cloud-init support: https://www.bsdstore.ru/en/12.0.x/wf_bhyve_cloudinit_ssi.html
Use latest CBSD for that
