### ISSUE TITLE
Certificate error for bsdstore.ru

### ISSUE THREAD

**Issue by lbartoletti** [cbsd/cbsd#369]
Fetching base from bsdstore.ru is impossible:

```
REPO: https://bsdstore.ru
Found new mirror for 11.2: https://dl.bsdstore.ru
Looking for: https://dl.bsdstore.ru/releases/amd64/amd64/11.2/base.txz
Certificate verification failed for /CN=dl.bsdstore.ru
34370572288:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1925:
fetch: https://dl.bsdstore.ru/releases/amd64/amd64/11.2/base.txz: Authentication error
```

**Comment by olevole** [comment]
Hmm, with some upgrade of  **py36-certbot** on FreeBSD, default location for cert was changed from **/usr/local/etc/letsencrypt/live/** to **/etc/letsencrypt/live/**. I missed this moment.

Strange, a few years this line worked for me in cron:

`certbot-3.6 -n --agree-tos --email <myemail> --webroot -w /home/web/letsencrypt/ certonly -d dl.bsdstore.ru`

Fixed, thank you!
