### ISSUE TITLE
Feature request: passwordless node connect

### ISSUE THREAD

**Issue by ntinti** [cbsd/cbsd#377]
Hey

I do not want to allow password based ssh logins, only with ssh pub key. But then I can't use the cbsd nodes system.

**Comment by olevole** [comment]
new args added for node script: cbsdkeyfile= , e.g:

`cbsd node mode=add node=XXX cbsdkeyfile=<path_to_id_rsa>`

of course, the nodes must exchange keys first for cbsd user.

**Comment by olevole** [comment]
commited to ports: https://svnweb.freebsd.org/ports?view=revision&revision=499381
