### ISSUE TITLE
Unknown parameter: allow.mount.tmpfs

### ISSUE THREAD

**Issue by Astaoth** [cbsd/cbsd#378]
Hi here !

Yesterday, I upgraded my FreeBSD server from the v11.2 to the 12.0. After having completed the upgrade, when I try to start a jail with cbsd, I have this error : 
root prompt: > cbsd jstart test1
Default NIC automatically selected: bge0
Applying /usr/ports/CHANGES -A28 ^20140930 work-around
Starting jail: test1, parallel timeout=5
jail: test1: unknown parameter: allow.mount.tmpfs

And next, when I check, the jail isn't launched. I don't know which version of cbsd I had before the system upgrade. Have you any clue of why this problem appeared ?

FreeBSD version ( uname -a ): FreeBSD 12.0-RELEASE-p2 FreeBSD 12.0-RELEASE-p2 GENERIC  amd64

CBSD version ( cbsd version ): 12.0.3

Cheers

**Comment by Astaoth** [comment]
I made a test with a ln -s /bootpool/boot /boot and it works. So this is not a bug related to CBSD but to the upgrade process to FreeBSD 12 with zfs.
Sorry for the noise !

**Comment by olevole** [comment]
Yes, this is some kind of massive problem when upgrading from 11 -> 12. Someone already wrote to me about it
