### ISSUE TITLE
CentOS 7 starts in VNC mode even if port=1

### ISSUE THREAD

**Issue by mathiasp** [cbsd/cbsd#389]
FreeBSD-RELEASE-p3, cbsd 12.0.3

Fresh install of both, creating a byhve instance, switching of VNC with vnc_port=1 the vm boots, but on cbsd blogin vm it says "VM started in VNC mode, but no VNC port found. Do you still want to connect to UEFI console?"
Saying yes shows me bhyve boot arguments, but gets me no console

How can I start CentOS in console mode? VNC is not workeable in my current setup.

Thanks,
Mathias

**Comment by olevole** [comment]
Hi Mathias!

This option seems to have suffered when I decided not to support the grub-bhyve method in CBSD. Ill try to check this in weekend. But overall, it seems that this should no longer work.

The reasons are quite serious (see: https://github.com/cbsd/cbsd/issues/323), and I often find confirmation that I did the right thing. ;-)

Why VNC is not workeable in current setup for you ?

**Comment by mathiasp** [comment]
Well, the server is at a remote location, and vnc on my local HiDPI display is, well, unreadable.
And I can't find a vnc client with actually working (= readable) scaling on FreeBSD.
And since I'm in hospital right now, I have no chance to use a lower dpi display.

One other question, just to check if it's worth staying with cbsd:
I have a working bridge with a routing setup from vm-bhyve experiments [1], but cannot choose it in bconstruct. Is there a way around that? Do I have to make it known to cbsd somewhere?

[1] https://github.com/churchers/vm-bhyve/issues/296

**Comment by mathiasp** [comment]
Oh, and thank you for your fast reaction, and for cbsd, which I would love to try. Looks great!
Although I don't like vnc installs: the less open ports the better!

**Comment by mekanix** [comment]
I'm successfully using custom configured bridge interface, but I still don't understand where "Permission denied" comes from.

**Comment by mathiasp** [comment]
Yes, I'm puzzled, too. 
But since the exact same machine is working with the routed setup described, I've stopped investigating.

**Comment by mathiasp** [comment]
;) Some puzzle, too: I guess the last two answers would belong here https://github.com/churchers/vm-bhyve/issues/296 ;)

**Comment by olevole** [comment]
tigervnc (  net/tigervnc ) works great as VNC client, you can try it - it is available on all platforms.
Also VNC resolution regulated via bconstruc-tui/bconfig -> VNC options >> bhyve_vnc_resolution

**Comment by mathiasp** [comment]
;) I know that, but, higher resolution does not change dpi... I can see the gui in tigervnc, but the fonts are so small that it's useless. And scaling with tigervnc does not lead to a readable font :(
But I'll try again to guess my way through the install...

**Comment by mathiasp** [comment]
Since this is a known, well, restriction in cbsd I'll close this.

**Comment by olevole** [comment]
@mathiasp Ok! Thanks, you are welcome ;)!
