### ISSUE TITLE
NAT configuration behaviour

### ISSUE THREAD

**Issue by Astaoth** [cbsd/cbsd#390]
Hi !

I have identified few weird or annoying behaviours of CBSD with a NAT configuration.

1. When, with cbsd natcfg, the nat interface is an interface and not an IP address, then /usr/jails/etc/ipfw.conf and /usr/jails/etc/pfnat.conf are rewriten to there original state at every boot or use of the "cbsd naton" command.
When with cbsd natcfg, it's an ip address which is defined, /usr/jails/etc/ipfw.conf isn't rewriten.

2. /usr/jails/etc/pfnat.conf is always rewriten with "cbsd naton" or a server reboot, there is no way to have some manual configuration (for example, I would like to indicate the right nated network)

3. When configuring a nat with ipfw, the nated networks are 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16. When configuring a nat with PF, the nated networks are 10.0.0.0/8 and 172.16.0.0/12.
When executing "cbsd natcfg", we should be able to choose what is the nated network. In my case, it's 192.168.254.0/24.

So in my case, I must stick with ipfw in order to configure my nat (because the nated network address is 192.168.254.0/24). However, with the default config adapted to my network and with the right ports exposed, the DNS jail can' t be joined. The server emits a ICMP answer about an unreachable host.
If I change the ipfw config and write the nat rule with an higher ID than the ones about the port forwarding, when the DNS answer come from the DNS jail and go to a client, an ICMP answer is generated from the client, saying "host administratively prohibited" (ICMP code 10).

So how can I either configure my nat with ipfw, or manually change the pfnat config and keep it when my server reboots ?

FreeBSD version ( uname -a ): FreeBSD localhost 12.0-RELEASE-p2 FreeBSD 12.0-RELEASE-p2 GENERIC  amd64

CBSD version ( cbsd version ): 12.0.3

Cheers,
Astaoth

**Comment by olevole** [comment]
Thx for issue.

I will try to check it out soon.

In fact, it is very difficult to combine automatic and manual configuration, as many scenarios are possible.
If you have your own fw rules, it is safer to disable automatic NAT from the CBSD.

Also, some stability (for mix auto/manual rule) can be added via include in pf (and/or maybe table in ipfw) as suggested by @Annakan:  https://github.com/cbsd/cbsd/issues/320#issuecomment-416929801 . However, I have not yet found the time for this.

**Comment by Astaoth** [comment]
Thank you for your answer. That what I have done : I have disabled CBSD nat configuration and I have manually defined my rules with PF.

I think if you can add the possibility to the user to indicate his nated network instead to consider all local network will be nated, it will be great.
And about the ipfw nat file (points 1 & 2), this behaviour is very confusing. Imo it will be better if either it can be always rewriten or never like the one of pfnat.

**Comment by olevole** [comment]
Small cleaning: mark this Issue as a duplicate https://github.com/cbsd/cbsd/issues/320, since the implementation of 'include' will allow us to solve any custom configurations. Thanks for reports!
