### ISSUE TITLE
bhyve-ppt causes instant reboot.

### ISSUE THREAD

**Issue by josephsimoneau** [cbsd/cbsd#397]
FreeBSD version ( uname -a ): 12.0-RELEASE-p3
CBSD version ( cbsd version ): 12.0.7 (installed via pkg Quarterly)

I'm attempting to run a pfsense VM with 2 of my intel NICs passed through.
/boot/loader.conf contains `pptdevs="101/0/2 101/0/3"`, and `vmm_load="YES"`
They show up in `cbsd bhyve-ppt mode=list`
`pciconf -l -v` shows them as ppt0@pci0:101:0:2 and ppt1@pci0:101:0:3

The commands I've tried (from the cbsd shell) are: 
bhyve-ppt mode=attach jname=pfsense1 ppt=101/0/2
bhyve-ppt mode=attach jname=pfsense1 ppt=101/0/3
bhyve-ppt mode=attach jname=pfsense1 ppt="101/0/2 101/0/3"

Each of them causes an instant reboot. Once the host comes back up, they don't show up in the VM, though they're still visible in list mode.

Any ideas?

**Comment by olevole** [comment]
Instant reboot when you exec 'bhyve-ppt' + bstart ? Or when doing 'cbsd bhyve-ppt' ?
The second is very strange behavior because 'bhyve-ppt' just save information into SQLite3 db.
Parameters are applied only with the 'cbsd bstart' command

**Comment by josephsimoneau** [comment]
Immediately after any of those bhyve-ppt commands. It is very strange....hence posting here. 

After the host comes back up, the VM will start but without those devices passed through.

Is there any log file or debugging output I can post to help figure it out? Is there anything specific I have to do in bconstruct-tui to allow it?

**Comment by olevole** [comment]
bhyve-ppt not a dangerous operation (does nothing with system but work with SQLite3):

https://github.com/cbsd/cbsd/blob/v12.0.8/tools/bhyve-ppt

Although there may be a problem here: https://github.com/cbsd/cbsd/blob/v12.0.8/tools/bhyve-ppt#L82-L84

https://github.com/cbsd/cbsd/blob/v12.0.8/virtual.subr#L423

via acpidump we check availability of DMAR table. Can you try to execute this command in FreeBSD shell?

`/usr/sbin/acpidump -t | /usr/bin/grep DMAR`

**Comment by josephsimoneau** [comment]
Yep.

That also caused an instant reboot. I did look through the script, but I didn't think that particular line was doing something that would cause a crash.

Any idea why it's happening?

It looks like it's just checking for VT-d. I just checked and VT-d and SR-IOV are enabled in BIOS. Is it safe to just disable that check, or is it indicating that something about the setup is wrong?

**Comment by olevole** [comment]
I think it makes sense to at least send an error message via http://bugs.freebsd.org about **acpidump** (and/or via freebsd maillist), and provide information about your system (for example, attach /var/run/dmesg.boot). Since the panic of the rock-stable OS  through the exec of userland utility is a problem :-)

As for ppt, you can try to comment this line:

https://github.com/cbsd/cbsd/blob/v12.0.8/virtual.subr#L423-L425

- check_dnar should return 1 for you. Then re-run 'cbsd initenv' and try to use bhyve-ppt again

**Comment by olevole** [comment]
close
