### ISSUE TITLE
jimport error

### ISSUE THREAD

**Issue by sturican** [cbsd/cbsd#400]
Mandatory info for bug reports:
Доброго дня! 
Писал в жаббер на olevole@jabber.ru, дублирую сюда:

`cbsd jimport jname=wordpress newjname=xxx`
вот такую штуку выдал: 
```
Importing image, please stand by: wordpress
CBSD Image, version: 4
Image was created on node: host.net
Image was created at: 20190424
Image size: 6g
Environment flat size after extracting: 7g
Compress level: 6
WIP: [0wordpress-data/usr/local/www/wordpress/xxx/usr/local/tmp/wordpress-mysql.sock: Hard-link target 'wordpress-data/usr/local/tmp/wordpress-mysql.sock' does not exist.
...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%...100%wordpress-data/usr/local/www/wordpress/yyyy/usr/local/tmp/wordpress-mysql.sock: Hard-link target 'wordpress-data/usr/local/tmp/wordpress-mysql.sock' does not exist....100%]
tar: Error exit delayed from previous errors.
data
```

при этом cbsd jls пустой, там хардлинки на сокет, понятно, что он ругнулся, но это же не фатально должно быть? 

С запущенным дебугом, концовка после tar (env CBSD_DEBUG=1)
```
tar: Error exit delayed from previous errors.
+ [ 1 -ne 0 ]
+ err 1 'imghelper error'
+ exitval=1
+ shift
+ echo 'imghelper error'
+ [ '' '=' 1 ]
+ exit 1
+ /bin/rm -f /zjails/tmp/imgpart-log.15063
+ _ret=1
+ printf ''
+ [ 1 -ne 0 ]
+ echo data
data
+ return 1
+ /bin/rm -f /zjails/tmp/jimport-log.36080
```

FreeBSD version ( uname -a ): 12.0-RELEASE-p3 FreeBSD 12.0-RELEASE-p3 GENERIC  amd64

CBSD version ( cbsd version ): 12.0.7

**Comment by olevole** [comment]
jabber что-то у меня забытый. С хард линком или unix sock по идее не фатально, надо проверять

**Comment by olevole** [comment]
В твоем случае за выход по ошибке это место отвечает:

https://github.com/cbsd/cbsd/blob/v12.0.17/tools/imgpart#L49

можно попробовать зачистить в ~cbsd/jails-data и ~cbsd/jails-system то что распаковалось от этой клетки, закомментить эту строчку в /usr/local/cbsd/tools/imgpart и после `cbsd initenv` попробовать еще раз заимпортить.

Если все пройдет, то все равно пока незнаю как лучше поступить )) tar просто возвращает код != 0 и где тут ошибка а где варнинг что там unix sock - непонятно. Надо ман покурить будет

**Comment by olevole** [comment]
еще я попробовал воспроизвести это и не смог

сделал клетку, в нем 

mkdir /usr/local/tmp
cd /usr/local/tmp
ln /usr/local/bin/mysql

+ там же unix.sock завел и по-живому сделал jexport. Что-то нет ошибок. Есть способ 100% воспроизведения? И желательно на последней cbsd)

**Comment by olevole** [comment]
а, я понял, ты хард линк сделал на unix socket ;-)

я сумел тоже:
mysql-data/usr/local/tmp/xxx.sock: Hard-link target 'mysql-data/usr/local/tmp/mysql.sock' does not exist.

**Comment by olevole** [comment]
В целом, я думаю что в CBSD делать нечего на эту тему. Вот простое воспроизведение и ожидаемая ошибка от tar:

1) не нашел как mknod-ой сделать unix sock, напишем на C что-нибудь что сделает unix sock:
```

mkdir /test
cd test
cat > test.c << EOF
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/un.h>
#include <string.h>

int main(int argc, char **argv)
{
        int sockfd, len;
        struct sockaddr_un local;

        sockfd = socket(AF_UNIX, SOCK_STREAM, 0);
        local.sun_family = AF_UNIX;
        strcpy(local.sun_path, "lol");
        len = strlen(local.sun_path) + sizeof(local.sun_family) + 1;
        bind(sockfd, (struct sockaddr *)&local, len);
        listen(sockfd, 0);
        return 0;
}
EOF
```

2) компилируем, запускаем
```
cc test.c
./a.out
```

3) видим внутри lol , который unix.socket:
```
file -s lol 
lol: socket
```

4) сделаем на него хард линк:
```
ln lol boo
```

5) запакуем:
```
cd /
tar cfz test.tgz test
: tar format cannot archive socket
```

6) распакуем в /tmp:
```
cp -a test.tgz /tmp
cd /tmp
tar xfz test.tgz
test/lol: Hard-link target 'test/boo' does not exist.
tar: Error exit delayed from previous errors.
echo $?
1
```

**Comment by olevole** [comment]
тут увы незнаю что делать с tar, предлагаю просто запомнить, что делать зард линки на unix socket - ненадо ;)

**Comment by sturican** [comment]
Спасибо!

Ну хардлинк не просто так взялся, если подскажете выход другой с радостью не буду делать хардлинки на мускуель сокеты :)

Суть какая, если php-fpm запускать в chroot, и мускуель база одна на все пулы, то как сделать без симлинка?

**Comment by sturican** [comment]
Ещё вариант, может попробовать к tar опцию добавить: --ignore-failed-read тогда он после нескольких ошибок спотыкаться не будет дальше, но в обычном поведении наверное это не очень хорошо, да?

**Comment by olevole** [comment]
Да,  --ignore-failed-read мне что-то не нравится)) Я мог бы смело и "tar ... || true " с тем же успехом сделать ( или не реагировать на != 0 errcode).

А jexport по-живому делается? Если нет, то можно наверное чистить при stop а при start создавать вновь. 

Про вариант без хард линка пока приходит на ум попробовать сделать shared folder (например:

mkdir /var/tmp-shared
chmod 0777 /var/tmp-shared
chmod u+t /var/tmp-shared

 мускуль настроить на сокет /tmp-shared/mysql.sock

и в ~cbsd/jails-fstab в соответствующих fstab.<jail>.local файлах что-то вроде такого:

`/var/tmp-shared /var/tmp-shared nullfs rw 0 0`

Но я это не проверял. Второй вариант - просто MySQL на TCP перевесить, тем более что если не тюнить 

net.local.stream.recvspace=
net.local.stream.sendspace=

то unix-socket на фре по дефолту медленнее чем по tcp, ЕМНИП


Еще я думаю, что в jexport можно попробовать добавить --exclude или конфиги где писать exclude. Чтобы можно было jexport-у указать какие локации внутри jail ненадо бекапить.

**Comment by olevole** [comment]
Пожалуй, запилить jexport с exclude будет правильным подходом. Когда-нибудь сделаю как время будет

**Comment by sturican** [comment]
Ага, спасибо за наводку(и)!

**Comment by sturican** [comment]
А да, по живому. Была бы миграция как через jcoldmigrate только чтобы клетка в слейв не переводилась, а для тестов там мало ли перетащить надо, было бы круто!

**Comment by olevole** [comment]
jcoldmigrate состоит из 

j2prepare
j2slave
+ jswmode (которая и меняет статус)

Так что можно пользоваться не ей, а 1 раз сделать j2prepare, а дальше в crontab пускать j2slave.

**Comment by sturican** [comment]
отлично, попробую, спасибо!
