### ISSUE TITLE
Не ясное поведение при обновлении cbsd из пакетов

### ISSUE THREAD

**Issue by xvfl8mzajp** [cbsd/cbsd#404]
Mandatory info for bug reports:
При обновлении пакета, выводится сообщение о необходимости запуска `cbsd initenv`. Однако после запуска видно следующее:
```
[Stage 0: upgrading and migration data from 12.0.10 to 12.0.10]
```
что, по идее, говорит о завершении миграции на этапе установки. Но подтверждение этого в портах не нашёл, и вывода скрипта миграции на этапе установки не увидел. Возможно что-то работает не так.

Полный вывод скрипта миграции:
```
-------[CBSD v.12.0.10]-------
 This is install/upgrade scripts for CBSD.
 Don't forget to backup.
-----------------------------
Do you want prepare or upgrade hier environment for CBSD now?
[yes(1) or no(0)]
1
>>> Installing or upgrading
[Stage 0: upgrading and migration data from 12.0.10 to 12.0.10]
  * Update local::bsdsrc: source
[Stage 1: account & dir hier]
 * Check hier and permission...
[Stage 2: build tools]
[Stage 3: local settings]
[Stage 4: update default skel resolv.conf]
[Stage 5: refreshing inventory]
[Stage 6: authentication keys]
[Stage 7: modules]
[Stage 9: cleanup]
 * Remove obsolete files...
[Stage X: upgrading]
>>> Done
```

FreeBSD version ( uname -a ): `12.0-RELEASE-p3 FreeBSD 12.0-RELEASE-p3 GENERIC  amd64`

CBSD version ( cbsd version ): `12.0.10`

**Comment by olevole** [comment]
Привет. Спасибо, исправлено. Регрессия была вызвана работой по добавлению множественных рабочих каталогов, в результате которой часть файлов была удалена в рабочем каталоге как дубликат из /usr/local/cbsd. В одном из этих файлов сохранялась старая версия, она и была утеряна.
