### ISSUE TITLE
Incorrect size shown on export jail

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#405]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 11.2-RELEASE

CBSD version ( cbsd version ): 12.0.5

При экспорте "толстого" jail'а некорректно показан размер образа:
`environmets flat size: 0, images size mail-clone.img: 2g`
Если сжатый образ занимает 2 Гига - вряд ли несжатый весил 0 ;)
Кстати, надо бы заодно опечатку в "environmets" исправить ;)

**Comment by olevole** [comment]
есть возможность проверить на последней версии (12.0.10) ? Тк в каких-то свежих версиях были правки связанные с объемом. Единственное, что свежей версией не только надо распаковывать, но и запаковать - ошибка была в jexport

**Comment by Peter2121** [comment]
Хорошо, обновлюсь и проверю.
Уточняю, ошибка при экспорте.

**Comment by olevole** [comment]
угу, в jexport и была проблема. еще, конечно, может от FS зависеть, если ZFS то объем датасета взять можно моментально, а в UFS - от 'du -sh ' я сразу отказался, тк jail может быть большим. Поэтому там считается объем обработанных данных и соотв, цифра пост-фактум только выходит, когда архив уже создан.

**Comment by olevole** [comment]
Опечатку да, поправлю как у настоящего компа буду)

**Comment by Peter2121** [comment]
У меня ZFS везде ;)

**Comment by Peter2121** [comment]
Проверил на 12.0.10 - точно так же
`environmets flat size: 0, images size mail-clone.img: 2g`

**Comment by olevole** [comment]
А мелкие jail на этой же инсталляции показывают не 0 ? Если это поведение только на толстом jail, есть подозрение на какой-нибудь integer overflow, в /bin/sh переменной, из-за количества байт.

**Comment by Peter2121** [comment]
Да, с мелкими все нормально. Я тоже думаю на переполнение чего-то, но не понимаю где и чего :)

**Comment by olevole** [comment]
@Peter2121 а какой оригинальный объем клетки?

zfs get used,referenced **dataset**

?

**Comment by Peter2121** [comment]
```
> zfs get used zroot/jais/mail

NAME             PROPERTY  VALUE  SOURCE

zroot/jais/mail  used      3.54G  -
```

**Comment by olevole** [comment]
@Peter2121 вся жопа в том, что у меня не воспроизводится ;-(

```
root@gizmo-lenovo:/ # zfs get used zroot/ROOT/default/fatcat
NAME                       PROPERTY  VALUE  SOURCE
zroot/ROOT/default/fatcat  used      52.8G  -
```

```
root@gizmo-lenovo:/ # cbsd jexport jname=fatcat compress=0
Exporting (with compress level:0), please stand by: fatcat
environment flat size: 105g, images size fatcat.img: 105g
jexport done in 18 minutes and 48 seconds
```

**Comment by Peter2121** [comment]
Да, архитектура x86-64.
Может быть не воспроизводится при экспорте без сжатия?

**Comment by olevole** [comment]
![fatcat_compress](https://user-images.githubusercontent.com/926409/58831958-8947bc00-8656-11e9-8478-f808e989c8cc.png)

Не, с компрессией тоже ок.

У меня на данный момент две мысли:

1) если ошибка имеет место быть, то вероятно, она как-то контентозависима. Например мильен мелких файлов внутри, вдруг это влияет. 

2) Я точно помню, что эта ошибка имела место быть и я ее когда-то правил, поэтому есть мысль также, что каким-то образом cbsd не обновила все файла в твоем окружении, например 'initenv' вроде бинарь не будет пересобирать если он уже есть. В cbsdtee может быть ошибка, я там long long добавлял. Можно попробовать еще вот так поступить:

cd /usr/local/cbsd
make clean
make
cbsd initenv

У меня в связи с п.2 есть большая просьба по возможности, проверить это поведение на каком-то другом хосте, где других версий кроме как 12.0.11 нет. И ею заэкспортить какой-нить пузатый контейнер. Тк продебажить что-то весь ход довольно проблематично.

**Comment by olevole** [comment]
@Peter2121 ping? есть возможность проверить то что я прошу?

**Comment by Peter2121** [comment]
Прошу прощения за тормоза.
Пересобрать cbsd могу попробовать, другого хоста, без старых версий, сейчас под рукой нет и сделать его негде (ибо для пузатого контейнера нужно место).

**Comment by olevole** [comment]
да, другого хоста ненадо, просто бинари пересобрать на рабочей 12.0.11 :
```
cd /usr/local/cbsd
make clean
make
cbsd initenv
```

и сделать jexport, наверное можно по-живому (ради проверки, но образ выкинуть после теста) чтобы не стопать.

**Comment by olevole** [comment]
@Peter2121 проверь тогда, пжлст, сразу на 12.0.12, я ее в порты влил только что.
после обновления все написанные шаги актуальны, пусть пересоберет еще раз бинари на всякий железный случай

**Comment by Peter2121** [comment]
Обновился до 12.0.12, пересобрал бинари как написано.
Проблема исчезла :)
```
environment flat size: 6g, images size mail.img: 6g
exported image file: /jails/cbsd/export/mail.img
jexport done in 12 minutes and 25 seconds

```
Благодарю за помощь!
