### ISSUE TITLE
SSH port

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#407]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 11.2

CBSD version ( cbsd version ): 12.0.9

При инициализации с использованием конфигурационного файла `initenv inter=0 cbsd.ini` по умолчанию модифицируется `/etc/rc.conf` - меняется порт сервиса SSH на 22222. Это не всегда нужно. Как я могу деактивировать эту модификацию? Код initenv смотрел, никаких идей не появилось...

**Comment by olevole** [comment]
да, давно хотел но руки не доходили.

https://github.com/cbsd/cbsd/commit/87f95f3d088ef3b564426fe74a791a100536c2cc

В 'preseed' конфиге теперь можно будет использовать так:

`
initenv_modify_sudoers="0"
initenv_modify_rcconf_hostname="0"
initenv_modify_rcconf_cbsd_workdir="0"
initenv_modify_rcconf_cbsd_enable="0"
initenv_modify_rcconf_rcshutdown_timeout="0"
initenv_modify_syctl_rcshutdown_timeout="0"
initenv_modify_rcconf_cbsdrsyncd_enable="0"
initenv_modify_rcconf_cbsdrsyncd_flags="0"
initenv_modify_cbsd_homedir="0"
`

^^ регулирует любые модификации.

Также, я выпилил предложение сменить SSH порт по-умолчанию, это было сделано в 2014 году когда cbsd была фокусирована на jail и кроме как ssh по-быстрому вариантов коммуникации я не видел). Сейчас это все депрекатед.

**Comment by Peter2121** [comment]
Спасибо, только что-то я ни вижу в списке переменных ничего насчёт смены порта SSH - эту функциональность  совсем выпилили?

**Comment by olevole** [comment]
Ага, это пусть будет на совести админа или конфиг-менеджеров типа ansible

**Comment by Peter2121** [comment]
Отлично :)
