### ISSUE TITLE
Отсутствует механизм update от слова совсем.

### ISSUE THREAD

**Issue by click0** [cbsd/cbsd#410]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
```# uname -a
FreeBSD cbsd1.XXXXXXX 12.0-STABLE FreeBSD 12.0-STABLE r347140 SUPPORT-12-0-1  amd64
```
CBSD version ( cbsd version ): 
```
# cbsd version
12.0.11
```

Отстутствует опция `cbsd update`!

Попытался, через git обновить:

```
[12:03]cbsd1:root-> local/cbsd# git clone https://github.com/cbsd/cbsd.git
Клонирование в «cbsd»…
fatal: unable to find remote helper for 'https'
```

Попытался через порты:
```
portsnap auto
cd /usr/ports/sysutils/cbsd
make
make install
made deinstall && make install
```

В итоге получаю новый, дефолтный конфиг (/usr/local/cbsd/share/initenv.conf) cbsd!!!!!!!!!!!

Также отсутствует версионное резервное копирование главных настроек-конфигов cbsd.

**Comment by olevole** [comment]
почему fatal: unable to find remote helper for 'https' я незнаю, возможно нет пакета ca_root_nss. Клонироваться должно. 

в cbsd update большого смысла нет, потому что:

a) мы делаем релизы, а не 'rolling release', те, cbsd обновляется в FreeBSD тем методом, которым обновляется абсолютно весь софт в FreeBSD - порты и pkg.

b) в Github идет разработка, там код не всегда может работать также хорошо как релизный. Но тем, кто все таких хочет использовать тот код - да git clone 1 раз и в дальнейшем 'git pull' - это тот самый 'update'. Кроме git clone надо проделать еще несколько ручных работ, описано в доке  на сайте: https://www.bsdstore.ru/ru/installing_cbsd.html

Поэтому, если нужна промежуточная development версия - надо разобраться, почему git clone не прошел.

Про резервное копирование с моей точки зрения тоже спорный вопрос. Мой 20-летний опыт админства и девопс показывает, что к бекапу системы нужно подходить комплексно, решая эту задачу отдельно. Те, софт не должен пытаться решить за человека совершенно все задачи там, где могут быть варианты. Здесь варианты - что именно бекапить, как много, как долго, куда бекапить, какие-то политики ротации и тд - все это гиганская работа, кому-то нужен будет бекап SQL, кому-то -всех контейнеров или bhyve/xen. Поэтому, вопрос бекапа также оставлен на совести оператора-администратора системы. На сайте есть вся информация о иерархии что и где находится и таким образом, можно решить самостоятельно содержимое бекапов. Любые другие продукты, как nginx, mongodb, redis, postgres, mysql/percona/maria/ и тд также ничего не бекапят самопроизвольно, но предоставляют информацию и утилиты (xtrabackup, pg_dump, mysql_dump, pg_basebackup, mongo_dump ), чтобы человек самостоятельно выбрал глубину бекапа, методы, политику ротаций и локации где хранить бекапы - самостоятельно. Не хочется делать CBSD исключением)

**Comment by click0** [comment]
Я очень разочарован ответом.
Буду пилить форк.
Уже полсотни правок есть.

**Comment by olevole** [comment]
Конкретные вопросы тогда:

- что не так с git clone и git pull ? Ошибка  'fatal: unable to find remote helper for 'https'' это частный случай, не зависящий от CBSD с которым нужно разобраться

- какие конфиги перезаписываются? Это баг, его надо исправить

**Comment by olevole** [comment]
вот иметь хук для кастомного скрипта (бекап) - идея неплохая, поэтому оформил https://github.com/cbsd/cbsd/issues/411

**Comment by olevole** [comment]
готово: https://github.com/cbsd/cbsd/commit/4436f73c3f68eaae5bf80da52b4f7e4ed32b2970

пример:

`mkdir ~cbsd/upgrade`

1)

> cat > ~cbsd/upgrade/post-initenv-test <<EOF
> #!/bin/sh
> date >> /tmp/post-initenv.log
> EOF
> 

2)

> cat > ~cbsd/upgrade/pre-initenv-test <<EOF
> #!/bin/sh
> date >> /tmp/pre-initenv.log
> EOF
> 


`chmod +x  ~cbsd/upgrade/*`


Доку на сайте обновлю когда время будет
