### ISSUE TITLE
Problem with cbsdd status pid

### ISSUE THREAD

**Issue by spagu** [cbsd/cbsd#417]
Mandatory info for bug reports:
```
#service cbsdd status
cbsdd is not running.
#ps -aux | grep cbsd
root  88131   0.0  0.0 15120  5512  2  S    21:00       0:00.02 /usr/local/bin/cbsd /usr/local/cbsd/tools/cbsdd
```

My setting of workdir in rc.conf:
```
cbsd_workdir="/usr/jails/cbsd"
```
Inside a `/usr/local/etc/rc.d/cbsdd` path to the pid is dafined as `pidfile="/var/run/$name.pid"` but pid is created here: `/usr/jails/cbsd/var/run/cbsdd.pid`

Possible fix:
```
# diff -u cbsdd.org cbsdd
--- cbsdd.org   2019-06-23 01:23:21.000000000 +0000
+++ cbsdd       2019-06-26 21:17:46.309212000 +0000
@@ -53,7 +53,7 @@
 extra_commands="restart"

 command="${toolsdir}/cbsdd"
-pidfile="/var/run/$name.pid"
+pidfile="${cbsd_workdir}/var/run/$name.pid"
 command_args="&"

 cbsdd_prestart() {
```

FreeBSD version ( uname -a ): 
FreeBSD 12.0-RELEASE-p4 FreeBSD 12.0-RELEASE-p4 GENERIC  amd64 ( latest )

CBSD version ( cbsd version ): 
CBSD version:         12.0.12

**Comment by spagu** [comment]
#418

**Comment by olevole** [comment]
Thx!
