### ISSUE TITLE
Jail does not start

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#427]
FreeBSD version ( uname -a ): 
11.2-RELEASE-p9

CBSD version ( cbsd version ): 
12.0.12

Периодически, остановленный для бэкапа jail не стартует :(

В логах - странная ошибка из консоли:
```
jail: mail: /bin/sh /etc/rc: timed out
mail: removed
```
mail - это имя jail'a

При попытке старта вручную - стартует через раз. Если не стартует - та же ошибка в консоли. Со второго раза как правило стартует.

Где копать??

**Comment by olevole** [comment]
сложно сказать, тк time out выдает не CBSD. Можно для начала попробовать исключить скрипты CBSD:

смонтировать FreeBSD base
1) mount -t nullfs -oro ~cbsd/basejail/base_amd64_amd64_12.0 ~cbsd/jails/mail   ( если 12.0-RELEASE )

смаунтить сверху индивидуальные jail локации
2) cbsd mountfstab jroot=/usr/jails/jails/mail fstab=/usr/jails/jails-fstab/fstab.mail (при условии что $workdir = /usr/jails )

можно руками написать jail.conf либо сгенерить через CBSD
3) cbsd makejconf jname=mail out=/tmp/jail.conf

Те, сейчас все готово для того, чтобы воспользоваться простым /usr/sbin/jail и запустить его так, как делает CBSD:

4) /usr/sbin/jail -f /tmp/jail.conf -c mail


Я только могу предположить что это какой-нибудь наймаут из разряда

exec.timeout = "180";

может на старт у rc тоже есть timeout по аналогии с rcshutdown_timeout. Но в любом случае если рубит по таймауту - то твой контейнер почему-то слишком уж долго стартует. Если реально в процессе старта висит а не сразу вываливается в 'time out' можно хотя бы ctrl+t понажимать, посмотреть кто и чем там занимается

**Comment by Peter2121** [comment]
Да, jail толстый и большой (mail server). Стартует долго. Поскольку проблема проявляется не всегда - ручные тесты мало что дадут. Я подозреваю что проблема в скорости доступа к дискам (это виртуалка на shared hosting) из-за которой долго стартует какой-то сервис (думаю что MySQL). Из-за этого другие сервисы подвисают на старте (ибо ждут когда MySQL поднимется).
Ну то есть вопрос сводится к тому где и как увеличить тот таймаут по которому оно вываливается.

**Comment by olevole** [comment]
ну вот я про exec.timeout только могу подумать, и он регулируется там же где и все другие параметры:

`cbsd jconfig` 

или jset:

`jset  jname=jail1 exec_timeout="600"`

**Comment by Peter2121** [comment]
Ну если это в секундах - то явно надо искать что-то другое. Там отваливается через минуту примерно, может быть даже меньше.

**Comment by olevole** [comment]
Можно попробовать куда-нибудь в freebsd-jail@ спросить. 

jailp.h:
```
#define JF_TIMEOUT      0x0200  /* A command (or process kill) timed out */
#define IP_STOP_TIMEOUT,        /* Time to wait after sending SIGTERM */
```
собственно наверное ошибка вот с этой строчки идет:

https://github.com/freebsd/freebsd/blob/master/usr.sbin/jail/command.c#L190

**Comment by olevole** [comment]
Закрою, поскольку незнаю что можно сделать со стороны CBSD. Если будет конкретная информация о параметре (если exec_timeout не сработает) и его нет в CBSD - переотрой плз.
