### ISSUE TITLE
cbsd initenv failed if tmux is missing  when upgrading to 12.1.0

### ISSUE THREAD

**Issue by nelson-ks** [cbsd/cbsd#431]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD freebsd-gw.my.domain 12.0-RELEASE-p8 FreeBSD 12.0-RELEASE-p8 GENERIC  amd64

CBSD version ( cbsd version ): 
12.1.0

I did an upgrade of cbsd from 12.0.13 to 12.1.0 from the ports.
When I ran cbsd initenv it failed with following:
```
-------[CBSD v.12.1.0]-------
 This is install/upgrade scripts for CBSD.
 Don't forget to backup.
-----------------------------
Do you want prepare or upgrade hier environment for CBSD now?
[yes(1) or no(0)]
1
>>> Installing or upgrading
[Stage 0: upgrading and migration data from 12.0.13 to 12.1.0]
[Stage 1: account & dir hier]
 * Check hier and permission...
cmdboot: no such executable: tmux
/usr/jails/cmd.subr: 29: Syntax error: end of file unexpected (expecting "fi")
/usr/jails/cmd.subr: 29: Syntax error: end of file unexpected (expecting "fi")
```

Then the cmd.subr was broken and the cbsd failed to ran afterwards.

The solution for me was to edit the cmd.subr (to end with fi) and install tmux.

Maybe the port was not updated with tmux as dependency?

Thanks for your great work.

**Comment by olevole** [comment]
Thx for the reports! This is already fixed on Github/develop but not included in the latest release. I will send a new port soon.

PS: and yes, tmux should remain optional because it is only for bhyve, this is a logical mistake in 12.1.0

**Comment by olevole** [comment]
12.1.1 bugfix release commited to ports. Thanks!
