### ISSUE TITLE
Not able to select 'DHCP' in cloud-init config of bconstruct-tui

### ISSUE THREAD

**Issue by mekanix** [cbsd/cbsd#435]
The dialog keeps returning static IP when entering 'DHCP'

**Comment by olevole** [comment]
@mekanix you mean 'real' DHCP server ? 'DHCP' value in ip4_addr used 'cbsd dhcpd' script which will return the first free IP from 'cbsd nodeippool' - this is correct behavior. 

regarding setting "use dhclient in VM" via cloud-init - it seems i haven't added it yet

**Comment by mekanix** [comment]
Ah, then it makes sense. As I already have DHCP server listening on that bridge interface, I thought 'DHCP' is for cases when you have a server. I would like to add that feature, but how should we represent it, as 'DHCP' means something else?

**Comment by olevole** [comment]
by the way, even if we add 'real' DHCP (dhclient) settings inside VM via cloud-init... Currently, I do not know how we can get information about what address is assigned to the virtual machine via DHCP server. Thus, for now, the cloud-init helper for static configuration. 

But you can manage cloud-init settings without  CBSD cloud-init form/helper in 'bconstruct-tui'. Just create/generate your own cloud-init in ~cbsd/jails-system/<vm>/cloud-init firectory. 

https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html#network-config-v1

with something like:
```
network:
  version: 1
  config:
  - type: physical
    name: eth0
    subnets:
      - type: dhcp
```
