### ISSUE TITLE
Не обновляются пакеты в jail-ах

### ISSUE THREAD

**Issue by xvfl8mzajp** [cbsd/cbsd#436]
Mandatory info for bug reports:
При вызове операции `cbsd pkg mode=upgrade jname='*'` не обновляются пакеты:
```
root@kaoru:/home/a* # cbsd pkg mode=upgrade jname='*'
Hint: Press 'Ctrl+t' to see last logfile line for active task
 * [jexec: pending: 2:[ todolist media-sv], active: 1:[ phab]]
phab: failed in 2 sec:

Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
New version of pkg detected; it needs to be installed first.
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
	pkg: 1.11.1 -> 1.12.0

Number of packages to be upgraded: 1

The process will require 15 MiB more space.
7 MiB to be downloaded.

Proceed with this action? [y/N]: 

todolist: failed in 1 sec:

Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
New version of pkg detected; it needs to be installed first.
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
	pkg: 1.11.1 -> 1.12.0

Number of packages to be upgraded: 1

The process will require 15 MiB more space.
7 MiB to be downloaded.

Proceed with this action? [y/N]: 
 * [jexec: pending: 1:[ media-sv], active: 0]
media-sv: success in 0 sec:

Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking for upgrades (0 candidates): . done
Processing candidates (0 candidates): . done
Checking integrity... done (0 conflicting)
Your packages are up to date.



Multiple pkg: done

```

FreeBSD version ( uname -a ): 
`FreeBSD kaoru.a*.local 12.0-RELEASE-p10 FreeBSD 12.0-RELEASE-p10 GENERIC  amd64`

CBSD version ( cbsd version ): `12.1.1`

**Comment by olevole** [comment]
у меня сейчас нет ни одной FreeBSD где можно проверить. Вот строчка которая работает:

https://github.com/cbsd/cbsd/blob/develop/modules/pkg.d/pkg.subr#L86

я незнаю какой там ключ еще добавить, кроме  -g -U -y

разве что могу предложить попробовать добавить ASSUME_ALWAYS_YES=yes  IGNORE_OSVERSION=yes, тк, написать эту строку так:

`env ASSUME_ALWAYS_YES=yes env IGNORE_OSVERSION=yes ${PKG_PRE} ${PKG_STATIC_PATH} ${PKGARGS} upgrade -g -U -y ${*}`

**Comment by xvfl8mzajp** [comment]
Если запустить `pkg` в `jail` с данными параметрами, она отрабатывает нормально. А автоматом через `cbsd pkg` не работает. Возможно дело в обёртке. Последняя версия на которой точно работало `12.0.14`

**Comment by olevole** [comment]
А то что я выше ответил - возможность проверить есть?

**Comment by xvfl8mzajp** [comment]
Работает
