### ISSUE TITLE
jrename fails

### ISSUE THREAD

**Issue by uropro** [cbsd/cbsd#438]
Trying to rename the stopped jail 'dbjail' to 'db2jail':
`cbsd jrename old=dbjail new=db2jail`

Output:

    RenameSwitch to ZFS pool
    cannot create '/usr/jails/jails-data/db2jail-data': leading slash in name
    cannot open '/usr/jails/jails-data/db2jail-data': leading slash in name
    rm: /usr/jails/jails-data/dbjail-data: Device busy
    .rmdir: /usr/jails/jails-data/dbjail-data: Device busy
    ok
    jrename done in 12 seconds

ZFS dataset name did not change; neither its mountpoint: 
`zfs list`

    zroot/ROOT/default/dbjail         723M   826G    88K  /usr/jails/jails-data/dbjail-data

/usr/jails/jails shows two empty directories 'dbjail' and 'db2jail'
/usr/jails/jails-data shows an empty 'dbjail-data'-directory and a populated 'db2jail-data' directory.
/usr/jajils/jails-fstab: Only file 'fstab.db2jail'
/usr/jails/jails-system: Only directory 'db2jail'
`cbsd jls` looks correct (JNAME and PATH is correct db2jail)

FreeBSD version: 12.0-RELEASE-p5
CBSD version: 12.1.1_1

**Comment by olevole** [comment]
this error seems to exist for a long time ;-(
Thanks! Fixed in GH.

https://github.com/cbsd/cbsd/commit/24ab17a6d26747ad7bfbae352a1fcac70ee96b7c
