### ISSUE TITLE
cbsd jexec jname="*" date    .... hangs.

### ISSUE THREAD

**Issue by uropro** [cbsd/cbsd#440]
Running above command will hang (all related pkg commands too).
I see two related processes, while the command hangs:
```
/usr/local/bin/sudo -E /usr/local/cbsd/sudoexec/jexec jname=* date
/usr/local/bin/cbsd /usr/local/cbsd/sudoexec/jexec jname=* date
```
Both processes are marked stopped ('T' in ps -aux).
Output on console:
```
# cbsd jexec jname='*`
Hint: Press 'Ctrl+t' to see last logfile line for active task
 * [jexec: pending: 2:[ myjail testjail], active: 0]
```
Running the command `cbsd jexec jname=myjail date` works.

FreeBSD version:  12.0 RELEASE p11
CBSD version: 12.1.1

**Comment by uropro** [comment]
running that command with `env CBSD_DEBUG=1 cbsd jexec jname='*' date` produces a lot of outputs, the last line being:
```
+ task 'mode=new' 'logfile=/usr/jails/tmp/jexec_multiple.myjail.log.61670' 'client_id=myjail' 'autoflush=0' 'owner=jexec_multiple' /usr/bin/env 'NOCOLOR=1' /usr/local/bin/cbsd jexec 'jname=myjail' date
```
The mentioned log file does not exist.

**Comment by uropro** [comment]
I just observe that the cbsd process consumes approx. 25% CPU time (info from "top"- command).

**Comment by olevole** [comment]
can you post output for:

```cbsd taskls```

?

I also have an idea to rewrite 'cbsd task mode=new' and cbsdd  with beanstalkd-based engine (minimalist broker, was demonstrated in https://www.bsdstore.ru/en/broker_driven_sample_ssi.html ). 

However, the current implementation should handle simple operations like this.

**Comment by olevole** [comment]
Currently, all parallel/massive commands work according to the following principle:

1) add cmd to queue,e.g:

`cbsd task mode=new date`

2) **cbsdd** process (daemonized shell/cbsd, /usr/local/etc/rc.d/cbsdd) watch via kqueue(2) for taskd.sqlite modification ( ~cbsd/var/db/cbsdtaskd.sqlite ) and wakeup when any new task is coming.

3) cbsdd execute commands with output to /tmp/*.log and update result/status.

3) jexec/jstart/jstop/... command just 'poll' job status and read /tmp/*.log when status 'complete'

**Comment by uropro** [comment]
The problem here was simple and stupid: cbsdd was not running...
