### ISSUE TITLE
bhyve and nmdm does not work

### ISSUE THREAD

**Issue by uropro** [cbsd/cbsd#441]
Creating a FreeBSD guest with cbsd bconstruct-tui and selecting **nmbd** as vm_console does not work. After starting the vm with `cbsd bstart myvm` I get the host console output:
```
bhyve renice: 1
can't find window: cu -l /dev/nmdm0B -s 9600
create window failed: index in use: 1
Waiting for PID.
PID: 63686
Use cbsd blogin webvm for attach to console
```
When trying to connect the console with `cbsd blogin myvm`, the tmux screen is opened. The output of the bootloader is shown and the start-command of the bhyve. The expected behaviour would be that the nmdm0B device is opened with cu.
Running `ps -aux | grep nmdm`shows:
```
root 45278    0.0  0.0   12352   3580  3  Is+  23:15      0:00.00 csh -c cu -l /dev/nmdm1B -s 9600
root 48530    0.0  0.0   10880   2492  3  I+   23:15      0:00.00 cu -l /dev/nmdm1B -s 9600
root 48690    0.0  0.0   10880   2488  3  I+   23:15      0:00.00 cu -l /dev/nmdm1B -s 9600
root 45658    0.0  0.0   12352   3580  4  Is+  23:15      0:00.00 csh -c cu -l /dev/nmdm0B -s 9600
root 48846    0.0  0.0   10880   2492  4  I+   23:15      0:00.00 cu -l /dev/nmdm0B -s 9600
root 48883    0.0  0.0   10880   2488  4  I+   23:15      0:00.02 cu -l /dev/nmdm0B -s 9600
```
Why are there two nmdm sessions?
When I kill these processes, I can connect to the vm with `cu -l /dev/nmdm0B -s 9600`

FreeBSD version ( uname -a ): 12.0 RELEASE p11
CBSD version ( cbsd version ): 12.1.1

**Comment by olevole** [comment]
It seems I forgot to remove this option from CBSD when I decided not to support the non-UEFI boot method ;-)   (details/motivation: https://github.com/cbsd/cbsd/issues/323 )

As long as I remember, nmdm ( serial console ) mainly used with bhyveload and grub-bhyve method ? can it work together with UEFI-GOP ?

it seems this can also be used with virtio-console, i still haven't tried this

**Comment by olevole** [comment]
BTW, if you prefer installation through the console/CLI, check out cloud-init way: https://www.bsdstore.ru/en/12.1.x/wf_bhyve_cloudinit_ssi.html#cloudinit_fromargs

**Comment by uropro** [comment]
I'd love to be able to run and operate at least a FreeBSD guest through the console (tmux). What is preventing cbsd from doing so? I have read Oleg's post in #323 and can understand it, but his motivation applies to Linux guests, not FreeBSD, if I understand correctly.
Could we find some work-around to get FreeBSD guest running under tmux? That would be great.
