### ISSUE TITLE
validate_jname bug

### ISSUE THREAD

**Issue by maxatome** [cbsd/cbsd#448]
It seems [`validate_jname` function](https://github.com/cbsd/cbsd/blob/develop/nc.subr#L451) is not correct.

Then, IMHO, it should return 0 on success to simplify its calls testing (supposed that empty string is not correct):
```sh
validate_jname()
{
	# [ -z "$1" ] && return 0    # if empty string should be accepted
	echo ${1} | ${GREP_CMD} -qvE "^[0-9-]|[E%^&\(\)+\/?><:\{\}=\.]"
}
```
And when it is used (0 status is correct now + arg correctly quoted):
```sh
# in sudoexec/jlogin
validate_jname "${jname}" || err 1 "${N1_COLOR}Bad jname${N0_COLOR}"

# in tools/jconstruct
if !validate_jname "${_input}"; then

# in settings-tui.subr
validate_jname "${_input}"
case $? in
	0)

# in jailctl/jscp
validate_jname "${jname}" || log_err 1 "${N1_COLOR}Bad jname: ${jname}${N0_COLOR}"

# in jailctl/bscp
validate_jname "${jname}" || log_err 1 "${N1_COLOR}Bad jname: ${jname}${N0_COLOR}"

# in modules/bsdconf.d/adduser-tui
validate_jname "${login}"
case $? in
0)
```
I can fill a PR if you're interested.

Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD any 12.1-RELEASE-p1 FreeBSD 12.1-RELEASE-p1 GENERIC  amd64

CBSD version ( cbsd version ): 12.1.2

**Comment by mekanix** [comment]
I think it's easier to follow with the PR, so please send it.

**Comment by maxatome** [comment]
Done with #449

**Comment by olevole** [comment]
@maxatome Thank you for debug/review, it looks reasonable to me!

**Comment by olevole** [comment]
probably solved?
