### ISSUE TITLE
проблемы после обновления cbsd до 12.1.2

### ISSUE THREAD

**Issue by sturican** [cbsd/cbsd#450]
Mandatory info for bug reports:
После обновления cbsd initenv
на любой команде jls, cbsd и тд. вылетает ряд ошибок:

`cbsd`
`/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/pkg_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/bsdconf_enabled=NO: not found
/zjails/nc.inventory: mod_/zjails/modules/zfsinstall_enabled=NO: not found`

на cbsd jls подобное плюс: 
`printf: Illegal option - 
printf: Illegal option - 
printf: Illegal option - 
printf: Illegal option - 
printf: Illegal option - 
printf: Illegal option -`

Что можно попробовать сделать?

FreeBSD version ( uname -a ): 
11.2-RELEASE-p7 FreeBSD 11.2-RELEASE-p7

CBSD version ( cbsd version ): 
12.1.2

**Comment by Dorlas** [comment]
cbsd initenv заново сделать ?

**Comment by Dorlas** [comment]
Переместить nc.inventory из корня CBSD и снова cbsd initenv

**Comment by olevole** [comment]
возможно еще 

make -C /usr/local/cbsd

пригодится до `cbsd initenv`

сложновоспроизводимая бага, я незнаю где проблема но мув ~cbsd/nc.inventory и переинициализация через 'cbsd initenv' должна спасти

**Comment by sturican** [comment]
удалил из nc.inventory снизу: 
`mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/pkg_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/bsdconf_enabled="NO"
mod_/zjails/modules/zfsinstall_enabled="NO"`

потом сделал `cbsd initenv`

Всё заработало, спасибо. 

Единственное при cbsd jls вываливает сверху немного ошибок:

`cbsd jls
printf: Illegal option - 
printf: Illegal option - 
printf: Illegal option - 
printf: Illegal option - 
printf: Illegal option - 
printf: Illegal option - 
NODENAME             JNAME `

**Comment by olevole** [comment]
мне кажется, такой вывод в `jls` может возникнуть когда в SQLite3 информация об окружении есть, а в виде файлов ( персональный sqlite3 база в ~cbsd/jails-system/<XXX> ) - нету.

Можно проверить это например запросом в основную БД:

```
sqlite3 ~cbsd/var/db/local.sqlite "SELECT jname FROM jails"
```

По всем этим записям CBSD пробует открыть персональный sqlite3:

```
file -s ~cbsd/jails-system/<jail>/local.sqlite
```

- если такого файла нет, скорее всего к подобному выводу и приведет. Если реально есть какой-то битый jail, можно удалить врукопашную запись о нем:
```
sqlite3 ~cbsd/var/db/local.sqlite "DELETE FROM jails WHERE jname='badjail'"
```

**Comment by olevole** [comment]
Еще кстати такой вывод может быть, если добавлена нода ( cbsd node mode=add ) и версии между этими CBSD не синхронизированы - те, на локальной машине версия CBSD не совпадает с удаленной - поэтому рассинхрон в схемах. Если нода есть по
```
cbsd node mode=list
```

то либо обновить удаленную тоже и запустить синхру руками ( cbsd retrinv ), либо просто отлинковать ноду через

```
cbsd node mode=delete ..
```

**Comment by sturican** [comment]
> file -s ~cbsd/jails-system/<jail>/local.sqlite

тут всё нормально, битых не нашлось.

А вот с нодами да, ноды имеются. И одна disconnected... 12.1.1

Спасибо!

**Comment by sturican** [comment]
Ещё вопрос, в /var/log/messages завален подобными сообщениями:
cbsd[20336]: cbsdd: update remote inventory for 192.168.20.20 via loop_per_retrinv [10]
это когда nodы как раз есть. Их можно как-то задисаблить? Это же уведомления, а не ошибки я так понимаю?

**Comment by olevole** [comment]
Про уведомления - это просто notice, не ошибка. Уровень по идее можно регулировать через ~cbsd/etc/logger.conf (https://github.com/cbsd/cbsd/blob/develop/etc/defaults/logger.conf) но точно проверить ща не могу. В таком случае, если проблем больше нет, закрываю

**Comment by sturican** [comment]
попробую, спасибо!

**Comment by olevole** [comment]
насильно в stop - это только jstop, но если процесс там неубиваемый, скриптами cbsd тут не обойтись)) надо смотреть что это за неубиваемый процесс и в каком он состоянии ( procstat -kk <pid> )

**Comment by sturican** [comment]
php-fpm повесился. Самое интересное в state у него был nullfs повесился при service php-fpm reload ... но к cbsd это уже мало отношения конечно имеет :) про jstop понятно
