### ISSUE TITLE
Packages not installed in jail (sometimes)

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#452]
FreeBSD version ( uname -a ): 
11.3-RELEASE-p5
CBSD version ( cbsd version ): 
12.1.2

Использую cbsd в Ansible playbook для создания jail'а из ini файла. В этом файле присутствует параметр pkglist, который указывает на файл со списком необходимых пакетов. Всё делается автоматически, абсолютно одинаково каждый раз. 
НО! Примерно **в одном случае из 10** - jail создаётся, но кроме pkg других пакетов там нет!
Никаких ошибок не выводится, jail создан, но в нём (естественно) ничего не работает.
Проблема очень неприятная, поскольку в том самом jail'e должен потом отработать таск Jenkins'a, который естественно, вываливается в ошибку из-за отсутствия необходимых пакетов.
Я так понимаю что во время установки пакетов на этапе создания jail'a что-то иногда происходит (ну например репа недоступна из-за проблем с сетью). Нельзя ли об этом как-нибудь информировать, чтобы можно было ошибку ловить и разруливать?

**Comment by olevole** [comment]
Давай подумаем что можно сделать. Самое основное, о чем у меня мысли - не смотря на то что jcreate должна создавать jail и он создается, ошибки при работе pkg считать фаталом и таким образом возвращать ненулевой errcode и неправильный jail в итоге удалять. Тк вроде как, то что просили систему сделать - у нее не вышло. 

При этом это поведение придется отделить от возможных ошибок при pkg bootstrap, тк люди часто могут создавать jail с кривыми сетевыми настройками и pkg у них не пройдет - те, признак анализа кода pkg - только если при создании jail есть список ПО.

Либо можно попробовать post-фактум создания jail, если был список софта, отдельно по этому списку пробежаться на предмет проверки наличия каждого из перечисленного пакета. Составить список какого пакета нет и:

a) выдать варнинг с этим списком по окончанию отработки
b) застолбить за таким jail какой-то отдельный errcode, например *2*. И на выходе клетку не удалять, но и errcode выдать не 0.

Еще думается что можно хотя бы один retry сделать в pkg, но это уже из разряда костыля для чуть-чуть небольшого потенциального улучшения. 

PS: не в рамках обсуждения проблемы - если что, то CBSD поддерживает создание клетки из снапшота (zfs_snap параметр вроде в конфиге). Либо jclone - тоже может клонировать методом ZFS clone, возможно для твое задачи с нарезкой большого кол-ва jail есть резон это использовать - создаешь 1 раз в _сутки_месяц_вечность_ какой-то *gold* образ со всем софтом, а дальше клонишь на ее базе остальные - это 1-3 секунды на все

**Comment by olevole** [comment]
@Peter2121 а ты сам не смотрел почему ~10-й раз не проходит?Там output от pkg не должен мьютится, в stdout/err все идет. Сетевая ошибка? Может rate limit какой-то есть на GET на фряхины репы)

**Comment by Peter2121** [comment]
Посмотрел логи.
В любом случае, логи pkg при создании jail'a **не видно**. Ни в случае успешного (со всеми пакетами) ни в случае неуспешного создания (в этом случае присутствует только пакет pkg).
Я могу косвенно понять что "что-то пошло не так" исключительно из-за того что я после создания jail прописываю туда репу latest и делаю pkg upgrade. Соответственно, в случае проблемы там в логах ничего нет - обновлять нечего.
Наверное, правильно было бы выводить логи pkg который работает при создании jail.

Обнаружился ещё один интересный fail - вывод pkg просто обрывается "на полуслове":
```
"[build1.reseaucloud.local] [65/80] Fetching glib-2.56.3_6,1.txz: .......... done", 
"[build1.reseaucloud.local] [66/80] Fetching git-lite-2.24.1.txz: . done"
```
Это уже на стадии pkg upgrade с использованием latest.
Чуть позднее отвечу по предыдущим вопросам.

**Comment by Peter2121** [comment]
> не в рамках обсуждения проблемы - если что, то CBSD поддерживает создание клетки из снапшота (zfs_snap параметр вроде в конфиге). Либо jclone - тоже может клонировать методом ZFS clone, возможно для твое задачи с нарезкой большого кол-ва jail есть резон это использовать - создаешь 1 раз в сутки_месяц_вечность какой-то gold образ со всем софтом, а дальше клонишь на ее базе остальные - это 1-3 секунды на все

Да, я об этом думаю, для данной задачи, вероятно, это наиболее правильный путь. Надо написать сценарий Ansible и попробовать. Займусь. 
Но изначальную проблему тоже надо как-то решать ибо она может вылезти в других задачах, где клонирование не подойдёт.

**Comment by Peter2121** [comment]
> Давай подумаем что можно сделать. Самое основное, о чем у меня мысли - не смотря на то что jcreate должна создавать jail и он создается, ошибки при работе pkg считать фаталом и таким образом возвращать ненулевой errcode и неправильный jail в итоге удалять. Тк вроде как, то что просили систему сделать - у нее не вышло.
> 
> При этом это поведение придется отделить от возможных ошибок при pkg bootstrap, тк люди часто могут создавать jail с кривыми сетевыми настройками и pkg у них не пройдет - те, признак анализа кода pkg - только если при создании jail есть список ПО.

Мне кажется, это верный путь. Более того, логично будет возвращать ошибку и случае невозможности сделать pkg bootstrap - это ж вроде бы опция такая, соответственно, если она активирована - значит невозможность её осуществить это тоже fail. То есть, тот кто активирует pkg bootstrap должен позаботиться о том чтобы сетевой конфиг был верным. Можно показывать предупреждение в случае активации pkg bootstrap - типа если сетевая конфигурация некорректна - jail не будет создан. Ну и, кстати, как вариант - брать pkg c хоста.

> Либо можно попробовать post-фактум создания jail, если был список софта, отдельно по этому списку пробежаться на предмет проверки наличия каждого из перечисленного пакета. Составить список какого пакета нет и:
> 
> a) выдать варнинг с этим списком по окончанию отработки
> b) застолбить за таким jail какой-то отдельный errcode, например 2. И на выходе клетку не удалять, но и errcode выдать не 0.

Слишком сложно, и главное - непонятно что с этим всем делать в случае автоматических задач. Там надо или success или failure. А если вручную всё делается - так можно просто руками ещё раз запустить pkg install для всех пакетов.

> Еще думается что можно хотя бы один retry сделать в pkg, но это уже из разряда костыля для чуть-чуть небольшого потенциального улучшения.

Я думаю что это годный костылик. Более того, можно разделить задачу на две - сначала с несколькими retries скачать все пакеты (тут можно хоть бесконечный цикл retries сделать с выходом из него по какому-нибудь длииииииинному конфигурируему таймауту), а потом уже одну или две попытки непосредственно установки уже скачанных пакетов. Ибо скорее всего засада ожидает именно на этапе скачивания пакетов, а не на этапе непосредственно установки. Можно ещё в случае retries добавить в самом начале проверку доступности репы (или реп) и после нескольких фэйлов вываливаться в ошибку даже без запуска pkg.

**Comment by olevole** [comment]
сделал пару улучшений по этой задаче:

a) теперь pkg юзает *2* retry
b) ошибка при bootstrap не считается фатальной (тк бутстрап обычно включен при создании jail, но при этом усеры могут не юзать pkglist через который сразу ставят софт в jail - поэтому и не фатал)
c) ошибка при pkg install и других операциях - фатальна. Те, если при создании jail имеется ненулевой pkglist и произошла ошибка - jail удаляется.

+ количество retry, verbose вывод и само поведение фатал-не-фатал теперь регулируется через конфигу, если кого-то что-то не устроит ( пример: https://github.com/cbsd/cbsd/blob/develop/modules/pkg.d/etc-sample/pkg.conf ). Те, чтобы заоверрайдить дефолт, можно сделать cp -a /usr/local/cbsd/modules/pkg.d/etc-sample/pkg.conf ~cbsd/etc и там откорректировать параметры. 

Теперь поведение должно стать лучше

**Comment by olevole** [comment]
probably done, will be available in CBSD 12.1.3
