### ISSUE TITLE
Problem with sources for jails

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#455]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 11.3-RELEASE-p5

CBSD version ( cbsd version ): 12.1.2

Цель: смонтировать в каждый jail свои сорцы (ну то есть в 11.2 - сорцы от 11.2, а в 11.3 - сорцы от 11.3) желательно - обновлённые.

Обнаруживаю с радостью необходимую команду `cbsd repo`. Однако, "что-то пошло не так" :
```
# cbsd repo action=get sources=src ver=11.3
repo: you already have 11.3: /jails/cbsd/src/src_11.3
# cbsd repo action=get sources=src ver=11.2
repo: you already have 11.2: /jails/cbsd/src/src_11.2
```
Открываю `/jails/cbsd/src` - директория пустая. Совсем.

Проверяю результат активации опции `mount_src` в конфиге jail'a - ничего нового не смонтировано, в fstab у соответствующего jail'a никаких намёков на монтирование в jail `/usr/src` откуда бы то ни было.

Что я делаю не так??

**Comment by olevole** [comment]
Делаешь все так тута. Просто это было сделано очень и очень давно, когда src.tgz я на своем сервере выкладывал, а на FreeBSD.org ресурсах ничего небыло. Когда на freebsd.org стали выкладывать, я переделал чтобы забирало оттуда (а у меня и сервер пропал который билдил) - переделал kernel, bases, а до src тупо не дошел тк никому небыло нужды. Вижу что src.txz есть - https://download.freebsd.org/ftp/releases/amd64/12.1-RELEASE/ , надо доделать, ага

**Comment by olevole** [comment]
Кроме пока что неработающей 'cbsd repo',  средствами cbsd можно счекаутить сырцы через `cbsd srcup` (cbsd srcup ver=11.2, cbsd srcup ver=head, и тд) ( https://www.bsdstore.ru/ru/base_cbsd.html#obtain ) , но это выкачает через SVN (или git) и там избыток инфо из-за .svn или .git.

**Comment by Peter2121** [comment]
> Кроме пока что неработающей 'cbsd repo', средствами cbsd можно счекаутить сырцы через cbsd srcup 

Не, ну через SVN я и руками тоже могу :)
А куда `cbsd srcup` положит сорцы? В принципе, это неплохой вариант - там как минимум всё с апдейтами, а в `src.txz` - похоже нет. Мне, собственно, самое интересное - понять куда я могу сорцы положить внутри директории cbsd чтобы это не было затёрто при каком нибудь обновлении и было по фэн шую ;)

**Comment by olevole** [comment]
От апдейтов то в src тут не оч много профита, это ж сырцы) разве что врукопашную делать cd /usr/src/<..>  и пересобирать патченную утилиту. Пути можно тоже глянуть запустив `cbsd srcup`, это

/usr/jails/src/src_12.1/src
/usr/jails/src/src_11.2/src

или если stable=1 ( RELENG ), то например будет так: /usr/jails/src/src_13/src (без минорной версии)

Я обычно делаю `cbsd srcup` и делаю `ln -s ~cbsd/src/src_12.1/src /usr/src` чтобы не дублировать в своей системе еще одну копию в /usr/src

**Comment by olevole** [comment]
поправлено, доделана операция `repo: action=get source=src [ver=xx.z]`

будет доступно CBSD 12.1.3

**Comment by Peter2121** [comment]
Version 12.1.5

Пытаюсь сделать:
`cbsd repo action=get source=src ver=11.2`

Отвечает:
`Give me sources`

Я что-то не так понял?

**Comment by olevole** [comment]
Все правильно отвечает)) см

`cbsd <cbsd> --help`

у repo нет опции source, зато есть sources
