### ISSUE TITLE
Question about /etc and upgrade

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#456]
Я правильно понимаю что `/etc` у `baserw=0` jail при запуске берётся из `jails-data/<jailname>/etc`, а содержимое в эту директорию в свою очередь копируется из `basejail/<version>/etc` при создании jail'a? То есть при апгрейде мне надо натравить `etcupdate` на `jails-data/<jailname>/etc`, используя в качестве референсов `basejail/<old-version>/etc` и `basejail/<new-version>/etc`?

**Comment by olevole** [comment]
/etc и у baserw=1 и у baserw=0 в качестве первоисточника берется из ~cbsd/basejail/ каталога, в котором по факту содержится иерархия после выполнения команд:

`make installworld + make distribution` таргетов из Makefile каталога */usr/src*

Если с помощью *etcupdate* стоит цель обновить /etc контент _непосредствено_ в jail, то и при baserw=0 и при baserw=1 он натравливается на сам jail: jails-data/<jailname>/etc, тк никаких референсов нет - копируется единожды при создании jail и больше не связан с ~cbsd/basejail содержимым.  Если же хочется обновить через *etcupdate* то, что для будущих jail-ов станет etc - то натравливается на ~cbsd/basejail/base_* каталог, тк это первоисточник.

PS: для вопросов лучше юзать телеговский чат или maillist, которые есть у проекта. Либо можно мне в личку на мыл, Issue на GH лучше использовать по назначению - для багов/идей.

**Comment by Peter2121** [comment]
> для вопросов лучше юзать телеговский чат

Мне показалось что в отсутствие доков по данному вопросу, будет уместно оставить это здесь ;)

**Comment by olevole** [comment]
Если каждый так будет делать, то тут начнется ад, как раз для этих целей чатик с мыллистом есть) К тому же, у проекта кроме меня есть еще пара контрибуторов (Горан например) и они не говорят по-русски, а на Issue могут реагировать)
