### ISSUE TITLE
cbsdd doesn't go to background ?

### ISSUE THREAD

**Issue by ntinti** [cbsd/cbsd#461]
FreeBSD version: 12.0 and 12.1
CBSD version ( cbsd version ):  12.1.x

cbsdd  doesn't go completely to background. Any few seconds there comes a WATCH and WAIT on the console

WATCH
WAKE
WATCH
WAKE
WATCH
WAKE
WATCH
WAKE
WATCH
WAKE
WATCH

and so on...

**Comment by mekanix** [comment]
To be a bit more precise, CBSD does go to background, but it continue to print WATCH/WAKE. If you press `<Enter>` you should have prompt, but I do agree, it's really, really annoying

**Comment by ntinti** [comment]
I can press ENTER but WATCH/WAKE continue...

**Comment by mekanix** [comment]
Yes, it continues, and it is a bug we will fix, what I tried to say is that cbsdd itself does go to background. I was only trying to describe the bug.

**Comment by mekanix** [comment]
On my machines, the reproducible way to get this is by running `cbsd initenv`.

**Comment by olevole** [comment]
it's true, CBSDD writes these messages from the background. its actual only for current session where cbsdd was started - for example, just logout and re-login.

Anyway, I remove this strings just now: https://github.com/cbsd/cbsd/commit/2348d13f3825a95d2e2f68a47acd1e353f3ac434

**Comment by trombik** [comment]
I am using the following patch to fix the issue. the log from `cbsdd` goes to syslog.

* do not terminate when `cbsdd natoff` fails. always stop the daemon
* fix `restart`

```
--- cbsdd.orig	2020-04-01 00:33:12.486974000 +0000
+++ cbsdd	2020-04-01 00:57:23.959362000 +0000
@@ -45,6 +45,7 @@
 
 . ${localcbsdconf}
 
+start_cmd=${name}_start
 start_precmd=${name}_prestart
 stop_precmd=${name}_prestop
 stop_cmd=${name}_stop
@@ -72,7 +73,9 @@
 cbsdd_prestop()
 {
 	${rcddir}/jails-astart stop
-	[ -n "${nat_enable}" ] && /usr/local/bin/cbsd natoff
+	if [ -n "${nat_enable}" ]; then
+		/usr/local/bin/cbsd natoff || echo "failed to cbsd natoff"
+	fi
 }
 
 cbsdd_stop()
@@ -91,12 +94,8 @@
 
 cbsdd_restart()
 {
-	if [ -f "${pidfile}" ]; then
-		pkill -9 -f ${pidfile} > /dev/null 2>&1
-		/bin/rm -f ${pidfile}
-	fi
+	run_rc_command "stop"
 	run_rc_command "start"
-	exit 0
 }
 
 cbsdd_status()
@@ -118,4 +117,9 @@
 	fi
 }
 
+cbsdd_start()
+{
+	echo "Starting ${name}"
+	/usr/sbin/daemon -c -S -T ${name} ${command}
+}
 run_rc_command "$1"
```

**Comment by olevole** [comment]
@trombik I can’t remember why I don’t use a demon in this place ;-)
If the `service cbsdd status`  and `service cbsdd stop` work correctly - how about pull/merge request to upstream ^^ ?
