### ISSUE TITLE
Alternative concept for boot order

### ISSUE THREAD

**Issue by obma** [cbsd/cbsd#465]
No bug, no feature request - let's call it a feature-wish

Regarding the boot / start order of jails I'm used to the concept of ezjail, where you can define PROVIDE and REQUIRE for each jail an ezjail calculates the order of how to start the jails. In my opinion that is really elegant.

Maybe that's a feature to add?

**Comment by olevole** [comment]
Hi! Do you mean to add this to the existing *b_order* parameter? By b_order, you can adjust the sequence without reference to the name of the containers, which can be renamed or deleted:

```
% cbsd jls display=jname,b_order
JNAME  B_ORDER
jail1  10          
jail2  10          
jail3  10          
jail4  10          
jail5  10          
```
Change sequence: jail1 should start last, while jail5 - first:

```
% cbsd jset b_order=50 jname=jail1
b_order: 50
% cbsd jset b_order=5 jname=jail5
b_order: 5
```

the *jorder* shows how the container should start at startup:

```
% cbsd jorder
jail5 jail2 jail3 jail4 jail1
```

and *jorder* with *order=DESC* show order for stop ( when cbsdd/host shutdown ):
```
% cbsd jorder order=DESC
jail1 jail2 jail3 jail4 jail5
```

When ordering by name using REQUIRE/PROVIDE, a not so flexible scheme is obtained:

in addition to the already mentioned problem with the removal of the container and cloning/renaming ( we have to do a lot of checking which container has dependencies on the old name ) we get non-obvious behavior for 'jimport/jexport' command and, as a rule, we should generate a separate list for the reverse operation - e.g, when you have jail which provide LDAP or Backend/Endpoint service and you have jail which depends on the first ( e.g Jira/Redmine integrated with LDAP or WEB balancer ), 

You must have the following scheme to start:

jail ldap: provide LDAP
jail jira: require LDAP

but when you do 'shutdown -r now' or `shutdown -p now`, you have to stop first 'jira' then - ldap.

When you use 'require/provide' ( or delete ldap jail ) this name becomes unobvious: when required jail missing - should we start jail ?
