### ISSUE TITLE
cbsd jrename does not rename fstab directory

### ISSUE THREAD

**Issue by uropro** [cbsd/cbsd#467]
cbsd jrename old=test new=test2
will not rename <cbsd-base>/jails-fstab/test directory to test2, but will create a file fstab.test2 (old style)
and <cbsd-base>/jails/test2 directory is not removed.

FreeBSD version ( uname -a ): 12.1-RELEASE-p2
CBSD version ( cbsd version ): 12.1.5

**Comment by olevole** [comment]
@uropro Thank you for report!

fstab files were moved to a personal directory for better support external file systems ( https://www.bsdstore.ru/en/articles/cbsd_with_dfs.html#dfs_nfs ). 
These changes were not reflected in the script, fixed via https://github.com/cbsd/cbsd/commit/9d75a093cb613ffaa1c907f4eb7ddc8aee50584a

You can test/appply changes via 
```
// move old file
mv /usr/local/cbsd/jailctl/jrename /tmp

fetch -i /usr/local/cbsd/jailctl/jrename https://raw.githubusercontent.com/cbsd/cbsd/develop/jailctl/jrename

chmod +x /usr/local/cbsd/jailctl/jrename
```

please re-open Issue if you still observe problems

**Comment by uropro** [comment]
Works - Thank you very much!
