### ISSUE TITLE
jexec removing options from command

### ISSUE THREAD

**Issue by obma** [cbsd/cbsd#470]
$ sudo cbsd jexec jname='*' pkg upgrade -r poudriere -y
Hint: Press 'Ctrl+t' to see last logfile line for active task
 * [jexec: pending: 3:[ jail1 jail2 jail3], active: 0]

 * [jexec: pending: 1:[ jail3], active: 2:[ jail1 jail2]]

jail1: success in 3 sec:

Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
Updating poudriere repository catalogue...
poudriere repository is up to date.
All repositories are up to date.
pkg: poudriere is not installed, therefore upgrade is impossible
Checking integrity... done (0 conflicting)
Your packages are up to date.

 * [jexec: pending: 0, active: 2:[ jail2 jail3]]

**Comment by olevole** [comment]
@obma Could you comment a little which option was lost? As well as which cbsd you are using.

Also, _apart from the problem_ - cbsd has a pkg wrapper  ( https://www.bsdstore.ru/en/12.1.x/modules/pkg.d_ssi.html or `cbsd pkg --help` )

**Comment by obma** [comment]
I'm trying to run
`pkg upgrade -r poudriere -y`
inside the jail.

It looks like the dashes get lost.

Today I noticed that it does not happen if i run jexec for a specific jail, i.e.:
`$ sudo cbsd jexec jname='jail1' pkg upgrade -r poudriere -y`
does work as expected, while
`$ sudo cbsd jexec jname='*' pkg upgrade -r poudriere -y`
doesn't.

**Comment by olevole** [comment]
@obma I think you're right that we are losing some of the arguments. Can you try changes from https://github.com/cbsd/cbsd/commit/29fb7f26e68c04cf1d21ee10a00a73f38c52a2c5  ?

Instead of: 
  exec /usr/bin/nice -n ${nice} ${SETFIB} ${CPUSET} ${JEXEC_CMD} -U ${user} ${jid} <CMD>

we must pass arguments as is in HEREDOC block

**Comment by olevole** [comment]
Also we need quoted cmd in multiple jname.

Please fetch and test latest changes, I believe your problem should be fixed:

# move old script somewhere:
```
mv /usr/local/cbsd/sudoexec/jexec /tmp
```

get script from GitHub:
```
fetch -o /usr/local/cbsd/sudoexec/jexec https://raw.githubusercontent.com/cbsd/cbsd/develop/sudoexec/jexec
chown root:wheel /usr/local/cbsd/sudoexec/jexec
chmod +x /usr/local/cbsd/sudoexec/jexec
```

Please re-open if the problem still remains

**Comment by olevole** [comment]
commited to ports tree https://svnweb.freebsd.org/ports?view=revision&revision=r529081

**Comment by obma** [comment]
Sorry to reopen - but the fix didn't work. See below.

```
$ sudo cbsd jexec jname='*' pkg upgrade -r poudriere -y
Hint: Press 'Ctrl+t' to see last logfile line for active task

jail1: failed in 0 sec:

nice: illegal option -- U
usage: nice [-n increment] utility [argument ...]

 * [jexec: pending: 1:[ jail3], active: 1:[ jail2]]
jail2: failed in 1 sec:

nice: illegal option -- U
usage: nice [-n increment] utility [argument ...]


jail3: failed in 1 sec:

nice: illegal option -- U
usage: nice [-n increment] utility [argument ...]



$ pkg info cbsd
cbsd-12.1.7
Name           : cbsd
Version        : 12.1.7
Installed on   : Thu Mar 26 09:39:10 2020 CET
Origin         : sysutils/cbsd
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : sysutils
Licenses       : BSD2CLAUSE
Maintainer     : olevole@olevole.ru
WWW            : https://www.bsdstore.ru
Comment        : Yet another FreeBSD Jail, XEN and Bhyve Management Utility
Shared Libs required:
        libedit.so.0
        libssh2.so.1
        libsqlite3.so.0
Annotations    :
        FreeBSD_version: 1201000
        repo_type      : binary
        repository     : poudriere
Flat size      : 16.5MiB
Description    :
Yet another FreeBSD jail and bhyve management tool.

WWW: https://www.bsdstore.ru
$ 
```

**Comment by olevole** [comment]
@obma  It is very strange. Did you run `cbsd initenv` after package upgrade ? Looks like your ~cbsd/cmd.subr file does not contain any macro from these commands:

exec /usr/bin/nice -n ${nice} ${SETFIB} ${CPUSET} ${JEXEC_CMD} -U ${user} ${jid} /bin/sh

^^ SETFIB, CPUSET and JEXEC_CMD should be in ~cbsd/cmd.subr

**Comment by obma** [comment]
Sorry! My fault! As you said: don't forget to run `cbsd initenv` after upgrade.
