### ISSUE TITLE
switching to new cbsd.io

### ISSUE THREAD

**Issue by olevole** [cbsd/cbsd#471]
Steps required to switch content/articles to a new https://cbsd.io site without regressions and without loss of old works.

- [ ] sync all **english only** content from old resources ( the site has been constantly modified over time: https://github.com/cbsd/cbsd-wwwdoc/commits/master); I would like to see multi-language support, but at the moment only **russian** is up to date (I can someday translate/rewrite this myself). As far as i see, **deutsch** quite irrelevant, although it was also spent a lot of time by different people)

- [ ] versioning ( e.g 11.X, 12.X dirs: https://github.com/cbsd/cbsd-wwwdoc/tree/master/en ): this gives us the ability to maintain documentation for older versions;

- [ ] RSS feeds ( at the moment: https://github.com/cbsd/cbsd-wwwdoc/blob/master/rss.xml , managed by hands )

- [ ] (_optional_, but very desirable. old site made with this in mind): the ability to generate static html files for offline usage. We can have an option [X] WITH_DOCS in FreeBSD ports to install all documentation into /usr/local/share/doc/cbsd, where the user can by lynx/links/w3c/... Of course, we can accompany and duplicate documentation from the site into man page, but so far the project does not have enough contributors and now no one will do it. Therefore, this step is necessary in conditions of limited human resources. At the moment, the main documentation is written by one person, and he does not have the strength to duplicate this in another format)

- [ ] update link in all CBSD scripts:

       /usr/local/cbsd/cbsd.conf cbsddocsrc="https://www.bsdstore.ru/en/${docversion}"
       +
       all scripts with EXTHELP params  ( `grep -R EXTHELP= /usr/local/cbsd/` )

- [ ] update WWW: in /usr/ports/sysutils/cbsd ports tree

- [ ] create redirect from old site

**Comment by mekanix** [comment]
I would like to revive this ticket. So for start just to be clear, I intend to replace only docs from the old site. That being said, I don't think RSS feed is needed for docs. Maybe I'm missing something so @olevole please fill in if I'm wrong.

For building the docs, we already do that before publishing the site, so the same process can be repeated for offline usage. If that's all, we might even tick off that one.

I would like to keep current site as it is and just have documentation be a link to cbsd.io, hence last two are not relevant.

**Comment by olevole** [comment]
@mekanix RSS feed for docs is not required, it is only for news, and it can remain a static file. 

I am concerned about the situation with the synchronization of content from the old sites to the new, since my forces are enough to maintain (and additions as the project develops) only single resource (and I do it still on the old resource, because it contains additional information).

In addition, due to the lack of human resources, it worries me to update/sync the content in the future. 
For these reasons, lately I try to pay more attention to the self-documented scripts. E.g, take a look on:

```
cbsd jexec --help
cbsd vpc --help
cbsd buildworld --help
cbsd jcreate --help
..
```

I try to give a more description and examples directly in the script (by analogy with a good man page ;-)
Thus, a dilemma arises - as with extremely limited (mostly - my) resources continue to support three sources of documentation in the current state ;-)

Recently, I came to the belief that part of the documentation could be generated automatically from one data source. For example, it may be necessary to focus the strength on good documentation in the scripts ( **--help args**, instead of man ) and this information could be automatically displayed on the site (which is likely to be in addition to it must have more advanced information).

In addition, I like the idea to share information on small but related pieces, as is done on the old FreeBSD website.
My old site is focused on this structure: https://www.bsdstore.ru/en/docs.html

I start from the easiest chapter to complex. And you can get all the combined documentation through one single file (which is a consistent include of all chapters).

The idea was simple. By combining logically interconnected small pieces of chapters, we can get and distribute well structured big 'CBSD book'. Again, this idea is not caused by a good life. The presence of a big 'CBSD' handbook  is a very good idea. But there are no resources for maintaining documentation and work separately in the book.

Maybe when the project suddenly gets rich, we can order the "CBSD book" from Michael Lucas ;-)

**Comment by olevole** [comment]
I have a plan :point_up:
Since I am the only one who knows the capabilities and strengths of the project as best as possible ;), it is logical that I should write the documentation. This summer I want to revise all the documentation on site and significantly revise it by removing the old one and updating the new one. Then order a paid professional translation of the resulting book into English and release it for free.

**Comment by olevole** [comment]
due to financial/payments difficulties, we will abandon domains and switch to a GitHub/WIKI markdown: https://github.com/cbsd/cbsd/wiki
