### ISSUE TITLE
etcupdate wrapper for CBSD

### ISSUE THREAD

**Issue by olevole** [cbsd/cbsd#474]
I want to open a discussion on CBSD etcupdate wrapper implementation for jail (sorry for my lang, as usual ;-) 

cc for: @Peter2121 ( feature requester/etcupdate user ;), @mekanix , @Stefar77. Since you all use jail more than me ;-)

As I understand it, [https://man.freebsd.org/etcupdate(8)](https://man.freebsd.org/etcupdate(8)) is an alternative and a better replacement for the old [https://man.freebsd.org/mergemaster(8)](https://man.freebsd.org/mergemaster(8)) script (e.g: better merge).

We have cbsd `baseupgrade` ( upgrade ~cbsd/basejail/bases_* ) script and 'jupgrade' (for baserw=1) which update base but not distribution files ( mainly /etc/* content ).

With Peter, I tried to look at etcupdate and write a wrapper for CBSD:

https://github.com/cbsd/cbsd/blob/develop/system/etcupdate
( work log: https://pastebin.com/njx7hYu5 )

Nevertheless, I have many questions on how to do it right:

For example, etcupdate needs for ( etcupdate build/extract ) to use with -t <tgz>.

It seems that this step needs to be done each time when you use base-in-pkg, after 'make -C /usr/src packages' as extra-step generate .tgz. 

But for correct etcupdate operation we need for bootstrap - this means that we must also have the source code of the old version in order to execute 'etcupdate extract'

( this is another strange question for me - extract will generate 'current' dir with 'distribtion' content while 'build' generate .tgz which can be used via -t  ( or new/ dir as well )

At the moment I generate necessary content _for_ _all_ version via srcup script (checkout):

https://github.com/cbsd/cbsd/blob/develop/system/srcup#L287-L289

FreeBSD/re@ people nowhere generate similar content available to receive from official FreeBSD.org resource, so it will be strange when CBSD gets base.txz from official resources and after that it starts to download strange things from third-party resources (if we place this on the CBSD resources).

it seems this is no different from ~cbsd/basejail/base*/etc content except some files outside /etc dir  ( /COPYRIGHT, /.profile, /.cshrc  + /root/{.profile,.cshrc,.k5login,.login} .. ) - probably we can only use */etc* with exclude all files outside /etc dir ( I do not like the idea of accompanying an additional list with these files in the CBSD these files must be maintained and monitored ;-( )

And finaly, can we make it easier for the user to select versions for from= or/and to= ? E.g, we can use 'cbsd ver' for actual (desired/final version for 'to=' args), or use ELF to determine actual version in jail, e.g:  `/usr/local/cbsd/misc/elf_tables --freebsdver /bin/sh` where /bin/sh  - path to jails /bin/sh.
It seems we should make the user always remember what the old version was (can store information in ~cbsd/jail-system/<jname> dir ?)

What do you think about it all, I'm at a loss). Any ideas? 

Update and sync /etc/* content when updating the jail version - a rather urgent task.

**Comment by Stefar77** [comment]
I usually make a new base, change the base of the jail and start reinstalling/recompiling all packages/ports and that takes care of most of the updating.
Some older jails I have /etc mounted as a unionfs so that it changes with the base except for the files I have changed (rc.conf etc) but I barely use them and unionfs was always a pain if you started combining it with nullfs or tmpfs like filesystems. (didn't try that for a long time)

Let me check into it some more, I have many FreeBSD 9,10 and 11 /etc that are now running on 12.1 jails and they all seem fine. (I use 1 service per jail and all base stuff is as good as disabled so no complaints about missing ntpd users or anything like that)

**Comment by mekanix** [comment]
Unless I'm totally off, we don't have `cbsd baseupgrade`, only `cbsd baseupdate`. For upgrade I use what @Stefar77 described. To be perfectly precise, this is what I do: https://meka.rs/blog/2019/11/18/cbsd-base-upgrade/

As CBSD has support for compiling base from source, maybe that's what you mean?

**Comment by olevole** [comment]
@Peter2121 perfectly. I had high hopes for these two guys ^^. but now, it seems, you are the only person on earth who decided to use the etcupdate and jail. i need meditation.

**Comment by Peter2121** [comment]
I wish you stay in meditation for some days to give me some time to digg it myself ;)

**Comment by Peter2121** [comment]
Adding `-I '/etc/*.db'` to my script I've got it working for 11.3->12.1 jail upgrade.
It seems that as there are no binary files in trees produced by `etcupdate build` command, the exit status of diff for binary files is not correctly processed by etcupdate. So, IMHO, if binary files are eliminated from comparison - we can use 'normal' trees from bases, downloaded from freebsd.org (and updated by `cbsd baseupdate`).
We need more tests though ;)

**Comment by olevole** [comment]
Almost all issues have been resolved. The initial script is included in 12.1.7, we will test and improve
