### ISSUE TITLE
jstart does not call /etc/rc after upgrade to 12.1.6

### ISSUE THREAD

**Issue by mobstef** [cbsd/cbsd#475]
```
@@ -541,11 +550,13 @@
 export_jail_data_for_external_hook
 external_exec_master_script "master_prestart.d"
 
+
 if [ "${ver}" = "empty" ]; then
 	path="/"
 	exec_start="${jailsysdir}/${jname}/run.sh"
 else
 	[ ! -d "${data}/var/cache/pkg" ] && ${MKDIR_CMD} -p "${data}/var/cache/pkg"
+	exec_start=""
 fi
 
 #determine that jail is FreeBSD. Useful for vnet operation in makejconf and
```
This is regression caused by #469 https://github.com/cbsd/cbsd/commit/85bc9463ade34d1820a0028c405ee5472e68712f
The exec_start is cleared, but still needed later for late_start. Removing this line fixes the issue.

FreeBSD version ( uname -a ):
FreeBSD zulu.home 12.1-RELEASE-p2 FreeBSD 12.1-RELEASE-p2 GENERIC  amd64

CBSD version ( cbsd version ): 
12.1.6

**Comment by olevole** [comment]
@mobstef As far as I understand that you are using **vnet** and/or ZFS attached dataset ?

I tried to check it and at first glance, everything is fine:

```
% cbsd jcreate jname=xxx runasap=1
% cbsd pkg mode=install jname=xxx nginx 
% cbsd sysrc jname=xxx nginx_enable="YES"

```

`% cbsd jrestart xxx`

```
% cbsd jexec jname=xxx ps axfx
  PID TT  STAT    TIME COMMAND
11953  -  SNsJ 0:00.00 /usr/sbin/syslogd -ss -c
12008  -  SNsJ 0:00.00 nginx: master process /usr/local/sbin/nginx
12009  -  SNJ  0:00.00 nginx: worker process (nginx)
12015  -  SNsJ 0:00.00 sendmail: accepting connections (sendmail)
12018  -  SNsJ 0:00.00 sendmail: Queue runner@00:30:00 for /var/spool/clientmqueue (sendmail)
12022  -  SNsJ 0:00.00 /usr/sbin/cron -s
12333  0  RN+J 0:00.02 ps axfx
```

**Comment by czkarex** [comment]
I'm in the same situation. The only difference is activation / deactivation of VNET.
If VNET is turned off, everything works, RC.CONF is loaded.

Karel

**Comment by mobstef** [comment]
@olevole 
Yes, I actually use both VNET and ZFS.

**Comment by olevole** [comment]
@mobstef @czkarex Got it, Thanks. Unfortunately, I don’t have enough time right now to refactor, so I’ll roll back this change via ports patch level: https://svnweb.freebsd.org/ports?view=revision&revision=r528603
Fix the dual-launch services with zfs attached dataset will require some more time for investigation.

**Comment by olevole** [comment]
When you receive updates for the ports, cbsd-12.1.6_1 should fix the new problem  (and return the old one)

**Comment by olevole** [comment]
notes for myself:
https://github.com/cbsd/cbsd/issues/439
https://github.com/cbsd/cbsd/commit/de72591558c9bf0aa699ffd2a6d29a4c76c9bccd
