### ISSUE TITLE
missing documentation: "jail_active" in profile

### ISSUE THREAD

**Issue by trombik** [cbsd/cbsd#479]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD default-freebsd-121-amd64.vagrantup.com 12.1-RELEASE-p3 FreeBSD 12.1-RELEASE-p3 GENERIC  amd64

CBSD version ( cbsd version ): cbsd-12.1.2

Following steps in https://www.bsdstore.ru/en/12.1.x/wf_profiles_ssi.html, I was unable to create a custom profile. After a few hours, finally found that `jail_active` is the variable to enable/disable a profile.

there are other things that needs to be documented. it would be nice if the repository has documentation in itself so that changes are always in sync when code is modified. commits that include new features and changes in behaviors should include corresponding changes in documentation. tutorials may be kept in another repository, but the canonical documentation should be in this repository.

thanks for tons of work in `cbsd`. the work exceeds my expectation.

**Comment by olevole** [comment]
@trombik Thanks for the report. You are also involved in improving the project by creating these reports. Yes, development does not always keep up with the documentation ;-) I try to fix this from time to time.

**Comment by olevole** [comment]
fixed:  https://github.com/cbsd/cbsd-wwwdoc/commit/ee0cdd871a252cb6f9d26ee9bd23ddd46741d6bd

Thank you!
