### ISSUE TITLE
Feature Request: novnc integration

### ISSUE THREAD

**Issue by ntinti** [cbsd/cbsd#487]
Hi

I think it would be helpful to integrate novnc into cbsd so vnc for bhyve can be used in normal webbrowser. In the Ports: www/novnc, on GitHub : https://novnc.com/info.html

**Comment by olevole** [comment]
Ehlo! 
Such integration has existed for three years, and the name of this integration is the ClonOS - https://clonos.tekroutine.com/ 

In fact, CBSD is low-level framework for working with virtual machines. And we have great opportunities to integrate any of your scenarios. pay attention to stop, start hooks

**Comment by olevole** [comment]
can be done quite easily without any additional development from CBSD side:

1) pkg install -y novnc

2) Use custom scripts as CBSD master_poststart.d hook (see: https://www.bsdstore.ru/en/12.1.x/wf_jconfig_ssi.html#execscript ):

```
cat > ~cbsd/jails-system/vm1/master_poststart.d/vnc.sh <<EOF
#!/bin/sh

# just for debug
echo "[$vm_vnc_port] [$vnc_port]" > /tmp/testvnc.txt
echo "$bhyve_vnc_resolution"  >> /tmp/testvnc.txt
echo "$bhyve_vnc_tcp_bind"  >> /tmp/testvnc.txt
echo "$vnc_password" >> /tmp/testvnc.txt

# lauch novnc:
daemon -f /usr/local/bin/bash /usr/local/libexec/novnc/utils/launch.sh --listen 6081 --vnc ${bhyve_vnc_tcp_bind}:${bhyve_vnc_port}

EOF

chmod +x /usr/jails/jails-system/vm1/master_poststart.d/vnc.sh
```

open novnc.html in your favorite browser  after **vm1** start:

http://<HOST>:6081/vnc.html?host=<HOST>&port=6081

I hope that someday we will be able to arrange this on the site as one of the howto material.

ps: another sample of start/stop hooks in CBSD: https://www.bsdstore.ru/en/articles/cbsd_vm_hook_dhcpd.html
