### ISSUE TITLE
About master and slave

### ISSUE THREAD

**Issue by clem16** [cbsd/cbsd#506]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD Apollo 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64

CBSD version ( cbsd version ): 
12.1.13

Just a quick question. - Working with jails, I am able to move them around between my nodes.
What is the effect of the master and slave status?

How does it work?

**Comment by olevole** [comment]
do you mean 'jcoldmigrate' work ? if memory serves me right, the container on the source node goes into 'slave' only for backup only. And if for some reason the container did not work on the destination host, you have the opportunity to start it in the old place. If everything is ok, you can delete it.

The reasons for this behavior are that there is still no full-fledged check in the CBSD that the container is fully operational - for example, before synchronizing the container, we do not check for disk space on the destination node ( in this case, we risk sending only part of the data ). Or the network on the remote server is not configured correctly. All this can lead to a situation when the original is deleted during migration, and the container on the receiver does not work.

In a good way, we must scan all the files (check CRC) on the source and check their status on the destination server ( for non-ZFS ) and check/compare dataset size with ZFS. But this work unfortunately has not yet been done. Therefore, the CBSD does not automatically destroy the container and switch jail into a special status 'slave'. You can remove them or unregister via 'cbsd junregister'

**Comment by clem16** [comment]
Ok! That helps clarify a few points.

Thanks for taking the time to help me understand. Basically the slave status is just a flag that gets set that stops the jail from being started by jstart. Until the flag is changed. It has no other effect, as far as I am understanding. I was hoping that while in "slave" mode it would receive rsync updates from the master keeping everything up to date. This doesn't seem to be the case.

What is the effect of the 'unregistered' flag?

Just trying to nail down exactly what these terms mean in the context to how they function within the system so I can write scripts that take advantage of their functionality. There is still some vagueness, I have found when pouring over the documentation.

Just for context for anyone wondering. Here is what I'm trying to accomplish.

I have two identical small super micro servers in my home lab, which I am running several jailed processes in - serving home network services.

- I am in the process of writing some shell scripts that run via cron periodically, to monitor several things.
- Checking if the server online, if the jail process running, if the service in the jail is up. 
- If none of these conditions are true, try to correct them. 
- Failing any correction - switch the "slave" flag to "master" and on the local node fire up jail. 
- Then when the other server comes online check for running processes if one is found to be running, switch the jail into slave mode.

- I am trying to accomplish this without using my main file server and its nfs mounts in regards to synchronization between the jails. (as that puts a dependency on another machine, and I'm trying to eliminate or mitigate any single point of failure.) 
- So I still need to solve the problem of keeping the nodes as synchronized as possible across the two hosts. 
- I was intending them to run as standalone and as bare bones to a vanilla FreeBSD install with cbsd, nano, screen and the crontabs being the only other modifications to the host needed. This allows me, with very little effort, add or remove hardware from my network.
- I am trying to do this all with FreeBSD and its mirrored disks of ZFS. - as I love the stability it provides, how clean, organized and well documented it is.
- Now that I've found cbsd and started to learn it's in's and outs. - I think all the building blocks of a setup like this are potentially possible.

**Comment by olevole** [comment]
> I was hoping that while in "slave" mode it would receive rsync updates

hehe, Unfortunately no. it's just a bad status 'name' ;)

unregister/register - This is the operation of de-registering/registragin an environment record in the main SQLite3 database, without any without any data movement. For example, if you have any shared storage (Ceph, GlusterFS, NFS, ...) for your two servers, you can migrate the environment with zero copying of data. Just unregister it on one node and register on another: https://www.bsdstore.ru/en/articles/cbsd_with_dfs.html

There are many options for how you can make fault tolerance with your servers. 
Both with and without common/shared storage. Without DFS you can use iSCSI-based two ZPOOLs. Or ZFS replication ( discrete replication ), e.g. via sysutils/zrep or https://github.com/zrepl/zrepl ...
