### ISSUE TITLE
При старте сваливается демон cbsdd останавливается с coredump

### ISSUE THREAD

**Issue by theawgur** [cbsd/cbsd#514]
Mandatory info for bug reports:
При запуске демон сваливается с отбрасывая coredump. В логах:
```
Sep  3 21:48:35 localhost cbsd[47483]: jails-astart: jail start order: phab todolist media-sv dmz-files 
Sep  3 21:48:35 localhost cbsd[47483]: jails-astart: astart=1, start scheduled: phab 
Sep  3 21:48:35 localhost cbsd[47484]: cbsdd: cbsdd: max_simul_jobs:60,loop_timeout:30 
Sep  3 21:48:35 localhost cbsd[47483]: jails-astart: astart=1, start scheduled: todolist 
Sep  3 21:48:35 localhost cbsd[47483]: jails-astart: astart=1, start scheduled: media-sv 
Sep  3 21:48:35 localhost cbsd[47483]: jails-astart: astart=1, start scheduled: dmz-files 
Sep  3 21:48:35 localhost kernel: pid 47484 (cbsd), jid 0, uid 0: exited on signal 6 (core dumped)
```
coredump прилагаю

[cbsd.core.zip](https://github.com/cbsd/cbsd/files/5170678/cbsd.core.zip)

При этом 12.1.13 работает отлично

FreeBSD version ( uname -a ): `FreeBSD localhost 12.1-RELEASE-p9 FreeBSD 12.1-RELEASE-p9 GENERIC  amd64`

CBSD version ( cbsd version ): `12.1.14`

**Comment by olevole** [comment]
попробуй плз на 12.1.15, позавчера в порты заслал из-за этой проблемы

**Comment by theawgur** [comment]
Принято. Как прибежит с обновлениями, поставлю и отпишусь в инцидент.

**Comment by theawgur** [comment]
С `12.1.15` всё взлетело. Но есть одна странность; при миграции через `cbsd initenv` с `12.1.13` к `12.1.15` было выдано следующее:
```
[Stage 0: upgrading and migration data from 12.1.15 to 12.1.15]
```
Начиная с `12.1.15` миграция выполняется при обновлении пакета?

**Comment by olevole** [comment]
> С 12.1.15 всё взлетело

отлично!


По поводу миграций - нет, пакет при установке миграции не делает. Надо будет глянуть, откуда берется версия в выводе  'from', проверю попозже
