### ISSUE TITLE
Jail with zfs snapshots cannot be completely removed

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#515]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 11.3-RELEASE-p5

CBSD version ( cbsd version ): 12.1.15

If a jail has snapshots created out of 'cbsd jsnapshot' - this jail cannot be removed correctly.

Example: jail 'db1clone' was created as a clone of jail 'db1'. In the meantime there were some zfs snapshots created by backup software. now I don't need the jail 'db1clone' anymore. Trying to remove it I get several errors, some zfs snapshots  are not removed:

```
# cbsd jremove
List of local jails:
 0 .. CANCEL
 a .. db1 on local
 b .. db1clone on local
 c .. innotop on local

Remove jail db1clone. Are you sure?
[yes(1) or no(0)]
1

Auto-promote FS: tankjail/jails/db1
cannot destroy 'tankjail/jails/db1clone': filesystem has children
use '-r' to destroy the following datasets:
tankjail/jails/db1clone@2020-09-13
tankjail/jails/db1clone@2020-09-07
tankjail/jails/db1clone@2020-09-09
tankjail/jails/db1clone@2020-09-10
tankjail/jails/db1clone@2020-09-12
tankjail/jails/db1clone@2020-09-11
tankjail/jails/db1clone@2020-09-08
cannot destroy 'tankjail/jails/db1@cbsd-original-db1clone': snapshot has dependent clones
use '-R' to destroy the following datasets:
tankjail/jails/db1clone@2020-09-13
tankjail/jails/db1clone@2020-09-07
tankjail/jails/db1clone@2020-09-09
tankjail/jails/db1clone@2020-09-10
tankjail/jails/db1clone@2020-09-12
tankjail/jails/db1clone@2020-09-11
tankjail/jails/db1clone@2020-09-08
tankjail/jails/db1clone
jremove done in 18 seconds
```

**Comment by mekanix** [comment]
What would be the best way to handle this? I was thinking about another question like "remove all snapshots?" or something, but also adding something like `env ALWAYS_YES=yes cbsd jremove` so it can be scripted. Sounds reasonable?

**Comment by Peter2121** [comment]
The idea about 'env ALWAYS_YES=yes' is global, maybe there are some other places where it can be usable.
Yes, a question about removing all 'foreign' snapshots would be OK, but with an option to cancel removing the jail and examine the situation manually. For this case showing a list of 'foreign' snapshots could be usable.

**Comment by olevole** [comment]
One of the reasons why I am not handling this is that I don’t know what to do best ;-) We also need to handle cases where the snapshot might be the original for another environment. In this case, deleting with the -r key will destroy the other container.

**Comment by JEAholding** [comment]
I am not 100% sure if this will help anyone in the future but when I have issues with children/clones in ZFS I just do a separate snapshot for the clone and start deviating from the source... I think that should break the children from the source metadata, at least it has worked for me, have not test this further as I only learn/do the minimum to resolve my issues/use case.

**Comment by olevole** [comment]
> I just do a separate snapshot for the clone and start deviating from the source... 

Can you share information how you do it?

**Comment by olevole** [comment]
closed: unfortunately, at the moment I have no options for solving this problem due to the huge number of cases where automation is dangerous.
In the case when the environment is created from a snapshot (no matter who created it), automation is not able to decide whether the user needs it or not. I think this is one of those cases where it's best to leave the resolution of this situation up to the user.
