### ISSUE TITLE
Error initenv on i386

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#516]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 11.3-RELEASE-p13 i386

CBSD version ( cbsd version ): 12.1.15

cbsd cannot be initialized - bhyvectl is not present.

```
# env workdir="/usr/local/jails/cbsd" /usr/local/cbsd/sudoexec/in
-------[CBSD v.12.1.15]-------
 This is install/upgrade scripts for CBSD.
 Don't forget to backup.
-----------------------------
Do you want prepare or upgrade hier environment for CBSD now?
[yes(1) or no(0)]
1
>>> Installing or upgrading
[Stage 1: account & dir hier]
 * Check hier and permission...
./.rssh missing (created)
./.ssh missing (created)
./.ssh/sockets missing (created)
./basejail missing (created)
./etc missing (created)
./etc/defaults missing (created)
./export missing (created)
./ftmp missing (created)
./import missing (created)
./jails missing (created)
./jails-data missing (created)
./jails-fstab missing (created)
./jails-rcconf missing (created)
./jails-system missing (created)
./share missing (created)
./share/dialog missing (created)
./share/helpers missing (created)
./share/FreeBSD-jail-puppet-skel missing (created)
./share/FreeBSD-jail-skel missing (created)
./share/FreeBSD-jail-vnet-skel missing (created)
./share/emulators missing (created)
./src missing (created)
./tmp missing (created)
./var missing (created)
./var/cron missing (created)
./var/cron/tabs missing (created)
./var/db missing (created)
./var/log missing (created)
./var/mail missing (created)
./var/run missing (created)
./var/spool missing (created)
cmdboot: no such executable, CBSD dependency/requirement: bhyvectl
initenv cmdboot error: missing necessary binaries
```

**Comment by olevole** [comment]
I wonder what happened to 'bhyvectl' in FreeBSD 11.3-RELEASE/i386.

as far as i know it should be:

HISTORY
     The bhyvectl command first appeared in FreeBSD 10.1.

@Peter2121 is this an official release? `whereis bhyvectl' or `which bhyvectl' return nothing ?

**Comment by Peter2121** [comment]
Evidently, this is an official release (VM installed from official ISO).
Evidently, nothing found by 'which' and 'whereis'.
Maybe there is something to install (base component or package), but I have no idea what exactly.
I have only one server like this, installed to test build of some software, so I cannot do a wide-scale test ;)

**Comment by olevole** [comment]
it's easy to check:

```
% mkdir /tmp/test
% cd /tmp/test/
% fetch http://ftp.freebsd.org/pub/FreeBSD/releases/i386/11.3-RELEASE/base.txz
% tar xfz base.txz
% find . -type f -name bhyvectl
;-(
```

I think we should have a list of optional commands in cmdboot script: https://github.com/cbsd/cbsd/blob/develop/misc/cmdboot

For example if there is no command 'jail' command then CBSD set something like 'jail_feat=0' in config file, when no 'bhyve' - 'bhyve_feat=0' respectively. But this will not be a fatal initialization error. 

I think this is relevant not only when porting to other potential platforms (Dragonfly, NetBSD/Open), it is also useful for custom FreeBSD base ( with NO_JAIL=yes or NO_BHYVE=yes KNOBS )

**Comment by olevole** [comment]
Ok, we now assume the absence of some commands: https://github.com/cbsd/cbsd/commit/eb5c4b070b722feb38dbe812b2560970fe459b75

At the moment, the XXX_feat=0 is not handled anywhere in the code. Just pass init stage
