### ISSUE TITLE
Jails database is not updated after cold migration

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#517]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 12.1-RELEASE-p9

CBSD version ( cbsd version ): 12.1.15

After a cold migration of a jail between two hosts with different paths of cbsd base directory, the database var/db/local.sqlite on destination host is not updated to change paths of the jail. The fields rcconf, data, mount_fstab, path point to the paths of initial host where the jail comes from. As a result - jail directories are not unmounted after jail stop, many errors on jail restart. 
Manually changing the paths in database fixes the problem.

**Comment by olevole** [comment]
Replacement for working directory exists. However, it broke for a while due to the loss of a variable in **j2prepare**  script.
Fixed now. Thank you!
