### ISSUE TITLE
[Feature request] Add a command to create a new jail from an existing snapshot

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#519]
It is really useful to be able to create a new jail from an old snapshot of an existing jail (created using 'cbsd jsnapshot' command). I used this feature in iocage/iocell. Please, add it to cbsd.

**Comment by olevole** [comment]
this option has been around for a very long time: ''zfs_snapsrc" in 'cbsd jconstruct-tui' or options/parameter for 'cbsd jcreate'. Just put snapshot name as 'zfs_snapsrc'

**Comment by Peter2121** [comment]
> Just put snapshot name as 'zfs_snapsrc'
Should I put a cbsd snapname or a zfs snapshot name?

**Comment by olevole** [comment]
Full snapshot name from `zfs list -t snapshot`, e.g:

1) create jail with nginx package

> % cbsd jcreate jname=nginx pkglist=www/nginx ver=12.1

2) create snapshot

`% cbsd jsnapshot jname=nginx mode=create snapname=nginx`

3) get name of snapshot:

```
%  zfs list -t snapshot |grep nginx
zroot/ROOT/default/nginx@nginx                                               0B      -     70.2M  -
```

4) create new jail from existing snapshot:

`% cbsd jcreate jname=new zfs_snapsrc=zroot/ROOT/default/nginx@nginx ver=12.1`

5) check for nginx package

```
% cbsd jexec jname=new which nginx
/usr/local/sbin/nginx
```

**Comment by olevole** [comment]
Hope this help, closed
