### ISSUE TITLE
Incorrect resolv.conf in jail

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#520]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): any

CBSD version ( cbsd version ): any

cbcd initenv[-tui] does not check input data for nameservers and put the data 'as is' to resolv.conf.

I can put multiple servers (separated by space) in cbcd initenv-tui, and then they are put on the same line:
`nameserver 213.186.33.99 1.1.1.1   # CBSD makeresolv function`
Probably, they should be put one per line:
```
nameserver 213.186.33.99   # CBSD makeresolv function
nameserver 1.1.1.1   # CBSD makeresolv function
```
...or the second (third,...) server should be ignored.

The man page of resolv.conf says:
Up to MAXNS (currently 3) name servers may be listed, **one per keyword**.

Some programs cannot parse resolv.conf with multiple IP addresses so DNS resolution is failed (ex. libasr).

**Comment by olevole** [comment]
This parameter has not changed for the last 8 years and requires the use of a comma for several values:

https://www.bsdstore.ru/en/installing_cbsd.html#initenv

>  **jnameserver** — List of IP DNS servers to be inserted in the newly created jail's /etc/resolv.conf. If several addresses are added, they must be separated by commas. 

processing takes place in the tools/makeresolv script: https://github.com/cbsd/cbsd/blob/develop/tools/makeresolv#L21-L22
