### ISSUE TITLE
Feature request: Add support for Linux jails

### ISSUE THREAD

**Issue by PaddyMac** [cbsd/cbsd#526]
There is a wiki at https://wiki.freebsd.org/LinuxJails which describes how to set up an Ubuntu chroot on FreeBSD using the Linux emulation. I've followed the directions myself and have been very satisfied with the results. I'd like to see cbsd be able to set up and manage Linux jails. I'm not sure what all would be involved, but one of the Linuxulator contributors I spoke to mentioned "marking" the jail as a Linux jail, mounting the necessary filesystems when bringing up the jail, and being able to use the service command inside the jail to start services automatically inside of the jails instead of the usual FreeBSD rc(8).

And of course it would be nice to have more options to choose from than only Ubuntu.

**Comment by olevole** [comment]
I think this can be easily implemented. Take a look at the **kfreebsd-wheezy** profile. 

This script is run when the profile is activated: https://github.com/cbsd/cbsd/blob/develop/share/FreeBSD-jail-kfreebsd-wheezy-system-skel/tests/00.check_distribution.sh

i think it can be a base for a linux profile

**Comment by olevole** [comment]
Linux container profiles was added to Git/CBSD **13.0.4** version.
Implementation based on records with the FreeBSD Linuxlator wiki page ( https://wiki.freebsd.org/LinuxJails )  and the old CBSD script to create a kFreeBSD environment ( https://github.com/cbsd/cbsd/blob/develop/share/FreeBSD-jail-kfreebsd-wheezy-system-skel/tests/00.check_distribution.sh )
