### ISSUE TITLE
CBSD ignores allow_fusefs after reboot

### ISSUE THREAD

**Issue by Doralitze** [cbsd/cbsd#527]
Mandatory info for bug reports:

After rebooting I'm not able to mount a fuse based filesystem inside a jail. Cbsd states that allow_fusefs is set to 1 for the running jail. In order to be able to use fuse within a jail one needs to run the following commands.

```
sudo cbsd jstop fusetest
sudo cbsd jset jname=fusetest allow_fusefs=0
sudo cbsd jset jname=fusetest allow_fusefs=1
sudo cbsd jstart fusetest
```

This seams to be a bug.

Prior to running the commands above one can observe the following behaviour:

```
cloud:/root@[13:57] # /usr/local/bin/bindfs -u www -g www /mnt/shared /usr/local/var/nextclouddata/leondietrich/files/Shared
mount_fusefs: /dev/fuse on /usr/local/var/nextclouddata/leondietrich/files/Shared: Operation not permitted
cloud:/root@[13:57] # lsvfs
Filesystem                              Num  Refs  Flags
-------------------------------- ---------- -----  ---------------
msdosfs                          0x00000032     0  
fdescfs                          0x00000059    10  synthetic, jail
devfs                            0x00000071    10  synthetic, jail
cd9660                           0x000000bd     0  read-only
tmpfs                            0x00000087     1  jail
procfs                           0x00000002     0  synthetic, jail
nfs                              0x0000003a     0  network
ufs                              0x00000035     1  
linprocfs                        0x000000b5     0  synthetic, jail
nullfs                           0x00000029    86  loopback, jail
smbfs                            0x00000086     0  network
fusefs                           0x000000ed     0  synthetic, jail
zfs                              0x000000de    38  jail, delegated-administration
linsysfs                         0x0000008a     1  synthetic, jail
cloud:/root@[13:57] # 
```

FreeBSD version ( uname -a ): FreeBSD server3.technikradio.org 12.1-RELEASE-p8 FreeBSD 12.1-RELEASE-p8 GENERIC  amd64

CBSD version ( cbsd version ): 12.1.13

**Comment by olevole** [comment]
do you have fuse.ko module at boot ?
```
fuse_load="YES"
```

in loader.conf or:

```
kld_list="... fuse ..."
```
in /etc/rc.conf

?

**Comment by Doralitze** [comment]
> do you have fuse.ko module at boot ?
> 
> 
> ```
> fuse_load="YES"
> ```
> 
> in loader.conf
> 
> or:
> 2)
> 
> ```
> kld_list="... fuse ..."
> ```
> 
> in /etc/rc.conf
> 
> ?

Yes. I do so. It is being loaded within rc.conf and shows up in kldstat right after boot.

**Comment by Doralitze** [comment]
> do you have fuse.ko module at boot ?
> 
> 
> ```
> fuse_load="YES"
> ```
> 
> in loader.conf
> 
> or:
> 2)
> 
> ```
> kld_list="... fuse ..."
> ```
> 
> in /etc/rc.conf
> 
> ?

Yes. I do so. It is being loaded within rc.conf and shows up in kldstat right after boot.

**Comment by olevole** [comment]
How is the file system mounted inside the container automatically, rc.d-script, fstab, rc.local ? Can you share mount script/records ? Or share image of jail without [private] data but with  working bindfs mount ? unfortunately I have no information to reproduce.

I did/compare result from 

`cbsd jexec jname=fuse sysctl -a |grep jail`

after host reboot and after restart jail and the output is the same.

**Comment by olevole** [comment]
BTW, on the other hand, I found that this check never passes:

https://github.com/cbsd/cbsd/blob/develop/tools/makejconf#L307

kldstat -m fuse

if not valid for my FreeBSD-13-CURRENT host. Valid test is:

kldstat -qm **fusefs**

but in this case, I do not understand why turning off and on the setting helps you.

**Comment by olevole** [comment]
Changed fuse test in /usr/local/cbsd/tools/makejconf: https://github.com/cbsd/cbsd/commit/b89461a2855b77a4c929b7e12f74cab3a78d7728

if it doesn't help you try checking output for:

'cbsd jls display=jname,allow_mount,allow_fusefs,astart'
`cbsd jexec jname=fusetest sysctl -a |grep fuse'

after FreeBSD hoster boot. And  after jail restart by hand. Or/also, I would be greatly helped by a container image where I can reproduce this behavior

**Comment by Doralitze** [comment]
First of all: Thanks for your help!
> How is the file system mounted inside the container automatically, rc.d-script, fstab, rc.local ? Can you share mount script/records ? Or share image of jail without [private] data but with working bindfs mount ? unfortunately I have no information to reproduce.
> 
Unfortunately I cannot share the jails data.

The jail is being provided with a directory prior to its upstart using cbsd's jails-system/$jail/master_poststart.d scripts. After mounting said directory within the jail the script calls `/usr/local/bin/cbsd jexec jname=$jail /bin/sh /etc/rc` which starts the actual jail rc. Everything works as expected so far.

Now within the jails `rc.d` directory is an init script which essentially calls `/usr/local/bin/bindfs -u www -g www /mnt/${rf_subdir} /usr/local/var/nginx/${rf_subdir}` Which does not work right after jails upstart but requires a toggle of the said jail property. Of course I can insert that command within the file mounting the first directory layer after calling `/bin/sh /etc/rc` but that doesn't seam to be a great solution.
> I did/compare result from
> 
> `cbsd jexec jname=fuse sysctl -a |grep jail`
> 
> after host reboot and after restart jail and the output is the same.

I didn't had time to check your proposed change jet but I'll do so within the next couple of days. I'll also try to get you an image but I can't promise on that one.

**Comment by olevole** [comment]
Returning to the problem...

To play the problem, I launched a new stock FreeBSD 13.0 installation and latest CBSD from pkg:

1) my environment:
```
zfs23:/@[15:22] # uname -rm
13.0-RELEASE amd64

zfs23:/@[15:22] # cbsd version
13.0.9
```
2) Enable fusefs module on boot and load in runtime:
```
echo "fusefs_load=YES" >> /boot/loader.conf
kldload fusefs
```
3) Create new 'fusefs' jail with fusefs-bindfs package inside, allow_fusefs enabled: 
````
cbsd jcreate jname=fusefs runasap=1 allow_fusefs=1 pkglist="fusefs-bindfs"
```
4) to check that allow_fusefs is enabled:
```
cbsd jget jname=fusefs allow_fusefs
cbsd jls display=jname,allow_fusefs
```
5) create '/usr/local/www' mount point inside jail:
```
cbsd jexec jname=fusefs mkdir /usr/local/www
````
6) mount /bin directory inside jail via bindfs to /usr/local/www
```
cbsd jexec jname=fusefs /usr/local/bin/bindfs -u www -g www /bin /usr/local/www
```
7) to check mount:
```
cbsd jexec jname=fusefs ls -la /usr/local/www
```
8) reboot host

9) after host boot: check for allow_fusefs and try to mount:
```
zfs23:/@[15:29] # uptime
 3:29PM  up 32 secs, 1 user, load averages: 0.12, 0.03, 0.01
zfs23:/@[15:29] # cbsd jget jname=fusefs allow_fusefs
allow_fusefs: 1
zfs23:/@[15:29] # cbsd jexec jname=fusefs /usr/local/bin/bindfs -u www -g www /bin /usr/local/www
zfs23:/@[15:29] # 
zfs23:/@[15:29] # cbsd jexec jname=fusefs ls /usr/local/www |head -n5
[
bash
cat
chflags
chio
```

At the moment is not reproduced. Please re-open if you can write similar steps to play a problem.
