### ISSUE TITLE
Feature Request: Arch Linux bhyve template

### ISSUE THREAD

**Issue by jnbek** [cbsd/cbsd#53]
You've done a great job with this!! I'd like to request a bhyve template for Arch Linux though... The Arch Linux ISO is about half the size of the Fedora ISOs and should be a pretty simple addition to the project.

**Comment by olevole** [comment]
do not come quickly - unfortunately, I'm not very familiar with the process of installation of arch linux. I've create template for boot from iso:
https://github.com/olevole/cbsd/blob/master/etc/defaults/vm-linux-ArchLinux-x86-2015.09.01.conf

But I have not yet found how to boot it from HDD. When i try to boot via UUID i got panic:

https://asciinema.org/a/7dpp5vlcpatjkkmeurym02don

**Comment by jnbek** [comment]
hmm, yea the wiki defaults to -U flag for genfstab... should be able to switch that to -L we'll need to make sure that the docs outline this caveat... I'll play with it some and see what options there are to overcome this... otherwise, it looks great!!

**Comment by jnbek** [comment]
Grrr.... been through all this work setting up an environment and went to test this and found out my CPU isn't supported by bhyve... I'll see if I can find another test computer that may support it. Now, I'm inclined to say roll this, since it did in fact install and boot most of the OS. The problem seems to be related to the fstab setting which most experienced Arch Linux users should be able to figure out.

**Comment by olevole** [comment]
Will be available with CBSD 11.0.5  and UEFI options. I've not recommended to use grub-bhyve boot method for Linux, so for UEFI support you need update hoster to FreeBSD 11.0+
