### ISSUE TITLE
ppt devices not showing up inside VM when trying to use PCI passthrough

### ISSUE THREAD

**Issue by PaddyMac** [cbsd/cbsd#530]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD 13.0-CURRENT #3 88d21a5afef-c271973(master)

CBSD version ( cbsd version ): 12.1.16

I'm trying to set up a pfSense VM with bhyve using cbsd. I'm trying to use PCI passthrough to give two NICs directly to the VM.

I have vmm_load="YES" and pptdevs="4/0/0 4/0/1" in /boot/loader.conf. "pciconf -lv" shows the ppt devices exist:

ppt0@pci0:4:0:0:        class=0x020000 rev=0x20 hdr=0x00 vendor=0x14e4 device=0x1639 subvendor=0x103c subdevice=0x7055
    vendor     = 'Broadcom Inc. and subsidiaries'
    device     = 'NetXtreme II BCM5709 Gigabit Ethernet'
    class      = network
    subclass   = ethernet
ppt1@pci0:4:0:1:        class=0x020000 rev=0x20 hdr=0x00 vendor=0x14e4 device=0x1639 subvendor=0x103c subdevice=0x7055
    vendor     = 'Broadcom Inc. and subsidiaries'
    device     = 'NetXtreme II BCM5709 Gigabit Ethernet'
    class      = network
    subclass   = ethernet

I ran "cbsd bhyve-ppt mode=attach ppt=4/0/0 jname=pfsense1" and "cbsd bhyve-ppt mode=attach ppt=4/0/1 jname=pfsense1".

This is the relevant line in /usr/jails/vm/pfsense/bhyve.conf showing that the commands did work:
pci_passthru_args=' -s 6,passthru,4/0/0 -s 7,passthru,4/0/1'

However, when I start the VM, I'm having at least a couple of issues. Many times now, the VM crashes the moment I connect to the VM with VNC. It never did this before enabling PCI passthrough. So I repeatedly have to restart the VM. Every once in a while,it won't crash the moment VNC connects. When I have been able to log in via VNC and run commands like ifconfig or pciconf inside the VM, it shows that the two ppt devices are not available in the VM.

Maybe this isn't a cbsd issue. Maybe it's a bhyve issue. I haven't tried setting up a bhyve VM manually to see if these issues are still present.

**Comment by olevole** [comment]
@PaddyMac unfortunately I am now very limited by hardware with FreeBSD, I do not have a physical server with an extra PCI device. Is there any result of your tests without cbsd?

**Comment by PaddyMac** [comment]
I tried both chyves and vm-bhyve to setup VMs, and I got similar but not identical behavior. For example, with chyves the VM would crash immediately upon starting if both PCI passthrough and VNC were enabled. But if VNC was not enabled, PCI passthrough actually worked, and the NIC appeared to the OS inside the VM just as if it were running on hardware. With vm-bhyve, the device did not show up inside the VM just as with cbsd.

So frankly it appears that there may be some odd mix of issues where bhyve is partly at fault and cbsd, chyves, and vm-bhyve all have their own issues with handling PCI passthrough.

If you're interested, I'd be willing to create a shell account on my system for you and let you poke around on it at your leisure.

**Comment by olevole** [comment]
> If you're interested, I'd be willing to create a shell account on my system for you and let you poke around on it at your leisure.

I would be interested to see. I'm not sure if this will happen quickly. Also, experimenting with PPTs can lead to crashes. Although, maybe I'm wrong ;)

**Comment by olevole** [comment]
no response
