### ISSUE TITLE
flatcar linux bhyve vm-linux-cloud-*

### ISSUE THREAD

**Issue by mariusrugan** [cbsd/cbsd#533]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD 12.1-RELEASE-p10 GENERIC  amd64

CBSD version ( cbsd version ): 
12.1.16

Hi,
first, thanks a lot for your work, i'm new to bhyve on freebsd & i find it more approachable than other bhyve managers;
i'm coming from kvm/libvrt on linux where i also instrumented the ecosystem with similar bash and simple system binaries. 

i'm looking to run (add support for) Flatcar Linux (https://www.flatcar-linux.org/) which is CoreOS resurrected. 
From what i can read in docs, i going to remove the package and take the dev env route. Is there any work conflicting with this ? 
TIA

**Comment by mekanix** [comment]
Hello,

First of all, thank you for the kind words, and welcome!

If I understand layout of https://stable.release.flatcar-linux.net/amd64-usr/current/ right, there are .iso images available, so it can be installed like any other Linux distro. For how to make new disto profile, check out https://github.com/cbsd/cbsd-vmprofiles. Those profiles are in `/usr/local/cbsd/etc/defaults`.

Did I answer your question?

**Comment by mariusrugan** [comment]
yes, thanks, 

am looking to add "cloud-init way" first, because i understand it, namely make available a qcow2 [1] or compatible image to bhyve and cloud-init the installation, just like the other vm-linux-cloud-* in cbsd; 

second, am looking to dig into adding support for Ignition [2] as an alternative to cloud-init, which is just adding a kernel parameter for boot [3] (inherited from CoreOS but not fully compatible with what CoreOS had) 

[1] https://docs.flatcar-linux.org/os/booting-with-libvirt/
[2] https://docs.flatcar-linux.org/ignition/what-is-ignition/
[3] https://github.com/flatcar-linux/ignition/blob/flatcar-master/doc/supported-platforms.md
_Use the coreos.config.url kernel parameter to provide a URL to the configuration. The URL can use the http://, https://, tftp://, or s3:// schemes to specify a remote config or the oem:// scheme to specify a local config, rooted in /usr/share/oem._

**Comment by mekanix** [comment]
To create cloud-init image, you need to use raw disk format. If I'm wrong, @olevole please correct me.

**Comment by olevole** [comment]
> To create cloud-init image, you need to use raw disk format. If I'm wrong, @olevole please correct me.

Yes, bhyve has experimental support for QCOW2 format, but it is not in the base yet

**Comment by mariusrugan** [comment]
we're talking about this raw format right?
```qemu-img convert xyz.qcow2 xyz.raw```

**Comment by olevole** [comment]
@mariusrugan unfortunately I'm not familiar with **Ignition** (and flatcar). All cloud-init-based images in CBSD used localStorage configstorage ( fat/cd9660 drive ). i'm sure using post/pre-start hooks we can manage HTTP content on the server. 
But I haven't taken the time to experiment with that yet. Although I mimicked openstack URL/data structure once and it worked for bhyve

**Comment by olevole** [comment]
> we're talking about this raw format right?
> `qemu-img convert xyz.qcow2 xyz.raw`

yes it can be used in profile. 

qemu-img convert -f qcow2 -O raw flatcar_production_openstack_image.img flatcar_production_openstack_image.raw

**Comment by mariusrugan** [comment]
Update, 
prototyping with _flatcar_production_qemu_uefi_image.img_ which is qcow2 format, and converted it to raw, (i think _flatcar_production_openstack_image.img_ is not UEFI compatible) i've succeed to boot. 
i have to figure out cloud-init part and will fork vmprofiles and create a PR.
Is there any easy way that i can work with my own fork locally (vmprofiles) ?

TIA

**Comment by mekanix** [comment]
You can clone repo in, for example, `/home/user/repos/vm-profiles` and then you can null mount them over existing profiles with `mount -t nullfs /home/user/repos/vm-profiles /usr/local/cbsd/etc/defaults`. That way original installation won't be touched, and you can have the changes in git repo once you're finished. To "undo" the mount `umount /usr/local/cbsd/etc/defaults`. Note that I didn't try this myself, so if it doesn't work, you can always symlink new file to the one you have in your git repository. Good luck, and thank you for contribution!

**Comment by mekanix** [comment]
I don't understand the `EDIT` part, so can you elaborate it more, please?

**Comment by mariusrugan** [comment]
Sure, thanks for quick re:

If we take this for example:
https://github.com/cbsd/cbsd-vmprofiles/blob/master/vm-linux-cloud-ubuntuserver-amd64-20.04.conf#L28
there is a iso_extract step; can it be abused also to convert the image from qcow2 to raw via same CLI oneliner ?
_bzip2 -d xyz.img.bz2 && qemu-img ..._

**Comment by mekanix** [comment]
Give it a try. I never tested it,  so we might have new think on our hands once you finish :o)

**Comment by olevole** [comment]
Looks like we need for quotes to support || or ';' or '&&' combination in all **$extract_iso** (e.g https://github.com/cbsd/cbsd/blob/v12.1.16/tools/fetch_iso#L103 )

**Comment by olevole** [comment]
I guess the profile **vm-linux-cloud-Flatcar-edge-x86_64.conf** could be like this: https://pastebin.com/2p8KM5JK

just save it in ~cbsd/etc/vm-linux-cloud-Flatcar-edge-x86_64.conf and try to create:

cbsd bcreate jname=flat1 vm_os_type="linux" vm_os_profile="cloud-Flatcar-edge-x86_64" vm_ram=1g vm_cpus=1 runasap=1 astart=0

...

**Comment by olevole** [comment]
plz apply changes first: https://github.com/cbsd/cbsd/commit/18dbb8b6d7de845ee9a6e9b8eb87198cedba5115

**Comment by olevole** [comment]
cleanup: at the moment there is no possibility
