### ISSUE TITLE
Inconsistent command and description (jremove)

### ISSUE THREAD

**Issue by michael-o** [cbsd/cbsd#537]
FreeBSD version ( uname -a ): FreeBSD bsd1srv.fritz.box 12.2-STABLE FreeBSD 12.2-STABLE r365640 GENERIC  amd64

CBSD version ( cbsd version ): 12.2.0

This may be subjective, but I think this is inconsistent and I'll give it a try. After a jail has been created/constructed I wanted to delete/destroy them.
From an admin's/programmer's point of view there are two pairs of terms one can use: create/construct + destroy/delete and add + remove.
I see:
```
# cbsd jremove --help
[jail] Destroy jail
require:
opt: jname inter
External help: https://www.bsdstore.ru/en/12.x/wf_jremove_ssi.html
```

My point is:
* Why are two different terms used here? This is confusing jremove => Destroy jail
* If I remove something I have to add it first, but there is no `jadd` command.

I hope you get my idea of inconsistency.

**Comment by olevole** [comment]
Most likely you are right) 
The reasons for the remove are most likely historical, when the CBSD was originally created for jail and we can remove the jail:
```
   -c      Create a new jail.  The jail jid and name parameters (if
             specified on the command line) must not refer to an existing
             jail.
```

```
    -r      Remove the jail specified by jid or name.  All jailed processes
             are killed, and all jails that are children of this jail are also
             removed.
```

these commands still reflect these actions:
```
cbsd jcreate jname=xxx runasap=1 astart=0
cbsd jremove jname=xxx
```

**Comment by michael-o** [comment]
Thanks for the confirmation. What is your recommendation to resolve this confusion with new users?

**Comment by olevole** [comment]
This is a difficult question. For new users, to clear up any confusion, I definitely recommend starting with the official documentation: https://www.bsdstore.ru/en/12.1.x/wf_jremove_ssi.html 

As for terminology, this is a debatable issue. Do you suggest using destroy instead of remove ?

**Comment by michael-o** [comment]
> Do you suggest using destroy instead of remove ?

Yes,  would prefer destroy/delete over remove for consistency.

**Comment by olevole** [comment]
@Stefar77 @mekanix  what do you think? I don't see anything wrong (except huge work to rewrite tons of scripts ;) with adding an alias 'destroy' to 'remove'

**Comment by michael-o** [comment]
> 
> 
> @Stefar77 @mekanix what do you think? I don't see anything wrong (except huge work to rewrite tons of scripts ;) with adding an alias 'destroy' to 'remove' - this work may take a year ;), but if this is a very suitable change - why not. If it is useful, then we will leave this issue. Otherwise I propose to close this task as now the project has few(man power) resources for changes related to command renaming (code change, document change, announcement via mailing list / telegram, change Ansible / puppet playbooks, RestAPI .. ;-)

Again, thanks for taking this up. I don't expect a solution any time soon. Having this documented as an open issue is enough for now. for other not to trip over. Still trying to understand other rough edges of CBSD where documentation doesn't really help or I am too stupid to figure out myself.

**Comment by mekanix** [comment]
Sorry for late reply, we had a last few days of moving out Tilda Center :o(

I thought about the "problem" a bit and realized that I actually like aliases. If spoken language (in this case English) has words like remove/delete/destroy i really like when program using same spoken language for commands has remove/delete/destroy. One example: I hate it when I have to remove git remote. Which of the 3 is the proper command? And realistically, why does it even matter which of the 3 I typed in when they all have same semantic meaning. So yes, aliases! :o)

**Comment by mekanix** [comment]
> Still trying to understand other rough edges of CBSD where documentation doesn't really help or I am too stupid to figure out myself.

The result of neighter me nor @olevole are English native speakers, is that docs, even when they are written with care, are probably not the best. I know the site states that English is Google translate from Russian, so it's not great. I believe language and documentation are where we need most help as we're not able to do it better because of the lack of knowledge of the language.

That being said, maybe we should try a call for help? For me, it's not even the lack of time, it's the language, so I could even coordinate the project if needed. In short, we would like to improve the documentation if somebody helps us.

**Comment by michael-o** [comment]
> 
> 
> > Still trying to understand other rough edges of CBSD where documentation doesn't really help or I am too stupid to figure out myself.
> 
> The result of neighter me nor @olevole are English native speakers, is that docs, even when they are written with care, are probably not the best. I know the site states that English is Google translate from Russian, so it's not great. I believe language and documentation are where we need most help as we're not able to do it better because of the lack of knowledge of the language.

Neither am I a native English speaker. But have written a lot of documentation in English.

> That being said, maybe we should try a call for help? For me, it's not even the lack of time, it's the language, so I could even coordinate the project if needed. In short, we would like to improve the documentation if somebody helps us.

The problem is unless someone is very well acquiant with the system it is virtually impossible to write decent documentation. I will try to spend the next couple of weeks to wrap my mind around jail templates, skel and hook directories to migrate a jail from ez-jail and prepare ground work for upcoming projects based on jails. Based on this I may try to share documentation.

**Comment by olevole** [comment]
>So yes, aliases! :o) 

@mekanix well, it's all settled! ;) - we will add an alias and declare the remove as deprecated )
I think all these remarks make the project better and more convenient. So why not.

PS: Agree about the documentation. Little by little, slowly over time..))

**Comment by mekanix** [comment]
> The problem is unless someone is very well acquiant with the system it is virtually impossible to write decent documentation.
That's why I said I'd coordinate the doc effort.

**Comment by mekanix** [comment]
@olevole I wouldn't deprecate any variant, I would live them as equal.
