### ISSUE TITLE
Bhyve guest CPU cores issue

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#552]
FreeBSD version ( uname -a ): `FreeBSD hydrogen01 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64`
CBSD version ( cbsd version ): `12.2.3`

I've managed to successfully setup a Windows 10 bhyve guest using CBSD. However, I'm experiencing a performance related issue: No matter how many CPU cores I assign to the guest (4, 8, 16, ...) it seems that the bhyve host machine only maxes out two cores when running a heavy load in the guest.

Is there some (CBSD) setting I need to adjust to ensure that bhyve guest VMs can take full advantage of my 14 cores / 28 threads system?
This Windows 10 guest is supposed to be a build agent for a Jenkins setup so CPU power is kind of a vital metric here :p

Host:
- FreeBSD 12.2 64-bit
- Intel Xeon E5-2690 v4 @ 2.60GHz (14C/28T)
- 128 GB DDR4 ECC

Please let me know if I should provide additional information. I'm fairly new to CBSD/bhyve. I've only worked with jails so far.

**Comment by olevole** [comment]
Unfortunately I don't know for sure) I think I once heard something about this. This is either license related or one of the options: https://answers.microsoft.com/en-us/windows/forum/windows_10-performance-winpc/windows-10-versions-cpu-limits/905c24ad-ad54-4122-b730-b9e7519c823f

If it has to do with topology, you can try to create alternative topology for Windows VM via `cbsd vm-cpu-topology-tui`, e.g, instead of X cpu, try to create:

> 1 cpu (socket), 8 cores, 1 thr
or
> 1 cpu (socket), 8 cores, 4 thr
or
> 1 cpu (socket), 1 cores, 16 thr
...

**Comment by olevole** [comment]
By the way, as far as I know, physical servers exist where the number of threads is more than 2 (e.g ARM8 Cavium ThunderX2 has 4 threads per core), therefore, a large number of threads is ok for windows ;-)

**Comment by Tectu** [comment]
I didn't have the Windows 10 installation activated yet as I wanted to be sure that everything works out before doing so. I've now activated it successfully with a genuine license but the issue remains. The task manager continues to report back 2 sockets with 2 cores when the CBSD settings are set to 8 cores.

How do I apply/attach the new CPU topology I created with `cbsd vm-cpu-topology-tui`?

**Comment by olevole** [comment]
new topology can be applied through 'cbsd bconfig' or 'cbsd jset vm_cpu_topology=XXX jname=YY` command

**Comment by Tectu** [comment]
After creating a custom CPU topology & assigning that to my Windows 10 VM everything works as expected. The Windows task manager now reports 16 cores as expected and running a heavy multi-threaded load results in more cores being maxed out on the host machine as expected.

Thank you!

**Comment by Tectu** [comment]
Just wanted to report back with an update on this: Today I configured & installed a Windows 11 VM. I encountered the same issue again: Without manually assigning a correctly defined VM CPU topology the Windows VM only reported 2 cores being available although `vm_cpus` was set to `8`.

**Comment by olevole** [comment]
Unfortunately, I don't know what we can improve here for the user. Theoretically, for Windows profiles, we can offer an alternative default topology(???). But perhaps it will be something like a [POLA](https://docs.freebsd.org/en/books/handbook/glossary/#pola-glossary), where the user can expect the same behavior from the CBSD. Any thoughts?

@Stefar77 sorry for the call, but you are an experienced windows guest user ;-) Any comment?

**Comment by olevole** [comment]
Stefan via TG: https://t.me/cbsdofficial/24068

**Comment by Tectu** [comment]
> Unfortunately, I don't know what we can improve here for the user.

I didn't mean to complain. I merely wanted to update this issue for future readers so somebody looking for this type of symptom via a web search engine now has a better chance of ending up here due to the notion of "Windows 11".

> Theoretically, for Windows profiles, we can offer an alternative default topology(???).

I assume you'd have to generate this profile "dynamically" for each CBSD host individually, right? The topology depends on the underlying hardware (unless I misunderstood something).

Maybe leaving a note regarding this in the official documentation might be sufficient for now :)
