### ISSUE TITLE
Installing Windows Server

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#553]
Based on the documentation I am having trouble figuring out what the preferred/recommended way is of getting a Windows Server 2016 installation running with CBSD.

Do I have to create a custom profile or is that not necessary for a "one shot" installation? Would I get by with selecting the existing Windows 10 profile but exchanging the ISO for the Windows Server one?

**Comment by olevole** [comment]
Microsoft does not allow to distribute Windows ISO, so in CBSD, 'windows' profile exist for sample only  - you need to create your own profile. Or create any VM and attach ISO

```
cbsd media mode=register path=<path to ISO>
cbsd media mode=attach ...
```
(or attach ISO via `cbsd bconfig`)


in addition, CBSD supports for cloudbase (Windows cloud image, demo: https://www.youtube.com/watch?v=PDkxrHb5Xt8 ) but again, I don’t know the policy for the distribution of Windows virtual images. For this reason, there is no ready-made profile.

( cloubase for Windows is the same as cloud-init for Linux/BSD - you can forget about the long OS installation every time and run it in one click within a few seconds )

**Comment by Tectu** [comment]
Thanks. This information should be sufficient for me to proceede.
