### ISSUE TITLE
Remove cloned bhyve

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#554]
I am currently in the following scenario: I have three bhyve VMs: A, B and C. The VM B is a clone of A. The VM C is also a clone of A.
I want to keep VMs B and C but remove A as it is no longer needed.

Currently I cannot remove VM A because both B and C depend on it. Is there a way to remove this constraint and make VM's B and C "standalone" VMs that are not depending on A anymore?

**Comment by olevole** [comment]
if my memory serves me, there is a 'promote' flag for jclone/bclone, which executes the 'zfs promote' command: [zfs-promote(8)](https://man.freebsd.org/zfs-promote/8.)  Unfortunately I cannot check it in the next week

**Comment by Tectu** [comment]
Hello Oleg,

Would you by any chance be able to have a look at this? I am very new to cbsd & bhyve and would appreciate more detailed inputs at this time.

**Comment by Tectu** [comment]
After manually issuing `zfs promote` on the affected datasets I was able to successfully execute `cbsd bremove`.
