### ISSUE TITLE
Proper way of upgrading jails

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#555]
So I've been playing around with CBSD and jails for a while now. I am quite happy about CBSD - except for the documentation :p

The time has come to upgrade my jails. So far I have upgraded the host itself to the latest FreeBSD release.
What is the process of upgrading one or more Jails properly? From the documentation I understand that I would upgrade the base jail - and all my other jails would then be upgraded too? How do I locate the base jail? How do I upgrade the base jail? What requirements are there for a successful upgrade of a host with about 12 jails managed through CBSD?

I'd really appreciate it if somebody could provide some information/explanations and outline the process. I want to understand this better before attempting the jail(s) upgrade.

**Comment by olevole** [comment]
depends on what you mean by 'upgrading'. 
If you need to bump[1] jail base to major.minor version, just choose/set another version via `cbsd jconfig' or `cbsd jset`[2]:
```
cbsd jset ver=12.2 jname='*'
```

This will force the use of a different base tree in ~cbsd/basejail/bases_*

If you need to update current base tree to latest ( e.g patchlevel: FreeBSD 12.1-p1, FreeBSD 12.1-p2 .. ), just use `cbsd baseupdate` ( this can happen automatically when the base is received[3] ) or by hand via freebsd-update[4]


> except for the documentation :p

Yeah, this is an eternal problem of free-time projects: docs just does not keep up with the development ;-)

__
[1] - https://www.bsdstore.ru/en/12.2.x/wf_jupgrade_ssi.html
[2] - https://www.bsdstore.ru/en/12.2.x/wf_jconfig_ssi.html#jset
[3] - https://www.bsdstore.ru/en/base_cbsd.html#general
[4] - https://www.bsdstore.ru/en/12.2.x/wf_jupgrade_ssi.html#freebsd-upgrade

**Comment by Tectu** [comment]
Could you explain the differences of bumping vs updating the current base tree? What are the differences? When would I choose which option (In general, of course)? What are the consequences?

From my point of view I just want to upgrade my jails like I upgrade any FreeBSD machine. Eg. from 12.1 to 12.2.
