### ISSUE TITLE
cbsd etcupdate tries to update files in /root

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#556]
Actual version of `cbsd etcupdate` does not exclude `/root` from etcupdate processing. So, modifications in `/root/.cshrc` create merge conflicts. It would be nice to add an option to disable `/root` processing during etcupdate. Or even better - add an option where one can pass additional options directly to etcupdate, so any additional tuning of the update process could be possible.

**Comment by olevole** [comment]
Such an opportunity is provided: https://github.com/cbsd/cbsd/blob/develop/etc/defaults/etcupdate.conf#L9
But apparently it doesn't work, need to double-check

**Comment by olevole** [comment]
fixed
