### ISSUE TITLE
Cannot migrate jails

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#558]
FreeBSD version ( uname -a ): 12.2-RELEASE-p1 GENERIC amd64

CBSD version ( cbsd version ): 12.2.4

Trying to migrate a jail to another host:

```
cbsd jcoldmigrate node=bimp-jails-3.reseaucloud.local jname=coredns3
Coldmigrate.Error in j2prepare
Guru meditaion:
Preparing.   * check for remote CBSD version: 12.2.4
....Error in rexe_2
Guru meditaion:
chown: /jails/cbsd/etc/coredns3.secrets: Operation not permitted
```

**Comment by olevole** [comment]
most likely this is due to my error in the comparison condition in ALL files with SUDO: https://github.com/cbsd/cbsd/commit/975ecd3e176f7070d1732b732d8de740da545346 . This is fixed in the github version. I plan to release it in January 2021

**Comment by olevole** [comment]
tested with 12.2.5a
```
cbsd jcoldmigrate node=srv-01.olevole.ru jname=gogo
Coldmigrate.....ok
jcoldmigrate done in 1 minutes and 25 seconds
```
