### ISSUE TITLE
Limit of 16 vcpu to the vm 

### ISSUE THREAD

**Issue by Firemad03** [cbsd/cbsd#559]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD xtrem03 13.0-CURRENT FreeBSD 13.0-CURRENT #0 f659bf1d31c-c254882(main): Thu Dec  3 04:51:57 UTC 2020

CBSD version ( cbsd version ): 12.2.4

I got 2 x Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz in my server. (https://ark.intel.com/content/www/us/en/ark/products/64595/intel-xeon-processor-e5-2670-20m-cache-2-60-ghz-8-00-gt-s-intel-qpi.html)

I got a minor problem that I think it doesn't matter but I don't know but it can have a connection with my problem.

If I run cbsd cpu-topology well I get the following 

```
Model: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Sockets num: 2
Cores num: 48
Threads num: 16
--
Core max: 64
```

Well I don't think it does matter for my bug but anyways it's reporting wrong for some reasons and I don't understand why I get 64 cores max cpu... I know this cpu have 3 edition (I got the first one and it's the reason for the 0) so maybe it's mistaken something or I don't understand something :)

If we go to my problem is that the maximum for a VM is 16 vcpu per vm but I can go to a maximum of 32 vcpu... (because Intel said that I have 16 threads per socket and because I have 2 sockets I have a maximum of 32 not 64...) I don't know why I have a hard limit to 16 for the VM.

If I go to the cbsd bconfig of the VM and I add a topology for my cpu (right one so 2 socket, 8 cores and 2 threads = 32) well the cbsd gui can see it for a maximum of 32 for my vm but if I set it and I start my vm I got the: sorry 1-16 vcpu only.

Any reasons about the 16 vcpu only ?
Is it a limitation ?
A bug ?
Something wrong with my config ?

Sorry to bother you if it isn't a bug. I don't understand :) 

Note: Really nice work with cbsd. I tried others and cbsd was the best.

**Comment by Firemad03** [comment]
I saw the this issue about the cpu toplogy that you posted on your website: https://reviews.freebsd.org/D9930 and I see in the conversation the limit of 16 vcpu... I hope it isn't a bhyve limitation :)

**Comment by Firemad03** [comment]
Oh god... it's a limit of bhyve: https://lists.freebsd.org/pipermail/freebsd-virtualization/2014-November/003104.html 

I guess for this vm that I need more vcpu I will move it to a jail instead :)

**Comment by olevole** [comment]
Thanks for your feedback!
As I recall, **16** is an old limitation, and Rodney W. Grimes (<rgrimes at FreeBSD.org>) has worked to support over 24+ cores.

I've seen patches somewhere, but I'm not sure if they went upstream. Try to ask Rodney or freebsd-virtualization@  

As for the CBSD, the limitation is set through the configuration file https://github.com/cbsd/cbsd/blob/develop/etc/defaults/bhyve-default-default.conf#L53

All settings in /usr/local/cbsd/etc/defaults/* can be overriden by ~cbsd/etc/<file>.  E.g:
```
echo 'vm_cpus_max=36' >> ~cbsd/etc/bhyve-default-default.conf
```

and try to create/start vm, e.g:

```
cbsd bcreate jname=test \
  vm_os_profile="cloud-FreeBSD-zfs-x64-12.2" \
  vm_os_type="freebsd" \
  vm_ram=2g \
  vm_cpus=32 \
  imgsize=10g \
  ci_gw4=10.0.0.1 \
  ci_ip4_addr=10.0.99 \
  runasap=1
```

(where 10.0.0.1/10.0.0.100 - valid gw/IP for your net)

**Comment by olevole** [comment]
yes, `cbsd cpu-topology` gives incorrect information for your host. this needs to be fixed, of course ;)

**Comment by olevole** [comment]
someone has already been interested in this issue: https://lists.freebsd.org/pipermail/freebsd-virtualization/2018-November/006992.html. I remember exactly that somewhere (maybe on someone's twitter) I saw a bhyve load with an increased number of cores. But I can't find where I saw this ;(

**Comment by olevole** [comment]
FYI:
https://cgit.freebsd.org/src/commit/?id=c76e4b89
https://cgit.freebsd.org/src/commit/?id=f1d450dd
