### ISSUE TITLE
REQ - Add Linuxlator support while creating jails

### ISSUE THREAD

**Issue by jas-s2r** [cbsd/cbsd#562]
This is not a bug but a feature request.
It would be great if CBSD would support creating jails using Linuxlator

**Comment by mekanix** [comment]
That would be a nice feature. I think it would be best to start with FreeBSD of version at least 13 (BETA1 at the moment of writing this) as linuxator got many improvements last year. Anyway, what is needed today to have linuxator in jail? With the quick search I found https://forums.freebsd.org/threads/linuxulator-how-to-run-google-chrome-linux-binary-on-freebsd.77559/ to be very comprehensive. Is there anything better in terms of documentation that we should follow?

**Comment by jas-s2r** [comment]
I think that post sums up many of the resources available.

**Comment by olevole** [comment]
for now I can only suggest using the solution from https://github.com/cbsd/cbsd/issues/526 
At the moment I have no way to check it in work

**Comment by olevole** [comment]
Linux container profiles was added to Git/CBSD **13.0.4** version.
Implementation based on records with the FreeBSD Linuxlator wiki page ( https://wiki.freebsd.org/LinuxJails )  and the old CBSD script to create a kFreeBSD environment ( https://github.com/cbsd/cbsd/blob/develop/share/FreeBSD-jail-kfreebsd-wheezy-system-skel/tests/00.check_distribution.sh )
