### ISSUE TITLE
CBSD 13 on FreeBSD 12 - errors on jail startup, unusable jail

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#563]
FreeBSD version ( uname -a ): 12.2-RELEASE-p3 amd64

CBSD version ( cbsd version ): 13.0.0

I get many errors on newly created jail startup:

```
Default NIC automatically selected: wlan0
set resource limit: [ ]
jail renice: 1
Starting jail: netbox1, parallel timeout=0
netbox1: created
mtree: unknown user `ntpd'
mtree: failed at line 49 of the specification
cp: /var/log/utx.lastlogin: No such file or directory
chmod: /var/log/utx.lastlogin: No such file or directory
cp: /var/log/utx.log: No such file or directory
chmod: /var/log/utx.log: No such file or directory
ELF ldconfig path: /lib /usr/lib /usr/lib/compat /usr/local/lib /usr/local/lib/compat/pkg /usr/local/lib/compat/pkg
ldconfig: mkstemp(/var/run/ld-elf.so.hints.5Qwj7B): No such file or directory
32-bit compatibility ldconfig path: /usr/lib32
ldconfig: mkstemp(/var/run/ld-elf32.so.hints.7h6bLM): No such file or directory
Setting hostname: netbox1.domain.local.
Generating host.conf.
Creating and/or trimming log files.
eval: cannot create /var/run/syslogd.sockets: No such file or directory
Starting syslogd.
syslogd: cannot open pid file: No such file or directory
Clearing /tmp (X related).
Updating motd:.
Updating /var/run/os-release install: /var/run/os-release: No such file or directory
done.
Starting sendmail_submit.
451 4.0.0 can not chdir(/var/spool/mqueue/): No such file or directory
/etc/rc: WARNING: failed to start sendmail_submit
Starting sendmail_msp_queue.
Starting cron.
cron: can't open or create /var/run/cron.pid: No such file or directory
/etc/rc: WARNING: failed to start cron

Wed Feb 17 17:58:28 CET 2021
jstart done in 4 seconds
```

Trying to use the jail I get strange errors like libraries not found etc.
In short, CBSD 13.0.0 does not work correctly on FreeBSD 12.2.
Please, fix it.
This is not a production system, but I would like to repair CBSD installation though.
BTW, is there any way to downgrade CBSD _without_ backup of the database? ;)

**Comment by Peter2121** [comment]
It seems that the problem comes from incorrect /var directory. I could manually copy it from another jail and now my jail seems to work correctly.

**Comment by olevole** [comment]
most likely this is a problem of mismatch between your base and password files (hoster env): https://github.com/cbsd/cbsd/issues/361#issuecomment-444683439

**Comment by olevole** [comment]
> BTW, is there any way to downgrade CBSD without backup of the database? ;)

downgrate can be done by replacing the files in /usr/local/cbsd + `cbsd initenv`. But with one condition - if there were no SQL schema migrations during the update.
