### ISSUE TITLE
[Feature request] Add "directory" parameter to cbsd jexec

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#564]
Sometimes it is important to execute a command in jail in the context of a given jail's directory. It would be nice to have a parameter like `dir=/usr/local/frpc` to use in `cbsd jexec`. If this parameter is set - cbsd should change the current directory to the given one before executing the command.
For example:
`cbsd jexec jname=netbox1 dir="/home/peter/netbox-software/"  cmd="python3.7 setup.py develop"`

**Comment by olevole** [comment]
It sounds reasonable

**Comment by olevole** [comment]
done, will be available at 13.0.4
