### ISSUE TITLE
When reusing a bridge (manual network) for bhyve, cbsd creates a second bridge anyway

### ISSUE THREAD

**Issue by hexadecagram** [cbsd/cbsd#565]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD 12.2-RELEASE-p4 GENERIC amd64

CBSD version ( cbsd version ): 13.0.0

With [manual network](https://cbsd.io/cbsd/tutorials/Bhyve-network-options/#options-2-bridge-network-manual) configured, cbsd still behaves as though auto network is enabled. Here is a trace of what I see when I run bstart:

> $ ifconfig -l
> igb0 igb1 ix0 ix1 ix2 ix3 lo0 lagg0 bridge0 tap0
> $ sudo cbsd bstart myvm; ifconfig -l
> igb0 igb1 ix0 ix1 ix2 ix3 lo0 lagg0 bridge0 tap0 bridge1 tap1 tap2

In my case, bridge0 is a parent of lagg0, which in turn is a parent of ix[0-3]. igb0 is the interface that gets the default route. tap0 is my openvpn server. All of that gets configured in /etc/rc.conf and /usr/local/etc/openvpn/openvpn.conf.

Immediately after bstart, cbsd creates tap1 and bridges it with igb0 via bridge1, which would be expected if auto network were enabled (which it isn't). Then, it **also** creates tap2 and bridges it with lagg0 via bridge0. tap1 and bridge1 never get used or destroyed.

**Comment by olevole** [comment]
can you check if the behavior is different if you enter name of interface via 'manual' input ?

cbsd bconfig -> bhyvenic -> nic1 -> nic_parent ->  'manial' -> "bridge0"

AFAIK, bridge1+tap is 'system' bridge for CBSD to avoid flop of uplink interface when add/del members (resetting TSO), this behavior can be adjusted via: `create_cbsdsystem_tap=0` in ~cbsd/etc/bhyve-default-default.conf

**Comment by olevole** [comment]
@hexadecagram by the way, the cbsd logs when starting a virtual machine can also help:
`cbsd bstart`
`grep cbsd /var/log/messages`

**Comment by mekanix** [comment]
You can mimic how CBSD creates bridge with `ifconfig bridge0 description lagg0`. That's what Reggae is doing.
