### ISSUE TITLE
Cannot log into jail after update

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#566]
FreeBSD version ( uname -a ): `FreeBSD xxx 12.2-RELEASE-p4 FreeBSD 12.2-RELEASE-p4 GENERIC  amd64`
CBSD version ( cbsd version ): `13.0.1`

I updated from cbsd `12.x` to `13.0.1` on several hosts. After updating the cbsd package, I ran:
```sh
/usr/local/cbsd/sudoexec/initenv `/usr/local/cbsd/share/initenv.conf
```
Everything ran smoothly except on one host: After the update I am no longer able to log into a jail:
```sh
# cbsd jlogin my_jail
jexec: execvp: -f: No such file or directory 
```
However, starting, stopping and restarting the jail works. Also, the jail itself is "working". What I mean is: There's a server running in that jail and the server runs as expected. I simply cannot log into the jail anymore.

From reading the documentation I couldn't figure out what causes this issue and how to fix it.
Could somebody help me out here?

**Comment by olevole** [comment]
try 'cbsd initenv' pls

**Comment by Tectu** [comment]
After running `cbsd initenv` things appear to be working as expected again.

Running `/usr/local/cbsd/sudoexec/initenv` is something I gathered from the cbsd documentation. Is this incorrect or outdated? Should one only run `cbsd initenv`? or both? What is the difference?

Thank you for your help!

**Comment by olevole** [comment]
yes, `/usr/local/cbsd/sudoexec/initenv` = `cbsd initenv`. It is strange if this migration has not worked the first time.
