### ISSUE TITLE
Cloud image ZVOL error 63 (name too long)

### ISSUE THREAD

**Issue by mekanix** [cbsd/cbsd#570]
It is not CBSD bug, but I think we should handle it better. With FreeBSD-13 it is fixed, so soon it will be behind us. Anyway, this is the ZVOL@snap that was created: `zroot/usr/cbsd/cbsd-cloud-cloud-Debian-x86-10.7.0.raw@boot-debian1`. Can we loose two `cloud-`s from that ZVOL?

Just for reference: [FreeBSD PR](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238112).

**Comment by olevole** [comment]
Yes, I know about this problem and I don`t know what to do with it, except to use the latest version of FreeBSD ;-)

extra 'cloud-' in zvol name is a bug, of course. Need to check the profile in /usr/local/cbsd/etc/defaults/cloud*.conf or code that executes the clone.

**Comment by mekanix** [comment]
Just to confirm, upgrading my laptop to 13-RC2 made the error go away. Closing the ticket as the only thing we can really do is wait for 12 EOL.
