### ISSUE TITLE
CBSD and poudrier

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#571]
I am using CBSD on almost every FreeBSD host I have/run/manage.
Right now I am looking into using poudrier to start building my own ports instead of relying on `pkg` to further make my life easier.

From the documentation I understand that poudrier will automatically create one or more jails to separate the building of packages from the host OS.

I was wondering whether there is anything that could potentially going wrong when running poudrier on a system which also uses cbsd?
As far as I can judge the situation cbsd is mainly a collection of scripts (and small programs?) purely for administration. While it seems that cbsd does a lot more under the hood I believe that there is no reason to expect issues when running poudrier on the same system.

Is this assessment correct? Are there any actual experiences with this configuration/usage?

**Comment by mekanix** [comment]
I'm running CBSD + poudriere on multiple instances without problems. I suspect you know how to run CBSD :o) so I'll just paste the commands here that I use to create poudriere build jail:
```
poudriere jail -c -j 12amd64 -v 12.2-RELEASE -a amd64 # Create build jail
poudriere ports -c -m null -M /usr/ports -p local # Use /usr/ports from host

# Make your list of packages to be built
echo 'mail/postfix' >/usr/local/etc/poudriere.d/12amd64-local-pkglist
echo 'mail/dovecot' >>/usr/local/etc/poudriere.d/12amd64-local-pkglist

# Optional, makes subsequent builds faster
echo 'WITH_CCACHE_BUILD=YES' >/usr/local/etc/poudriere.d/make.conf
```

I use this to `poudriere testport` and to build [packages for Tilda Center](https://pkg.tilda.center)

**Comment by Tectu** [comment]
Thank you for your quick reply - It's certainly good to know that this is known to work!

I might need some more information here as my experience with CBSD is only about 12 months of basic operations such as jail & bhyve creation, starting, stopping, upgrading bases etc. 

The notes that you are showing, where does CBSD fit in here? Is this simply a matter of poudrier doing its thing and CBSD doesn't care at all or would I somehow "register" the build jail created by poudrier with CBSD?
From your notes it seems like that is just the basic overall poudrier setup without anything special related to CBSD.

**Comment by olevole** [comment]
Poudriere works with its own ZFS/ZPOOL data set (see ZPOOL/ZROOTFS settings in /usr/local/etc/poudriere.conf), so there should be no conflicts from CBSD.

**Comment by Tectu** [comment]
Will I be able to manage the poudrier build jail through CBSD?

**Comment by mekanix** [comment]
No. Poudriere and CBSD are ignorant of each other in every respect. @olevole maybe you can comment what [CPR](https://github.com/cbsd/modules-cpr) can provide in this regard?

**Comment by olevole** [comment]
https://github.com/cbsd/modules-cpr It was created for my needs before creating poudriere ( in ~2013 ;-) and still requires improvements (at least, documentation), still can't find time for this.
