### ISSUE TITLE
Restoring from external backup

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#572]
I'm currently dealing with the situation that one of the hosts running CBSD needs to be re-installed due to an issue with the `zroot` pool preventing the system from booting. I am planning to migrate the system's `zroot` pool to a different host by booting a FreeBSD live image and migrating the pool using `zfs send`.

My question: After re-installing the operating system on the affected host, what steps are necessary to "restore" jails operated/maintained by CBSD?
The datasets created for each jail by CBSD are intact and can just be restored. However, I assume that there is some sort of configuration that I also have to migrate.

What is the proper way of doing this? Should I re-create the jails using the same configuration on the newly installed host and then simply replace the jail's dataset or is there a better way of doing this?

**Comment by mekanix** [comment]
I'm just curious, did `zroot` pool become unbootable? As in ZFS is complaining it can not create some dataset? If yes, is the host version less than 13? What I'm trying to ask is if your issue is https://github.com/cbsd/cbsd/issues/570

**Comment by Tectu** [comment]
Yeah, the affected host is currently unable to boost from `zroot`.
However, this issue is not related to CBSD at all. I screwed it up myself. Here's the corresponding forum post: https://forums.freebsd.org/threads/no-boot-device-after-zfs-upgrade.79414

Before re-installing the host OS I would like to understand how I can restore my jails (and maybe CBSD config(s)) afterwards.

**Comment by mekanix** [comment]
Ah, I see. I did exactly the same thing yesterday and had to reinstall my laptop. :o( OK, so, back to restore from backup. If you zfs send/recv the datasets, I think the CBSD dir will be transfered, too. I mean, if it has it's own ZFS and ZFS feat is on. I can't tell from experience, but I'm 70% sure this is enough.

**Comment by Tectu** [comment]
So what you're saying is that I can just install CBSD on the fresh host and then copy the main CBSD directory (I believe the documentation refers to it as "working directory"?) - by default `/usr/jails` - and everything will be fine?

**Comment by olevole** [comment]
if the working directory is the same ( /usr/jails), this shouldn't be a problem. Just copy /usr/jails from old hoster to new. The only thing is that on the new system, the cbsd version should not be younger.

in addition to the zvol, which are virtual machine disks, all CBSD relevant data (settings) are located in ~cbsd/var/db/local.sqlite (symlink) and ~cbsd/jails/jails-system/<envname>/

**Comment by olevole** [comment]
if we are talking about jails, then there is no ZVOL, only a dataset with ~cbsd/jails-data/<envname>-data  mount point
