### ISSUE TITLE
Cannnot create jail with 13.0.2 on FreeBSD 13.0

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#573]
FreeBSD version ( uname -a ): FreeBSD 13.0-RC2

CBSD version ( cbsd version ): 13.0.2 (installed from packages)

Trying to create a jail (configured using `cbsd jconstruct-tui`):

```
Please wait: this will take a while...
Applying skel dir template from: /jails/share/FreeBSD-jail-skel
No such jail: jailnet1
No such jail: jailnet1

Creating jailnet1 failed: postcreate_module_action
no such jail: jailnet1
No such jail: jailnet1
jdestroy done in 0 seconds
Config file for jconf: /jails/ftmp/jailnet1.26074.jconf
```

/jails/ftmp/jailnet1.26074.jconf:

```
relative_path="1";
jname="jailnet1";
path="/jails/jails/jailnet1";
data="/jails/jails-data/jailnet1-data";
rcconf="/jails/jails-rcconf/rc.conf_jailnet1";

# FQDN for environment
host_hostname="jailnet1.my.domain";
# default environment IP
ip4_addr="DHCP";

# start with system boot?
astart="0";

# first NIC hardware address
nic_hwaddr="0";

# create from ZFS snapshot?
zfs_snapsrc="";
# run immediately upon creation
runasap="0";
# bind to interface
interface="auto";
rctl_nice="1"
jailskeldir="/jails/share/FreeBSD-jail-skel"
jail_profile="default"
mount_devfs="1";
allow_mount="1";
allow_devfs="1";
allow_nullfs="1";
allow_fusefs="0";
allow_linsysfs="0";
allow_linprocfs="0";
allow_raw_sockets="0";
mount_fstab="/jails/jails-fstab/jailnet1/fstab";
mount_fstab_old="/jails/jails-fstab/fstab.jailnet1";
arch="native";
mkhostsfile="1";
devfs_ruleset="4";
ver="native";
basename="";
baserw="0";
mount_src="0";
mount_obj="0";
mount_kernel="0";
mount_ports="1";
vnet="1";
applytpl="1";
mdsize="0";
floatresolv="1";

exec_poststart="0";
exec_poststop="";
exec_prestart="0";
exec_prestop="0";

exec_master_poststart="0";
exec_master_poststop="0";
exec_master_prestart="0";
exec_master_prestop="0";

pkg_bootstrap="1";
with_img_helpers="";

allow_reserved_ports="1";
allow_unprivileged_proc_debug="1";

persist="1";
childrenmax="0";
enforce_statfs="1";
sysrc_enable="";

mnt_start="0";
mnt_stop="0";

allow_mlock="0";
jailnic_temp_sql="";
fsquota="";
exec_start="/bin/sh /etc/rc"
exec_stop="/bin/sh /etc/rc.shutdown"
emulator="jail"
```

**Comment by mekanix** [comment]
CBSD doesn't know how to do -RC or -BETA bases. If you're OK with having 12.2 base for few more days (until 13-RELEASE is out), you can change from `ver="native"` to `ver="12.2"` in the .jconf file (or choosing a version from jconstruct-tui menu).

**Comment by olevole** [comment]
Not sure if it is version related. However, it is not clear to me what is wrong.

**postcreate_module_action** may fail, for example, due to pkg (bootstrap) - e.g. no internet for jail. 

probably debug can say more: `env CBSD_DEBUG=1 cbsd jcreate jconf=<path-to-config>.jconf

**Comment by mekanix** [comment]
@olevole my understanding is that `ver="native"` is not supported on non-RELEASE bases (excluding STABLE, that one is special). To be precise, my understanding is that you can not have `ver="13.0-RC2"`. Is that right?

**Comment by olevole** [comment]
@mekanix that's right, but this is not CBSD limitation. **ver** value affects the generation of the source url from where to get an base.txz (if fetch method is preferred). However, I do not see that the problem with obtaining the base.

**Comment by mekanix** [comment]
I just tried jconstruct-tui on 13-RC2 hoster with ver="native" and this is the URL it's trying to fetch:
https://download.freebsd.org/ftp/releases/amd64/amd64/13.0-RELEASE/base.txz

If only RELEASE would be RC2, that would work. Is it a bug? Can we (and I mean I with your help) fix it?

**Comment by olevole** [comment]
this is not a bug. version for 'native' taken from the `/usr/local/cbsd/misc/elf_tables --freebsdver /bin/sh` (or `file -s /bin/sh`, elf header). we do not pay attention to other sources of information (e.g /etc/os-release or freebsd-version, because they may not match the actual/runtime version)

**Comment by Peter2121** [comment]
@mekanix 
Indeed there is a problem fetching base for 13. I tried to use 'populate' but it was failed with many errors like 'file not found'. Then I tried to use 'fetch' and finally I could fetch it from bsdstore.ru repo. _BTW, it would be nice to fix 'populate' option to be able to correctly get base from host_.

@olevole the idea of failed bootstrap for pkg seems to be the nearest to the real problem. Indeed, I try to create a jail with VNET, but without NAT (I want to test the config with routing/ipsec). IMHO, some additional information about the error happened would be nice here ;)
I'll test `CBSD_DEBUG=1` this evening.

Thanks!

**Comment by olevole** [comment]
@Peter2121 yeah, 'populate' should work, so this is a bug) I will update the index file for 13 shortly.

to exclude the influence of pkg, just disable 'pkg_bootstrap' in jconstruct-tui or jconf file

**Comment by Peter2121** [comment]
I retried 'from scratch', without pkg bootstrap. I have the same result, but `No such jail: jailnet1` is not shown twice - only once. No jail created :(

**Comment by olevole** [comment]
I can't reproduce it with the specified ^^ jail configuration file in the fresh/clean FreeBSD 13.0-RC2:
```
root@srv-03:~ # uname -a
FreeBSD srv-03.olevole.ru 13.0-RC2 FreeBSD 13.0-RC2 #5 releng/13.0-n244691-cb370b19715-dirty: Thu Mar 18 11:45:49 UTC 2021     root@srv-03.olevole.ru:/usr/obj/usr/jails/src/src_13.0/src/amd64.amd64/sys/GENERIC  amd64

root@srv-03:~ # cat /root/jailnet.jconf
relative_path="1";
jname="jailnet1";
path="/usr/jails/jails/jailnet1";
data="/usr/jails/jails-data/jailnet1-data";
rcconf="/usr/jails/jails-rcconf/rc.conf_jailnet1";

# FQDN for environment
host_hostname="jailnet1.my.domain";
# default environment IP
ip4_addr="DHCP";

# start with system boot?
astart="0";

# first NIC hardware address
nic_hwaddr="0";

# create from ZFS snapshot?
zfs_snapsrc="";
# run immediately upon creation
runasap="0";
# bind to interface
interface="auto";
rctl_nice="1"
jailskeldir="/usr/jails/share/FreeBSD-jail-skel"
jail_profile="default"
mount_devfs="1";
allow_mount="1";
allow_devfs="1";
allow_nullfs="1";
allow_fusefs="0";
allow_linsysfs="0";
allow_linprocfs="0";
allow_raw_sockets="0";
mount_fstab="/usr/jails/jails-fstab/jailnet1/fstab";
mount_fstab_old="/usr/jails/jails-fstab/fstab.jailnet1";
arch="native";
mkhostsfile="1";
devfs_ruleset="4";
ver="native";
basename="";
baserw="0";
mount_src="0";
mount_obj="0";
mount_kernel="0";
mount_ports="1";
vnet="1";
applytpl="1";
mdsize="0";
floatresolv="1";

exec_poststart="0";
exec_poststop="";
exec_prestart="0";
exec_prestop="0";

exec_master_poststart="0";
exec_master_poststop="0";
exec_master_prestart="0";
exec_master_prestop="0";

pkg_bootstrap="1";
with_img_helpers="";

allow_reserved_ports="1";
allow_unprivileged_proc_debug="1";

persist="1";
childrenmax="0";
enforce_statfs="1";
sysrc_enable="";

mnt_start="0";
mnt_stop="0";

allow_mlock="0";
jailnic_temp_sql="";
fsquota="";
exec_start="/bin/sh /etc/rc"
exec_stop="/bin/sh /etc/rc.shutdown"
emulator="jail"

root@srv-03:~ # cbsd jcreate jconf=/root/jailnet.jconf
Please wait: this will take a while...
Applying skel dir template from: /usr/jails/share/FreeBSD-jail-skel

To edit VM properties use: cbsd jconfig jname=jailnet1
To start VM use: cbsd jstart jailnet1
To stop VM use: cbsd jstop jailnet1
To remove VM use: cbsd jremove jailnet1
For attach VM console use: cbsd jlogin jailnet1

Creating jailnet1 complete: Enjoy!
jcreate done in 13 seconds
```

So CBSD_DEBUG=1 output is still relevant to issue

**Comment by Peter2121** [comment]
Sorry, I forgot to test with debug yesterday.
Voila:
https://pastebin.com/raw/VuLhUkm7

**Comment by olevole** [comment]
There is nothing in this dump, at the end the container is created successfully:
```
jcreate done in 2 seconds
```

the only error I saw in the trace is a etcupdate:
```
+ err 1 'etcupdate error: no such ver='
+ exitval=1
```
Can you add `etcupdate_init=0` params into **.jconf** file and re-run jcreate  to to exclude this place?
```
echo 'etcupdate_init="0" >> /jails/ftmp/jailnet1.26074.jconf'
cbsd jcreate jconf=/jails/ftmp/jailnet1.26074.jconf
```

However, I do not see anything that at this stage can delete the container, because it is the end of the script: https://github.com/cbsd/cbsd/blob/develop/sudoexec/jcreate#L543

**Comment by olevole** [comment]
@Peter2121 hmm, can you try this? :
```
sqlite3 ~cbsd/var/db/local.sqlite  'ALTER TABLE jails ADD COLUMN tags text default "0"'
```

**Comment by Peter2121** [comment]
Trying to recreate the jail after adding `etcupdate_init="0"` I get the error:
```
lenovo# cbsd jcreate jconf=/jails/ftmp/jailnet1.26074.jconf
Please wait: this will take a while...
create_zfs_fs: zroot/ROOT/default/jailnet1 already in use
```
Checking the zfs datasets - indeed, I see two jail datasets created:
```
zroot/ROOT/default/jail22    10.2M   441G     10.2M  /jails/jails-data/jail22-data
zroot/ROOT/default/jailnet1  10.2M   441G     10.2M  /jails/jails-data/jailnet1-data
```
But the output of `cbsd jls` is still blank:
```
lenovo# cbsd jls
JNAME  JID  IP4_ADDR  HOST_HOSTNAME  PATH  STATUS
```
So, probably, this is a problem of the database.
The command `sqlite3 ~cbsd/var/db/local.sqlite  'ALTER TABLE jails ADD COLUMN tags text default "0"'` did not return any error, but the output of `cbsd jls` is still blank.

**Comment by Peter2121** [comment]
I renamed the jail in jconf and tried to recreate it. I got an interesting error, it seems that cbsd is searching skel in a bad place:
```
lenovo# cbsd jcreate jconf=/jails/ftmp/jailnet2.26074.jconf
Please wait: this will take a while...
Skel dir template not found: /usr/jails/share/FreeBSD-jail-skel
cp: /usr/jails/jails-rcconf/rc.conf_jailnet2: No such file or directory
no rcconf /jails/jails-rcconf/rc.conf_jailnet2 file for jail: jailnet2

Creating jailnet2 failed: cbsd jregister
Please review bad config file: /tmp/rc.conf_jailnet2
mv: rename /usr/jails/jails-rcconf/rc.conf_jailnet2 to /tmp/rc.conf_jailnet2: No such file or directory
```

**Comment by olevole** [comment]
Yes, the problem was in an incorrect database. I will update the port ASAP. After ALTER TABLE, the new container should be created successfully

**Comment by olevole** [comment]
13.0.3 commited into ports tree, with sql schema fix. @Peter2121 thx for report!

**Comment by Peter2121** [comment]
Indeed, after updating to 13.0.3 everything works as expected!
Thanks for fixing it!
