### ISSUE TITLE
jstart list not returning jail IDs all set to 1

### ISSUE THREAD

**Issue by nestorwheelock** [cbsd/cbsd#576]
FreeBSD  12.2-RELEASE-p4 FreeBSD 12.2-RELEASE-p4 GENERIC  amd64
CBSD version 13.0.3

`cbsd jstart list ` is not returning jail IDs all ID's set to 1

ie:

```
1 .. web0 on local
1 .. web1 on local
1 .. web2 on local
```

**Comment by olevole** [comment]
list in `cbsd jstart` is valid jail name here ?

**Comment by olevole** [comment]
please recheck with CBSD 13.0.5
