### ISSUE TITLE
jget asks always for jname even it is right

### ISSUE THREAD

**Issue by nestorwheelock** [cbsd/cbsd#577]
FreeBSD 12.2-RELEASE-p4 FreeBSD 12.2-RELEASE-p4 GENERIC amd64
CBSD version 13.0.3

As reported by Nicola Tiling and reproduced by me.

jget asks always  for „jname“ even it is right.

```
web0     8     192.168.0.101 web0 /jails/cbsd/jails/web0 On
web1     4025  192.168.0.103 web1 /jails/cbsd/jails/web1 On
web2     9     192.168.0.104 web2 /jails/cbsd/jails/web2 On
...
# cbsd jget jname=web0
Give me jname

```

**Comment by olevole** [comment]
I saw it in the mailing list, but there was no time to answer. This regression is fixed in Git: https://github.com/cbsd/cbsd/commit/2037f2b0105804b986d4f8254273c32ca5f404cb

To apply:
```
rm -f /usr/local/cbsd/jailctl/jget 
fetch -o /usr/local/cbsd/jailctl/jget https://raw.githubusercontent.com/cbsd/cbsd/develop/jailctl/jget
chmod +x /usr/local/cbsd/jailctl/jget
```

Thanks!
