### ISSUE TITLE
Pass physical interface to VNET jail

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#578]
FreeBSD version ( uname -a ): `12.2-RELEASE-p6`
CBSD version ( cbsd version ): `13.0.3`

I recently read the FreeBSD documentation on VNET jails. From the documentation, it seems that I can "hand over" an entire network interface from the host to the jail (as opposed to creating the `epairX` solution). In that case, the interface should completely disappear from the host's `ifconfig` list and show up in the jail instead.

I fail to understand how to achieve this with cbsd.
On a freshly created jail, I used `jconfig` to perform the following settings:
- Set `ip4_addr` to `0` (ncurses L)
- Enable the `vnet` option (ncurses A)
- Set `interface` top `0` (ncurses K)
Then I started messing with the `jailnic - Network config` options but as the dialog title states, that seems to be only for virtual interfaces (this will create the `epairX` on the host).

How can I "pass through" an interface to a jail so the jail gets full control over that interface and it disappears from the host using cbsd?

**Comment by olevole** [comment]
Apparently you are expecting something like SR-IOV + ppt ( https://www.bsdstore.ru/en/13.0.x/wf_bhyveppt_ssi.html#sriov ) from VNET ;). But not - VIMAGE is not about passthru physical interface, its just 'visualized' network stack ( from the user side, you get, for example, a full working loopback in jail, a routing table and a firewall ).

CBSD create epair interface, where epairX**a** on the host side and epairX**b** - pass to jail ( as **eth0** interface ).
With CBSD 13.0.4 (commited to ports tree today) you can manage IP and defaultrouter= records inside jail (via rc.conf).
With '0' values in ip4_addr, you have to configure the network settings yourself inside the container.

In addition, if you are interested in isolated networks for vnet-based jails, you may be interested in trying the VALE switch (FreeBSD 13.0-RELEASE highly recommended): https://www.bsdstore.ru/en/13.0.x/wf_bhyvenetwork_ssi.html#bhyvenetwork_opt4

**Comment by Tectu** [comment]
I must have misinterpreted the documentation. I could swear that I read somewhere in the FreeBSD docs that VNET allows passing an interface to a jail that will then disappear from the host and the jail gets full control over it... :(

I quickly read over the VALE documentation you linked - this looks certainly useful for what I am about to attempt - thank you for pointing me towards that!
