### ISSUE TITLE
Creating jails in encrypted dataset

### ISSUE THREAD

**Issue by satriani-vai** [cbsd/cbsd#583]
With FreeBSD 13.0 we can finally create encrypted datasets. It's the greatest feature for this release, in my opinion. So I think to create the jail in an encrypted dataset is a must feature for cbsd. What do you think about it?

FreeBSD version ( uname -a ): FreeBSD Server1 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

CBSD version ( cbsd version ): 13.0.3

**Comment by olevole** [comment]
@satriani-vai Encryption always sounds very good! How do you see the implementation of this function in CBSD? CBSD does not create a pool, it creates zfs datasets for containers. Thus, the encrypted pool for the CBSD must be created earlier.

**Comment by satriani-vai** [comment]
@olevole надеюсь ты не против если я перейду на русский. Так проще :smile: 
Если я правильно всё понял, то для шифрования датасета создавать пул не надо.
Главное чтобы функция шифрования была активирована.
```
# zpool get all zroot | grep encryption
zroot  feature@encryption             enabled                        local
```
Форматы ключей: "none | raw | hex | passphrase"
Я пользуюсь passphrase. Другие не пробовал. Вот команда для создания зашифрованного датасета
```
# zfs create -o encryption=on -o keyformat=passphrase zroot/test
# zfs get encryption zroot/test
NAME        PROPERTY    VALUE        SOURCE
zroot/test  encryption  aes-256-gcm  -
```
Правда после каждой перезагрузки надо монтировать зашифрованный датасет. Но до этого необходимо расшифровать датасет ключом.
```
# zfs load-key zroot/test
Enter passphrase for 'zroot/test':
# zfs mount zroot/test
```
Очень надеюсь увидеть это замечательное дополнение в следующей версии CBSD

**Comment by olevole** [comment]
@satriani-vai да, похоже переключить enc можно в рантайме:
```
zfs create -o encryption=on -o keysource=passphrase,prompt tank/enc
```

ну тогда да, zfs encription можно легко добавить как бакенд к уже имеющемуся GELI в скрипт https://www.bsdstore.ru/en/cbsd_geli.html

Надо только посмотреть, работает ли это с vol, чтобы кроме датасетов криптованны могли быть диски виртуалок.

ps: а все же, кто круче, Сатриани или Вай ? ;)

**Comment by satriani-vai** [comment]
@olevole очень рад, что откликнулось.
Лично я бы предпочёл криптованный датасет перед GELI. Думаю что в плане производительности GELI даже уступает.
Надо проверить. А что касается юзабилити, так там вообще вопросов нет. Вообще 13ый релиз очень хороший, мне нравится.

Как ты думаешь, со следующей версией CBSD удастся внедрить датасет криптование? И как это примерно будет выглядеть в твоём представлении, в плане настроек и создания клеток (jails)?

> ps: а все же, кто круче, Сатриани или Вай ? ;)

Мистер Вай это космос :rocket:. Гитара уже безнадёжно приросла к его телу :roll_eyes: :laughing:
В отличие от других виртуозов он обладает неповторимо ярко и красочно выраженным вкусом.
Но и нельзя забывать кто его учитель и также выдающийся гитарист. Поэтому оба достойно нашли место в моём нике :wink:

**Comment by olevole** [comment]
Тоже фанат Вая, хотя у Сатриани более мягкий и изысканный звук))

Про имплементацию надо думать. Во-первых, я хочу сделать также как в GELI - одной фразой (masterphrase) будет открываться криптованный датасет, где находятся уже секреты в виде файлов. Каждый файл может раскриптовать другой криптованный датасет, который может быть датасетом как всего jail, так и отдельной точкой монтирования в jail. 
Те нет смысла криптовать инфо, которая не является секретной - а это весь / и /usr/local.  А вот /var/db в клетке или /usr/local/www/ и тд, конкретные локации, могут быть шифрованы. 

А второе что напрашивается, это просто passhrase per jail.

Те, при создании будет фраза на passhrase  и при каждом jstart будет интерактивный вопрос пароля (или путь к ключу на файловой системе, которая не обязательно будет локальной FS - хоть через шифрованный канал связи на NFS или sshfs смонтированная в ro, лишь бы на FS ключей небыло)

Короче в раздумьях - если есть мысли как с точки зрения усера удобно видеть - пиши

**Comment by olevole** [comment]
Метод с интерактивным passphrase и криптованием всего jail-ового датасета добавить было легко и уже можно проверить из git версии ( https://github.com/cbsd/cbsd/commit/daf7f72d904994eee5235d0e08a3a06f18fd0227 ).

Про другие варианты надо поразмыслить. 

keyfile наверное можно безопасно ложить и на файловой системе без шифрования, если загрузка хостера происходит через PXE, когда ключи для дешифрования лежат на сервере. Ключи уязвимы если атакующий получит доступ  в рантайм (но если получит доступ - значит он и так уже читает все данные ), но это защищает от ситуации когда в чужом ДЦ хост изымают/обпесточивают и пробуют грузнуть - в этом случае, неинтерактивная загрузка криптованных окружений вполне возможна.

**Comment by satriani-vai** [comment]
Ухты... резко ты смастерил. :bowing_man: Для начала вполне годное решение :+1:  И даже более чем, я бы сказал.
Ща буду испытывать на прочность.

> Про имплементацию надо думать. Во-первых, я хочу сделать также как в GELI - одной фразой (masterphrase) будет открываться криптованный датасет, где находятся уже секреты в виде файлов. Каждый файл может раскриптовать другой криптованный датасет, который может быть датасетом как всего jail, так и отдельной точкой монтирования в jail.
> Те нет смысла криптовать инфо, которая не является секретной - а это весь / и /usr/local. А вот /var/db в клетке или /usr/local/www/ и тд, конкретные локации, могут быть шифрованы.

Согласен, это безусловно наиболее грамотный подход. Те зашифрованные папки будут указаны в конфиг файле к каждому джейлу. При этом необходимо учесть, чтобы юзер мог создавать новые криптованые папки внутри джейлов.

> keyfile наверное можно безопасно ложить и на файловой системе без шифрования, если загрузка хостера происходит через PXE (sshfs/secured-NFS?), когда ключи для дешифрования лежат на сервере (но в этом случае сервер должен понимать, когда быстро ревокнуть ключи).
> 
> Ключи уязвимы если атакующий получит доступ в рантайм (но если получит доступ - значит он и так уже читает все данные ), но это защищает от ситуации, когда в чужом ДЦ хост изымают/обесточивают и пробуют грузнуть. В этом случае, неинтерактивная загрузка криптованных окружений вполне возможна. Хотя это только теория, на практике скорее всего неинтерактивно даже с PXE/HTTPs boot не выйдет использовать keyfile ( или без доп. дешифрации)

У меня например сервера на Hetzner и доступ к которым только через SSH. Я думаю что на всякий случай должна быть опция дешифрования исключительно в ручную. Например, при первом ssh логине после ребута, сразу в лоб запрос на passphrase.

**Comment by satriani-vai** [comment]
> Метод с интерактивным passphrase и криптованием всего jail-ового датасета добавить было легко и уже можно проверить из git версии ( daf7f72 ).

создал 6 jails, перегрузил сервер и запустил все jails одной командой.

```
# cbsd jstart jname='*'
jstart: encrypted dataset: aes-256-gcm
jstart: encryption keyformat: passphrase
jstart: encrypted dataset: aes-256-gcm
jstart: encryption keyformat: passphrase
jstart: encrypted dataset: aes-256-gcm
jstart: encryption keyformat: passphrase
jstart: encrypted dataset: aes-256-gcm
jstart: encryption keyformat: passphrase
jstart: encrypted dataset: aes-256-gcm
jstart: encryption keyformat: passphrase
jstart: encrypted dataset: aes-256-gcm
jstart: encryption keyformat: passphrase
Waiting for starting jail who have pid: 7727
Waiting for starting jail who have pid: 7727
Waiting for starting jail who have pid: 7727
Waiting for starting jail who have pid: 7727
Waiting for starting jail who have pid: 7727
Waiting for starting jail who have pid: 7727
Multiple jstart: done
#
```

После начались глюки. В командную строку ничего не вводилось, тут сразу стало ясно что активен режим ввода passphrase. После каждого ввода pasphrase выходили ошибки:
`Enter passphrase for 'zroot/ROOT/default/jail1':Key load error: Passphrase too short (min 8).`
В общем вводил больше чем количество jails, тем не менее всё завелось.

**Comment by olevole** [comment]
jstart по маске ( jname='*' ) форкает процессы и выполняет задачи в бекграунде, делая pwait за child процессом. Интерактивщину в таком режиме не сделать. Надо будет глянуть почему флаг интерактивности не отработал, тк криптоклетки должны были по-скип-аться

**Comment by satriani-vai** [comment]
# cbsd version
13.0.9

Попробовал в новой версии запустить джейлы по маске ( jname='*' ). Думал может ты уже нашёл решение данной проблемы, но по ходу решения пока нет. Когда джейлов немного, не велика беда, но когда джейлов больше сотни, как-то напрягает :roll_eyes: :laughing:

**Comment by olevole** [comment]
С маской и интерактивщиной надо подумать, как и для astart - скорее всего интерактивные клетки не запускать на автомате вовсе (ибо - а че делать то?). Таску прикрою, тк формально zfs encryption хотя бы с паролем есть, эти проблемы (и вероятно keyfile-based бы надо) сделаю в рамках другой активности
