### ISSUE TITLE
Upgrade of jails from 12.1 to 12.2 does not work, basejail is not created

### ISSUE THREAD

**Issue by goligo** [cbsd/cbsd#585]
FreeBSD version ( uname -a ): 
FreeBSD vmbsd.fritz.box 12.2-RELEASE-p6 FreeBSD 12.2-RELEASE-p6 GENERIC  amd64

CBSD version ( cbsd version ): 
13.0.4

When trying to update basero-jails to version 12.2, cbsd does not create the basejail for the new version, but rather starts them with the old basejail and ignores the new version setting.

```
# cbsd jstop test
Stoping jail: test, parallel timeout=5
jstop done in 3 seconds
# cbsd jset ver=12.2 jname=test
ver: 12.2
# cbsd jstart test
Default NIC automatically selected: em0
set resource limit: [ ]
Applying /usr/ports/CHANGES -A28 ^20140930 work-around
Starting jail: test, parallel timeout=5
test: created
ELF ldconfig path: /lib /usr/lib /usr/lib/compat /usr/local/lib /usr/local/lib/compat/pkg /usr/local/lib/compat/pkg
32-bit compatibility ldconfig path: /usr/lib32
Setting hostname: test.fritz.box.
Creating and/or trimming log files.
Starting syslogd.
Clearing /tmp (X related).
Updating motd:.
Starting sendmail_submit.
Starting sendmail_msp_queue.
Starting cron.

Mon Apr 19 03:41:33 CEST 2021
jstart done in 3 seconds
# cbsd jlogin test
Last login: Mon Apr 19 03:40:12 on pts/0
FreeBSD 12.2-RELEASE-p6 GENERIC
# freebsd-version
12.1-RELEASE
# pkg update
Updating FreeBSD repository catalogue...
[test.fritz.box] Fetching meta.txz: 100%    916 B   0.9kB/s    00:01
[test.fritz.box] Fetching packagesite.txz: 100%    6 MiB   3.3MB/s    00:02
Processing entries:   0%
Newer FreeBSD version for package tdb:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1202000
- running kernel: 1201000
Ignore the mismatch and continue? [y/N]: n
pkg: repository FreeBSD contains packages for wrong OS version: FreeBSD:12:amd64
Processing entries: 100%
Unable to update repository FreeBSD
Error updating repositories!
```

**Comment by goligo** [comment]
I tried to create a new jail with ver="12.2", this worked as expected, so the 12.2-basejail is properly created now, however this does not change anything for the existing jails, looks like it just ignores whatever I put into the "ver" property and keeps using the 12.1-basejail.

**Comment by goligo** [comment]
Looks like unmounting/remounting the basejail does no longer happen, so it just keeps mounted on the same version. When I call 

```
# umount /usr/jails/jails/test
```

before starting the jail, the correct (configured) version of the basejail is mounted.

**Comment by goligo** [comment]
Issue seems to be caused by a recent change in jcleanup ( https://github.com/cbsd/cbsd/commit/843bfadaafd841ab34513bee5b59a40c952a95ef ). when reverting this file to previous version, jails are unmounted when they are stopped and get the new version mounted, when they are started again.

**Comment by olevole** [comment]
Fixed, thanks!
