### ISSUE TITLE
cbsd jconstruct missing property descriptions, making it unusable

### ISSUE THREAD

**Issue by goligo** [cbsd/cbsd#586]
FreeBSD version ( uname -a ):
FreeBSD vmbsd.fritz.box 12.2-RELEASE-p6 FreeBSD 12.2-RELEASE-p6 GENERIC amd64

CBSD version ( cbsd version ):
13.0.4

When using "cbsd jconstruct", for most questions only the response options are displayed, but not the actual property or setting you are configuring with it:

```
# cbsd jconstruct
---------[CBSD v.13.0.4]---------
Welcome to jcreate config constructor script.

For DIALOG-based menu please use jconstruct-tui utility
-----------------------
Proceed to construct? [yes or no]
yes
Jail name. Name must begin with a letter / a-z /  and not have any special symbols: -,.=% e.g: jail1
test3
Jail Fully Qualified Domain Name e.g: test3.my.domain
test3.fritz.box
 e.g: 192.168.2.103
192.168.2.103
 e.g: native

 e.g: native

 ( 0 - nullfs base mount in RO, 1 - no nullfs, RW ) e.g: 0

 (0 - no, 1 - yes): e.g: 0

 ( 0 - no, 1 - yes) e.g: 1

1,yes - Automatically start Jail when system boot ( 0 - no, 1 -yes) e.g: 1

Auto create and auto remove IP on selected NICs. 0 for disable, auto - for auto detect e.g: auto

 ( 0 - no, 1 - yes) e.g: 1

 ( 0 - no, 1 - yes) e.g: 1

/usr/local/cbsd/tools/jconstruct: make_jail_part: not found
Do you want to create jail immediately?
[yes(1) or no(0)]
0
You can make now: cbsd jcreate jconf=/usr/jails/ftmp/test3.12135.jconf
```

**Comment by olevole** [comment]
I think I completely forgot about the existence of this script and was going to remove it ;-)
@goligo How comfortable for you such a dialog for the creation of containers? 
It seems that there are more convenient options, e.g:

```
cbsd jcreate jname=xxx ver=12.2 ip4_addr=10.0.0.5 runasap=1 [any other options from jconf]
```

or via CBSDfile:
```
jail_victoria()
{
        ip4_addr="DHCP,DHCPv6"
        host_hostname="${jname}.my.domain"
        pkg_bootstrap=1
        pkglist="misc/mc"
}
```
 and:
 **cbsd up**


PS: I know that the site documentation still refers to the **jconstruct** method.

**Comment by goligo** [comment]
Well, I did not discover this issue by searching for errors, but jconstruct is my preferred method to create jails. I don't do it often enough to know config parameters by heart and I don't like menus in the shell. A dialog based configuration feels most natural to me.

However, obviously it is not something I need urgently or I couldn't live without.

**Comment by olevole** [comment]
I think I forgot to do include after the settings were split. Can you check https://github.com/cbsd/cbsd/commit/6f2c00ca290f8c0869fe387ff2b9b6e0560ef53f#diff-df27ad17e50ab20f0c833df12624204da19de026bea6a0ed5ac80c1af1df345cR11 ?

just add:
```
. ${distdir}/settings-tui-jail.subr
```

after
```
. ${settingstui}
```

**Comment by olevole** [comment]
@goligo well, I'll know that this option/script might be usefull for some users, thanks for the opinion.
