### ISSUE TITLE
ip4_addr="inherit"

### ISSUE THREAD

**Issue by satriani-vai** [cbsd/cbsd#588]
Есть jails которые не должны быть доступны с интернета, но изнутри доступ к интернету необходим для обновлений, установок программ итд. Всегда использовал в таком случаи "ip4 = inherit;" в jail.conf
В CBSD команда `cbsd jset jname=jail1 ip4_addr="inherit"` по всей видимости не работает.
Что посоветуете?

FreeBSD version ( uname -a ): 13.0

CBSD version ( cbsd version ): daf7f72d904994eee5235d0e08a3a06f18fd0227

**Comment by olevole** [comment]
насколько я понимаю, inherit это тоже самое что 'interface=0' (disable) и в IP4_addr указать уже ранее проинициализированный за пределами CBSD IP. Но не очень понимаю какая связь между обновлениями.

Для доступа к ним, достаточно делать клетки на rfc1918 адресах и использовать NAT
