### ISSUE TITLE
Extra quotes around vars

### ISSUE THREAD

**Issue by mekanix** [cbsd/cbsd#592]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD thinker.meka.rs 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

CBSD version ( cbsd version ): 
13.0.5

Comparing `jexec` and `cbsd jexec`
```
jexec cbsd env ASSUME_ALWAYS_YES=yes pkg bootstrap -f
Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:13:amd64/latest, please wait...
[cbsd.thinker.meka.rs] Installing pkg-1.16.3...
package pkg is already installed, forced install
[cbsd.thinker.meka.rs] Extracting pkg-1.16.3: 100%
```
```
cbsd jexec jname=cbsd env ASSUME_ALWAYS_YES=yes pkg bootstrap -f
The package management tool is not yet installed on your system.
Do you want to fetch and install it now? [y/N]: y
Bootstrapping pkg from pkg+http://pkg.FreeBSD.org/FreeBSD:13:amd64/latest, please wait...
pkg-static: Invalid type for environment variable ASSUME_ALWAYS_YES, got "yes", while expecting a boolean
[cbsd.thinker.meka.rs] Installing pkg-1.16.3...
package pkg is already installed, forced install
[cbsd.thinker.meka.rs] Extracting pkg-1.16.3: 100%
```
I checked, it happens with any command prefixed with `env ...`.

**Comment by mekanix** [comment]
It works with `cmd="env ASSUME_ALWAYS_YES=yes pkg bootstrap -f"`. Is cmd= way preferred?

**Comment by olevole** [comment]
this casting is caused by large restriction by shell ;-( 

e.g, valid jexec:

`cbsd jexec jname=test ls -la /tmp`

`cbsd jexec jname=test "ls -la /tmp; pwd; whoami;hostname"

```cbsd jexec jname=test <<EOF
ls -la 
pwd
whoami
hostname
pkg update -f
EOF
```

In such cases, it is very difficult for shell tools to avoid the expansion of quotes (e.g $*  or $@ loose quotes ). Therefore, we recreate the quotes to pass them into the container. 

A higher-level (C lang?) solution may be required to handle such cases. This requires serious r&d. I don't have a quick fix at the moment ;-(

**Comment by mekanix** [comment]
As `cmd=...` is working, I would say it's the current work around. Should we leave it for other people looking for a solution?

**Comment by olevole** [comment]
@mekanix  I think we should find all the places in the examples where we refer to the variant without quotes and fix it.

For example the current version of `cbsd jexec --help` shows the correct sample

**Comment by olevole** [comment]
although I'm wrong, it `cbsd jexec jname=cbsd "env ASSUME_ALWAYS_YES=yes pkg bootstrap -f"`doesn't work ;-) I'll see what we can do here.

**Comment by olevole** [comment]
Unfortunately, on the shell, there is no possibility to make the most universal handler, therefore added more examples.
Especially for **[jb]exec** script and **env**, we can try to add a separate parameter **env=** e.g:

cbsd jexec jname=xxx pwd=/tmp env="ASSUME_ALWAYS_YES=1 TRUE=FALSE" pkg bootstrap -f

 but probably it's not that many expect, POLA violation ;-)
