### ISSUE TITLE
Cannot create virtual NIC

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#593]
FreeBSD version ( uname -a ): FreeBSD 13.0-RELEASE
CBSD version ( cbsd version ): 13.0.5

After jexport of a jail (v.12.2) without vnet I've imported it on another host. Then I activated vnet on it. The virtual NIC was not created automatically, so I went to `jailnic          Network config >>` to create it. When I click on `A Add  Add New Virtual NIC` - nothing happens. There is an error shown shortly on the screen though:
`/usr/local/cbsd/jail.subr: 132: Syntax error: ")" unexpected (expecting ";;")`

**Comment by Peter2121** [comment]
BTW, the file `/usr/local/cbsd/jail.subr` does not exist!

**Comment by olevole** [comment]
@Peter2121 thanks, lost **;;** in case: https://github.com/cbsd/cbsd/blob/v13.0.5/share/bsdconfig/cbsd/jailnic-newnic#L131

Also jail.subr was renamed to settings-tui-jail.subr and this was not reflected in bsdconfig files.
