### ISSUE TITLE
Mounting NFS share to jail not working

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#594]
FreeBSD version ( uname -a ): `13.0-RELEASE`
CBSD version ( cbsd version ): `13.0.4`

I am attempting to mount an NFS share on a CBSD host to a jail directory. However, I am running into a weird issue documented here: https://forums.freebsd.org/threads/unexpected-behavior-mounting-nfs-share-to-jail-data.80278/

As mentioned by SirDice, it's possible that CBSD works some magic here.
I would like to know whether this is the case and what the appropriate way of mounting an NFS share on a CBSD host and making that mounted share available to a jail is?

**Comment by olevole** [comment]
I think there are several options. First and and likely the most logical and easy is to use a local fstab file: https://www.bsdstore.ru/en/13.0.x/wf_jconfig_ssi.html#fstab.

E.g:

1) NFSv4 server-side: 
```
sysrc -q nfsv4_server_enable="YES"
sysrc -q nfscbd_enable="YES"
sysrc -q nfsuserd_enable="YES"
sysrc -q mountd_enable="YES"
sysrc -q nfsuserd_enable="YES"
sysrc -q rpc_lockd_enable="YES"
```
vi /etc/exports:
```
/nfs -alldirs -maproot=root 172.16.0.100
V4: / 172.16.0.100
```
Where **172.16.0.100** - CBSD hoster.

zfs create or `mkdir -p /nfs/myjail-data`
(don't forget for `zfs set sharenfs=on <dataset>` when ZFS)

2) CBSD hoster.

a) create jail:
```
cbsd jcreate jname=myjail
```

b) create NFS mount point in myjail dir hier, e.g. into **/usr/local/mnt**:
```
mkdir ~cbsd/jails-data/myjail-data/usr/local/mnt
```

c) Drop fstab line into ~cbsd/jails/jails-fstab/myjail/fstab.local:

```
cat > ~cbsd/jails-fstab/myjail/fstab.local <<EOF
172.16.0.3:/nfs/myjail-data /usr/local/mnt nfs rw,vers=4 0 0
EOF
```

where 172.16.0.3 - NFSv4 server.

d) start jail.

```
cbsd jstart myjail
```

**Comment by olevole** [comment]
Another possibility - you can use an external script that will start the mount line.

And finally you can mount NFS share from jail, but you need to enable `allow.mount`. In **CBSD**:

cbsd jconfig -> jail_options -> [x] allow_mount

or 

`cbsd jset jname=myjail allow_mount=1`

**Comment by olevole** [comment]
By the way, I looked at your message in the forum:

> mount -t nfs -o nfsv4,rw 192.168.250.61:/mysare /ssd/cbsd/jails-data/myjail-data/usr/local/storage

^^ this is correct only when baserw=1 jail. Otherwise (baserw=0), you must mount into **path** directory:

```mount -t nfs -o nfsv4,rw 192.168.250.61:/mysare /ssd/cbsd/jails/myjail/usr/local/storage```

because the /ssd/cbsd/jails-data/myjail-data is mounted via nullfs on a read-only base in /ssd/cbsd/jails/myjail (overlays)

**Comment by olevole** [comment]
@Tectu I decided to check the first scenario and found a bug. Already fixed in GIT: https://github.com/cbsd/cbsd/commit/1d90c276ac0cd6a9d37eaf71f8990dd21a62ece9 

if you decide to work according to the first scenario (via fstab.local for jail) please fetch fix first:
```
rm -f /usr/local/cbsd/tools/mountfstab
fetch -o /usr/local/cbsd/tools/mountfstab https://raw.githubusercontent.com/cbsd/cbsd/develop/tools/mountfstab
chmod +x /usr/local/cbsd/tools/mountfstab
```

Hope this helps

**Comment by Tectu** [comment]
Thank you for your explanation & bug fixing :)
I would definitely like to use the first method you described.

> if you decide to work according to the first scenario (via fstab.local for jail) please fetch fix first:
> 
> ```
> rm -f /usr/local/cbsd/tools/mountfstab
> fetch -o /usr/local/cbsd/tools/mountfstab https://raw.githubusercontent.com/cbsd/cbsd/develop/tools/mountfstab
> chmod +x /usr/local/cbsd/tools/mountfstab
> ```
It this something I can do safely? This won't interfere with upgrading to a later cbsd version via `pkg`?

**Comment by olevole** [comment]
I'll try to update the ports on the weekend. Feedback is encouraged - the wider the use cases, the more stable and versatile the tool is. This is good :point_up:

**Comment by Tectu** [comment]
While the mounting is working as expected, I am running into some permissions issue: I created `/usr/local/mnt/storage` in the jail. However, the owner is set to `nobody:nogroup`:
```
myjail:/root@[12:22] # ls -l /usr/local/mnt/
total 1
drwxr-xr-x  3 nobody  nogroup  3 May  7 12:16 storage
```
I need my `www` user and `www` group to have `rw` access on the storage.

I tried to `chmod www:www /usr/local/mnt` from within the jail but that doesn't work:
```
No name and/or group mapping for uid,gid:(80,80)
chown: /usr/local/mnt/storage/: Operation not permitted
```
Doing this outside the jail (on the host) does not work either.

What am I missing here? How can I change the owner of the mount point to my jail's `www:www`?

**Comment by Tectu** [comment]
I might need a bit more help here...

CBSD host: `192.168.250.60`
NFS server: `192.168.250.61`

My NFS server's `/etc/exports` looks like this:
```
V4: /hdd/nfs
/hdd/nfs/myshare -maproot=root 192.168.250.60
```
On the CBSD host: `~cbsd/jails-fstab/myjail/fstab.local`:
```
192.168.250.61:/myshare /usr/local/mnt/storage nfs rw,vers=4 0 0
```
Inside the jail, I need `rw` access to `usr/local/mnt/storage`. However, the mounting of the NFS share happens through the CBSD host's `root` account (correct?) hence my NFS export declaration lists the `root` user.

Given the configuration stated, what needs to happen to make the `/usr/local/mnt/storage` owned by the jail's `www:www` user & group? Shouldn't it be possible to mount an NFS share to `/usr/local/mnt/storage` but the mount point itself is owned by `www:www`? If not, my other option would be to modify my NFS server's `/etc/exports` to `mproot=www:www` but how would that work? My NFS server doesn't know about the jail's `www:www` and also it's the CBSD host's `root` user performing the mount anyway?

It seems like I am missing something here.
This is the first time I'm working with NFS so please be patient :p
