### ISSUE TITLE
when destroying vm, pf record is not deleted

### ISSUE THREAD

**Issue by aeifn** [cbsd/cbsd#598]
pf records added by expose remains after destroying associated VM.

Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD bhyve.cloud 13.0-CURRENT FreeBSD 13.0-CURRENT #0 r368657: Tue Dec 15 22:13:30 MSK 2020     root@bhyve.cloud:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

CBSD version ( cbsd version ): 12.2.6a

**Comment by olevole** [comment]
this should be fixed in 13.0.1, please upgrade
