### ISSUE TITLE
Feature if could be added: https certificate for web

### ISSUE THREAD

**Issue by joeshua** [cbsd/cbsd#613]
1) Can the feature be added for https web rather http by default using openssl or an option between openssl and letsencrypt ?

2) can we use doas as default then sudo ?

3) No firewall after install by default or something that could be easier which could be set via web ?

Thanks for the project.

FreeBSD version ( uname -a ): 13.0-CURRENT

CBSD version ( cbsd version ):

**Comment by olevole** [comment]
For **1,3** question: CBSD does not work with the WEB. Or do you mean ClonOS?
**2**: I do not know how to implement this with doas: https://github.com/cbsd/cbsd/issues/83

**Comment by joeshua** [comment]
> For **1,3** question: CBSD does not work with the WEB. Or do you mean ClonOS?
Yes for the web having option with openssl cert or lets encrypt but atleast default with openssl
