### ISSUE TITLE
Does cbsd support jail backup and restore?

### ISSUE THREAD

**Issue by satriani-vai** [cbsd/cbsd#615]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD ServBSD 13.0-RELEASE-p3 FreeBSD 13.0-RELEASE-p3

CBSD version ( cbsd version ): 13.0.9

Так как форума поддержки нет, напишу здесь.
Если я правильно всё понял, то cbsd предоставляет такую возможность, создавать резервную копию те. backup джейлов и впоследствии их восстанавливать (restore).
Попробовал я и понял, что ничего я не понял :laughing: 

`# cbsd jbackup node=Node1 jname=Jail1`
`Preparing. * check for remote CBSD version: 13.0.9`
`.: No such node. Please execute cbsd add node=Node1 first`
`j2prepare failed for Jail1 to Node1`
`# cbsd add node=Node1`
`cbsd: add: not found`

Цель такова: Переезжаю на новый сервер в Hetzner. Соответственно хочу перевезти джайлы на новый сервер.
CBSD мне в этом поможет или придётся переезжать вручную?

**Comment by olevole** [comment]
Сначала надо обменяться ключами:

1) cbsd node mode=add node=
2) на таргет хосте иметь поднятым сервис cbsdsryncd (в rc.d )
3) дальше jrclone или вышеупомянутый jbackup  ( это пуск j2prepare и j2slave скриптов )

но если разовый перенос, то есть и проще метод:

cbsd jexport  (если клетки оч жирные, compress= аргумент регулирует степень сжатия -> скорости операции)
scp ..
cbsd jimport (на таргет хосте)
