### ISSUE TITLE
Cannot migrate jail to another host

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#617]
FreeBSD version ( uname -a ): 
FreeBSD jails-5.reseaucloud.local 12.2-RELEASE-p4 FreeBSD 12.2-RELEASE-p4 GENERIC  amd64

CBSD version ( cbsd version ): 
v.13.0.10

```
# cbsd jcoldmigrate node=erpj-2.reseaucloud.local jname=gletest1
coldmigrate.Error in j2prepare
Guru meditaion:
Preparing.   * check for remote CBSD version: 13.0.10
.Error in rexe_1
Guru meditaion:
sudo: sorry, you are not allowed to preserve the environment
```

cbsd_sudoers on both hosts:

```
Defaults     env_keep += "workdir DIALOG NOCOLOR CBSD_RNODE"
Cmnd_Alias   CBSD_CMD = /usr/local/cbsd/sudoexec/*,/usr/local/cbsd/sudoexec/*
cbsd   ALL=(ALL) NOPASSWD:SETENV: CBSD_CMD
```

Log on destination host:

`Jul 21 10:33:00 erpj-2 sudo[18459]:     cbsd : user not allowed to preserve the environment ; TTY=pts/5 ; PWD=/var/empty ; USER=root ; COMMAND=/usr/local/cbsd/sudoexec/secretsfile jname="gletest1" mode="off"
`

**Comment by olevole** [comment]
valid sudoers cbsd_sudoers:
```
Defaults     env_keep += "workdir DIALOG NOCOLOR CBSD_RNODE"
Cmnd_Alias   CBSD_CMD = /usr/local/cbsd/sudoexec/*,/usr/local/cbsd/sudoexec/*
cbsd   ALL=(ALL) NOPASSWD:SETENV: CBSD_CMD
```

Please change it manually, you have a very old installation. Unfortunately there is no migration for this file.

**Comment by Peter2121** [comment]
Sorry, I don't see any difference between my file and the one you've suggested.

**Comment by Peter2121** [comment]
Any news? ;)

**Comment by olevole** [comment]
I cant reproduce this on my only stand.

you get an error on this command:
```
cbsd rexe node=node=erpj-2.reseaucloud.local tryoffline=1 /usr/local/bin/cbsd secretsfile jname=gletest1 mode=off
```
who does this:
```
/usr/bin/ssh -oControlPath=/usr/jails/.ssh/sockets/%r@%h:%p -t -l cbsd -oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=5 -q -oPort=22 -i /usr/jails/.rssh/id_rsa <IP of erpj-2.reseaucloud.local> -C cbsd secretsfile jname=xxx mode=off
```

secretsfile script:

https://github.com/cbsd/cbsd/blob/develop/tools/secretsfile

But why 'sudo -E' doesn't work on your system i don't understand ;-(


cbsd   ALL=(ALL) NOPASSWD:**SETENV**: CBSD_CMD
                                                     ^^^^^^^^^ should permit setenv. You probably have some additional sudo settings.

**Comment by olevole** [comment]
Also, try to check permission for ~cbsd/.ssh and ~cbsd/.rssh directory. Try doing this on both servers before migrating:
```
chown cbsd:cbsd ~cbsd/.ssh ~cbsd/.rssh
```

This is a bug (fix: https://github.com/cbsd/cbsd/commit/0fea73f4e5d0b035cd415051018a7666440dd533 ) in the recent version of the CBSD (came out after registering your problem).

I will add my how-to to reproduce the problem. Initial situation - clean installation of FreeBSD 13.0 ZFS.

**node1:**
1) `pkg install -y cbsd`
2) 
```
env workdir=/usr/jails /usr/local/cbsd/sudoexec/initenv 
-------[CBSD v.13.0.15]-------
...
```
3) `service cbsdd start` 
4) `cbsd jcreate jname=xxx runasap=1`
5) `passwd cbsd` // set pass for 'node add'
6) chown cbsd:cbsd ~cbsd/.ssh ~cbsd/.rssh  ( bug: https://github.com/cbsd/cbsd/commit/0fea73f4e5d0b035cd415051018a7666440dd533 )

**node2:**
1) `pkg install -y cbsd`
2) 
```
env workdir=/usr/jails /usr/local/cbsd/sudoexec/initenv 
-------[CBSD v.13.0.15]-------
...
```
3) `service cbsdd start` 
4) `cbsd repo action=get sources=base`
5) `passwd cbsd` // set pass for 'node add'
6) chown cbsd:cbsd ~cbsd/.ssh ~cbsd/.rssh ( bug: https://github.com/cbsd/cbsd/commit/0fea73f4e5d0b035cd415051018a7666440dd533 )


Migration:

1) add nodes:
**node1 ( 172.16.0.7 )**:
 `cbsd node mode=add node=172.16.0.8`
 
 **node2 ( 172.16.0.8 ):**
  `cbsd node mode=add node=172.16.0.7`
  
  
  2) jcoldmigrate:
  
  **node1 ( 172.16.0.7 )**:
`cbsd jcoldmigrate jname=xxx node=fbsd2.my.domain tryoffline=1`
```coldmigrate...[Stopping jail: xxx].....ok
jcoldmigrate done in 15 seconds
```

  **node1 ( 172.16.0.8 )**:
```
# jls
   JID  IP Address      Hostname                      Path
     1  10.0.0.1        xxx.my.domain                 /usr/jails/jails/xxx

# cbsd jls
NODENAME         JNAME  JID  IP4_ADDR  HOST_HOSTNAME  PATH                  STATUS
fbsd2.my.domain  xxx    1    10.0.0.1  xxx.my.domain  /usr/jails/jails/xxx  On
```

Maybe I can help from CBSD side, if you investigate the reasons for the non-working commands from my comment ( https://github.com/cbsd/cbsd/issues/617#issuecomment-929523142 ) in your environment. Waiting for info.
