### ISSUE TITLE
Build fails on HardenedBSD 14-CURRENT/arm64

### ISSUE THREAD

**Issue by lattera** [cbsd/cbsd#618]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): `FreeBSD arm64-01 14.0-CURRENT-HBSD FreeBSD 14.0-CURRENT-HBSD #0 : Wed Jul  7 19:46:31 UTC 2021     root@ci-12.md.hardenedbsd.lan:/usr/obj/usr/src/arm64.aarch64/sys/HARDENEDBSD  arm64`

CBSD version ( cbsd version ): I think 13.0.10, if I'm reading the poudriere build log correctly.

It appears that on arm64, CBSD fails to build. The link to the build log is here: http://tx-01.md.hardenedbsd.org/data/hardenedbsd-current_arm64-local/2021-07-23_19h59m24s/logs/errors/cbsd-13.0.10_1.log

The relevant portion of the log:

```
=======================<phase: stage          >============================
===>  Staging for cbsd-13.0.10_1
===>   Generating temporary packing list
===> Creating groups.
===> Creating users
Installing in /usr/local/cbsd
/bin/mkdir -p /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd
cp -f -a /wrkdirs/usr/ports/sysutils/cbsd/work/cbsd-13.0.10/ /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd
install  -s -m 555 -s /wrkdirs/usr/ports/sysutils/cbsd/work/cbsd-13.0.10/bin/cbsdsh/cbsd /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/bin
install  -s -m 555 -s /wrkdirs/usr/ports/sysutils/cbsd/work/cbsd-13.0.10/misc/src/sipcalc/sipcalc  /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd/misc/sipcalc
/bin/rm -f -rf /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd/bin/cbsdsh  /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd/bin/src  /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd/lib  /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd/misc/src  /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd/sbin/src  /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd/tools/src
install  -m 444 /wrkdirs/usr/ports/sysutils/cbsd/work/cbsd-13.0.10/man/cbsd.8 /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/man/man8/cbsd.8
====> Compressing man pages (compress-man)
===> Staging rc.d startup script(s)
===========================================================================
=======================<phase: package        >============================
===>  Building package for cbsd-13.0.10_1
pkg-static: Unable to access file /wrkdirs/usr/ports/sysutils/cbsd/work/stage/usr/local/cbsd/misc/popcnttest:No such file or directory
*** Error code 1

Stop.
make: stopped in /usr/ports/sysutils/cbsd
=>> Cleaning up wrkdir
===>  Cleaning for cbsd-13.0.10_1
build of sysutils/cbsd | cbsd-13.0.10_1 ended at Wed Jul 28 11:19:34 EDT 2021
build time: 00:01:20
!!! build failure encountered !!!
```

**Comment by olevole** [comment]
Hmm, **popcnttest** is not a mandatory tool for CBSD (it is mainly used to test the POPCNT instruction on x86 ( `grep POPCNT /var/run/dmesg.boot` ) when running bhyve ).

Most likely, we will be able to make a condition in pkg-plist for non x86-64. I believe this is relevant not only for HardenedBSD, but also for FreeBSD arm64

**Comment by olevole** [comment]
@lattera Is there any differences in the ports framework between **HardenedBSD** and **FreeBSD**? In FreeBSD:

_/usr/ports/sysutils/cbsd/pkg-plist_:

```
%%X86%%cbsd/misc/popcnttest
```

and _/usr/ports/sysutils/cbsd/Makefile_:
```
.if ${ARCH} == amd64 || ${ARCH} == i386
PLIST_SUB=      X86=""
.else
PLIST_SUB=      X86="@comment "
.endif
```
this allows us to have a dynamic file list depending on the architecture.

**Comment by olevole** [comment]
Waiting for comments. From the port point: it is processed. It is necessary to check the synchronization of ports and port framework in HarrendBSD
