### ISSUE TITLE
On CBSD Upgrade UNABLE to fetch VM

### ISSUE THREAD

**Issue by JEAholding** [cbsd/cbsd#622]
FreeBSD version ( uname -a ): 
Freebsd 13
13.0-RELEASE-p4 FreeBSD 13.0-RELEASE-p4

CBSD version ( cbsd version ): 
13.0.13

The problem began when upgrading cbsd to the latest previously I was able to view and operate the VM... 

========================================================================

env workdir="/zroot_r820_samsung1/usr/jails" cbsd initenv

After now 
env workdir="/zroot_r820_samsung1/usr/jails" cbsd bls

JNAME  JID  VM_RAM  VM_CURMEM  VM_CPUS  PCPU   VM_OS_TYPE                                                                                    IP4_ADDR  STATUS  VNC
Unable    to   fetch   vm         data     from:  /zroot_r820_samsung1/usr/jails/jails-system/[NAME_of_1_VM]/local.sqlite

env workdir="/zroot_r820_samsung2/usr/jails" cbsd bls
Unable    to   fetch   vm         data     from:  /zroot_r820_samsung2/usr/jails/jails-system/[NAME_of_1_VM]/local.sqlite

CHECKING DB
sqlite3 /var/db/[name*** node].sqlite

select * from bhyve;
SHOWING all ACTIVE CREATED VM 
select * from jails;
SHOWING same number of VM table

CHECKING:
ls -lac /usr/jails/jails-system/

ls vm/[NAME_of_1_VM]/
sqlite3 vm/[NAME_of_1_VM]/local.sqlite
sqlite> .tables
sqlite> select * from settings;
sqlite> select * from bhyvedsk;
sqlite> select * from pcibus;

Everything was working normally prior to the update I have 2 zfs boot drives install on non OS HDD both running CBSD, BOTH stop working after the upgrade.

**Comment by olevole** [comment]
Do I understand correctly that the tables are empty? Or have you hidden the conclusion?

Can you check schema ?
```
sqlite3  /zroot_r820_samsung2/usr/jails/jails-system/[NAME_of_1_VM]/local.sqlite ".schema settings"
```

to dump data:
```
sqlite3  /zroot_r820_samsung2/usr/jails/jails-system/[NAME_of_1_VM]/local.sqlite ".dump settings"
```

?

**Comment by olevole** [comment]
@JEAholding  It seems that the migration script overwrites a working directory from environment.

Try temporarily change the global working directory through the /etc/rc.conf file:

sysrc cbsd_workdir="/zroot_r820_samsung2/usr/jails"

and re-run `cbsd initenv`

(then change cbsd_workdir values to old value)

**Comment by JEAholding** [comment]
Ok just for informational purposes.... AS your last message fix the issue no problem...

Changing rc.conf to new directory workdir. NOW question is in rc.conf I can put multiple workdir or only 1? 
So if is only 1 allowed on rc.conf I have to make change every time I upgrade cbsd initenv? 
I have 3 CBSD workdir in total 
1 on OS HDD called it root workdir.
1 extra cbsd workdir on /zroot_r820_samsun1 folder
1 extra cbsd workdir on zroot_r820_samsung2 folder

So the procedure to upgrade will be to change rc.conf FIRST after run cbsd initenv on new define directory OR I can have all 3 workdir on rc.conf ? 
Example
cbsd_workdir
cbsd_workdir2
cbsd_workdir3

_Will this work?_ 


The previous commands just for information output:

sqlite3  /zroot_r820_samsung2/usr/jails/jails-system/[NAME_of_1_VM]/local.sqlite ".schema settings"

> CREATE TABLE settings (  created TIMESTAMP DATE DEFAULT (datetime('now','localtime')), astart integer default 0, vm_cpus integer default 1, vm_ram integer default 536870912, vm_os_type text default freebsd, vm_boot text default hdd, vm_os_profile text default 0, bhyve_flags text default 0, vm_vnc_port integer default 0, virtio_type text default "ahci-hd", bhyve_vnc_tcp_bind text default "127.0.0.1", bhyve_vnc_resolution text default "1024x768", cd_vnc_wait integer default 0, protected integer default 0, hidden integer default 0, maintenance text default 0, ip4_addr text default 'DHCP', vnc_password text default '', state_time TIMESTAMP DATE DEFAULT (datetime('now','localtime')), vm_hostbridge text default "hostbridge", vm_iso_path text default 0, vm_console text default "tmux", vm_efi text default "none", vm_rd_port integer default 0, bhyve_generate_acpi integer default 1, bhyve_wire_memory integer default 0, bhyve_rts_keeps_utc integer default 0, bhyve_force_msi_irq integer default 0, bhyve_x2apic_mode integer default 0, bhyve_mptable_gen integer default 1, bhyve_ignore_msr_acc integer default 0, bhyve_vnc_vgaconf text default 'io', media_auto_eject integer default 0, vm_cpu_topology text default 0, debug_engine text default "none", xhci integer default 1, cd_boot_firmware text default "bhyve", jailed text default "0", vm_iso_path2 text default 0, on_poweroff text default "destroy", on_reboot text default "restart", on_crash text default "destroy", vm_zfs_guid text default "0", vnc_port integer default 0, soundhw text default "none", bhyve_cmd text default "/usr/sbin/bhyve", double_acpi , virtio_rnd , hdd_boot_firmware text default "0", chrooted text default "0", uuid text default "0", bhyverun_wrapper text default "/usr/local/cbsd/share/bhyverun.sh", bhyvestop_wrapper text default "0"  );

sqlite3  /zroot_r820_samsung2/usr/jails/jails-system/[NAME_of_1_VM]/local.sqlite ".dump settings"

> PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE settings (  created TIMESTAMP DATE DEFAULT (datetime('now','localtime')), astart integer default 0, vm_cpus integer default 1, vm_ram integer default 536870912, vm_os_type text default freebsd, vm_boot text default hdd, vm_os_profile text default 0, bhyve_flags text default 0, vm_vnc_port integer default 0, virtio_type text default "ahci-hd", bhyve_vnc_tcp_bind text default "127.0.0.1", bhyve_vnc_resolution text default "1024x768", cd_vnc_wait integer default 0, protected integer default 0, hidden integer default 0, maintenance text default 0, ip4_addr text default 'DHCP', vnc_password text default '', state_time TIMESTAMP DATE DEFAULT (datetime('now','localtime')), vm_hostbridge text default "hostbridge", vm_iso_path text default 0, vm_console text default "tmux", vm_efi text default "none", vm_rd_port integer default 0, bhyve_generate_acpi integer default 1, bhyve_wire_memory integer default 0, bhyve_rts_keeps_utc integer default 0, bhyve_force_msi_irq integer default 0, bhyve_x2apic_mode integer default 0, bhyve_mptable_gen integer default 1, bhyve_ignore_msr_acc integer default 0, bhyve_vnc_vgaconf text default 'io', media_auto_eject integer default 0, vm_cpu_topology text default 0, debug_engine text default "none", xhci integer default 1, cd_boot_firmware text default "bhyve", jailed text default "0", vm_iso_path2 text default 0, on_poweroff text default "destroy", on_reboot text default "restart", on_crash text default "destroy", vm_zfs_guid text default "0", vnc_port integer default 0, soundhw text default "none", bhyve_cmd text default "/usr/sbin/bhyve", double_acpi , virtio_rnd , hdd_boot_firmware text default "0", chrooted text default "0", uuid text default "0", bhyverun_wrapper text default "/usr/local/cbsd/share/bhyverun.sh", bhyvestop_wrapper text default "0"  );
INSERT INTO settings VALUES(1615963459,1,4,4294967296,'linux','hdd','CentOS-7-x86_64-minimal','0',3357,'ahci-hd','LOCAL_IP','1280x720',1,0,0,'0','GLOBAL_IP','',1623100006,'hostbridge','iso-CentOS-7-x86_64-minimal','tmux','uefi',0,1,0,1,0,0,1,0,'io',0,'default','none',1,'refind','0','0','destroy','restart','destroy','17396254950847978731',3357,'none','/usr/sbin/bhyve','1','1','refind','0','[SOMEUUID]','/usr/local/cbsd/share/bhyverun.sh','0');
COMMIT;

**Comment by olevole** [comment]
> So if is only 1 allowed on rc.conf I have to make change every time I upgrade cbsd initenv?

Of course this is a bug that needs to be fixed. I'll see soon. I suggested changing the global variable via /etc/rc.conf to verify my theory). At least now we know where the problem is.

With the latest update bhyve got the 'boot_delay' option (pause before bhyve domain startup (for smoothing load when host boots))  - the migration script did not use the environment variable and this led to a difference in the SQL schema.

Most likely, I will add an option for automatic migration (besides fixing this error) so that the initialization happens automatically when the version is updated.

**Comment by JEAholding** [comment]
Alright, it is CONFIRM your solution is proven and cbsd upgrade/ cbsd initenv works by changing rc.conf workdir

I was able to upgrade all of the supplemental workdir (3 workdir in total via this method in rc.conf) 15 VM in TOTAL now showing in distributed workdir.

Glad I was able to assist on finding some errors, in future 5-6 month with more usage would like to look and help out under the hood. 
 
Let me know if you want me to close or if you want to leave it open until you do a new version_commit to fix the bug.

**Comment by olevole** [comment]
Yeah, please leave this Issue open. In fact, I personally switched to the use of several hosts ( as described here: https://www.bsdstore.ru/en/cbsd_api_ssi.html + IPAM as 'cbsd dhcpd' helper: https://www.bsdstore.ru/en/13.0.x/wf_ipam_ssi.html ), so multiple environments are tested little.

> Glad I was able to assist on finding some errors

Thank you. Soon I will make even more bugs, I'm sure! ;-)

**Comment by olevole** [comment]
the task with automatic migration will be done later as it is not a trivial task
