### ISSUE TITLE
jails with multiple IPs/NICs use incorrect syntax in  pfnat

### ISSUE THREAD

**Issue by namotco** [cbsd/cbsd#623]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64

CBSD version ( cbsd version ): 12.1.13

If the jail IPs are setup as: igb0#192.168.1.205,bxe2#10.125.200.205
Then: cbsd expose produces incorrect pf syntax in jails/etc/pfnat.cfg:

What happens:
rdr pass proto tcp from any to 10.123.45.200 port 3182 -> igb0#192.168.1.205,bxe2#10.125.200.205 port 3182
Correct:
rdr pass proto tcp from any to 10.123.45.200 port 3182 -> 192.168.1.205 port 3182

Example
# pfctl -sn
...
rdr pass inet proto tcp from any to 10.123.45.200 port = 3182 -> { 10.123.45.200, 172.16.29.11, 172.16.29.3, 172.16.29.4, 172.16.29.100, 172.16.29.99, 172.16.29.13, 172.16.29.15, 172.16.29.16, 172.16.29.17, 172.16.29.18, 172.16.29.19, 172.16.29.21, 172.16.29.80, 172.16.29.27, 172.16.29.28, 172.16.29.29, 172.16.29.30, 172.16.29.31, 172.16.29.35, 172.16.29.38, 172.16.29.39, 172.16.29.40, 172.16.29.41, 172.16.29.42, 172.16.29.43, 172.16.29.44, 172.16.29.45, 172.16.29.6, 172.16.29.46, 172.16.29.47, 172.16.29.48, 172.16.29.7, 172.16.29.10, 172.16.29.12, 172.16.29.20, 172.16.29.8, 172.16.29.2 } round-robin

**Comment by olevole** [comment]
@namotco Thank! If you update CBSD to the latest version (13.0.5) - try to add this via: https://github.com/cbsd/cbsd/commit/1fd9fb94520a9edfcfe662cc714f20fbd0ebe478 , e.g:

```
mv /usr/local/cbsd/tools/expose /tmp
fetch -o /usr/local/cbsd/tools/expose https://raw.githubusercontent.com/cbsd/cbsd/develop/tools/expose
chmod +x /usr/local/cbsd/tools/expose
```

My test:

```
# ifconfig bridge1 create
# ifconfig bridge2 create
# ifconfig bridge1 inet 192.168.50.1/24 up
# ifconfig bridge2 inet 192.168.60.1/24 up
# cbsd jcreate jname=test1 runasap=1 ip4_addr="bridge1#192.168.50.2,bridge2#192.168.51.2"
# cbsd expose jname=test1 in=3128 out=3128 mode=add

# grep test1 ~cbsd/etc/pfnat.conf 
rdr pass proto tcp from any to 172.16.0.3 port 3128 -> 192.168.50.2 port 3128 # // Setup by CBSD expose: tcp-3128-test1
```

**Comment by olevole** [comment]
@namotco By the way, due to the difference in versions, if you have any problems with 'cbsd jls' after upgrading CBSD 12.x -> 13.0.15, try to remove cmd.subr file and re-run `cbsd initenv` again:

```
rm -f ~cbsd/cmd.subr
/usr/local/cbsd/sudoexec/initenv
```
