### ISSUE TITLE
Create jail config file?

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#635]
I know we can use `cbsd jcreate jconf=/path/to/conf.jconf` to create a jail from a config file.
But is there any way to create such config file from an existing jail?

**Comment by olevole** [comment]
Original config for jail create must exist in ~cbsd/jails-system/**ENV**/ directory as rc.conf_**ENV**

or try:
```
cbsd jmkrcconf jname=<env>
 ```
 
hint: best way to create lots of jail from single tpl is [CBSDfile](https://www.bsdstore.ru/en/cbsdfile.html) ;)
