### ISSUE TITLE
13.0.17: Unexpected update message

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#650]
First of all: Thank you for providing a new release this quickly!

After building and installing `cbsd 13.0.17`, running `cbsd initenv` shows something I'd consider "unexpected":
```none
jbo@fbsd_beefy01 /u/h/jbo> cbsd initenv
Warning: CBSD is 13.0.17 while workdir initializated for 13.0.16. Please re-run: env workdir=/zroot/cbsd cbsd initenv
-------[CBSD v.13.0.17]-------
 This is install/upgrade scripts for CBSD.
 Don't forget to backup.
-----------------------------
Do you want prepare or upgrade hier environment for CBSD now?
[yes(1) or no(0)]
1
>>> Installing or upgrading
[Stage 0: upgrading and migration data from 13.0.17 to 13.0.17]
[Stage 1: account & dir hier]
 * Check hier and permission...
    cmdboot: no such optional executable: xl, xen_feat disabled
[Stage 2: build tools]
[Stage 3: local settings]
[Stage 4: update default skel resolv.conf]
[Stage 5: refreshing inventory]
[Stage 6: authentication keys]
[Stage 7: nodes]
[Stage 8: modules]
[Stage 9: cleanup]
 * Remove obsolete files...
[Stage X: upgrading]
>>> Done
```
Specifically, this line:
```none
[Stage 0: upgrading and migration data from 13.0.17 to 13.0.17]
```
Now, I see no problem in this. I was just wondering whether it's a helpful contribution to mention this.

**Comment by aeifn** [comment]
> [Stage 0: upgrading and migration data from 13.0.17 to 13.0.17]

It just means that `${workdir}/nc.inventory` file has already been updated.

`oldver` is assigned here:
https://github.com/cbsd/cbsd/blob/92ae674879c7ae8d1e66ebaf8f025a668ae5f4b1/sudoexec/initenv#L228-L234

**Comment by aeifn** [comment]
While this

> `Warning: CBSD is 13.0.17 while workdir initializated for 13.0.16. Please re-run: env workdir=/zroot/cbsd cbsd initenv`

is produced by `nc.subr`, which reads `${workdir}/ver`:

https://github.com/cbsd/cbsd/blob/92ae674879c7ae8d1e66ebaf8f025a668ae5f4b1/subr/nc.subr#L135-L140

And `${workdir}/ver` wasn`t updated for some reason.

@olevole probably we should identify `workdir` version using `nc.inventory` only.
