### ISSUE TITLE
cbsd : command not found

### ISSUE THREAD

**Issue by Marietto2008** [cbsd/cbsd#659]
On FreeBSD 13,I did : 

pkg install sudo libssh2 rsync sqlite3 git pkgconf
git clone https://github.com/cbsd/cbsd.git /usr/local/cbsd
pw useradd cbsd -s /bin/sh -d /nonexistent -c "marietto"
cd /usr/local/etc/rc.d
ln -s /usr/local/cbsd/rc.d/cbsdd
ln -s /usr/local/cbsd/rc.d/cbsdrsyncd
mkdir -p /usr/local/libexec/bsdconfig
ln -s /usr/local/cbsd/share/bsdconfig/cbsd /usr/local/libexec/bsdconfig
rebooted
cbsd : command not found

marietto@marietto:/usr/home/marietto $ service cbsdd onestart
no workdir

marietto@marietto:/usr/home/marietto $ service cbsdrsyncd onestart

/usr/local/etc/rc.d/cbsdrsyncd: WARNING: /etc/rsyncd.conf is not readable.
/usr/local/etc/rc.d/cbsdrsyncd: WARNING: failed precmd routine for cbsdrsyncd

why ? istructions about how to install and run the development version dont' seem to be accurate.

**Comment by mekanix** [comment]
Well, the first thing I notice is that you're missing [initenv](https://cbsd.io/cbsd/Installing-cbsd/#initenv) part of install. Also, cbsd command is only available to root, and it looks like you're trying to run it as non-root user.

**Comment by olevole** [comment]
> On FreeBSD 13,I did :
> 
> pkg install sudo libssh2 rsync sqlite3 git pkgconf git clone https://github.com/cbsd/cbsd.git /usr/local/cbsd pw useradd cbsd -s /bin/sh -d /nonexistent -c "marietto" cd /usr/local/etc/rc.d ln -s /usr/local/cbsd/rc.d/cbsdd ln -s /usr/local/cbsd/rc.d/cbsdrsyncd mkdir -p /usr/local/libexec/bsdconfig ln -s /usr/local/cbsd/share/bsdconfig/cbsd /usr/local/libexec/bsdconfig rebooted cbsd : command not found

Since you are installing from sources, some binaries are not yet available. They will compile after `cbsd initenv`:

env workdir=/usr/jails /usr/local/cbsd/sudoexec/initenv

or

`make -C /usr/local/cbsd`
`make -C /usr/local/cbsd install`

**Comment by Marietto2008** [comment]
yes ok but why the command that you mentioned is not present in the
instructions that ive read on the "how to install the development version ?
"

Il sab 20 nov 2021, 10:56 Oleg Ginzburg ***@***.***> ha
scritto:

**Comment by mekanix** [comment]
Because you didn't initenv.

**Comment by Marietto2008** [comment]
i didnt do it because the command has been omitted from the instructions.

Il sab 20 nov 2021, 11:11 Goran Mekić ***@***.***> ha scritto:

**Comment by aeifn** [comment]
> i didnt do it because the command has been omitted from the instructions. Il sab 20 nov 2021, 11:11 Goran Mekić ***@***.***> ha scritto:
> […](#)

you are right: readme is incomplete

**Comment by olevole** [comment]
@Marietto2008 you're right, the instructions need to be fixed. By the way, at the moment, the version in the GIT is now the same as the version in the port ( 13.0.18 released yesterday ;)

**Comment by aeifn** [comment]
> @Marietto2008 you're right, the instructions need to be fixed. By the way, at the moment, the version in the GIT is now the same as the version in the port ( 13.0.18 released yesterday ;)

Maybe @Marietto2008 wanted to contribute? :)

**Comment by Marietto2008** [comment]
i can contribute yes,by testing cbsd + jails + linux + bhyve and so on.

Il sab 20 nov 2021, 12:26 Egor Kuzmichev ***@***.***> ha
scritto:
