### ISSUE TITLE
README table of contents item 1 refers to a nonexistent anchor

### ISSUE THREAD

**Issue by grahamperrin** [cbsd/cbsd#661]
Under <https://github.com/cbsd/cbsd/blob/develop/README.md#table-of-contents>, item 

> 1. Project Description - What does the project do?

– refers to non-existent <https://github.com/cbsd/cbsd/blob/develop/README.md#project-description>.

Has the table somehow slipped below the Description <https://github.com/cbsd/cbsd/blob/develop/README.md#description> when it should be above?

**Comment by olevole** [comment]
Thanks @aeifn @grahamperrin. Much better now: no TOC - no problem ;)))
