### ISSUE TITLE
bhyve VM: Cannot add "virtual cores"

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#670]
I have a host running cbsd `13.0.18`. The host has an Intel Xeon CPU with 14 Cores / 28 threads.

Unfortunately, the VM can't take full advantages of the available system resources. cbsd doesn't allow me to set more than 16 cores.
Why is this? is there a way around this limitation? The VM is used for automated package building using poudriere and the server is only getting a ~50% load this way.

**Comment by mekanix** [comment]
I know 16 cores was the limit for bhyve before: https://lists.freebsd.org/pipermail/freebsd-virtualization/2014-November/003104.html. I don't know how relevant is it today.

**Comment by olevole** [comment]
That's right, 16 vCore is an artificial limit from CBSD side: man bhyve(5): https://man.freebsd.org/bhyve/8
```
The current maximum number of guest virtual CPUs is 16.
```

Probably freebsd-virtualization@freebsd.org mailing list can answer more.

**Comment by olevole** [comment]
@Tectu forget to say: you can override the maximum vCPU limit for bhyve in the CBSD, see `vm_cpus_max=` settings in https://github.com/cbsd/cbsd/blob/develop/etc/defaults/bhyve-default-default.conf#L53


All settings in `~cbsd/etc/defaults/*.conf` may be overwritten via `~cbsd/etc/*.conf` ( as **/etc/defaults** and **/etc/** in FreeBSD ), e.g.:

```
echo vm_cpus_max=32 >> ~cbsd/etc/bhyve-default-default.conf
```

This is a protection for user's input, when bhyve does not support XX number of vcore

**Comment by Tectu** [comment]
I'm adding this for future references: e13d88b64094ec11ab411c44f16dce192dbe05c5

**Comment by olevole** [comment]
FYI:
https://cgit.freebsd.org/src/commit/?id=c76e4b89
https://cgit.freebsd.org/src/commit/?id=f1d450dd

**Comment by Tectu** [comment]
Nice!!

However, there doesn't seem to be any MFC duration. So we probably won't get that into stable/13 any time soon - and most likely also not into 13.1-RELEASE.

**Comment by Tectu** [comment]
Raising the bhyve vCPU limit appears to have made it into 13.2-RELEASE (which should be officially announced tomorrow).
What exactly is the current state of this on the CBSD side? Are manual modifications of `vm_cpus_max` still necessary at this point to use more than 16 vCPUs?

**Comment by olevole** [comment]
@Tectu Great news! I missed this change.

I already submitted a patch to update _/usr/ports/sysutils/cbsd_ to the latest CBSD release ( *13.2.0*  ),  but we will reflect this change in the next CBSD release - they come out quite often ;-)

I guess we can in /usr/local/cbsd/etc/defaults/bhyve-default-default.conf instead of:
```
vm_cpus_max=16
```

something like that:
```
vm_cpus_max=16
[ ${freebsdhostversion} -ge 1302000 ] && vm_cpus_max=$( /sbin/sysctl -qn hw.vmm.maxcpu )
```
:thinking:

**Comment by Tectu** [comment]
That seems overall reasonable. If you'd want to be a bit trolling you could also use the `nproc(1)` given that this is also a new feature in 13.2 and you're dealing with a host OS version conditional anyway :D
That is more of a joke tho. I think `sysctl hw.vmm.maxcpu` is the way to go as this is also how `bhyve(8)` appears to behave out of the box.

**Comment by Tectu** [comment]
Just saw that this change was committed a few hours ago - nice!
Looking forwarding having a VM with more than 16 vCPUs on the next release :)
