### ISSUE TITLE
Jail upgrade from 12.2 to 13.0 blows out all config files

### ISSUE THREAD

**Issue by GitHubinat0r** [cbsd/cbsd#671]
_I could be performing an upgrade incorrectly. If that's the case, I apologize profusely._

FreeBSD version ( uname -a ): 
FreeBSD localhost 13.0-RELEASE-p4 FreeBSD 13.0-RELEASE-p4 #0: Tue Aug 24 07:33:27 UTC 2021     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

CBSD version ( cbsd version ): 
13.0.19

Below are the steps that I use to recreate the issue:
`
**root@localhost:/usr/home/user # cbsd jcreate jname=jail4 ip4_addr=DHCP ver=12.2**
Please wait: this will take a while...
Applying skel dir template from: /usr/cbsd/share/FreeBSD-jail-skel

To edit VM properties use: cbsd jconfig jname=jail4
To start VM use: cbsd jstart jail4
To stop VM use: cbsd jstop jail4
To remove VM use: cbsd jremove jail4
For attach VM console use: cbsd jlogin jail4
Creating jail4 complete: Enjoy!
jcreate done in 25 seconds

**root@localhost:/usr/home/user # cbsd jset jname=jail4 ver=13.0**
ver: 13.0

**root@localhost:/usr/home/user # cbsd jstart jail4**
Ip 192.168.0.1 already exists in LAN
Default NIC automatically selected: lo1
set resource limit: [ ]
jail renice: 1
Warning: jail version (13.0) and distribution (e.g: /etc dir content) (12.2) is differ
Warning: you can use etcupdate to sync content: cbsd etcupdate jname=jail4 mode=update from=12.2 to=13.0
Starting jail: jail4, parallel timeout=5
jail4: created
Generating host.conf.
ELF ldconfig path: /lib /usr/lib /usr/lib/compat /usr/local/lib /usr/local/lib/compat/pkg /usr/local/lib/compat/pkg
32-bit compatibility ldconfig path: /usr/lib32
Updating /var/run/os-release done.
Creating and/or trimming log files.
Updating motd:.
Starting syslogd.
Clearing /tmp (X related).
Starting cron.
Starting sendmail_submit.
Starting sendmail_msp_queue.
Tue Dec 14 08:21:28 PST 2021
jstart done in 4 seconds

**root@localhost:/usr/home/user # cbsd etcupdate jname=jail4 mode=update from=12.2 to=13.0**
etcupdate source hier: /usr/cbsd/src/src_12.2/etcupdate/current
etcupdate destination hier: /usr/cbsd/src/src_13.0/etcupdate/etcupdate.tgz
etcupdate: created backup: /usr/cbsd/jails-system/jail4/etcupdate/backup/20211214082539.tgz
[debug]: /usr/sbin/etcupdate -d /usr/cbsd/jails-system/jail4/etcupdate -t /usr/cbsd/src/src_13.0/etcupdate/etcupdate.tgz -D /usr/cbsd/jails/jail4 -I /etc/\*.db -I /root/\* -I /etc/hosts -F
  D /boot/device.hints
  D /etc/aliases
  D /etc/amd.map
  D /etc/auto_master
  D /etc/autofs/include_ldap
  D /etc/autofs/include_nis
  D /etc/autofs/include_nis_nullfs
  D /etc/autofs/special_hosts
  D /etc/autofs/special_media
  D /etc/autofs/special_noauto
  D /etc/autofs/special_null
  D /etc/blacklistd.conf
  D /etc/bluetooth/hcsecd.conf
  D /etc/bluetooth/hosts
  D /etc/bluetooth/protocols
  D /etc/cron.d/at
  D /etc/crontab
  D /etc/csh.cshrc
  D /etc/csh.login
  D /etc/csh.logout
  D /etc/ddb.conf
  D /etc/defaults/bluetooth.device.conf
  D /etc/defaults/devfs.rules
  D /etc/defaults/periodic.conf
  D /etc/defaults/rc.conf
  D /etc/devd.conf
  D /etc/devd/asus.conf
  D /etc/devd/devmatch.conf
  D /etc/devd/hyperv.conf
  D /etc/devd/iwmbtfw.conf
  D /etc/devd/uath.conf
  D /etc/devd/ulpt.conf
  D /etc/devd/zfs.conf
  D /etc/devfs.conf
  D /etc/dhclient.conf
  D /etc/disktab
  D /etc/dma/dma.conf
  D /etc/dumpdates
  D /etc/fbtab
  D /etc/freebsd-update.conf
  D /etc/ftpusers
  D /etc/gettytab
  D /etc/gss/mech
  D /etc/gss/qop
  D /etc/hosts.allow
  D /etc/hosts.equiv
  D /etc/hosts.lpd
  D /etc/inetd.conf
  D /etc/libalias.conf
  D /etc/libmap.conf
  D /etc/locate.rc
  D /etc/login.access
  D /etc/login.conf
  D /etc/mac.conf
  D /etc/mail.rc
  D /etc/mail/access.sample
  D /etc/mail/freebsd.cf
  D /etc/mail/freebsd.mc
  D /etc/mail/freebsd.submit.cf
  D /etc/mail/freebsd.submit.mc
  D /etc/mail/helpfile
  D /etc/mail/mailer.conf
  D /etc/mail/mailertable.sample
  D /etc/mail/Makefile
  D /etc/mail/README
  D /etc/mail/sendmail.cf
  D /etc/mail/submit.cf
  D /etc/mail/virtusertable.sample
  D /etc/mtree/BSD.debug.dist
  D /etc/mtree/BSD.include.dist
  D /etc/mtree/BSD.lib32.dist
  D /etc/mtree/BSD.root.dist
  D /etc/mtree/BSD.sendmail.dist
  D /etc/mtree/BSD.tests.dist
  D /etc/mtree/BSD.usr.dist
  D /etc/mtree/BSD.var.dist
  D /etc/netconfig
  D /etc/netstart
  D /etc/network.subr
  D /etc/networks
  D /etc/newsyslog.conf
  D /etc/newsyslog.conf.d/amd.conf
  D /etc/newsyslog.conf.d/ftp.conf
  D /etc/newsyslog.conf.d/lpr.conf
  D /etc/newsyslog.conf.d/opensm.conf
  D /etc/newsyslog.conf.d/pf.conf
  D /etc/newsyslog.conf.d/ppp.conf
  D /etc/newsyslog.conf.d/sendmail.conf
  D /etc/nscd.conf
  D /etc/nsmb.conf
  D /etc/nsswitch.conf
  D /etc/ntp.conf
  D /etc/ntp/leap-seconds
  D /etc/opieaccess
  D /etc/os-release
  D /etc/pam.d/atrun
  D /etc/pam.d/cron
  D /etc/pam.d/ftp
  D /etc/pam.d/ftpd
  D /etc/pam.d/imap
  D /etc/pam.d/login
  D /etc/pam.d/other
  D /etc/pam.d/passwd
  D /etc/pam.d/pop3
  D /etc/pam.d/README
  D /etc/pam.d/sshd
  D /etc/pam.d/su
  D /etc/pam.d/system
  D /etc/pam.d/telnetd
  D /etc/pam.d/xdm
  D /etc/pccard_ether
  D /etc/periodic/daily/100.clean-disks
  D /etc/periodic/daily/110.clean-tmps
  D /etc/periodic/daily/120.clean-preserve
  D /etc/periodic/daily/130.clean-msgs
  D /etc/periodic/daily/140.clean-rwho
  D /etc/periodic/daily/150.clean-hoststat
  D /etc/periodic/daily/200.backup-passwd
  D /etc/periodic/daily/210.backup-aliases
  D /etc/periodic/daily/300.calendar
  D /etc/periodic/daily/310.accounting
  D /etc/periodic/daily/330.news
  D /etc/periodic/daily/400.status-disks
  D /etc/periodic/daily/401.status-graid
  D /etc/periodic/daily/404.status-zfs
  D /etc/periodic/daily/406.status-gmirror
  D /etc/periodic/daily/407.status-graid3
  D /etc/periodic/daily/408.status-gstripe
  D /etc/periodic/daily/409.status-gconcat
  D /etc/periodic/daily/410.status-mfi
  D /etc/periodic/daily/420.status-network
  D /etc/periodic/daily/430.status-uptime
  D /etc/periodic/daily/440.status-mailq
  D /etc/periodic/daily/450.status-security
  D /etc/periodic/daily/460.status-mail-rejects
  D /etc/periodic/daily/480.leapfile-ntpd
  D /etc/periodic/daily/480.status-ntpd
  D /etc/periodic/daily/500.queuerun
  D /etc/periodic/daily/510.status-world-kernel
  D /etc/periodic/daily/800.scrub-zfs
  D /etc/periodic/daily/999.local
  D /etc/periodic/monthly/200.accounting
  D /etc/periodic/monthly/450.status-security
  D /etc/periodic/monthly/999.local
  D /etc/periodic/security/100.chksetuid
  D /etc/periodic/security/110.neggrpperm
  D /etc/periodic/security/200.chkmounts
  D /etc/periodic/security/300.chkuid0
  D /etc/periodic/security/400.passwdless
  D /etc/periodic/security/410.logincheck
  D /etc/periodic/security/500.ipfwdenied
  D /etc/periodic/security/510.ipfdenied
  D /etc/periodic/security/520.pfdenied
  D /etc/periodic/security/550.ipfwlimit
  D /etc/periodic/security/610.ipf6denied
  D /etc/periodic/security/700.kernelmsg
  D /etc/periodic/security/800.loginfail
  D /etc/periodic/security/900.tcpwrap
  D /etc/periodic/security/security.functions
  D /etc/periodic/weekly/310.locate
  D /etc/periodic/weekly/320.whatis
  D /etc/periodic/weekly/340.noid
  D /etc/periodic/weekly/450.status-security
  D /etc/periodic/weekly/999.local
  D /etc/pf.os
  D /etc/phones
  D /etc/pkg/FreeBSD.conf
  D /etc/portsnap.conf
  D /etc/ppp/ppp.conf
  D /etc/printcap
  D /etc/profile
  D /etc/protocols
  D /etc/rc
  D /etc/rc.bsdextended
  D /etc/rc.d/accounting
  D /etc/rc.d/addswap
  D /etc/rc.d/adjkerntz
  D /etc/rc.d/amd
  D /etc/rc.d/apm
  D /etc/rc.d/archdep
  D /etc/rc.d/auditd
  D /etc/rc.d/auditdistd
  D /etc/rc.d/automount
  D /etc/rc.d/automountd
  D /etc/rc.d/autounmountd
  D /etc/rc.d/bgfsck
  D /etc/rc.d/blacklistd
  D /etc/rc.d/bluetooth
  D /etc/rc.d/bootparams
  D /etc/rc.d/bridge
  D /etc/rc.d/bsnmpd
  D /etc/rc.d/bthidd
  D /etc/rc.d/ccd
  D /etc/rc.d/cfumass
  D /etc/rc.d/cleanvar
  D /etc/rc.d/cleartmp
  D /etc/rc.d/cron
  D /etc/rc.d/ctld
  D /etc/rc.d/DAEMON
  D /etc/rc.d/ddb
  D /etc/rc.d/defaultroute
  D /etc/rc.d/devd
  D /etc/rc.d/devfs
  D /etc/rc.d/devmatch
  D /etc/rc.d/dhclient
  D /etc/rc.d/dmesg
  D /etc/rc.d/dumpon
  D /etc/rc.d/FILESYSTEMS
  D /etc/rc.d/fsck
  D /etc/rc.d/ftp-proxy
  D /etc/rc.d/ftpd
  D /etc/rc.d/gbde
  D /etc/rc.d/geli
  D /etc/rc.d/geli2
  D /etc/rc.d/gptboot
  D /etc/rc.d/growfs
  D /etc/rc.d/gssd
  D /etc/rc.d/hastd
  D /etc/rc.d/hcsecd
  D /etc/rc.d/hostapd
  D /etc/rc.d/hostid
  D /etc/rc.d/hostid_save
  D /etc/rc.d/hostname
  D /etc/rc.d/inetd
  D /etc/rc.d/iovctl
  D /etc/rc.d/ip6addrctl
  D /etc/rc.d/ipfilter
  D /etc/rc.d/ipfs
  D /etc/rc.d/ipfw
  D /etc/rc.d/ipfw_netflow
  D /etc/rc.d/ipmon
  D /etc/rc.d/ipnat
  D /etc/rc.d/ippool
  D /etc/rc.d/ipropd_master
  D /etc/rc.d/ipropd_slave
  D /etc/rc.d/ipsec
  D /etc/rc.d/iscsictl
  D /etc/rc.d/iscsid
  D /etc/rc.d/jail
  D /etc/rc.d/kadmind
  D /etc/rc.d/kdc
  D /etc/rc.d/keyserv
  D /etc/rc.d/kfd
  D /etc/rc.d/kld
  D /etc/rc.d/kldxref
  D /etc/rc.d/kpasswdd
  D /etc/rc.d/ldconfig
  D /etc/rc.d/linux
  D /etc/rc.d/local
  D /etc/rc.d/local_unbound
  D /etc/rc.d/localpkg
  D /etc/rc.d/lockd
  D /etc/rc.d/LOGIN
  D /etc/rc.d/lpd
  D /etc/rc.d/mdconfig
  D /etc/rc.d/mdconfig2
  D /etc/rc.d/mixer
  D /etc/rc.d/motd
  D /etc/rc.d/mountcritlocal
  D /etc/rc.d/mountcritremote
  D /etc/rc.d/mountd
  D /etc/rc.d/mountlate
  D /etc/rc.d/moused
  D /etc/rc.d/msgs
  D /etc/rc.d/natd
  D /etc/rc.d/netif
  D /etc/rc.d/netoptions
  D /etc/rc.d/netwait
  D /etc/rc.d/NETWORKING
  D /etc/rc.d/newsyslog
  D /etc/rc.d/nfscbd
  D /etc/rc.d/nfsclient
  D /etc/rc.d/nfsd
  D /etc/rc.d/nfsuserd
  D /etc/rc.d/nisdomain
  D /etc/rc.d/nscd
  D /etc/rc.d/nsswitch
  D /etc/rc.d/ntpd
  D /etc/rc.d/ntpdate
  D /etc/rc.d/opensm
  D /etc/rc.d/os-release
  D /etc/rc.d/othermta
  D /etc/rc.d/pf
  D /etc/rc.d/pflog
  D /etc/rc.d/pfsync
  D /etc/rc.d/power_profile
  D /etc/rc.d/powerd
  D /etc/rc.d/ppp
  D /etc/rc.d/pppoed
  D /etc/rc.d/pwcheck
  D /etc/rc.d/quota
  D /etc/rc.d/random
  D /etc/rc.d/rarpd
  D /etc/rc.d/rctl
  D /etc/rc.d/resolv
  D /etc/rc.d/rfcomm_pppd_server
  D /etc/rc.d/root
  D /etc/rc.d/route6d
  D /etc/rc.d/routed
  D /etc/rc.d/routing
  D /etc/rc.d/rpcbind
  D /etc/rc.d/rtadvd
  D /etc/rc.d/rtsold
  D /etc/rc.d/rwho
  D /etc/rc.d/savecore
  D /etc/rc.d/sdpd
  D /etc/rc.d/securelevel
  D /etc/rc.d/sendmail
  D /etc/rc.d/serial
  D /etc/rc.d/SERVERS
  D /etc/rc.d/sppp
  D /etc/rc.d/sshd
  D /etc/rc.d/statd
  D /etc/rc.d/static_arp
  D /etc/rc.d/static_ndp
  D /etc/rc.d/stf
  D /etc/rc.d/swap
  D /etc/rc.d/swaplate
  D /etc/rc.d/syscons
  D /etc/rc.d/sysctl
  D /etc/rc.d/syslogd
  D /etc/rc.d/sysvipc
  D /etc/rc.d/timed
  D /etc/rc.d/tmp
  D /etc/rc.d/ubthidhci
  D /etc/rc.d/ugidfw
  D /etc/rc.d/utx
  D /etc/rc.d/var
  D /etc/rc.d/virecover
  D /etc/rc.d/watchdogd
  D /etc/rc.d/wpa_supplicant
  D /etc/rc.d/ypbind
  D /etc/rc.d/ypldap
  D /etc/rc.d/yppasswdd
  D /etc/rc.d/ypserv
  D /etc/rc.d/ypset
  D /etc/rc.d/ypupdated
  D /etc/rc.d/ypxfrd
  D /etc/rc.d/zfs
  D /etc/rc.d/zfsbe
  D /etc/rc.d/zfsd
  D /etc/rc.d/zvol
  D /etc/rc.firewall
  D /etc/rc.initdiskless
  D /etc/rc.resume
  D /etc/rc.sendmail
  D /etc/rc.shutdown
  D /etc/rc.subr
  D /etc/rc.suspend
  D /etc/regdomain.xml
  D /etc/remote
  D /etc/rmt
  D /etc/rpc
  D /etc/security/audit_class
  D /etc/security/audit_control
  D /etc/security/audit_event
  D /etc/security/audit_user
  D /etc/security/audit_warn
  D /etc/services
  D /etc/shells
  D /etc/snmpd.config
  D /etc/ssh/moduli
  D /etc/ssh/ssh_config
  D /etc/ssh/sshd_config
  D /etc/ssl/blacklisted/128805a3.0
  D /etc/ssl/blacklisted/157753a5.0
  D /etc/ssl/blacklisted/4d4ba017.0
  D /etc/ssl/blacklisted/5c44d531.0
  D /etc/ssl/blacklisted/62744ee1.0
  D /etc/ssl/blacklisted/6410666e.0
  D /etc/ssl/blacklisted/861a399d.0
  D /etc/ssl/blacklisted/c0ff1f52.0
  D /etc/ssl/blacklisted/def36a68.0
  D /etc/ssl/certs/02265526.0
  D /etc/ssl/certs/03179a64.0
  D /etc/ssl/certs/062cdee6.0
  D /etc/ssl/certs/064e0aa9.0
  D /etc/ssl/certs/06dc52d5.0
  D /etc/ssl/certs/09789157.0
  D /etc/ssl/certs/0a775a30.0
  D /etc/ssl/certs/0b1b94ef.0
  D /etc/ssl/certs/0bf05006.0
  D /etc/ssl/certs/0f5dc4f3.0
  D /etc/ssl/certs/0f6fa695.0
  D /etc/ssl/certs/1001acf7.0
  D /etc/ssl/certs/106f3e4d.0
  D /etc/ssl/certs/14bc7599.0
  D /etc/ssl/certs/1636090b.0
  D /etc/ssl/certs/18856ac4.0
  D /etc/ssl/certs/1d3472b9.0
  D /etc/ssl/certs/1e08bfd1.0
  D /etc/ssl/certs/1e09d511.0
  D /etc/ssl/certs/244b5494.0
  D /etc/ssl/certs/2923b3f9.0
  D /etc/ssl/certs/2ae6433e.0
  D /etc/ssl/certs/2b349938.0
  D /etc/ssl/certs/2e5ac55d.0
  D /etc/ssl/certs/32888f65.0
  D /etc/ssl/certs/3513523f.0
  D /etc/ssl/certs/3bde41ac.0
  D /etc/ssl/certs/3e44d2f7.0
  D /etc/ssl/certs/3e45d192.0
  D /etc/ssl/certs/40193066.0
  D /etc/ssl/certs/4042bcee.0
  D /etc/ssl/certs/40547a79.0
  D /etc/ssl/certs/406c9bb1.0
  D /etc/ssl/certs/4304c5e5.0
  D /etc/ssl/certs/48bec511.0
  D /etc/ssl/certs/4a6481c9.0
  D /etc/ssl/certs/4b718d9b.0
  D /etc/ssl/certs/4bfab552.0
  D /etc/ssl/certs/4f316efb.0
  D /etc/ssl/certs/5273a94c.0
  D /etc/ssl/certs/5443e9e3.0
  D /etc/ssl/certs/54657681.0
  D /etc/ssl/certs/57bcb2da.0
  D /etc/ssl/certs/5ad8a5d6.0
  D /etc/ssl/certs/5cd81ad7.0
  D /etc/ssl/certs/5d3033c5.0
  D /etc/ssl/certs/5e98733a.0
  D /etc/ssl/certs/5f15c80c.0
  D /etc/ssl/certs/5f618aec.0
  D /etc/ssl/certs/607986c7.0
  D /etc/ssl/certs/626dceaf.0
  D /etc/ssl/certs/653b494a.0
  D /etc/ssl/certs/68dd7389.0
  D /etc/ssl/certs/6b99d060.0
  D /etc/ssl/certs/6d41d539.0
  D /etc/ssl/certs/6fa5da56.0
  D /etc/ssl/certs/706f604c.0
  D /etc/ssl/certs/749e9e03.0
  D /etc/ssl/certs/75d1b2ed.0
  D /etc/ssl/certs/76cb8f92.0
  D /etc/ssl/certs/76faf6c0.0
  D /etc/ssl/certs/7719f463.0
  D /etc/ssl/certs/773e07ad.0
  D /etc/ssl/certs/7aaf71c0.0
  D /etc/ssl/certs/7f3d5d1d.0
  D /etc/ssl/certs/8160b96c.0
  D /etc/ssl/certs/8cb5ee0f.0
  D /etc/ssl/certs/8d86cdd1.0
  D /etc/ssl/certs/8d89cda1.0
  D /etc/ssl/certs/930ac5d2.0
  D /etc/ssl/certs/93bc0acc.0
  D /etc/ssl/certs/988a38cb.0
  D /etc/ssl/certs/9b5697b0.0
  D /etc/ssl/certs/9c8dfbd4.0
  D /etc/ssl/certs/9d04f354.0
  D /etc/ssl/certs/a3418fda.0
  D /etc/ssl/certs/a94d09e5.0
  D /etc/ssl/certs/aee5f10d.0
  D /etc/ssl/certs/b0e59380.0
  D /etc/ssl/certs/b1159c4c.0
  D /etc/ssl/certs/b66938e9.0
  D /etc/ssl/certs/b727005e.0
  D /etc/ssl/certs/b7a5b843.0
  D /etc/ssl/certs/bf53fb88.0
  D /etc/ssl/certs/c01eb047.0
  D /etc/ssl/certs/c28a8a30.0
  D /etc/ssl/certs/ca6e4ad9.0
  D /etc/ssl/certs/cbf06781.0
  D /etc/ssl/certs/cc450945.0
  D /etc/ssl/certs/cd58d51e.0
  D /etc/ssl/certs/cd8c0d63.0
  D /etc/ssl/certs/ce5e74ef.0
  D /etc/ssl/certs/d4dae3dd.0
  D /etc/ssl/certs/d6325660.0
  D /etc/ssl/certs/d7e8dc79.0
  D /etc/ssl/certs/d887a5bb.0
  D /etc/ssl/certs/dc4d6a89.0
  D /etc/ssl/certs/dd8e9d41.0
  D /etc/ssl/certs/de6d66f3.0
  D /etc/ssl/certs/e113c810.0
  D /etc/ssl/certs/e18bfb83.0
  D /etc/ssl/certs/e36a6752.0
  D /etc/ssl/certs/e73d606e.0
  D /etc/ssl/certs/e868b802.0
  D /etc/ssl/certs/e8de2f56.0
  D /etc/ssl/certs/ee64a828.0
  D /etc/ssl/certs/eed8c118.0
  D /etc/ssl/certs/ef954a4e.0
  D /etc/ssl/certs/f081611a.0
  D /etc/ssl/certs/f0c70a8d.0
  D /etc/ssl/certs/f249de83.0
  D /etc/ssl/certs/f30dd6ad.0
  D /etc/ssl/certs/f3377b1b.0
  D /etc/ssl/certs/f387163d.0
  D /etc/ssl/certs/f39fc864.0
  D /etc/ssl/certs/f51bb24c.0
  D /etc/ssl/certs/fc5a8f99.0
  D /etc/ssl/certs/fe8a2cd8.0
  D /etc/ssl/certs/ff34af3f.0
  D /etc/ssl/openssl.cnf
  D /etc/sysctl.conf
  D /etc/syslog.conf
  D /etc/syslog.d/ftp.conf
  D /etc/syslog.d/lpr.conf
  D /etc/syslog.d/ppp.conf
  D /etc/termcap
  D /etc/termcap.small
  D /etc/ttys
  D /etc/zfs
  D /etc/X11
  D /etc/syslog.d
  D /etc/ssh
  D /etc/security
  D /etc/rc.d
  D /etc/rc.conf.d
  D /etc/pkg
  D /etc/periodic/weekly
  D /etc/periodic/security
  D /etc/periodic/monthly
  D /etc/periodic/daily
  D /etc/periodic
  D /etc/pam.d
  D /etc/ntp
  D /etc/newsyslog.conf.d
  D /etc/mtree
  D /etc/gss
  D /etc/dma
  D /etc/devd
  D /etc/defaults
  D /etc/cron.d
  D /etc/bluetooth
  D /etc/autofs
Warnings:
  Modified regular file remains: /COPYRIGHT
  Modified regular file remains: /etc/group
  Modified regular file remains: /etc/mail/aliases
  Modified regular file remains: /etc/master.passwd
  Modified regular file remains: /etc/motd
  Modified regular file remains: /etc/passwd
  Non-empty directory remains: /etc/ssl/certs
  Non-empty directory remains: /etc/ssl/blacklisted
  Non-empty directory remains: /etc/ssl
  Non-empty directory remains: /etc/mail
  Non-empty directory remains: /etc
  Needs update: /etc/localtime (required manual update via tzsetup(8))
etcupdate: update successfull, bootstrap for: 13.0
root@localhost:/usr/home/user # 
`

**Comment by olevole** [comment]
Did you make a bootstrap for 12.2 and 13.0 bases as `cbsd etcupdate --help` script says? `etcupdate` is 3-way merge, so we need bootstrap (once) for each base version, e.g.:

```
% cbsd bases
PLATFORM  NAME  BASENAME  ARCH   TARGETARCH  VER   STABLE  ELF      STATUS  DATE
FreeBSD   base  -         amd64  amd64       14.0  0       1400044  0       2021-12-12  11:33:04
```

`cbsd repo action=get sources=base ver=12.2`
`cbsd repo action=get sources=base ver=13.0`

// on my host  I already did bootstrap earlier, so I will delete it first:
// rm -f /usr/jails/src/src_12.2/etcupdate/etcupdate.tgz
// rm -rf /usr/jails/src/src_12.2/etcupdate/current

// bootstrap for 12.2:
`cbsd etcupdate mode=extract default_obtain_etcupdate_method=index ver=12.2`
`cbsd etcupdate mode=build default_obtain_etcupdate_method=index ver=12.2`

// same for 13.0 base:
// on my host  I already did bootstrap earlier, so I will delete it first:
// rm -f /usr/jails/src/src_13.0/etcupdate/etcupdate.tgz 
// rm -rf /usr/jails/src/src_13.0/etcupdate/current

// bootstrap for 13.0:
`cbsd etcupdate mode=extract default_obtain_etcupdate_method=index ver=12.2`
`cbsd etcupdate mode=build default_obtain_etcupdate_method=index ver=12.2`

`cbsd jcreate jname=jail4 ip4_addr=DHCP ver=12.2`
`cbsd jstart jail4`   ( **in your example, jail4 never save 12.2 index, because you don't run it**, CBSD copy etcupdate index to /usr/jails/jails-system/jail4/etcupdate )
`cbsd jstop jail4`
`cbsd jset jname=jail4 ver=13.0`
`cbsd jstart jail4`


// **Also you can view diff before `cbsd etcupdate` do something:**
`cbsd etcupdate jname=jail4 mode=diff from=12.2 to=13.0`

// and apply:
`cbsd etcupdate jname=jail4 mode=diff from=12.2 to=13.0`

However, I see another error/bug. This does not lead to such destructive actions as you described. 
Please keep this issue open.

**Comment by GitHubinat0r** [comment]
I've been more careful in backing up my jails and I followed your above steps and the diff shows about 5-8 files that will be updated which looks sane and as soon as I set the mode=update, it blasts all the etc files like I noted before. It could very well be my issue, but I don't understand why the diff isn't aligning with the subsequent update.

Edit: It is also worth noting that I followed your above steps for a *new* jail as well and the etc update worked as expected. The existing jails however all had their etc files deleted.

**Comment by olevole** [comment]
hint: cbsd created backup ( If you did not turn it off via etcupdate.conf: https://github.com/cbsd/cbsd/blob/develop/etc/defaults/etcupdate.conf ) in ~cbsd/jails-system/jail4/etcupdate/backup/

As for removal: needs an investigation, WIP... thanks for report.

**Comment by GitHubinat0r** [comment]
Understood. I used the ZFS jsnapshot and I was able to recover following. (I wasn't 100% sure how to work with the etc backups that were generating.) I'm 90% certain the underlying state issue is tied to something I screwed up, but this is a good edge case to work with.

I'll leave the remainder of my jails on 12.2 for now. Hopefully, if you get time to develop a fix I'll be able to test.

**Comment by madisonblue** [comment]
hey! same thing happened to me. after doing `cbsd etcupdate jname=xxx mode=update from=12.2 to=12.3` most of the files in /etc/ are gone. I've been doing upgrades like this since 10.x and it never happened before. on the servers where I'm experiencing this issue I've upgraded CBSD multiple time via pkg upgrade(probably since FreeBSD 12.1 - running `cbsd initenv` afterwards). I can't replicate this issue on a fresh FreeBSD and CBSD installation.  

Thanks very much!

**Comment by GitHubinat0r** [comment]
I'm taking time to upgrade all of my jails as I get time. Another clue is that on a different system, I had the same issue. I looked at the ~cbsd/jails-system/jail4/etcupdate/backup/ directory and the backup directory was empty! There was an empty subfolder and the zipped file was obviously also empty.

I'm just going to nuke the jails and start over.

**Comment by olevole** [comment]
notes for myself:

1) distribute etcupdate indexes via https:// + CBSD CI/CD infra/mirror ?
2) control check point (e.g. have a small list of permanent files to check)
3) unit test https://github.com/cbsd/cbsd/tree/develop/tests

**Comment by olevole** [comment]
most likely the root of the problem is found - incorrect index files in /usr/local/cbsd/share/etcupdate_**XX**.txt.xz, a fix is planned for this week with CBSD **13.0.24.**

**Comment by olevole** [comment]
notes: also not affected when etcupdate files build from the sources ( default_obtain_etcupdate_method=build) instead of index files, e.g.:
```
cbsd etcupdate mode=extract ver=XX.Y default_obtain_etcupdate_method=build
```

But default_obtain_etcupdate_method=index is default, since 'build' requires full /usr/src for ver=XX.Y.

**Comment by olevole** [comment]
@GitHubinat0r unfortunately, backup also works by indexes and should copy only known for etcupdate files.For this reason, your directory is empty - the index file was not formed correctly.

@GitHubinat0r @madisonblue Thanks a lot for the report. Please re-open Issue if the problem persists after updating to CBSD 13.0.24 ( after some testing will be sent to the ports )

**Comment by madisonblue** [comment]
Thanks very much for your help!

**Comment by GitHubinat0r** [comment]
I'll keep an eye out for that release when I upgrade my last few stragglers. Thanks for your work on this project; it's greatly appreciated! :-)
