### ISSUE TITLE
unexpected operator error in jconstruct-tui

### ISSUE THREAD

**Issue by serpent7776** [cbsd/cbsd#678]
I run cbsd, typed `jconstruct-tui`, selected `C pkglist` and when I pressed enter I got repeated error:

[: 62: unexpected operator
[: 62: unexpected operator
[: 62: unexpected operator

I had to `pkill -9 cbsd` to end cbsd script.

The same happens when executing `cbsd jconstruct-tui` directly.

I can see some errors in syslog:
kernel: pid 3034 (tr), jid 0, uid 0: exited on signal 3
kernel: pid 3579 (conv2human), jid 0, uid 0: exited on signal 3
kernel: pid 3580 (tr), jid 0, uid 0: exited on signal 3

FreeBSD version ( uname -a ): 
FreeBSD DaemONX 12.3-RELEASE-p1 FreeBSD 12.3-RELEASE-p1 GENERIC  amd64

CBSD version ( cbsd version ): 
13.0.24

**Comment by olevole** [comment]
I agree, behavior is not very good.

I fixed the script a bit via https://github.com/cbsd/cbsd/commit/194db8eee39cbfb8bacc2aaeb431e65fd93fae7f , can you test the changes?

To apply changes:

1) remove old script:
`rm -f /usr/local/cbsd/tools/pkgbrowser`

2) fetch updated scripts from Github and restore executable:
```
fetch -o /usr/local/cbsd/tools/pkgbrowser https://raw.githubusercontent.com/cbsd/cbsd/develop/tools/pkgbrowser
chmod +x /usr/local/cbsd/tools/pkgbrowser
```

Try **jconstruct-tui** -> **pkglist** again.

Please re-open if the problem remains, thanks.

**Comment by serpent7776** [comment]
It does work without the issue with the fix.
Thanks for the lightning fast fix.
