### ISSUE TITLE
bad number error when assigning ipv4 using DHCP

### ISSUE THREAD

**Issue by serpent7776** [cbsd/cbsd#685]
I can see some errors when assigning ip address with DHCP for a jail

- execute `cbsd jconfig`
- select a jail
- select `ip4_addr`
- input `DHCP` into input box and accept
- ip is assigned correctly, but I can see unexpected output in the terminal:
```
[: 62 239: bad number
[: 62 239: bad number
[: 62 239: bad number
```

FreeBSD version ( uname -a ): 
FreeBSD DaemONX 12.3-RELEASE-p1 FreeBSD 12.3-RELEASE-p1 GENERIC  amd64

CBSD version ( cbsd version ): 
13.0.24

**Comment by olevole** [comment]
notes for myself: https://github.com/cbsd/cbsd/issues/678 related ? / (some changes in the bsdconfig dialog? check **f_dialog_max_size** function in /usr/share/bsdconfig/dialog.subr )

**Comment by olevole** [comment]
@serpent7776 Unfortunately, this time I can not reproduce. You see an error during the 'Probing for <IP> availability. Please wait...'  message ?

**Comment by serpent7776** [comment]
I don't see "Probing for availability. Please wait..." message. when I hit enter in ipv4 box, it briefly goes to terminal where I can see `[: 62 239: bad number` printed three times and then it goes back to jail configuration dialog.
It's entirely possible that I messed something up, I'm very inexperienced with jails.
Here's my jail config obtained with `jget`, maybe there's something misconfigured there https://gist.github.com/serpent7776/a5827a1aaa4cb839082bf339a2e48c2e
Also I'm not sure it's ok that jail gets assigned ip `10.0.0.1`

**Comment by olevole** [comment]
> Also I'm not sure it's ok that jail gets assigned ip `10.0.0.1`

CBSD assign IP from `nodeippool` range. Type `cbsd initenv-tui` to change default jail/VM network instead of 10.0.0.0/24 via `nodeippool`

**Comment by serpent7776** [comment]
`62 239` is my terminal size as returned by both `dialog --print-maxsize` and `stty size`. For some reason `f_dialog_max_size` doesn't set correct size in this case. 
`local __height` is set to `62 239` for some reason here: https://github.com/freebsd/freebsd-src/blob/releng/12.3/usr.sbin/bsdconfig/share/dialog.subr#L321
When I try this command locally in `/bin/sh` it works correctly:
```
$ s=$(stty size)
$ echo ${s%%[$IFS]*}
62
```
When I try to print `$IFS` inside `f_dialog_max_size` it looks like a space.
No idea, `$IFS` gets set to something weird?
When I tried to force set `IFS=" "` just before setting `local __height` it broke dialog
```
eval: interface: not found
eval: arch: not found
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
eval: childrenmax: not found
[...]
```

**Comment by serpent7776** [comment]
Actually, `IFS` is set here https://github.com/cbsd/cbsd/blob/5726adb3c24a07b1661dc11d28fa54f3358c82ee/subr/settings-tui.subr#L208
When I set `IFS=" "` before the `case "${_i}"` and set it back to `IFS=","` after matching `esac` the error goes away.

**Comment by olevole** [comment]
Wow, if only all reports were like this! ;)

It seems you are right.

Can you try the latest fixes from git ?, e.g:

```
rm -f /usr/local/cbsd/subr/settings-tui.subr
fetch -o /usr/local/cbsd/subr/settings-tui.subr https://raw.githubusercontent.com/cbsd/cbsd/develop/subr/settings-tui.subr
```

**Comment by serpent7776** [comment]
It works fine. Your "notes for myself" comment help a lot, I wasn't even aware of `/usr/share/bsdconfig` stuff.

Shouldn't `OIFS` be `local` in `get_construct_ip4_addr()`?

**Comment by olevole** [comment]
Thanks!
