### ISSUE TITLE
imgtype - raw -Can't enter device

### ISSUE THREAD

**Issue by jas-s2r** [cbsd/cbsd#686]
Mandatory info for bug reports:

CBSD won't allow to enter the device to be used as disk.

FreeBSD version ( uname -a ): 
13.0-RELEASE-p6 FreeBSD 13.0-RELEASE-p6 #0: Mon Jan 10 06:28:50 UTC 2022

CBSD version ( cbsd version ): 
13.0.24

![disk_type_raw](https://user-images.githubusercontent.com/78652502/157064240-cb37997d-0a59-46a7-93c2-683151d7bfd8.jpg)

**Comment by olevole** [comment]
Fixed.

raw disk support added in development/git version.

Will be available in 13.0.25-RELEASE.

see `cbsd bhyve-dsk --help` or via `cbsd jconstruct-tui' for new VM.
