### ISSUE TITLE
Connect problems with jails via ssh

### ISSUE THREAD

**Issue by joneum** [cbsd/cbsd#688]
Hello,
I have a fresh FreeBSD 13.0 system, with p7.
I have installed cbsd from the ports with version 13.0.24

I have taken the default installation with pf.
The jail has a fixed IP address, which I can ping.

With jexec I get into the jail without problems.

If I want to ssh from another computer directly into the jail, I end up on the mainhost.

The same, if I want to ssh from the mainhost into the jail, I land directly on the mainhost again. Like an endless loop.

what could be the reason for this?

Anything else I can help with configs?

**Comment by olevole** [comment]
If you are not using 'vnet=1' (VIMAGE, virtualized stack), the IP address of the jail is just alias on the mainhost. Therefore, as far as I understand, the ssh daemon in mainhost serves all addresses by default.

You can use at least two options. E.g, always use non-default port for mainhost, e.g.: `222`. You can set settings for sshd via **/etc/rc.conf**, via sshd_flags:
```
sshd_flags="-oUseDNS=no -oPort=222"
```
Another options: do not use ANY for bind ( `ListenAddress 0.0.0.0` by default ) and change 0.0.0.0 to IP address of mainhost - in this case, the sshd daemon (in mainhost) will not process connections that refer to the address of the container. E.g, via **/etc/rc.conf**:
```
sshd_flags="-oUseDNS=no -oListenAddress=192.168.0.2" 
```

where 192.168.0.2 - real IP address for your mainhost.

To apply changes:

```
service sshd restart
```

and logout/re-login.

Please reopen Issue if that doesn't help
