### ISSUE TITLE
jexport/jimport and expose

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#689]
FreeBSD version ( uname -a ): 
13.0-RELEASE-p6
CBSD version ( cbsd version ): 
13.0.24

VNET jail rproxy7 exported on one host and imported on another host.
Inbound NAT rules are not adapted for new IP:
```
# cbsd expose
Expose for bderp7:
Expose for consul7:
58500 -> 8500 (via 0 tcp)
Expose for coredns7:
53 -> 53 (via 0 tcp)
53 -> 53 (via 0 udp)
Expose for gle7:
443 -> 443 (via 0 tcp)
80 -> 80 (via 0 tcp)
Expose for mta7:
50025 -> 25 (via 0 tcp)
Expose for rproxy7:
50443 -> 443 (via 172.17.14.10 tcp)
54443 -> 4443 (via 172.17.14.10 tcp)
54343 -> 4343 (via 172.17.14.10 tcp)
50080 -> 80 (via 172.17.14.10 tcp)
```

172.17.14.10 is the IP of _old_ host, where the jail was exported.
Trying to delete the rule:
```
# cbsd expose mode=delete jname=rproxy7 in=50080 out=80
CBSD: Enable IP forwarding for NAT service
pfctl: pf already enabled
port already in use on 172.17.14.10: 50443
port already in use on 172.17.14.10: 54443
port already in use on 172.17.14.10: 54343
CBSD Expose for rproxy7: 50080 -> 80 (tcp)
CBSD: Enable IP forwarding for NAT service
pfctl: pf already enabled
# cbsd expose
Expose for bderp7:
Expose for consul7:
58500 -> 8500 (via 0 tcp)
Expose for coredns7:
53 -> 53 (via 0 tcp)
53 -> 53 (via 0 udp)
Expose for gle7:
443 -> 443 (via 0 tcp)
80 -> 80 (via 0 tcp)
Expose for mta7:
50025 -> 25 (via 0 tcp)
Expose for rproxy7:
50443 -> 443 (via 172.17.14.10 tcp)
54443 -> 4443 (via 172.17.14.10 tcp)
54343 -> 4343 (via 172.17.14.10 tcp)
50080 -> 80 (via 172.17.14.10 tcp)
```

So the NAT rule is not deleted.

I think that inbound NAT rules should be adjusted to the IP of the host where a jail is imported, or they should be removed.

**Comment by Peter2121** [comment]
After some tests - to delete a rule with inaddr defined, one _must_ use inaddr in delete command. In such case the rule is correctly deleted.

**Comment by olevole** [comment]
will be available in 13.1.0-RELEASE.

To test before release:
```
mv /usr/local/cbsd/tools/expose /tmp
fetch -o /usr/local/cbsd/tools/expose https://raw.githubusercontent.com/cbsd/cbsd/develop/tools/expose
chmod +x /usr/local/cbsd/tools/expose
```

PS: the fix will only apply to newly added rules

Thanks

**Comment by Peter2121** [comment]
> the fix will only apply to newly added rules
Sorry, what does it mean?

**Comment by olevole** [comment]
old records IN SQLite3 keep IP address (of nodeip). After fix,  new records saved as '0' (for `inaddr` fields) and always cast to $nodeip upon apply.
