### ISSUE TITLE
[Feature request] Show result of jsnapshot operation

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#690]
It would be nice to see the result of jsnapshot operation, something like 'snapshot created in 0.5 seconds' or 'failed to create a snapshot'. In case of zfs, probably, the exit code of 'zfs snapshot' command can give the necessary information.

**Comment by olevole** [comment]
@Peter2121 Try to fetch&test changes:

```
rm -f /usr/local/cbsd/jailctl/jsnapshot
fetch -o /usr/local/cbsd/jailctl/jsnapshot https://raw.githubusercontent.com/cbsd/cbsd/develop/jailctl/jsnapshot
chmod +x /usr/local/cbsd/jailctl/jsnapshot
```
it's all right?

**Comment by Peter2121** [comment]
Great! Works as expected, thanks!
