### ISSUE TITLE
etcupdate warning - typo

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#693]
FreeBSD version ( uname -a ): 
13.0

CBSD version ( cbsd version ): 
13.0.24

CBSD warning on start a jail with the new version set, but without etc update:
`Warning: you can use etcupdate to sync content: cbsd etcupdate jname=consul2 mode=update from=12.2 to=13.0 mode=diff`

At the end of the line there is `mode=diff` - probably it should not be here.

**Comment by olevole** [comment]
it's not a mistake. You are advised to first look at the result before applying and performing a critical operation
