### ISSUE TITLE
Typo in code appearing when cbsd up

### ISSUE THREAD

**Issue by aeifn** [cbsd/cbsd#694]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 13.0-RELEASE-p7

CBSD version ( cbsd version ): 13.0.24

<img width="516" alt="Screenshot 2022-03-26 at 09 53 20" src="https://user-images.githubusercontent.com/13631515/160228613-8982d4ed-9d92-4990-9bc3-2c8bb2466eec.png">

**Comment by olevole** [comment]
fixed in 13.0.26, due to uninitialized  `ssh_wait` variables: https://github.com/cbsd/cbsd/blob/v13.0.26/subr/up.subr#L625-L626
