### ISSUE TITLE
error while importing an image in bhyve

### ISSUE THREAD

**Issue by benoitc** [cbsd/cbsd#696]
when using bimport I get the following error:

```
/usr/bin/awk: out of memory in readrec 1
 input record number [1523362](tel:1523362), file /home/benoitc/utm-SNS-EVA-4.3.6-kvm.img
 source line number 1
/usr/bin/awk: out of memory in readrec 1
 input record number [1523362](tel:1523362), file /home/benoitc/utm-SNS-EVA-4.3.6-kvm.img
 source line number 1
[: -ge: unexpected operator
```

Mandatory info for bug reports:

FreeBSD version ( uname -a ):

FreeBSD host.mydomain.tld 13.0-RELEASE-p8 FreeBSD 13.0-RELEASE-p8 #0: Tue Mar 15 09:36:28 UTC 2022 [root@amd64-builder.daemonology.net](mailto:root@amd64-builder.daemonology.net):/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64

CBSD version ( cbsd version ): 13.0.24

**Comment by olevole** [comment]
**bimport** (and jimport) for archive/images created by **bexport** (and jexport) only
