### ISSUE TITLE
Show remaining bhyve RAM

### ISSUE THREAD

**Issue by aeifn** [cbsd/cbsd#699]
```
#!/bin/sh
# Show remaining bhyve RAM

TOTAL_BYTES=$(sysctl hw.physmem | awk '{ print $2 }')
TOTAL_MB=$(expr $TOTAL_BYTES / 1024 / 1024)
TOTAL_GB=$(expr $TOTAL_MB / 1024)

USED_MB=$(sudo cbsd bls | sed 1d | grep -v Off | awk '{ print $3 }' | paste -sd+ - | bc)
USED_GB=$(expr $USED_MB / 1024)

REMAINS_MB="$(expr $TOTAL_MB - $USED_MB)"
REMAINS_GB="$(expr $REMAINS_MB / 1024)"

echo "Total: $TOTAL_MB Mb / $TOTAL_GB Gb"
echo "Used: $USED_MB Mb / $USED_GB Gb"
echo "Remains: $REMAINS_MB Mb / $REMAINS_GB Gb"
```

**Comment by olevole** [comment]
Nice stats for `cbsd summary` ?

**Comment by aeifn** [comment]
Answer to the question: "How many more RAM bhyve can consume without overcommitting"

**Comment by olevole** [comment]
I don't think we can introduce (and use) memory overcommit statistics. At least until the bhyve becomes a backend for virtio-baloon. By default (without **wired** options), VM consumes a minimum of memory (on demand), but it never frees its memory. At the moment, the policy of hosters: never create virtual machines that exceed the amount of physical RAM.

Adding warning and check when creating a new virtual machine - it would also be very useful for us

**Comment by aeifn** [comment]
I mean just formal overcommit, not actual - to comply with the _policy_.
`cbsd summary` does not provide sum of memory dedicated to running VMs.
