### ISSUE TITLE
Missing nodeip6pool

### ISSUE THREAD

**Issue by mekanix** [cbsd/cbsd#700]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD hal9000.meka.rs 13.0-RELEASE-p11 FreeBSD 13.0-RELEASE-p11 #0: Tue Apr  5 18:54:35 UTC 2022     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

CBSD version ( cbsd version ): 
13.0.28

When using DHCPv6, either alone or as DHCP,DHCPv6, I get error instead of address `^[[0;35mno nodeip6pool^[[0m`. Do I need to enable something?

**Comment by mekanix** [comment]
OK, this error means I should initenv-tui and set it up. But what is the format for nodeip6pool in that form?

**Comment by olevole** [comment]
Format is same as `nodeippool`: network/prefix  ( use ',' for multiple network ). E.g:

![image](https://user-images.githubusercontent.com/926409/161972869-2edf7f94-b398-48f0-af1e-a9845aeff323.png)

**Comment by olevole** [comment]
When you use IPv6, `nodeip6` and `nodeip6pool` should be initialized. Type:

`cbsd dhcpdv6` to check

**Comment by olevole** [comment]
> I should initenv-tui and set it up

Also available via 'initenv' by config file, e.g. CBSD puppet module: https://github.com/cbsd/puppet-cbsd/blob/master/manifests/initenv.pp

where initenv template: https://github.com/cbsd/puppet-cbsd/blob/master/templates/initenv.conf.erb

So my CBSD env can be described in yaml via Puppet:

```
cbsd::nodeip: "%{::networking.ip4}"
cbsd::nodeip6: "%{::networking.ip6}"
cbsd::nodeippool: "10.0.0.0/16"
cbsd::nodeip6pool: "2a01:4f8:261:2b85::/64"
cbsd::freebsd_bases::ver: [ 'native' ]

cbsd::jail:
  'cbsdpuppet1':
    pkg_bootstrap: '1'
    jprofile: 'cbsdpuppet'
    astart: '0'
    status: 'stopped'
    ver: 'native'
    ip4_addr: '0'
...
```

**Comment by mekanix** [comment]
Perfect, thank you! Do you want us to update the docs before closing this ticket, as I couldn't find example for nodeip6pool, I'm sure it would benefit others to have an example.

**Comment by olevole** [comment]
Depends on where to update ;-)
For now, we need to freeze the main (www.bsdstore.ru) site. Let's update cbsd.io ;-)

With next CBSD release i will change WWW to https://cbsd.io
