### ISSUE TITLE
VM profile question

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#702]
I have a question regarding the VM profile when creating a new bhyve VM. I'm not sure whether maybe I'm just simply not understanding this properly.

Basically I found myself in the need to create a FreeBSD 14.0 i386 VM. As I'm used to I fired up `cbsd bconstruct-tui`. However, the dialog appears to force me to select a profile from the existing profiles list. But none of the existing profiles made sense. While there is a profile for FreeBSD 14.0 that one appears to be specific to `amd64`.

Why exactly am I not allowed to create a VM without selecting a profile? I just want a bare, basic VM where set a name, disk size, RAM size, CPU count and then boot from an ISO. Is creating a profile a technical necessity? If so, why?

**Comment by olevole** [comment]
A profile is just pre-configured (sometimes - specific to a particular OS) settings. 

The concept of profiles is also good because it describes the registration and naming of VM/images.

However, the CBSD has rich customization possibilities: you can create your own profiles (or even overwrite official profiles!) if you create a profile file in the directory **~/cbsd/etc/** directory ( do not confuse with **~cbsd/etc/defaults/** ), for example your steps to get what you want:

1)
```
cat > ~cbsd/etc/vm-freebsd-FreeBSD-i386-14.0-LATEST.conf <<EOF
vm_profile="FreeBSD-i386-14.0-LATEST"
vm_os_type="freebsd"
long_description="FreeBSD 14.0 i386 CURRENT/HEAD"
fetch=1
iso_site="https://download.freebsd.org/snapshots/i386/i386/ISO-IMAGES/14.0/"
iso_img="FreeBSD-14.0-CURRENT-i386-20220317-4f75af31a86-253814-disc1.iso"
iso_img_dist="FreeBSD-14.0-CURRENT-i386-20220317-4f75af31a86-253814-disc1.iso.xz"
iso_extract="nice -n 19 idprio 29 xz -d ${iso_img_dist}"
register_iso_name="cbsd-iso-${iso_img}"
register_iso_as="iso-FreeBSD-i386-14.0-CURRENT-amd64-disc1"
default_jailname="freebsd"
xen_active=1
bhyve_active=1
qemu_active=1
vm_vnc_port="0"
vm_efi="uefi"
vm_package="small1"
sha256sum="0"
virtio_rnd="1"
EOF
```

2) `cbsd bcreate jname=f32 vm_os_type="freebsd" vm_os_profile="FreeBSD-i386-14.0-LATEST" cpus=1 vm_ram=1g imgsize=2g runasap=1`


If you want an empty profile - just expand CBSD. You can use Ansible/Puppet/Chef/Salt/..  to create a profile file like this: ~cbsd/etc/vm-other-empty.conf:
```
vm_profile="empty"
vm_os_type="other"
bhyve_active=1
```

**Comment by Tectu** [comment]
Thank you for your reply - I understand!

Is there a way to keep custom profiles at some different location (eg. in my user's home directory) and have CBSD look for them? Or explicitly telling CBSD to find more profiles at a specific location?

**Comment by olevole** [comment]
Сurrently only these paths are used for lookup profiles (vm-XXX-.conf)  (in the appropriate order):
```
~cbsd/etc/defaults/
~cbsd/etc/
```

Perhaps adding a custom path later makes sense.

But it seems to me that a regular Unix symbolic link is a good option? E.g., manage your own profiles in **/root/etc/** directory and create symlink to?

```
ln -sf /root/etc/vm-other-empty.conf ~cbsd/etc/vm-other-empty.conf
ln -sf /root/etc/vm-freebsd-FreeBSD-i386-14.0-LATEST.conf  ~cbsd/etc/vm-freebsd-FreeBSD-i386-14.0-LATEST.conf
```

**Comment by Tectu** [comment]
Would the profile look-up by any chance be recursive so that I could at least symlink an entire directory?

**Comment by olevole** [comment]
No,its per file solution.

Well, that makes sense ( configure additional custom directory to lookup profiles) - I keep forgetting that some people don't use Ansible/Puppet/Chef/Salt/.. ;-)


Can you create new feature request with the right wording?

**Comment by Tectu** [comment]
>Can you create new feature request with the right wording?

Gladly! -> #703 

> I keep forgetting that some people don't use Ansible/Puppet/Chef/Salt/.. ;-)

I don't only  use CBSD for "server" purposes. I'm a developer. Part of my activities are developing C/C++ libraries. I use CBSD on all my desktops as I need a lot of different platforms and environments to test on. Sometimes, when a user of a library reports an issue, I quickly spin up a VM via CBSD to reproduce the environment reported by the user.
Maybe this helps to understand some use cases which you would consider "unusual".
It's not my fault that CBSD works so god damn well! :p

**Comment by olevole** [comment]
@Tectu Thx! In fact, I am very happy when users describe use cases and what they need. Discussions like this provide a broader view, and this kind of information has a significant impact on flexibility. And this is a way to improve the project as a whole.

ps:  I use CBSD mostly in a similar job (a lot of R&D+QA that requires different OSes). However, all my custom images are **cloud images** (e.g. image with Gitlab runner, RabbitMQ cluster, Kubernetes cluster ..), not ISOs ;) Also, a high startup speed is an excellent base for building scalling FaaS/SaaS platform.

**Comment by Tectu** [comment]
> Discussions like this provide a broader view, and this kind of information has a significant impact on flexibility.

That is very much like-wise.
For example, I have actually never looked into the "cloud images" aspect of CBSD. Everything that contains the term "cloud" immediately makes me go "ewh".
I like to run stuff on my own infrastructure whenever possible. But maybe I should have a look at this as the R&D+QA aspect you're talking about very much applies to my end too.

**Comment by olevole** [comment]
Wait.. You have been using CBSD for several years and have not tried cloud images ;-/ ? This is one of the strengths of CBSD/bhyve.

I have a similar relationship with the 'cloud' word: this is a synonym for the 'pain' for me ;-) And I'm waiting for a new era - 'cloudless technologies' era. Sounds like 'painless', 'technology without pain'. But in CBSD, cloud images are images that use the https://www.freshports.org/net/cloud-init/ package to skip the long and manual "installation" steps.

E.g.: 
```
cbsd bcreate jname=c1 vm_ram=4g vm_cpus=2 vm_os_type=freebsd vm_os_profile=cloud-FreeBSD-ufs-x64-13.0 imgsize=20g ci_ip4_addr=10.0.1.88 ci_gw4=10.0.1.3
```

where 10.0.1.88 and 10.0.1.3 - valid IP for VM and a working gateway for this network

When you see the 'pings', you can use your virtual machine (e.g: `cbsd blogin`). Also ZFS/COW allows you to keep only one copy of 'gold' image in ZFS volume. All subsequent launches/bcreate will take place instantly.

CLI and TUI is nice bonus for 'user-friendly' interface, but I highly recommend using CBSDfiles ( https://github.com/cbsd/cbsd/tree/develop/share/examples/cbsdfile or https://github.com/cbsd/cbsdfile-recipes/tree/master/jail as examples ). 

And almost all my environments look the same, like this:
```
bhyve_debbuilder1()
{
        vm_ram="4g"
        vm_cpus="2"
        imgsize="30g"
        vm_os_type="linux"
        vm_os_profile="cloud-ubuntuserver-amd64-20.04"

        ip4_addr="10.0.100.143"
        ip4_gw="10.0.100.1"
        ci_jname="${jname}"
        ci_fqdn="${fqdn}"
        ci_ip4_addr="${ip4_addr}"
        ci_gw4="${ip4_gw}"
        imgtype="zvol"
        runasap=1
        ssh_wait=1
}

postcreate_debbuilder1()
{
        bscp prepare.sh ${jname}:prepare.sh
        # puppet ssl
        bscp puppetlabs.tgz ${jname}:puppetlabs.tgz
        bexec jname=${jname} sudo /home/ubuntu/prepare.sh
}
```

When I need for 'deb' package builder service as VM, I do:
```
cd /root/upfiles/bhyve/debbuilder
cbsd up
```

after VM starts, it registered in my Puppetserver where do i manage the virtual machine.

Some users do the same with ansible:
```
bhyve_centos9-001()
{
        vm_ram="4g"
        vm_cpus="2"
        imgsize="6g"
        vm_os_type="linux"
        vm_os_profile="cloud-CentOS-stream-9-x86_64"

        ip4_addr="10.0.100.101"
        ip4_gw="10.0.100.1"
        ci_jname="${jname}"
        ci_fqdn="${jname}.${domain}"
        ci_ip4_addr="${ip4_addr}"
        ci_gw4="${ip4_gw}"
        imgtype="md"
        runasap=1
        ssh_wait=1
}

postcreate_centos9-001()
{
       bscp /storage/cbsd/environments/first_cluster/add_ansible.sh ${jname}:add_ansible.sh
       bexec << EOF
sudo chmod 755 add_ansible.sh
sudo ./add_ansible.sh
EOF
}
```


But even without 'postcreate_' function for config management ( or executing of remote command via 'cbsd bexec` ), you really can save your time:
```
cbsd up
cbsd blogin   (when VMs ready, for ssd it is usually 10-30 seconds maximum )
```

If you need to run different VMs frequently, this will make your life much better.

![image](https://user-images.githubusercontent.com/926409/162643301-ab7ed22f-00b6-4eed-868c-1887d54a061d.png)

**Comment by Tectu** [comment]
> Wait.. You have been using CBSD for several years and have not tried cloud images ;-/ ? 

Yes, I'm that idiot :D

What you're showing me here is pretty intriguing and I should indeed have looked at this earlier.
However, I'm currently still not sure where the "cloud" aspect comes in. Is this (in your/my case) purely related to the `cloud-init` technology? i.e. I can use this also locally?

One of the (many) things on my CBSD related ToDo list is figuring out how to spin up VMs from my desktop on private servers (physically on-premise - not cloud instances).
Based on what I read above it seems like this could work out with a lot less efforts than I might have expected?
I know that CBSD is able to do migrations from one node to another. But I think that is not necessarily covering my use-case here. What I'd really like is to have one or more CBSD servers on-premise and use my desktops as pure clients. i.e. the same way that you can spin up VMs on popular cloud hosting providers via API I'd like to be able to use my laptop to instruct our CBSD server(s) that I need an Ubuntu 21.04 VM with X amount of resources and then just connect to it.
Am I right to assume that what you're showing above is pretty much that?

I'm especially intrigued by the notion of just doing `cbsd blogin` on my desktop to "connect" to a VM on our CBSD server(s). Is it possible to configure this in a way that when I connect to a Windows VM it fires up an RDP client, if I connect to a Linux "desktop" VM it fires up VNC, if I connect to a head-less FreeBSD VM it uses SSH etc?

The way I'm currently handling this is by manually spawning an SSH tunnel from my desktop to the CBSD server(s), log into the CBSD server and then utilize `cbsd jlogin` to log into jails or directly using a VNC client via that SSH tunnel to connect to a VM.
I know this is not ideal - but I expected this to be much harder to achieve than what you're suggesting above.

**Comment by olevole** [comment]
Ignorance is strength)

Cloud images  it's just a pre-formed image ( like official FreeBSD image https://download.freebsd.org/releases/VM-IMAGES/13.0-RELEASE/amd64/Latest/ ), nothing else.

What you want is achieved in CBSD using cloud images + API: https://www.bsdstore.ru/en/cbsd_api_ssi.html 

^^ An example of a multi-node cluster and a workstation as a thin client. For example, when I create a virtual machine via the API, I never know what host it will be created on. But thanks to the VXLAN/VPC (overlay) network, it is always available to me (and others).

slowly but surely CBSD is moving towards clustering, which is enshrined in the original goals of the project.
