### ISSUE TITLE
Custom profiles directory location

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#703]
This is an official feature request based on the discussion of #702.

It would be awesome if CBSD would provide the ability to specify one or more custom locations for profile lookups. Personally, I'd like to be able to create a directory with custom profile somewhere in my user's home directory and have CBSD parse them as well.

I'm not sure what is the best approach to stay within the CBSD philosophy/design. Personally, I'd really like to have the ability to  register & unregister an arbitrary number of these custom profile directories similar to how the existing `media` command functions.

**Comment by olevole** [comment]
done: [00c1356](https://github.com/cbsd/cbsd/commit/00c1356cd43c0973180b739ca42ab1ca60a0b9fc)

will be available in 13.1.0-RELEASE.

Location can be specified via ~cbsd/etc/bhyve-default-default.conf config file or via `extra_profile_dir=`, e.g.:
```
cbsd show_profile_list search_profile=vm-other show_bhyve=1 extra_profile_dir="/root/cbsd-profiless"
```
