### ISSUE TITLE
Jail import/export question

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#706]
I'm in need to migrate a couple of jails from one host to another. The hosts are not setup to communicate to each other via the CBSD node management.
Instead, I'm looking at `jexport` and `jimport`. However, from the documentation it's not clear to me what exactly is contained in the exported image.

Does the exported image contain the entirety of the jail with CBSD configuration (eg. the stuff one can edit via `jconfig`), network interfaces and all that? If I do a `jexport` on one host, transmit the image and do a `jimport` on another host, will everything be retained, including IP addresses, resource limits etc?

How does this work in regards of additional ZFS datasets mounted in the jail? Will the ZFS datasets (or at least the data itself) also be part of the image or would I migrate the ZFS datasets manually?

**Comment by olevole** [comment]
jexport packs only the data that CBSD knows about. Namely:

~cbsd/jails-data/<env>-data -  this is **rootfs** of the jail - this is the most important part as it is the container's file system itself.
~cbsd/jails-system/<env> - this is CBSD-only/related settings (RACCT, fstabs, traffic stats.

cbsd will not serve external volumes - you need to manage/sync it yourself.

By default, all data from jail `rootfs` is exported. But you can use `jexport_exclude` to list location for exclude (see `cbsd jexport --help` for examples )

**Comment by Tectu** [comment]
Thank you for your quick & precise answer!

May I suggest to update the documentation to reflect this information? I think this would be very handy for others down the road :)

**Comment by olevole** [comment]
Unfortunately, I'm very busy right now and can't improve the documentation: also, as a debt, the transition to the https://cbsd.io domain + MkDocs engine.

But I know that the CBSD documentation needs to be improved in general, and a good book needs to be written ;-) Reality does not allow me to do this yet.
