### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Eresko** [cbsd/cbsd#707]
Mandatory info for bug reports:

FreeBSD govno 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64

[root@ /usr/local/cbsd/tools]# cbsd version
zfs_enable: YES -> YES
13.1.1

[root@ /usr/local/cbsd/tools]# cbsd jstart
zfs_enable: YES -> YES
/usr/jails/ver: 13.1.3a: not found
Warning: CBSD is 13.1.1 while workdir initializated for . Please re-run: env workdir=/usr/jails cbsd initenv
/usr/local/cbsd/subr/sudoexec.subr: -f: not found
No arg for -r option
List of offline jail
/usr/local/cbsd/sudoexec/jstart: -d: not found
/usr/local/cbsd/sudoexec/jstart: +%s: not found
/usr/local/cbsd/sudoexec/jstart: Off$: not found
/usr/jails/ver: 13.1.3a: not found
Warning: CBSD is 13.1.1 while workdir initializated for . Please re-run: env workdir=/usr/jails cbsd initenv
/usr/local/cbsd/subr/cbsdinit.subr: -d: not found
/usr/local/cbsd/subr/cbsdinit.subr: -d: not found
/usr/local/cbsd/subr/cbsdinit.subr: -d: not found
/usr/local/cbsd/subr/cbsdinit.subr: -d: not found
/usr/local/cbsd/jailctl/jls: ,: not found
/usr/local/cbsd/jailctl/jls: [:lower:]: not found
/usr/local/cbsd/jailctl/jls: -t: not found
[: Can't: unexpected operator
exit: -f: not found
/usr/local/cbsd/sudoexec/jstart: -rf: not found
/usr/local/cbsd/sudoexec/jstart: -f: not found
Cancel pressed
[root@ /usr/local/cbsd/tools]# sqlite3 ~cbsd/var/db/local.sqlite "select jname,state_time from jails;"
Error: unable to open database "/usr/jails/var/db/local.sqlite": unable to open database file
[root@ /usr/local/cbsd/tools]# cbsd version
zfs_enable: YES -> YES
13.1.1

**Comment by olevole** [comment]
????

**Comment by Eresko** [comment]
I followed the instructions, but at the same time this, I can not help?

**Comment by Eresko** [comment]
[root@ /usr/local/cbsd/tools]#  env workdir=/usr/jails cbsd initenv
/usr/jails/ver: 13.1.3a: not found
Warning: CBSD is 13.1.1 while workdir initializated for . Please re-run: env workdir=/usr/jails cbsd initenv
/usr/local/cbsd/tools/initenv: -f: not found

**Comment by olevole** [comment]
How did you install the CBSD? There is no such version: `13.1.3a`. 

Checkout https://www.bsdstore.ru/en/installing_cbsd.html

and/or try this:

1) `pkg remove cbsd`
2) `rm -rf /usr/local/cbsd`
3) `pkg update -f`
4) `pkg install -y cbsd`
5) `env workdir=/usr/jails /usr/local/cbsd/sudoexec/initenv`
