### ISSUE TITLE
kernel and user space version mismatch

### ISSUE THREAD

**Issue by 4xoc** [cbsd/cbsd#709]
FreeBSD version ( uname -a ): FreeBSD red-queen.4xoc.com 13.1-RELEASE-p1 FreeBSD 13.1-RELEASE-p1 GENERIC amd64

CBSD version ( cbsd version ): 13.1.3

I'm trying to update some jails to a new version of the base jail but for some reason a few jails don't upgrade properly. Within the jail kernel and user space version are different from the host/basejail. All jails are based of a read-only mount of the base jail. I've already tried to set an older version of the base again and then try upgrading once more without luck. I'm following the docs at https://www.bsdstore.ru/en/13.0.x/wf_jupgrade_ssi.html.

Any idea how the mismatch could come from?

Example:
```
root@red-queen:~ # uname -a
FreeBSD red-queen.4xoc.com 13.1-RELEASE-p1 FreeBSD 13.1-RELEASE-p1 GENERIC amd64
root@red-queen:~ # cbsd jget jname=git |grep ver
ver: 13.1
root@red-queen:~ # cbsd jlogin git
Last login: Mon Aug 29 17:02:10 on pts/0
FreeBSD 13.0-RELEASE-p4 (GENERIC) #0: Tue Aug 24 07:33:27 UTC 2021
git:/root@[18:08] # uname -a
FreeBSD git.4xoc.com 12.2-RELEASE FreeBSD 12.2-RELEASE amd64
```

**Comment by olevole** [comment]
Please remove any 'UNAME*' records from:

/etc/csh.cshrc
/etcmake.conf
/etc/profile

( in jail )
Its old work-around ( see: grep ^20140930 -A19 /usr/ports/CHANGES ) which is no longer needed (and removed from the CBSD). But the old records remain.

**Comment by olevole** [comment]
If that doesn't help, please check/post **baserw** settings ( RO base or RW ):

```
cbsd jls display=jname,ver,baserw
```

**Comment by 4xoc** [comment]
Thanks, removing the UNAME vars solved it for me.
