### ISSUE TITLE
[Request] jls: show only running jails

### ISSUE THREAD

**Issue by lbartoletti** [cbsd/cbsd#712]
Mandatory info for bug reports:

Not a bug, but a feature request:

something like `cbsd jls running=1` My idea, is to display all active and running jails `cbsd jls header=0 display=jname running=1` (or status=1)

FreeBSD version ( uname -a ): 13.1

CBSD version ( cbsd version ): 13.1.15

**Comment by olevole** [comment]
All states are in the SQLite3 DB, so as a hardcore-workaround, you can use a SQL query ;-)

```
 sqlite3 ~cbsd/var/db/local.sqlite "SELECT jname FROM jails WHERE emulator='jail' AND status=1"
 ```
 
 E.g.:
 ```
 cbsd jrestart `sqlite3 ~cbsd/var/db/local.sqlite "SELECT jname FROM jails WHERE emulator='jail' AND status=1"`
 ```

**Comment by lbartoletti** [comment]
yes :)
but an "alias" could be cool :)

**Comment by olevole** [comment]
@lbartoletti Can you test new revision ?
```
mv /usr/local/cbsd/jailctl/jls /tmp/
fetch -o /usr/local/cbsd/jailctl/jls https://raw.githubusercontent.com/cbsd/cbsd/develop/jailctl/jls
chmod +x /usr/local/cbsd/jailctl/jls
```

e.g.:
```
cbsd jls jail1 jail2
cbsd jls ip4_addr=10.0.0.2
cbsd jls astart=1 status=on
```

**Comment by lbartoletti** [comment]
Nice! Thanks!
