### ISSUE TITLE
[Request] jrestart --all

### ISSUE THREAD

**Issue by lbartoletti** [cbsd/cbsd#713]
Mandatory info for bug reports:

Related to https://github.com/cbsd/cbsd/issues/712
Can we have an option to restart all running jails, please?

FreeBSD version ( uname -a ): 13.1

CBSD version ( cbsd version ): 13.1.15

**Comment by lbartoletti** [comment]
Today I run:

`cbsd jls header=0 display=jname,status | awk '/ On/ {print $1}' | xargs cbsd jrestart`

which does not works and returns for each jail:
`no such jail: ...`

**Comment by olevole** [comment]
All states are in the SQLite3 DB, so as a hardcore-workaround, you can use a SQL query ;-)

```
 sqlite3 ~cbsd/var/db/local.sqlite "SELECT jname FROM jails WHERE emulator='jail' AND status=1"
 ```
 
 E.g.:
 ```
 cbsd jrestart `sqlite3 ~cbsd/var/db/local.sqlite "SELECT jname FROM jails WHERE emulator='jail' AND status=1"`
 ```

**Comment by olevole** [comment]
In fact, for most of the command ( like 'jexec', 'jstop', 'jstart' ... ) CBSD supports for mask as jname, e.g.:

cbsd jexec jname='*' date

'jrestart' is no exception here. The only problem is that the command did not process the jail status (and started all containers, even if they were in off status)

Also, I have documented your case. Use on health)

To test:

```
mv /usr/local/cbsd/jailctl/jrestart /tmp
fetch -o /usr/local/cbsd/jailctl/jrestart https://raw.githubusercontent.com/cbsd/cbsd/develop/jailctl/jrestart
chmod +x /usr/local/cbsd/jailctl/jrestart
cbsd jrestart --help
cbsd jrestart jname='*'
```

**Comment by lbartoletti** [comment]
Perfect!
