### ISSUE TITLE
vnet jails has no gateway - automatically created bridge has no address

### ISSUE THREAD

**Issue by BigB84** [cbsd/cbsd#715]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
`13.1-RELEASE`

CBSD version ( cbsd version ): 
`13.1.15'

Hi, 
thanks for creating CBSD it is so helpful!

I have only vnet jails and NAT enabled.

I couldn't find in docs information on how to automatically assign address for created bridge, because without  manually running `ifconfig bridge1 inet x.x.x.x netmask x.x.x.x` jails gateway doesn't work.

I need it persist across reboots. So I created a dirty rc script that does the job:

```sh
#!/bin/sh
#
# PROVIDE: cbsdfix
# REQUIRE: LOGIN FILESYSTEMS sshd cbsdd
#
#

. /etc/rc.subr

bridgename="bridge1"
bridgeaddress="x.x.x.x"
bridgemask="x.x.x.x"

name=cbsdfix
rcvar=cbsdfix_enable
start_cmd="${name}_start"

cbsdfix_start()
{
	ISBRIDGE=$(ifconfig | grep $bridgename | cut -f 1 -d ':' | xargs echo -n)

	while [ "$ISBRIDGE" != "$bridgename" ]; do
		sleep 3s
		ISBRIDGE=$(ifconfig | grep $bridgename | cut -f 1 -d ':' | xargs echo -n)
	done
	
	ifconfig $bridgename inet $bridgeaddress netmask $bridgemask
	echo "Bridge configured"
}

load_rc_config $name
run_rc_command "$1"
```

Example:

My vnet jail `vnet1` has `10.0.0.2` address and fixed gateway `10.0.0.1` (configured using jconstruct-tui). 

Is there any persistent setting in cbsd that would automatically set bridge address and netmask?

**Comment by olevole** [comment]
There are several options. Partially manual - initialize the bridge yourself (via rc.conf), e.g.:

1)

```
sysrc cloned_interfaces+="bridge10"
sysrc ifconfig_bridge10="inet 10.0.0.1/24 up"
```

So, CBSD vnet jail can be created with:
```
cbsd jcreate jname=myjail1 ip4_addr=10.0.0.2/24 ci_gw4="10.0.0.1" vnet=1 runasap=1
```

Also, you can set 'ci_gw4' via global config file per host:
```
cat > ~cbsd/etc/jail-freebsd-default.conf <<EOF
default_ci_gw4="10.0.0.1"
ci_gw4="10.0.0.1"
EOF
```
(see defaults ~cbsd/etc/defaults/jail-freebsd-default.conf ). 
Hint: most likely, it is enough to redefine only '**ci_gw4**', without `default_ci_gw4`

2) If I'm not mistaken, CBSD can also auto-assign an address with `nic_address` params:

cbsd jconfig -> jailnic -> nic1 -> nic_address 

![image](https://user-images.githubusercontent.com/926409/198008779-558299cd-e767-48c4-a3ae-5920874c4bc7.png)

( in this case, IP address will set on epairA interface )
