### ISSUE TITLE
Always use the same bridge. Is it possible?

### ISSUE THREAD

**Issue by mekanix** [cbsd/cbsd#716]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD gmekic-l13-rmt.meka.rs 14.0-CURRENT FreeBSD 14.0-CURRENT #1 main-n258914-010175a76d06: Sat Oct 29 19:52:04 CEST 2022     meka@gmekic-l13-rmt.meka.rs:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64

CBSD version ( cbsd version ): 
13.1.15

Is it possible to configure bridge0 via /etc/rc.conf and make CBSD use it no matter what? For example, my laptop sometimes doesn't get an address before CBSD is started, so bridge1 is created and all NAT and PF rules don't apply to it. Naturally, jail's network is not-work. This is also true if I'm on the road somewhere or just sitting in a park or something. Setting interface when jconstruct/jcreate doesn't work as I guess it should set epair interface, not bridge.

**Comment by olevole** [comment]
If I understand you correctly, it's only about jail and vnet ?

vnet jails can configure each virtual interface where you can manually fix the uplink interface instead of 'auto':

cbsd jconfig -> jailnic -> nic1 -> nic_parent -> manual -> SET TO 'bridge0'

Of course, bridge0 must exist.

![image](https://user-images.githubusercontent.com/926409/198894697-e226a3ce-48ea-4886-b208-4cf0043ba632.png)

**Comment by mekanix** [comment]
That's great! I found it in jconstruct not jconfig, but that's fine. I saw that if I just generate the .jconf file there is no mention of bridge interface in it. I assume it is in /tmp/tmp.<something> file. Any chance that I can change nic_parent via jset or similar utility?

**Comment by olevole** [comment]
if you don't have multiple vnet (virtual) interfaces for jail, then the usual 'interface=' parameter should also work for vnet:

```
cbsd jcreate jname=meka interface=bridge0 vnet=1 runasap=1
```

(or interface= in .jconf )

**Comment by mekanix** [comment]
There's something weird. One jail respects the `interface=` set throgh `jset`, one doesn't. The one that doesn't work has 2 addresses: IPv4 and IPv6. Does that matter?

**Comment by mekanix** [comment]
And I guess it does. It works great for a single address, but not with multiple. On jail I have IPv4 and IPv6 static addresses it doesn't work. Any idea if we would break stuff if `interface=` for vnet jails can be applied to all epairs of that jail?

**Comment by mekanix** [comment]
I'm wrong,my code for reggae was wrong. https://github.com/cbsd/reggae/pull/263
