### ISSUE TITLE
[DragonflyBSD] errors installing package manager, base has no pkg installed by default.

### ISSUE THREAD

**Issue by BigB84** [cbsd/cbsd#717]
Mandatory info for bug reports:

DragonflyBSD version ( uname -a ): 
`DragonFly bsd 6.2-RELEASE DragonFly v6.2.2-RELEASE`

CBSD version ( cbsd version ): 
`13.1.4`

but - pkg info cbsd - says:
`Version        : 13.1.14`

Hi,

thanks for creating cbsd it's priceless!

I'm not sure where should I post this issue, as CBSD doesn't officially support dfly, however If i saw correctly, base for jails was fetched from bsdstore.ru

(inside dfly jail): This base has only pkg-static, so according to [docs](https://www.dragonflybsd.org/docs/howtos/HowToDPorts/) if I want package manager I should do:
```shell
cd /usr
make pkg-bootstrap
rehash
pkg-static install -y pkg
rehash
```

but `make pkg-bootstrap` gives:
```
make warning: /usr/obj: Read-only file system.
make[1] warning: /usr/obj: Read-only file system.
Warning: /etc/ssl/cert.pem and /usr/local/etc/ssl/cert.pem do not exist.
Disable certificate verification for fetch(1).
fetch --no-verify-peer -o /tmp/pkgboot.tar.xz https://mirror-master.dragonflybsd.org/dports/bootstraps/bootstrap_pkg_03_x86-64.tar.xz
/tmp/pkgboot.tar.xz                                   1785 kB  318 kBps    06s
tar -xJf /tmp/pkgboot.tar.xz -C /usr/local
make[1] warning: /usr/obj: Read-only file system.
/usr/local/sbin/pkg-static install -y  pkg
Updating Avalon repository catalogue...
pkg-static: repository meta has wrong version 2
pkg-static: Repository Avalon load error: meta cannot be loaded Undefined error: 0
Fetching meta.txz: 100%    236 B   0.2kB/s    00:01    
pkg-static: repository meta has wrong version 2
repository Avalon has no meta file, using default settings
Fetching packagesite.txz: 100%    6 MiB 626.8kB/s    00:10    
pkg-static: repository meta has wrong version 2
pkg-static: Repository Avalon load error: meta cannot be loaded Undefined error: 0
Unable to open created repository Avalon
Unable to update repository Avalon
Error updating repositories!
*** Error code 3

Stop.
make[1]: stopped in /usr
*** Error code 1

Stop.
make: stopped in /usr
```

and similarly  `pkg-static install -y pkg`:
```
Updating Avalon repository catalogue...
pkg-static: repository meta has wrong version 2
pkg-static: Repository Avalon load error: meta cannot be loaded Undefined error: 0
Fetching meta.txz: 100%    236 B   0.2kB/s    00:01    
pkg-static: repository meta has wrong version 2
repository Avalon has no meta file, using default settings
Fetching packagesite.txz: 100%    6 MiB 522.3kB/s    00:12    
pkg-static: repository meta has wrong version 2
pkg-static: Repository Avalon load error: meta cannot be loaded Undefined error: 0
Unable to open created repository Avalon
Unable to update repository Avalon
Error updating repositories!
```

Trying to fix this I wanted to mark in TUI allow mount obj but whenever I mark it, save and commit changes, it doesn't apply for some reason...

additionally I was trying to apply fixes from FreeBSD like [here](https://forums.freebsd.org/threads/pkg-update-error.74260/) but they mostly assumed you have pkg installed... So no luck.

**Comment by olevole** [comment]
This requires some investigation. But if you want to have a /usr/obj in RW within jail, you can:

1) use `baserw=1` type of jail  ( via TUI or: `cbsd jcreate jname=test1 baserw=1 runasap1 pkg_bootstrap=0` )
2) Use nullfs mount, e.g:
```
mkdir /var/jail-obj
echo "/var/jail-obj /usr/obj nullfs rw 0 0" > ~cbsd/jails-fstab/test1/fstab.local
```

where `test1` - jail name. This will mount the /var/jail-obj directory from the host at the time of the start of the container via nullfs/overlay FS.

( check ~cbsd/jails-fstab/ directory )

**Comment by olevole** [comment]
Take a look on 'man make'

You need to set 
```
MAKEOBJDIR=
OBJDIR=
```

to RW location.

Fixed in skel files:
```
MAKEOBJDIR=/usr/local/obj
OBJDIR=/usr/local/obj
```
