### ISSUE TITLE
Cannot login jails after upgrade 

### ISSUE THREAD

**Issue by Juronski** [cbsd/cbsd#718]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD 13.1-RELEASE-p3 GENERIC amd64
CBSD version ( cbsd version ): 
CBSD 13.1.18

Hi,

After upgraded to CBSD 13.1.18 and FreeBSD 13.1-p3 I cannot login anymore in to jails. 
When I do `sudo cbsd jlogin jailxyz`. 
I get:
```
jexec: give me jname
jlogin jexec errcode: 1: /usr/bin/nice -n 1   /usr/local/cbsd/jailctl/jexec 47 /usr/local/cbsd/tools/login -f root
```
How can this be fixed? 

Thank you in advance!
J.

**Comment by olevole** [comment]
Can you check fix ? @Juronski 

```
cp /usr/local/cbsd/misc/cmdboot /tmp
fetch -o /usr/local/cbsd/misc/cmdboot https://raw.githubusercontent.com/cbsd/cbsd/develop/misc/cmdboot
chmod +x /usr/local/cbsd/misc/cmdboot

cbsd initenv
```

looks like a typo. i will send this fix to the port soon

**Comment by Juronski** [comment]
The fix works @olevole. I also had a large number of CBSD-processes being started (5000+)  after issuing a CBSD-command (e.g. cbsd jstart). That also seems to be solved.

Thank you verry much @olevole 

Kind regards.
J.

**Comment by olevole** [comment]
https://cgit.freebsd.org/ports/commit/?id=a42599b6999299fe3c7025baec4c5060ff0bb8de
