### ISSUE TITLE
Better way of handling devfs

### ISSUE THREAD

**Issue by mekanix** [cbsd/cbsd#719]
There's a [better way of handling devfs](https://github.com/freebsd/poudriere/blob/master/src/share/poudriere/common.sh#L2006), and I think we could use it for VNET, for example. Anyone has anything against this approach being implemented?

**Comment by olevole** [comment]
@mekanix I don't understand logic very well. What problem is solved?

**Comment by mekanix** [comment]
If I understand how current CBSD code works with VNET jails it's to always use devfs rule number 5. If that's right, we can break dependence on devfs config and just unhide bpf and whatever other /dev entries we need. That way devfs rule number is not even needed (or it can be even used in combination with devfs.rules file? I'm not sure about that part).

**Comment by olevole** [comment]
I think this is a bad idea because a lot of people use custom devfs rules, not just 4 or 5. The config file adds flexibility. If we get rid of it and move to hardcode, then we should provide users another way to regulate the devices in /dev/
