### ISSUE TITLE
Jail with multiple network interfaces

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#720]
Hey!

I wanted to ask what the intended way of creating a jail with multiple IP addresses is? The documentation mentions that multiple addresses can be listed in `jconfig -> ip4_addr`. However, it mentions that these will be created as _aliases_.

My host has several interfaces (such as `igb0`, `igb1` and so on). I'd need the jail to get an IP address on `igb0` and different IP address on `igb1`.

**Comment by olevole** [comment]
if we're talking about vnet=0 jails, the example in the dialog says something about it:

![image](https://user-images.githubusercontent.com/926409/207357081-41f4088a-b06d-4ed1-9d49-60006620fcc2.png)


E.g:
```
ifconfig bridge10 create
ifconfig bridge11 create
cbsd jcreate jname=test ip4_addr='bridge10#10.0.10.1,bridge11#10.0.11.1' runasap=1
```

But a more predictable option is to initialize your IP addresses outside of CBSD, e.g. via /etc/rc.conf:

ifconfig_igb1_alias0="10.0.10.1/24"
ifconfig_igb2_alias0="10.0.11.1/24"

Set **ip4_addr** for jail  as usual ( `IP1,IP2` ) and **disable** managing of jail IP addresses by CBSD via 'interface=0' settings:

```
cbsd jset jname=jail1 ip4_addr="10.0.10.1,10.0.11.1" interface=0
```

When `interface=0` cbsd won't execute 'ifconfig <iface> <IP> alias' and 'ifconfig <iface> <IP> -alias` upon jstart/jstop.

https://www.bsdstore.ru/en/cbsd_rcconf.html

**Comment by Tectu** [comment]
Duuuh... the dialog indeed explains this. Total PEBKAC - excuse the noise!

This worked out perfectly fine after I followed the instructions.

Thank you very much for your help & your continued development efforts!
