### ISSUE TITLE
Cannot delete jail snapshots

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#722]
I just updated cbsd from `13.1.14` to `13.1.20` on a rarely used host.
Next, I wanted to destroy some snapshots. However, this doesn't seem to be working:

List of snapshots:
```plain
jbo@knox:~ % sudo cbsd jsnapshot mode=list
JNAME         SNAPNAME         CREATION           REFER
emby          20211003         2021-10-03__12:18  2.45G
emby          20220114         2022-01-14__16:21  4.68G
nextcloud     20220117         2022-01-17__15:57  1.64G
``` 

Attempting to delete a snapshot:
```plain
jbo@knox:~ % sudo cbsd jsnapshot mode=destroy jname=emby snapname=20211003
jsnapshot: destroyed 0 snapshots in 0 seconds
```

I cannot recall having ever had problems with deleting existing jail snapshots.
Am I missing something obvious here?

---
**UPDATE**

Apparently I also can't create a new snapshot:
```plain
jbo@knox:~ % sudo cbsd jsnapshot mode=create jname=emby snapname=test
zfs snapshot error: cannot open 'zroot/ROOT/20230102/emby': dataset does not exist
usage:
	snapshot [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
```

I think I might have hosed my system here.
I'm on a BE named `20230102`:
```plain
jbo@knox:~ % bectl list
BE                             Active Mountpoint Space Created
13.1-RELEASE_2023-01-02_150042 -      -          3.11M 2023-01-02 15:00
20220525                       -      -          11.3M 2022-05-25 13:19
20230102                       NR     /          10.3G 2023-01-02 14:55
default                        -      -          29.4G 2020-07-21 16:09
```

But it would seem that cbsd jails are all mounting `zroot/ROOT/default`: 
```plain
jbo@knox:~ % zfs list 
NAME                                        USED  AVAIL     REFER  MOUNTPOINT
nvme                                       1.92M   225G       96K  /nvme
nvme/cbsd                                    96K   225G       96K  /nvme/cbsd
storage                                    10.6T  6.80T      128K  /storage
storage/emby                               10.4T  6.80T     10.4T  /storage/emby
storage/nextcloud                           132G  6.80T      132G  /storage/nextcloud
zroot                                      39.6G   183G       88K  /zroot
zroot/ROOT                                 39.5G   183G       88K  none
zroot/ROOT/13.1-RELEASE_2023-01-02_150042     8K   183G     7.21G  /
zroot/ROOT/20220525                         884K   183G     7.10G  /
zroot/ROOT/20230102                        10.3G   183G     7.19G  /
zroot/ROOT/default                         29.2G   183G     5.52G  /
zroot/ROOT/default/blog                     473M   183G      219M  /usr/jails/jails-data/blog-data
zroot/ROOT/default/cppproperties            199M   183G      114M  /usr/jails/jails-data/cppproperties-data
zroot/ROOT/default/emby                    16.0G   183G     5.20G  /usr/jails/jails-data/emby-data
zroot/ROOT/default/git                     2.34G   183G     2.34G  /usr/jails/jails-data/git-data
zroot/ROOT/default/irc                      965M   183G      574M  /usr/jails/jails-data/irc-data
zroot/ROOT/default/nextcloud               4.76G   183G     1.93G  /usr/jails/jails-data/nextcloud-data
zroot/tmp                                   884K   183G      488K  /tmp
zroot/usr                                   840K   183G       88K  /usr
zroot/usr/home                              464K   183G      220K  /usr/home
zroot/usr/ports                             144K   183G       88K  /usr/ports
zroot/usr/src                               144K   183G       88K  /usr/src
zroot/var                                  7.07M   183G       88K  /var
zroot/var/audit                             144K   183G       88K  /var/audit
zroot/var/crash                             144K   183G       88K  /var/crash
zroot/var/log                              4.05M   183G     1.34M  /var/log
zroot/var/mail                             2.44M   183G     2.24M  /var/mail
zroot/var/tmp                               208K   183G       88K  /var/tmp
```

---

Related: https://forums.freebsd.org/threads/unable-to-delete-be.87616/

**Comment by olevole** [comment]
I do not really understand what influence the BE ( I have never used it)  on the name of the snapshots has. But how CBSD works with snapshot:

when you do 'jsnapshot mode=create', CBSD get jail dataset (e.g. `zroot/ROOT/default/nextcloud` for nextcloud) and performs 'zfs snapshot', e.g.:
```
zfs create zroot/ROOT/default/nextcloud@SNAPNAME
```

Also, CBSD marks the created snapshots by additional properties:
```
cbsdsnap:snapname
cbsdsnap:jname
```

In order to work only with СИЫВ snapshots.

Since these are ordinary ZFS snapshots, you can easily remove them without CBSD:

Find valid snapshot to delete:
```
zfs list -t snapshot | grep emby
```

```
zfs destroy <snapshotname>
```

Of course, the system will not allow you to remove the snapshot if it is used ( If you don't need it, you can remove recursively )

**Comment by Tectu** [comment]
Thank you for your response :)

> when you do 'jsnapshot mode=create', CBSD get jail dataset (e.g. zroot/ROOT/default/nextcloud for nextcloud) and performs 'zfs snapshot', e.g.:

Is that path hardcoded? If so, this can be a source of huge issues which might explain the situation I ran into now.
I'm no expert either so maybe it's good if you read up on boot environments and play around with them using `bectl`.
A boot environment is basically a ZFS clone and the bootloader can select one of these to boot from.

The default BE is called `default`. Hence under a fresh install, "everything" is located under `zroot/ROOT/default`). However, once can create (and boot into!) as many BEs as one would like doing something like `bectl create another_be`.
This will instantly create a clone of the currently active BE and place it under `zroot/ROOT/another_be`. If the system boots into that BE, the system simply boots from `zroot/ROOT/another_be`. 

The state of my system as outlined above (and in the linked forum post) would indicate that my overall system is running on the BE `20230102` but for an unknown reason, `cbsd` related stuff keeps mounting the `default` BE dataset.
If this is indeed the case, this is more or less a disaster :D

As I'm neither an expert on CBSD/jails nor BEs there's not much advice I can give here. I think it would be best if you look into proper use of BEs to figure out whether there's something "missing" on the CBSD side for a default setup to work.

**Comment by olevole** [comment]
`zroot/ROOT/default` is not hardcoded as path, if you named the pool as 'mypool1/dataset1'  then nextcloud jail will be created as `mypool1/dataset1/nextcloud`. I need to check what exactly the BEis doing with the datasets and why the cbsd stops seeing them.

But if go back to your original question: try deleting the snapshot via `zfs`, this information is not stored anywhere in the cbsd

**Comment by Tectu** [comment]
> But if go back to your original question: try deleting the snapshot via `zfs`, this information is not stored anywhere in the cbsd

That worked out well. `cbsd jsnapshot` doesn't list the snapshots anymore.
I guess it is a problem/bug/PEBKAC that `cbsd` could not destroy the snapshots itself so I am not sure whether you want to close this issue or keeping it open.

As for the boot environment discussion: I guess this will warrant a separate issue to discuss my questions/concerns/misunderstandings.

As usual: Thank you for your support!

**Comment by hansw-nlo** [comment]
I had a simular issue but was wondering if cbsd should clean up those snapshots. I can do it myself too. I did find I sometimes need to use the -f and/or -r flags in the zfs destroy command. I will have a closer look at using cbsd for it.

**Comment by olevole** [comment]
I believe that starting with [14.0.4 release](https://github.com/cbsd/cbsd/releases/tag/v14.0.4) we began to process the reasons for this situation - now the CBSD checks and requires a separate dataset. A separate dataset makes it possible not to be in conflict with services like `beadm`.  This is a radical solution to the problem, but there are no other better ideas. Unfortunately, systems installed before version 14.0.4 are still susceptible to the problem - the check only works during the first initialization of the cbsd working directory.

**Comment by Tectu** [comment]
I think given the situation that is a reasonable approach. I guess I'll have to migrate a bunch of stuff...

Maybe you could add a warning or notice message during `cbsd initenv` when upgrading to a newer CBSD version.
