### ISSUE TITLE
Jail update incorrect kernel version

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#723]
CBSD version ( cbsd version ): `13.1.20`
Host FreeBSD version: `13.1-RELEASE`

I have a jail which wasn't running for a while. As the jail is needed again I spun it up and attempted to update it.
Steps I performed:
1. `cbsd jstop myjail`
2. `cbsd baseupdate`
3. `cbsd jset ver=13.1 jname=myjail`
4. `cbsd jstart myjail`
5. `cbsd etcupdate jname=myjail mode=update from=12.1 to=13.1`
6. `cbsd jrestart myjail`

After that, I logged into the jail and got this situation on my hands: `freebsd-version` reports:
```plain
13.1-RELEASE-p5
``` 
But `uname -a` reports:
```
FreeBSD myjail.foo.com 12.1-RELEASE FreeBSD 12.1-RELEASE amd64
```
So the jail is still running kernel 12.1.

I triple checked my steps above but couldn't find any disagreements with my notes.
My usual question: What could have lead to this situation and how can I fix it? The jail should certainly run the `13.1-RELEASE` kernel.

**Comment by olevole** [comment]
Most likely this is old work-around which is no longer required ( see `grep -B1 -A29 ^20140930 /usr/ports/CHANGES`  ) as version substitution works through the sysctl. This work-around was removed from the CBSD a year ago, however, containers created a nefore can still contain this crap ;) Please checkout https://github.com/cbsd/cbsd/issues/709

Please re-open if the problem still remains after deleting UNAME* records in /etc/*

**Comment by Tectu** [comment]
Modifying the files mentined in #709 did the trick - everything back to normal!

Once again - and I cannot stress this enough: Thank you for your fast support!

**Comment by Tectu** [comment]
That did the trick - clearly I should have been familiar with this :D

Thank you!
