### ISSUE TITLE
List jail versions in jls

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#724]
Personally, I would find it really useful if `jls` would also show the underlying jail base (for each jail). Whether or not this needs to be displayed by default can certainly be debated (personally I would say yes).

I've checked the `jls display=` option help text and it doesn't seem like this is currently implemented and simply not displayed by default.

@olevole what do you think? :)

**Comment by olevole** [comment]
jails have quite a few parameters (you can see them in 'cbsd jconfig' / 'cbd jget') and I could not describe them all in `cbsd jls --help`. Nevertheless, it is a fairly well-known parameter, it's 'ver':

`cbsd jls display=jname,status,ver'

As for 'defaults', you can set your own 'default' filter for jls via ~cbsd/etc/jls.conf, e.g.:

```
echo 'display="jname,status,ver,allow_raw_sockets,arch"' > ~cbsd/etc/jls.conf
cbsd jls
```

I'll say more. You can even make your own fields! For example, add custom 'owner' field for each jails:

```
root@mother:~ # cbsd jls display=jname,status,owner
JNAME        STATUS  OWNER
cbsdpuppet1  Off     -         
gitea        Off     -         
mfs          On      -         
pup1         On      -         
sync         Off     -         
```

```
root@mother:~ # echo 'echo "Tectu@my.domain"' > ~cbsd/jails-system/sync/facts.d/owner
root@mother:~ # chmod +x ~cbsd/jails-system/sync/facts.d/owner
root@mother:~ # cbsd jls display=jname,status,owner
JNAME        STATUS  OWNER
cbsdpuppet1  Off     -                
gitea        Off     -                
mfs          On      -                
pup1         On      -                
sync         Off     Tectu@my.domain
```

**Comment by Tectu** [comment]
Man... you just rock!

I have seen, evaluated, tested, used & hated so many (software) projects. CBSD was one of the few that made it through my selection processes relatively unscared (documentation...). I have never looked back since.
And after many, many years of using CBSD exclusively in production I can safely say that there are zero regrets.

Every now and then I think of writing a blog article about it but:
1. My blog doesn't have any "followers". It's more of a "accidentally find it by google" type situation so it wouldn't really help you directly.
2. I want to spend some time testing a few more features I haven't really used yet (especially clustering & migrations across clusters).

**Comment by olevole** [comment]
No problem. 

By the way, this is a wonderful slogan: "you can use the project in production even without documentation", i like it ;-) 

@kraileth ^^ :satisfied:

**Comment by olevole** [comment]
@Tectu as for clustering, I recommend API-way (instead of SSH: `cbsd node mode=add`  mostly for 2-3 hosts and not scaling very well)

**Comment by kraileth** [comment]
> And after many, many years of using CBSD exclusively in production I can safely say that there are zero regrets.
> 
> Every now and then I think of writing a blog article about it but:
> 
>     1. My blog doesn't have any "followers". It's more of a "accidentally find it by google" type situation so it wouldn't really help you directly.
> 
>     2. I want to spend some time testing a few more features I haven't really used yet (especially clustering & migrations across clusters).

@Tectu I can second the rest you wrote as well, but wanted to specifically encourage you to maybe blog about your journey and thoughts after all. It sounds like you've used CBSD for longer than me (I think I became a user around 2018 or so?). If you've got something to write about (and I bet you do), please do so!

I'm currently writing an introduction / tutorial series with @olevole patiently enduring the many weird questions that I have and guiding me back on the road where I am lost. My blog isn't huge, either (still just a two-figure count of followers, but with over a decade of material I get quite some hits from search engines and get featured in more popular places now and then). The start of the CBSD series has been received well and I'd be happy to link to your blog if you write a post about using CBSD in production for a long time.
