### ISSUE TITLE
Cannot create jail with encrypted dataset

### ISSUE THREAD

**Issue by iron-udjin** [cbsd/cbsd#726]
FreeBSD version ( uname -a ): FreeBSD test 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64
CBSD version ( cbsd version ): 13.1.22

When I'm trying to create a new jail with encrypted zfs dataset I enabled `zfs_encription` option and then click `PROCEED!`. After that I see `Please wait: this will take a while...` which is waiting forever. If I hit Enter twice - I see:
```
cannot create 'zroot/ROOT/default/testjail': Passphrase too short (min 8).
/usr/local/cbsd/sudoexec/jcreate: Enter: not found
create_zfs_fs: zfs create failed: . No ZFS and zfsfeat=1?
Config file for jconf: /usr/jails/ftmp/testjail.93309.jconf
```
It looks like it was waiting for password in a background but TUI script silenced that prompt.

Even if I enter dataset encription password twice after `Please wait: this will take a while...` it looks like an encription key didn't set properly and jail failed to create:
```
/usr/local/cbsd/sudoexec/jcreate: Enter: not found
create_zfs_fs: zfs create failed: . No ZFS and zfsfeat=1?
Config file for jconf: /usr/jails/ftmp/testjail.95681.jconf
```

**Comment by olevole** [comment]
seems to be the problem was here  https://github.com/cbsd/cbsd/commit/4a6a3885fad2815bf51a510c378155780b758076

Can you check please ?

```
mv /usr/local/cbsd/subr/jfs.subr /tmp
fetch -o /usr/local/cbsd/subr/jfs.subr https://raw.githubusercontent.com/cbsd/cbsd/develop/subr/jfs.subr
```
+

```
cbsd jcreate jname=test2 zfs_encryption=1
```

**Comment by iron-udjin** [comment]
With this script everything works fine. Is this change will be included to next release?

P.S: It would be great to unload encryption key when `cbsd` stopps jail or at least have it as an option in jail config.

**Comment by olevole** [comment]
> With this script everything works fine. Is this change will be included to next release?

sure!
>
> P.S: It would be great to unload encryption key when `cbsd` stopps jail or at least have it as an option in jail config.

Yeah, It is reasonable. Options looks preferable

**Comment by olevole** [comment]
added new parameters in zfs.conf: **zfs_always_unload_key**=

to overwrite default settings ( zfs_always_unload_key=0 ) you can set zfs_always_unload_key=1 as global settings via:
_~cbsd/etc/zfs.conf_

or per-jail, e.g.:
_~cbsd/etc/jails-system/testjail/etc/zfs.conf_

To test:

1)
```
mv /usr/local/cbsd/jailctl/jcleanup /tmp
mv /usr/local/cbsd/sudoexec/jcreate /tmp

fetch -o /usr/local/cbsd/jailctl/jcleanup https://raw.githubusercontent.com/cbsd/cbsd/develop/jailctl/jcleanup
fetch -o /usr/local/cbsd/sudoexec/jcreate  https://raw.githubusercontent.com/cbsd/cbsd/develop/sudoexec/jcreate

chmod +x /usr/local/cbsd/sudoexec/jcreate /usr/local/cbsd/jailctl/jcleanup
```

2)
```
cbsd jcreate jname=xxx zfs_encryption=1 runasap=1
```

3)
```
echo "zfs_encryption=1" > ~cbsd/etc/zfs.conf
```
or per-jail

```
mkdir -p ~cbsd/jails-system/xxx/etc
echo "zfs_encryption=1" > ~cbsd/jails-system/xxx/etc/zfs.conf
cbsd jstop xxx
```
