### ISSUE TITLE
cbsd expose accept bad rules to pfnat configuration

### ISSUE THREAD

**Issue by george-pmk** [cbsd/cbsd#727]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

CBSD version ( cbsd version ): 13.1.0

to attempt to expose port 3050 with IP for one of our jails

I run command cbsd expose with a IP

> ~ cbsd expose jname=JAIL mode=add in=3050 out=172.24.xx.xx:3050
CBSD Expose for JAIL: 3050 -> 172.24.xx.xx:3050 (tcp)
CBSD: Enable IP forwarding for NAT service
/usr/jails/etc/pfnat.conf:7: unknown port 172.24.xx.xx
pfctl: Syntax error in config file: pf rules not loaded
pfctl: pf already enabled
➜  ~ cbsd expose jname=JAIL mode=list
3050 -> 3050 (inaddr=0 -> 10.xx.xx.xx tcp)
➜  ~ cbsd expose jname=JAIL mode=clear
rdr pass proto tcp from any to 10.xx.xx.xx port 3050 -> 172.16.xx.xx port 3050 # // Setup by CBSD expose: tcp-3050-JAIL
CBSD: Enable IP forwarding for NAT service
/usr/jails/etc/pfnat.conf:6: unknown port 172.24.xx.xx
pfctl: Syntax error in config file: pf rules not loaded
pfctl: pf already enabled

I got error messages “unknown port” and “rules not loaded“

after checking with 

> ~ cbsd expose jname=JAIL mode=list3050 -> 3050 (inaddr=0 -> 10.xx.xx.xx tcp)

I decided cbsd not accept the previous rule and nothing dangerous happen 

after this expose test I clean rules by 

> cbsd expose jname=JAIL mode=clear
> cbsd expose jname=JAIL mode=flush

and checked the results with 

> cbsd expose jname=JAIL mode=list

I was sure nothing changed in the ruleset
but it was a disaster 
cbsd put the bad rule with IP to /usr/jails/etc/pfnat.conf and pfnat stop working for all jails

How we can protect ourselves from this type of mistake?
Should we update cbsd version?

**Comment by olevole** [comment]
CBSD (re)-generate ~cbsd/etc/pfnat.conf files via `cbsd natcfg` + `cbsd naton`, so you can try to move old 'wrong' config and generate new one:
```
mv ~cbsd/etc/pfnat.conf ~cbsd/etc/pfnat.conf-o
cbsd natoff
cbsd natcfg
cbsd naton
```
As for protection. Of course, it is difficult to foresee all possible and impossible typos. But I believe that the CBSD can check at least the port values ( is_integer and 1-65535 range )

**Comment by olevole** [comment]
> Should we update cbsd version?

It always makes sense to update. Moreover, you use a very old version (13.1.0 released almost a year ago).
Also your version of FreeBSD EoL ( https://www.freebsd.org/security/unsupported/ + https://www.freebsd.org/security/#sup )

**Comment by olevole** [comment]
@george-pmk FYI: all expose/rdr settings per VM are located in the SQLite3 file: _~cbsd/jails-system/<JAILNAME>/expose.sqlite_ , this is another way to delete a bad record directly ( + edit `~cbsd/etc/pfnat.conf` and then re-load pf rules `pfctl -f ~cbsd/etc/pfnat.conf` )

I added (https://github.com/cbsd/cbsd/commit/947c79b2e195c104ed066c3c084d7ea771a7145f)  validation for **in/out** values, thus, at least your case will no longer lead to problems:

![image](https://user-images.githubusercontent.com/926409/221297479-c2e4296b-17e1-437a-948e-15bb68f898b6.png)

to test:
1) upgrade CBSD to latest, 13.1.23
2) `cbsd initenv`
3) backup file:
`mv /usr/local/cbsd/tools/expose /tmp/`
4) fetch new version of `expose` file from git:
```
fetch -o /usr/local/cbsd/tools/expose https://raw.githubusercontent.com/cbsd/cbsd/develop/tools/expose
chmod +x  /usr/local/cbsd/tools/expose
```

Please re-open issue if you still have any questions or suggestions with this.
