### ISSUE TITLE
Incorrect function is called from initenv-tui

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#728]
FreeBSD version ( uname -a ): 13.1-RELEASE
CBSD version ( cbsd version ): 13.1.23

Trying to configure NAT from `cbsd initenv-tui` (Nat config >>), `cbsd natcfg-tui` should be started, but it is not the case - `cbsd natcfg` is started.

![shot-2023-02-28_17-26-45](https://user-images.githubusercontent.com/3807655/221916600-48dd70d7-0e2c-4307-9730-6f4e463168c7.jpg)

![shot-2023-02-28_17-31-33](https://user-images.githubusercontent.com/3807655/221916769-177e74e6-ba5a-4472-891f-0c40ce7b15d3.jpg)

**Comment by olevole** [comment]
Fixed in the upcoming 13.2.0 release
