### ISSUE TITLE
Show all interfaces of VM

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#732]
I assume that this is going to be one of those "duuh..." moments but I can't figure it out myself right now.

Assuming that I have some bhyve VMs on my CBSD host and they have one or more interfaces each using DHCP, is there a way to query the interface configuration (eg. currently assigned IP) from CBSD?

I had a look at `bhyve-nic-list` but `NIC_ADDRESS` reports `0` for all my bhyve VMs (cbsd 13.1.25 on FreeBSD 13.1).

**Comment by olevole** [comment]
Without any auxiliary additions in guest OS, it is impossible to find out the addresses used in the guest. You can control the address from the CBSD when you use `cloud` images.

**Comment by Tectu** [comment]
Fair enough :D
