### ISSUE TITLE
Rebuilding Sqlite DB Config File for Bhyve Jails.

### ISSUE THREAD

**Issue by JEAholding** [cbsd/cbsd#733]
FreeBSD version ( uname -a ): 
13.1p2

CBSD version ( cbsd version ): 
13.1.4, 13.0.24, 13.0.22

====================================================================================================
I have multiple versions of the CBSD and FREEBSD OS around multiple hosts/servers...

Recently in one of the slots/boxes/servers, the second drive got full causing some of the VM running to crash. 

_Quick resolution HDD2:_ 
After such an occurrence (I had to clean old zfs snapshots that were eating more than 50 GB of space on the drive). 

_Persistent Problem HDD2:_
env workdir=/zroot_slot6_fbase2/usr/jails cbsd bls was NOT showing any VM...

I tried env workdir="/zroot_slot6_fbase2/usr/jails" cbsd initenv multiple times did not work.

I went to /zroot_slot6_fbase2/usr/jails/vm files are still there and the VHD still can be seen in ZFS. 

The 3 VM files are still in the correct location and all of the VHD are still intact only problem is the local. sqlite it seems...

_Debugging:_ 

1. I was able to launch the 3 VM in HDD2 that were being launched with CBSD with bhyve + tmux directly since env workdir=/zroot_slot6_fbase2/usr/jails cbsd is not working. 
2. I looked into sqlite db only seeing 2 relevant tables to my case.

```
.schema rctl
select * from rctl;
```
```
.schema jails
select * from jails;
```
Issues / Resolution / Assumptions:

1. 
I added the information in rctl and jails table in sqlite in HDD2 and CBSD began showing VM that were started without cbsd in HDD2. Will I need to edit any other location/config?  

2. 
```
INSERT INTO jails VALUES('vm_name',0,'/zroot_slot6_fbase2/vm_name','vm_name.vm_name.com','vm_name-ip',1,1,1,1,'/zroot_slot6_fbase2/usr/jails/jails-fstab/vm_name-ip/fstab',1,4,'auto','0','0',0,0,0,'0',1,1,'/zroot_slot6_fbase2/usr/jails/vm/vm_name-ip',0,1,0,'/zroot_slot6_fbase2/usr/jails/jails-rcconf/rc.conf_vm_name-ip',1,'native','native','0','/bin/sh /etc/rc','/bin/sh /etc/rc.shutdown','0','0','0','0','0','0','0','0',0,180,0,900,1,1,'0',1,1,0,'0','bhyve','0',0,'0','0',10,1,'0',0,0,'0','',1,0,1,1,'(strftime(''%s'',''now''))',0,0,0,0,0,0,1,'new','new','new','0','0',0,0,0,0,0,'0','0','0',0);


```
||
```
INSERT INTO jails (jname,jid,path ,host_hostname ,ip4_addr ,mount_devfs,allow_mount,allow_devfs,allow_nullfs,mount_fstab,mkhostsfile,devfs_ruleset,interface,basename,slavenode,baserw,mount_src,mount_obj,mount_kernel,mount_ports,astart,data,vnet,applytpl,mdsize,rcconf,floatresolv,ver,arch,masterhost,exec_start,exec_stop,exec_poststart,exec_poststop,exec_prestart,exec_prestop,exec_master_poststart,exec_master_poststop,exec_master_prestart,exec_master_prestop,status,exec_timeout,exec_fib,stop_timeout,mount_fdescfs,allow_dying,depend,allow_procfs,allow_tmpfs,allow_zfs,cpuset,emulator,emulator_flags,allow_kmem,exec_consolelog,jdomain,b_order,allow_fdescfs,allow_sysvipc,protected,hidden,maintenance,name, allow_reserved_ports,childrenmax,persist,enforce_statfs,state_time,allow_raw_sockets,allow_fusefs,allow_linprocfs,allow_linsysfs,allow_read_msgbuf,allow_vmm,allow_unprivileged_proc_debug,sysvsem,sysvshm,sysvmsg,mnt_start,mnt_stop,allow_mlock,mount_procfs,mount_linprocfs, mount_linsysfs,gid,tags,ci_gw4,zfs_encryption,boot_delay) VALUES('vm_name',0,'/zroot_slot6_fbase2/vm_name','vm_name.vm_name.com','vm_name-ip',1,1,1,1,'/zroot_slot6_fbase2/usr/jails/jails-fstab/vm_name-ip/fstab',1,4,'auto','0','0',0,0,0,'0',1,1,'/zroot_slot6_fbase2/usr/jails/vm/vm_name-ip',0,1,0,'/zroot_slot6_fbase2/usr/jails/jails-rcconf/rc.conf_vm_name-ip',1,'native','native','0','/bin/sh /etc/rc','/bin/sh /etc/rc.shutdown','0','0','0','0','0','0','0','0',0,180,0,900,1,1,'0',1,1,0,'0','bhyve','0',0,'0','0',10,1,'0',0,0,'0','',1,0,1,1,'(strftime(''%s'',''now''))',0,0,0,0,0,0,1,'new','new','new','0','0',0,0,0,0,0,'0','0','0',0);
```
Will I need to run env workdir="/zroot_slot6_fbase2/usr/jails" cbsd initenv after update because the VM seem like they're working from just sqlite add in.

(FYI: _I do not have a backup of this particular CBSD sqlite HDD2 db_.)

**Comment by olevole** [comment]
`rctl` table does not affect the visibility of virtual machines. The second important table is `bhyve` in ~cbsd/var/db/local.sqlite

Also each VM has some settings in ~cbsd/jails-system/<VM>.
```
% sqlite3 /zroot_slot6_fbase2/usr/jails/var/db/local.sqlite "SELECT * from jails WHERE emulator='bhyve'" ;
% sqlite3 /zroot_slot6_fbase2/usr/jails/var/db/local.sqlite "SELECT * from bhyve" ;
```

should show the same number of records;

In the absence of a backup, most likely the best recovery option is to create virtual machines on a test server with the same names and then dump 'jails' and 'bhyve' tables:

1) on the test server:
% sqlite3 ~cbsd/var/db/local.sqlite ".dump bhyve" > /tmp/bhyve.sql
% sqlite3 ~cbsd/var/db/local.sqlite ".dump jails" > /tmp/jails.sql
  
2) replace workdir in /tmp/jails to `/zroot_slot6_fbase2/usr/jails` in /tmp/jails.sql

3) copy /tmp/*.sql to prod server

4) Import tables:

```
sqlite3 /zroot_slot6_fbase2/usr/jails/var/db/local.sqlite  < /tmp/jails.sql
sqlite3 /zroot_slot6_fbase2/usr/jails/var/db/local.sqlite  < /tmp/bhyve.sql
```

Or use 'INSERT int bhyve' - just check relevant schema for bhyve tables:
```
sqlite3 ~cbsd/var/db/local.sqlite ".schema bhyve"
```

**Comment by olevole** [comment]
> INSERT INTO jails VALUES('vm_name',0,'/zroot_slot6_fbase2/vm_name'
> env workdir="/zroot_slot6_fbase2/usr/jails" 

There is an error in one of these lines. If working directory `/zroot_slot6_fbase2/usr/jails` then 'path' field in `jails` should be '**/zroot_slot6_fbase2/usr/jails**/jails/vm_name`

**Comment by JEAholding** [comment]
`sqlite3 /zroot_slot6_fbase2/usr/jails/var/db/local.sqlite "SELECT * from bhyve" ; `

I dont see this table in the sqlite db. 

Any comment on this ? What might be the reason?

**Comment by olevole** [comment]
Unfortunately, it’s hard for me to say in what condition your system is after the crash. It is not very clear how much information you could lose.

You can check the schema of the `bhyve` table on any other working system ( `.schema bhyve` ) or try to create it by the CBSD:
```
env workdir=/zroot_slot6_fbase2/usr/jails /usr/local/bin/cbsd /usr/local/cbsd/misc/updatesql /zroot_slot6_fbase2/usr/jails/var/db/local.sqlite /usr/local/cbsd/share/local-bhyve.schema bhyve
```

This will recreate the correct table if it does not exist.

What tables do you see in local.sqlite ?

```
sqlite3 /zroot_slot6_fbase2/usr/jails/var/db/local.sqlite ".tables"
```

If you use the ZFS file system, the data usually does not disappear. Perhaps your problem is something else.
