### ISSUE TITLE
VNET and Access to the external network

### ISSUE THREAD

**Issue by czkarex** [cbsd/cbsd#735]
FreeBSD version ( uname -a ): 
13.2-RELEASE
CBSD version ( cbsd version ): 
cbsd-13.2.1

I've got myself in a loop and need some advice. I can't access the external network from VNET jail and BHYVE guests. But only on new installations of HOSTS FreeBSD 13.2. I don't have the same problem on 13.1 installations and upgraded HOSTS to 13.2. Locally they are fully accessible (TCP/UDP) but not out. When I put a request from GUEST to the internet, it doesn't work - e.g., it returns one ping and then waits. When the log is read from the router, the request from the GUEST is asked as the HOST IP (On other HOSTS with version 13.1, GUESTS are asked with their own IP). But this only applies to the requests outside the local network, if, e.g., I ping the local IP of the router, the ask to the router is read from the GUEST IP, not the HOST.
Thanks, Karel

**Comment by olevole** [comment]
It's hard to say anything without detailed information ( ifconfig, NET/jail settings, NAT? Internal or external IP?. ).

If you are using CBSD NAT (via `pf`), please try `cbsd_nat_skip_natip_network=1` settings in ~cbsd/etc/cbsd-pf.conf , this is the only thing that has changed in the last few months. E.g.:

options1:
```
echo 'cbsd_nat_skip_natip_network=1' > ~cbsd/etc/cbsd-pf.conf
```

cbsd natoff
cbsd natcfg  (pf)
cbsd naton

// check access

options2:
```
echo 'cbsd_nat_skip_natip_network=0' > ~cbsd/etc/cbsd-pf.conf
```

cbsd natoff
cbsd natcfg  (pf)
cbsd naton

// check access


If you don't use CBSD NAT/pf, please paste full `ifconfig` output from the host, `cbsd jls display=jname,ip4_addr` + Firewall  rules.

**Comment by czkarex** [comment]
I appreciate your support. I am using pf - cbsd-nat, and "options1" was hitting the bull's eye... :-)

Thank you. Karel
