### ISSUE TITLE
Certbot requests to obtain or renew an SSL certificate fail if cbsdd is running.

### ISSUE THREAD

**Issue by PaddyMac** [cbsd/cbsd#736]
FreeBSD version ( uname -a ): 13.2-RELEASE
CBSD version ( cbsd version ): 13.2.1
py39-certbot version: 2.4.0,1

I had a jail set up and deleted it just to see if that would resolve the issue. It didn't. Just having the cbsdd daemon running is sufficient. I am using CBSD's PF NAT, and I can only assume that this is probably somehow responsible. In any case, I have not edited the default config files in ~cbsd/etc, so cbsd's default configuration somehow prevents Let's Encrypt's Certbot from obtaining or renewing an SSL certificate whether in standalone mode or using a plugin such as for Nginx. Shutting down cbsdd allows Certbot to work without any problem.

**Comment by olevole** [comment]
Can you check/test CBSD PF/NAT (_cbsd_nat_skip_natip_network_)  settings for you? E.g.: https://github.com/cbsd/cbsd/issues/735#issuecomment-1534442494 .
Perhaps I chose the wrong default value for `cbsd_nat_skip_natip_network`

**Comment by PaddyMac** [comment]
The file ~cbsd/etc/cbsd-pf.conf does not exist by default. However defaults/cbsd-pf.conf has the line cbsd_nat_skip_natip_network=0 as the default value. So I created ~cbsd/etc/cbsd-pf.conf and added the line cbsd_nat_skip_natip_network=1 then restarted cbsdd. Certbot failed. I tried again after setting it to 0 and restarting cbsdd. Certbot still failed. It only succeeds if I stop cbsdd. So it appears this parameter is not responsible.

However, on a hunch I opened up ~cbsd/etc/pfnat.conf and commented out two lines:

nat on bce0 from 10.0.0.0/8 to ! 10.0.0.0/8 -> 192.168.1.62 # // Setup by CBSD NAT
#nat on bce0 from 172.16.0.0/12 to ! 172.16.0.0/12 -> 192.168.1.62 # // Setup by CBSD NAT
#nat on bce0 from 192.168.0.0/16 to ! 192.168.0.0/16 -> 192.168.1.62 # // Setup by CBSD NAT

My jail was assigned an IP address on the 10.0.0.0 network, so I probably don't need the other blocks of IP addresses NATed. Then I restarted cbsdd. Certbot (which was being run on the 192.168.0.0 network) succeeded.

I mostly accepted the default values offered when I initialized cbsd, so I don't know if this is a fault on the part of the default configuration or some fault on my part. But at least this has resolved my issue.

**Comment by olevole** [comment]
you don't need to restart `cbsdd`: NAT config file is configured via `cbsd natcfg` + `cbsd naton`, so it was necessary to repeat the steps I referred:

echo 'cbsd_nat_skip_natip_network=1' > ~cbsd/etc/cbsd-pf.conf
```
cbsd natoff
cbsd natcfg (pf)
cbsd naton
```

Also default RFC1918 networks for NAT can be overwritten (default values: `cbsd_nat_networks="10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"`), in your case:

1)
```
cat > ~cbsd/etc/cbsd-pf.conf  <<EOF
cbsd_nat_networks="10.0.0.0/8" 
EOF
```

2)

```
cbsd natoff
cbsd natcfg
cbsd naton
```

as a result, you will get the configuration that you created by hand ^^
