### ISSUE TITLE
jexec jname='*' висит

### ISSUE THREAD

**Issue by satriani-vai** [cbsd/cbsd#737]
Приветствую, 

Вбиваем 

```
# cbsd jexec jname='*' pkg update && pkg upgrade -y && pkg audit -F
Hint: Press 'Ctrl+t' to see last logfile line for active task
 * [jexec: pending: 8:[ jail1 jail2 jail3 jail4 jail5 jail6 jail7 jail8], active: 0]
```

и ждём с моря погоды... приходится применять Ctrl + z чтобы выйти.

Баг или я чего-то не догоняю?

Всем добра!

FreeBSD version ( uname -a ): FreeBSD ServBSD 13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC amd64

CBSD version ( cbsd version ): 13.2.3

**Comment by olevole** [comment]
А `cbsdd_enable` в /etc/rc.conf присутствует и `ps axfww |grep cbsdd |grep -v grep` - процесс имеется?
Также инфо по этой теме:
```
cbsd task mode=list
```

после попытки (или параллельно посмотреть)

**Comment by satriani-vai** [comment]
```
# sysrc -a | grep cbsd
cbsd_workdir: /jails
cbsdd_enable: YES
cbsdrsyncd_enable: YES
cbsdrsyncd_flags: --config=/jails/etc/rsyncd.conf`
```


> `ps axfww |grep cbsdd |grep -v grep`

не выдаёт ничего, как и 

> `cbsd task mode=list`

**Comment by olevole** [comment]
надо чтобы работал cbsdd

**Comment by satriani-vai** [comment]
БлагоДарю.
завёл в ручную  `# service cbsdd start`

Почему не заводится автоматом? °_°

**Comment by olevole** [comment]
cbsdd_enable=YES  по идее делает это автоматом, но возможно по какой-то причине он был срублен (или крешнут)? надо проверить это с очередным ребутом на твоем хосте.
