### ISSUE TITLE
Jail kernel "broken" after version bump

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#739]
CBSD version:  `13.2.3`

I updated an "ancient" jail from 12.1 to 13.1 and then to 13.2. I did this via:
```
cbsd jset ver=13.1 jname=<jail_name>
```
Followed by the mandatory:
```
cbsd etcupdate ...
```
The jail starts just fine. However, it reports two different versions (probably world vs. kernel):
```
# freebsd-version
13.2-RELEASE
``` 
```
# freebsd-version -k
freebsd-version: unable to locate kernel
```
and:
```
# uname -a
FreeBSD ugfx_community.simulton.com 12.1-RELEASE FreeBSD 12.1-RELEASE amd64
```
Not sure what went wrong but... how do I fix this?

**Comment by olevole** [comment]
please check first info from: https://github.com/cbsd/cbsd/issues/723#issuecomment-1381057439

**Comment by olevole** [comment]
https://github.com/cbsd/cbsd/issues/709#issuecomment-1230837923

**Comment by Tectu** [comment]
That did the trick - clearly I should have been familiar with this :D

Thank you!
