### ISSUE TITLE
Also No Issue, Thanks, But....   

### ISSUE THREAD

**Issue by joeljohnston** [cbsd/cbsd#743]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD jjstudio 13.2-STABLE FreeBSD 13.2-STABLE GENERIC amd6

CBSD version ( cbsd version ): 13.2.5

Firstly Thank You,

But Also, 

How hard is it to create new linux profiles for jails, specifically ubuntu 22.04 (jammy)?  What's the best place to start to create such a thing and then (hopefully) contribute it back for everyone to use?  

Best,
Joel

**Comment by olevole** [comment]
Hi, Thanks for feedback.

Jails in CBSD described in two places - the first is the `profile` itself (a logical named group of parameters):

1) https://github.com/cbsd/cbsd/blob/develop/etc/defaults/jail-freebsd-ubuntu_jammy.conf

And second, functions to get `rootfs`. Functions to get FreeBSD base/rootfs is `get_base` https://github.com/cbsd/cbsd/blob/v13.2.6/subr/system.subr#L113 , but Linux-based rootfs at the moment it is a separate script, e.g.:

jammy:
https://github.com/cbsd/cbsd/blob/develop/share/FreeBSD-jail-ubuntu-jammy-system-skel/tests/00.check_distribution.sh

bookworm:
https://github.com/cbsd/cbsd/blob/develop/share/FreeBSD-jail-debian-bookworm-system-skel/tests/00.check_distribution.sh

and so on..

I don't really like using bootstrap (besides, it's only for deb/apt-based distros) and in the next version of CBSD I plan to remake it to get the `rootfs` tarball, as it was done for FreeBSD.

ps: any of my experiments and attempts to use Linux containers suggest that it is better to use `bhyve` instead (and cbsd has very powerful tools in the form of cloud profiles support).
