### ISSUE TITLE
CBSD 13.2.6 does not create mount-point for /usr/home

### ISSUE THREAD

**Issue by tm-up** [cbsd/cbsd#745]
Hi Oleg

I've just noticed that on FreeBSD 13.2 with CBSD 13.2.6, the /usr/home will not be mounted. It works on other machines with CBSD <13.2.6 and FreeBSD 13.2. And on the affected machine, it used to work until the upgrade to FreeBSD 13.2 and 13.2.6.

The fstab in jails-fstab look fine (have the entry for /usr/home nullfs).
I see an error message when starting the jail (jstart):

`mkdir: /usr/jails/jails/softkeyjail/usr/home: Read-only file system`

Do you have an idea why this could be?

Thanks and best regards,
-Urs

**Comment by olevole** [comment]
Hi,

Thanks for reporting. Its not CBSD regression - some time ago FreeBSD got rid of /usr/home location, CBSD base reflect this changes:

https://cgit.freebsd.org/src/commit/?id=9a6a948128c9e2e39ea728e5f60b8bb82c9c1fca
https://cgit.freebsd.org/src/commit/?id=1186ef86c3e18c7ed7e458260b73794c60aad7a1
https://cgit.freebsd.org/src/commit/?id=8955236a10137a1b645e642baf4eaca9c6460547
[...]

Unfortunately, I did not have time to add automatic migration of `fstab` records  (for example, through sed(1) ).
 Just correct these entries yourself for your containers, please edit:

_~cbsd/jails-fstab/**JNAME**/fstab_   

and replace '/usr/home' by /home'.

e.g:

```
find ~cbsd/jails-fstab/ -type f -name fstab | xargs sed -i.bak -e 's:/usr/home:/home:g'
```

PS: If you want to continue to use /usr/home, you need to create '/usr/home' in basejail hier first:
```
cd ~cbsd/basejail/base_amd64_amd64_**XXX**/usr
mkdir home
```

Please reopen if you need further advice on this issue.
