### ISSUE TITLE
Jails with baserw=0 upgrade 13.2 -> 14.0 issue: error while logging to jail

### ISSUE THREAD

**Issue by michalszmidt** [cbsd/cbsd#748]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
`14.0`

CBSD version ( cbsd version ): 
`14.0.1`

After I fetched 14.0 base I did:
```bash
cbsd jset jname=xxx ver=14.0
cbsd etcupdate mode=resolve jname=xxx
```
and got:
`jlogin jexec errcode: 1: /usr/bin/nice -n 1   /usr/sbin/jexec 23 /usr/bin/login -f root`

**Similar issue to** #718 mind the difference between jexec login command _path_

Fortunately I'm able to rever back using (...) jset=13.2 (...) and it starts.
(I also have snapshots)

How to properly upgrade baserw=0 jails when ABI changes?

Nothing broke when I was doing 13.1 -> 13.2 for this jails

**Comment by mergar** [comment]
how long ago was this 13.2 container created? ? if it was created more than a year ago, most likely this is a known issue/error and it has already been fixed. For example, if you create a new container on latest CBSD:

cbsd jcreate jname=xxx runasap=1 ver=13.2

and try to perform upgrade:

`cbsd jstop jname=xxx`
`cbsd jset ver=14.0 jname=xxx`
`cbsd jstart xxx`

will there be a problem with cbsd etcupdate ?

PS: also cbsd etcupdate should create a backup in ~cbsd/jails-system/jail/etcupdate/. Additionally, cbsd suggests using the "mode=diff" params first so you can see what the script will try to change (remove) before applying it.

**Comment by olevole** [comment]
@michalszmidt This is most likely due to changes to pam.d in 14.x. Yes, `etcupdate` should have corrected the situation, but I can’t say anything without logs.

You can make sure that the problem is not in the ABI by trying to execute 'chroot', instead of 'jlogin':
```
chroot ~cbsd/jails/jails/<jname> /bin/csh
```

if it works try syncing /etc/pam* from host (e.g. ~cbsd/basejail/base_amd64_amd64_14.0/etc/pam.d ) into jail's /etc
Most likely the `etcupdate` did not work as expected in your case ( please post `cbsd etcupdate jname=xxx  from=13.2 to=14.0 mode=diff` ). 

In my tests ( cbsd etcupdate jname=dnsmasq **mode=update** from=13.2 to=14.0 ): https://pastebin.com/9j2gEE33

**Comment by michalszmidt** [comment]
@olevole @mergar
Thanks for 1st class support!

You were right, I can chroot there so I tried syncing pam.d.

It worked!

So for others here's what I did:

1.  Update base and start jail
```
cbsd jset jname=xxx ver=14.0
cbsd etcupdate mode=resolve jname=xxx
cbsd jstart xxx
```
2. Should be there, but you can create quick backup of `/etc/pam.d` just in case
`rsync -avhSP  ~cbsd/jails/jails/xxx/etc/pam.d /somwhere`

3. Sync it with new base
`rsync -avhSP ~cbsd/basejail/base_amd64_amd64_14.0/etc/pam.d/ ~cbsd/jails/xxx/etc/pam.d/` 

4. Now you can login to jail
`cbsd jlogin xxx`

5. Fix pkg and ABI changes
```
pkg-static bootstrap -f
pkg update
pkg upgrade
```

6. Restart and you are good to go

If I could only suggest documenting it somehow?

Thank you so much!

**Comment by olevole** [comment]
@michalszmidt thanks for the documentation/info. However, I felt like an `etcupdate` should handle things like this. I'll try to double check when I have time!
