### ISSUE TITLE
Module installation inside a jail

### ISSUE THREAD

**Issue by satriani-vai** [cbsd/cbsd#749]
Mandatory info for bug reports: Как установить модуль внутри клетки?
Есть проблемы с конкретно данным модулем.

```
# kldload mac_portacl
kldload: can't load mac_portacl: Operation not permitted

```
```
# service start portacl
start does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
```
Целью является установка вебсервера Caddy в клетке по данной инструкции: https://wiki.freebsd.org/ThomasHurst/Caddy#VNET_Jails

FreeBSD version ( uname -a ): FreeBSD ServBSD 14.0-RELEASE-p2 FreeBSD 14.0-RELEASE-p2 #0: Tue Dec  5 00:31:31 UTC 2023     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64

CBSD version ( cbsd version ): 14.0.0

**Comment by olevole** [comment]
насколько я знаю, в jail нет возможности грузить ядерные модули - kldload mac_portacl нужно делать в хост-окружении
