### ISSUE TITLE
"unexpected operator" when executed in folder with space

### ISSUE THREAD

**Issue by lapo-luchini** [cbsd/cbsd#750]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
`FreeBSD deepie.home.lapo.it 13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC amd64`

CBSD version ( cbsd version ): 
`14.0.2`

This is what I did:
```sh
% mkdir 'a b'
% cd 'a b'
% sudo cbsd jlogin nextcloud
[: /home/lapo/a: unexpected operator
Last login: Thu Dec 21 18:14:20 on pts/34
FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC
nextcloud:/root@[18:21] #
```

**Comment by olevole** [comment]
We need to quotas CBSD_CWD vars, for this condition to work correctly:
> if [ -r ${Makefile} ]; then

There are several similar places in the CBSD code and this needs to be checked throughout the code. However, [this commit](https://github.com/cbsd/cbsd/commit/adffae89dcced16cec95981f0d2d42c06d272e3c) fix issue with `jlogin`.

ps/offtopic: thanks for using VictroriaMetrics on FreeBSD ;-)))))
