### ISSUE TITLE
Semi broken jail after base upgrade

### ISSUE THREAD

**Issue by Tectu** [cbsd/cbsd#751]
FreeBSD version ( uname -a ): `14.0-RELEASE-p2`
CBSD version ( cbsd version ): `14.0.2`

I upgraded a jail from `13.2` to `14.0` doing this:
```shell
cbsd jset ver=14.0 jname='myjail'
```
After starting it, I ran `etcupdate`:
```shell
cbsd etcupdate jname=silo mode=update from=13.2 to=14.0
```
Since then, the jail cannot mount ZFS datasets I'm passing through. When starting the jail:
```plain
mkdir: /usr/jails/jails/silo/usr/home: Read-only file system
```
When logging into the jail, `/home` is empty (this used to contain a user named `jbo`). 
Also, when doing something basic as `pkg update` inside the jail:
```
ld-elf.so.1: Shared object "libssl.so.111" not found, required by "pkg"
```
Any ideas what is going on here?

**Comment by Tectu** [comment]
Not sure if this is related but I created a new fresh 14.0 jail and tried to pass through some ZFS datasets and on each dataset I get this upon `jstart`:
```plain
cannot mount '/usr/home/jbo/storage/backups': failed to create mountpoint: Read-only file system

[...]

cannot mount '/usr/home/jbo/storage/backups': failed to create mountpoint: Read-only file system
property may be set but unable to remount filesystem
```
The `readonly` property on the ZFS datashets of the hosts are all set to `off`.

**Comment by olevole** [comment]
FreeBSD changed the default path to home directory - you need to change all path to `/home` instead of `/usr/home`. Somethins like that if you use ZFS mount via CBSD fstab:
```
find ~cbsd/jails-fstab/ -type f -name fstab | xargs sed -i.bak -e 's:/usr/home:/home:g'
find ~cbsd/jails-fstab/ -type f -name fstab.local | xargs sed -i.bak -e 's:/usr/home:/home:g'
```

**Comment by olevole** [comment]
Also when you upgrade jail from 13.x, please make sure you have synchronized the `/etc/pam.d` content as there have been changes that break the login, see: https://github.com/cbsd/cbsd/issues/748

**Comment by Tectu** [comment]
Thank you for your help, @olevole !
