### ISSUE TITLE
Страница недосягаема кода использую префикс в настройках клетки

### ISSUE THREAD

**Issue by satriani-vai** [cbsd/cbsd#752]
Ввожу
  
`# cbsd jset jname=WEB1 ip4_addr="10.0.0.1,81.43.19.20/29"`
сайты недосягаемы

ввожу
`# cbsd jset jname=WEB1 ip4_addr="10.0.0.1,81.43.19.20,81.43.19.21,81.43.19.22,81.43.19.23,81.43.19.24,81.43.19.25,81.43.19.26,81.43.19.27"`
всё работает

Публичные IP с префиксом не работают?

FreeBSD version ( uname -a ): FreeBSD ServBSD 14.0-RELEASE-p4

CBSD version ( cbsd version ): 14.0.0

**Comment by olevole** [comment]
Как `ifconfig` на хосте выглядит при префиксах? CBSD всего лишь 'проксирует' настройку ( если не указан префикс, то используется /32, иначе - пишет as-is) при вызове
```
ifconfig <iface> <IP> alias
```

Те, без CBSD будет также, если что-то неправильно в рутинге.

**Comment by satriani-vai** [comment]
```
# cat /etc/rc.conf
...
ifconfig_re0="DHCP"
ifconfig_re0_alias0="inet 81.43.19.20 netmask 255.255.255.248"
...

```

**Comment by olevole** [comment]
Я тут увы, не смогу никак помочь или проконсультировать, тк что-то FreeBSD-специфичное. Аналогичное поведение будет и без CBSD, если повторить этот сетап и надо смотреть как работает роут в FreeBSD. 

Если интересно, конкретный кусок кода, который отвечает за инициализацию:

https://github.com/cbsd/cbsd/blob/v14.0.2/tools/makejconf#L256-L277

Те, если сделаешь

```
cbsd makejconf jname=test1 out=/tmp/test1.jconf
```

То получишь в /tmp/test1.jconf тот самый оригинальный конфиг для jail(8), где прописаны IP адреса `as-is`. 

Это можно использовать для дальнейшего расследования вопроса, чтобы исключить CBSD (те, что поправить в ней - я не знаю)
