### ISSUE TITLE
Error Running: cbsd module mode=install clonos-database

### ISSUE THREAD

**Issue by cjemorton** [cbsd/cbsd#755]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD Zeus 13.2-RELEASE-p4 FreeBSD 13.2-RELEASE-p4 GENERIC amd64

CBSD version ( cbsd version ): 
14.0.3

I try to run: `cbsd module mode=install clonos-database` and it doesn't do anything but throw this error. Doesn't really say error, but as far as I can tell it's not actually installing clonos-database.

`root@Zeus:/usr/local/cbsd/modules # cbsd module mode=install clonos-database
VENDOR=amd
LOGNAME=root
LANG=en_US.UTF-8
PAGER=less
OSTYPE=FreeBSD
CBSD_PWD=/usr/local/cbsd/modules
MACHTYPE=x86_64
MAIL=/var/mail/root
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
EDITOR=nano
HOST=Zeus
PWD=/var/empty
freebsdhostversion=1302001
GROUP=wheel
NO_CBSD_HISTORY=yes
TERM=screen
CBSD_APP=module
HOME=/root
USER=root
workdir=/usr/jails
VIDEO_FORMAT=NTSC
PS1=cbsd@\h>
SHELL=/bin/csh
HOSTTYPE=FreeBSD
MM_CHARSET=UTF-8
BLOCKSIZE=K
SHLVL=2
module: MODULE_DIR != /usr/local/cbsd/modules in manifest: amd
root
en_US.UTF-8
less
FreeBSD
/usr/local/cbsd/modules
x86_64
/var/mail/root
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
nano
Zeus
/var/empty
1302001
wheel
yes
screen
module
/root
root
/usr/jails
NTSC
cbsd@\h>
/bin/csh
FreeBSD
UTF-8
K
2
/usr/local/cbsd/modules/clonosdb.d`

**Comment by olevole** [comment]
This command should have run this line:
```
/usr/local/bin/git clone --depth=1 --single-branch https://github.com/cbsd/modules-clonos-database.git /usr/local/cbsd/modules/clonosdb.d
```

Can you re-run `cbsd module mode=install clonos-database` with CBSD_DEBUG and paste output ? e.g.:
```
env CBSD_DEBUG=1 cbsd module mode=install clonos-database
```
