### ISSUE TITLE
custom jail creation profile is not listed in jconstruct-tui

### ISSUE THREAD

**Issue by mfrueh** [cbsd/cbsd#757]
Hi and first of all: thanks for your work on this awesome project!

### Mandatory info for bug reports:

FreeBSD version ( uname -a ): `FreeBSD hostname 14.0-RELEASE-p5 FreeBSD 14.0-RELEASE-p5 #0: Tue Feb 13 23:37:36 UTC 2024     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64`

CBSD version ( cbsd version ): `14.0.3`

### Bug description:
I have a custom jail creation profile in `$workdir/etc/` with a `jail_profile` name and `jail_active` set to 1, as described in the [jail profiles docs](https://www.bsdstore.ru/en/13.0.x/wf_profiles_ssi.html). However when I start `jconstruct-tui`, my profile is not listed.

After a quick look [in the sources](https://github.com/cbsd/cbsd/blob/09610d6a853703d710e067029290f0c428c7940d/jailctl/jconstruct-tui#L318) it seems like the profile selection menu is cached at `$workdir/tmp/get_construct_profile.menu` and this file is only deleted, if the default profile in `$workdir/etc/jail-freebsd-default.conf` is set to `default_profile="default"`. I have indeed another profile set as default.

I have found two workarounds to get my custom profile listed:

1. delete the cache file at `$workdir/tmp/get_construct_profile.menu`, or
2. set the `default_profile` back to "default"

However it would be nice, if the list would be automatically regenerated if the profiles change.

**Comment by olevole** [comment]
Thanks for the detailed description.

Now we use MD5-based CRC for profile's content. Thus, we now drop the cache file not only when a profile is added, but also when at least one byte in any profile changes:

![image](https://github.com/cbsd/cbsd/assets/926409/8146d1bb-c2f3-45e7-b24e-eebdc4fb5358)

release planned for early March
