### ISSUE TITLE
14.0.5 - cbsd_md5: not found

### ISSUE THREAD

**Issue by jas-s2r** [cbsd/cbsd#759]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
FreeBSD freebsd..local 14.0-RELEASE-p5 FreeBSD 14.0-RELEASE-p5 #0: Tue Feb 13 23:37:36 UTC 2024

CBSD version ( cbsd version ): 
14.0.6

After upgrading to cbsd 14.0.6 I tried to create a new bhyve VM running cbsd bconstruct-tui.
After running the command I get a warning:

/usr/local/cbsd/tools/get-profiles: /usr/local/cbsd/misc/cbsd_md5: not found

I checked for cbsd_md5 inside cbsd package and it was not found.

pkg info --list-files cbsd | grep md5

[freebsd:/usr/local/cbsd/misc $]> pkg info cbsd
cbsd-14.0.6
Name           : cbsd
Version        : 14.0.6
Installed on   : Sun Mar 17 19:55:04 2024 -03
Origin         : sysutils/cbsd
Architecture   : FreeBSD:14:amd64
Prefix         : /usr/local
Categories     : sysutils
Licenses       : BSD2CLAUSE
Maintainer     : olevole@olevole.ru
WWW            : https://www.bsdstore.ru
Comment        : Yet another FreeBSD Jail, XEN and Bhyve Management Utility

**Comment by olevole** [comment]
Forget to add cbsd_md5 directory to Makefile/pkg-plist. 

work-around:
```
cd /usr/ports
fetch -o /tmp/cbsd-14.0.6_1.diff https://www.bsdstore.ru/trash/cbsd-14.0.6_1.diff
patch < /tmp/cbsd-14.0.6_1.diff
make -C sysutils/cbsd reinstall
```


diff patch:
```
--- a/sysutils/cbsd/Makefile
+++ b/sysutils/cbsd/Makefile
@@ -1,5 +1,6 @@
 PORTNAME=      cbsd
 DISTVERSION=   14.0.6
+PORTREVISION=  1
 CATEGORIES=    sysutils
 
 MAINTAINER=    olevole@olevole.ru
@@ -58,6 +59,8 @@ do-install:
                ${STAGEDIR}${PREFIX}/bin
        ${INSTALL_PROGRAM} ${WRKSRC}/misc/src/sipcalc/sipcalc \
                ${STAGEDIR}${PREFIX}/cbsd/misc
+       ${INSTALL_PROGRAM} ${WRKSRC}/misc/src/cbsd_md5/cbsd_md5 \
+               ${STAGEDIR}${PREFIX}/cbsd/misc
        ${RM} -r ${STAGEDIR}${PREFIX}/cbsd/bin/cbsdsh \
                ${STAGEDIR}${PREFIX}/cbsd/bin/src \
                ${STAGEDIR}${PREFIX}/cbsd/lib \
diff --git a/sysutils/cbsd/pkg-plist b/sysutils/cbsd/pkg-plist
index 7fb6b8076a..f50666b714 100644
--- a/sysutils/cbsd/pkg-plist
+++ b/sysutils/cbsd/pkg-plist
@@ -392,6 +392,7 @@ cbsd/man/cbsd-jls.8
 cbsd/man/cbsd.8
 cbsd/misc/cbsd_dot
 cbsd/misc/cbsd_fwatch
+cbsd/misc/cbsd_md5
 cbsd/misc/cbsdlogtail
 cbsd/misc/cbsdtee
 cbsd/misc/chk_arp_byip
```

I'll be submitting to the FreeBSD ports tree soon
