### ISSUE TITLE
get_construct_exec_start/stop not found

### ISSUE THREAD

**Issue by ilmarh** [cbsd/cbsd#76]
While trying to follow Debian-kfreebsd jail construction (https://www.bsdstore.ru/ru/articles/installing_kfreebsd.html), and change ece_start/stop values, i've got "get_construct_exec_start/stop not found". These functions are also absent in settings-tui.subr script.
Changing exec_start/stop values in rc.conf_<jailname> in jails-system/<jailname> also have no effect

PS. I tried to expand settings-tui.subr with something like 
```
get_construct_exec_start()
{
        title=" exec_start "
        prompt="${exec_start_msg}"
        defaultitem="${exec_start}"
        cbsd_inputbox_simple && exec_start="${mtag}"
}

get_construct_exec_stop()
{
        local _input
        f_dialog_title " exec_stop "
        f_dialog_input _input "${exec_stop_msg}" "${exec_stop}" "${_message}" || return $?
        exec_stop="${_input}"

}
```

but any of these end up with *eval:1:Syntax error: Unterminated quoted string* error message with no effect.

**Comment by olevole** [comment]
Looks like this docs outdated a little. If you want kfreebsd in jail, just select 'kfreebsd' profile in 
~~~
cbsd jconstruct-tui  -> profile -> kfreebsd
~~~

All steps for getting kfreebsd already commited in CBSD
PS: I hope you use last version of CBSD -- 10.3.2 (from the ports)

Let me know if you meet any issue with new information

**Comment by ilmarh** [comment]
Ohhh, yes. It works like a charm!
