### ISSUE TITLE
bhyve pci passthrough

### ISSUE THREAD

**Issue by chil037** [cbsd/cbsd#760]
Mandatory info for bug reports:
bhyve pci passthrough not working

FreeBSD version ( uname -a ): 
FreeBSD nas.nx-gen.org 14.0-RELEASE-p5 FreeBSD 14.0-RELEASE-p5

CBSD version ( cbsd version ): 
CBSD version 14.06

Since CBSD version 13.2 to current the following command do not update the bhyve.conf file under the vm folder:

cbsd bhyve-ppt mode=attach jname=test ppt="2/0//0"

I noticed in the file byyve.conf is empty for "passthr=``" after the entering the above command.  Version 13.1 update the bhyve.conf file with passthr=`2/0/0` using the attach command and remove with the mode=detach.

**Comment by olevole** [comment]
This command just applies the entry in the SQLite3 database, to check:
```
sqlite3 ~cbsd/var/db/local.sqlite "SELECT * FROM bhyveppt"
```

You need to start VM  to have an effect.

**Comment by chil037** [comment]
Hi olevole.  I got an error "Error: in prepare, no such table: bhyveppt".  This time I noticed a warning when I start the vm that pci passthrough required '-S' options so I follow the instruction:  
cbsd bset bhyve_wire_memory=1 jname=test

Restart the vm.  still got the same error no such table for the bhyveppt so I start looking at other tables and found the ppt passthrough in the "pcibuis" table instead.

All good.  pci passthrough is working again.

thanks oleolvle.

**Comment by olevole** [comment]
@chil037 I'm wondering why you don't have a 'bhyveppt' table in main database: https://github.com/cbsd/cbsd/blob/v14.0.6/sudoexec/initenv#L870

Can you do this manually and check if the table exists?
```
/usr/local/bin/cbsd /usr/local/cbsd/misc/updatesql ~cbsd/var/db/local.sqlite /usr/local/cbsd/share/local-bhyveppt.schema bhyveppt
```

e.g.:
```
sqlite3 ~cbsd/var/db/local.sqlite ".tables bhyveppt"
```

**Comment by chil037** [comment]
Hi @olevole.  I checked the ~cbsd/var/db/local.sqlite and the bhyveppt table is there and the attached pci passthrough is also in the table.  Sorry, I was looking previous in the ~cbsd/vm/test/local.sqlite.  Thanks @olevole, still learning.
