### ISSUE TITLE
Latest FreeBSD 14.0-RELEASE-p6 when rebooting the host, majority of the jails come up with no networking.

### ISSUE THREAD

**Issue by o1crimsor1o** [cbsd/cbsd#763]
Mandatory info for bug reports:
FreeBSD orbit 14.0-RELEASE-p6 FreeBSD 14.0-RELEASE-p6 #0: Tue Mar 26 20:26:20 UTC 2024     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64

CBSD version ( cbsd version ): 

root@orbit:/fast/vm # cbsd --version
14.0.6
root@orbit:/fast/vm #

root@orbit:/fast/vm # cbsd jls
JNAME    JID  IP4_ADDR      HOST_HOSTNAME            PATH                              STATUS
deimos   11   10.1.1.48/24  deimos.dasgeekhaus.org   /fast/vm/jails-data/deimos-data   On
europa   12   10.1.1.49/24  europa.dasgeekhaus.org   /fast/vm/jails-data/europa-data   On
io       13   10.1.1.44/24  io.dasgeekhaus.org       /fast/vm/jails-data/io-data       On
jupiter  14   10.1.1.42/24  jupiter.dasgeekhaus.org  /fast/vm/jails-data/jupiter-data  On
mars     15   10.1.1.41/24  mars.dasgeekhaus.org     /fast/vm/jails-data/mars-data     On
moon     16   10.1.1.40/24  moon.dasgeekhaus.org     /fast/vm/jails-data/moon-data     On
nyx      17   10.1.1.45/24  nyx.dasgeekhaus.org      /fast/vm/jails-data/nyx-data      On
phobos   18   10.1.1.47/24  phobos.dasgeekhaus.org   /fast/vm/jails-data/phobos-data   On
titan    19   10.1.1.46/24  titan.dasgeekhaus.org    /fast/vm/jails-data/titan-data    On
venus    20   10.1.1.43/24  venus.dasgeekhaus.org    /fast/vm/jails-data/venus-data    On
root@orbit:/fast/vm #

Everything is assigned with a static ip also.

When I reboot the host (it got reboot last night due to power outage so it was in theory the first time I've reboot since I rebuilt the host). It came up with ALL the jails being started with no networking, they didn't even have interfaces inside the jail. They had external nic (on the host) and nothing inside the jail. Just lo0

The host has the outside interface, but inside the jail it only had the loopback (lo0)

I rebooted the host again, and some jails came up with networking. I couldn't take more time to troubleshoot so I tried a cbsd jrestart "all the jail names" and it fixed them all up properly.

But having been thru 2 restarts where jails didn't come up. I'm worried now and I wanna look into this more, but I am not sure where to start.

**Comment by olevole** [comment]
Can you post output for:

1)
```
cbsd jls display=jname,ip4_addr,astart,vnet,boot_delay,jorder
```

2)
```
grep parallel ~cbsd/nc.inventory
```

3)
Also, if you have the opportunity to reboot the server again (or find the time of the previous reboot in log files), the cbsd logs would be interesting:
```
grep cbsd /var/log/messages
```

In theory, the CBSD has race protection and when creating interfaces. However, if there are errors in the logs related to the creation of the interface, you can try using some delay with each container, e.g.:
```
cbsd jset boot_delay=2 jname=europa
cbsd jset boot_delay=4 jname=io
cbsd jset boot_delay=6 jname=io
cbsd jset boot_delay=8 jname=jupiter
cbsd jset boot_delay=10 jname=mars
cbsd jset boot_delay=12 jname=moon
cbsd jset boot_delay=14 jname=nyx
cbsd jset boot_delay=16 jname=phobos
cbsd jset boot_delay=18 jname=titan
cbsd jset boot_delay=20 jname=venus
```
..

However, this will be a work-around, not a fix of the the problem. Therefore, the logs are quite interesting.

**Comment by o1crimsor1o** [comment]
1)
root@orbit:~ # cbsd jls display=jname,ip4_addr,astart,vnet,boot_delay,jorder
JNAME    IP4_ADDR      ASTART  VNET  BOOT_DELAY  JORDER
deimos   10.1.1.48/24  1       1     0           -
europa   10.1.1.49/24  1       1     0           -
io       10.1.1.44/24  1       1     0           -
jupiter  10.1.1.42/24  1       1     0           -
mars     10.1.1.41/24  1       1     0           -
moon     10.1.1.40/24  1       1     0           -
nyx      10.1.1.45/24  1       1     0           -
phobos   10.1.1.47/24  1       1     0           -
titan    10.1.1.46/24  1       1     0           -
venus    10.1.1.43/24  1       1     0           -
root@orbit:~ #


2)
root@orbit:~ # grep parallel ~cbsd/nc.inventory
parallel="5"
root@orbit:~ #


I haven't managed to reboot yet, I will try it this weekend and update. here. But the above is the info I have so far.

**Comment by olevole** [comment]
Hmm, **vnet=1**. I suspect there is a race condition when CBSD is looking for a next free epair(4).
I'll try to reproduce this on my lab soon.

ps: boot_delay should help you as temporary work-around

**Comment by olevole** [comment]
@o1crimsor1o ok, I think I understand what's going on.
CBSD has protection against race, but the lock is set with a short timeout (12 seconds, infinite lock protection).

If I understand correctly, your server uses a hard drive (not an SSD/NVME) and when boots it has a fairly high I/O load.

**Comment by olevole** [comment]
possible fix: https://github.com/cbsd/cbsd/commit/17f0a9b9befdae6b7c130af5d2e222474aa1b5eb

@o1crimsor1o can you change '12' to '120' in https://github.com/cbsd/cbsd/blob/v14.0.7/tools/get-next-nic#L180 ?

> cbsd_lock 120 ...

Most likely, your system will boot correctly, to check:
```
cbsd jexec jname='*' ifconfig eth0
```

when all your containers will be online. You should see the 'eth0' interface everywhere.

if that doesn't help, I need the logs:
```
grep cbsd /var/log/messages
```
