### ISSUE TITLE
jail: JailName: unknown parameter: allow.nfsd

### ISSUE THREAD

**Issue by GitHubinat0r** [cbsd/cbsd#768]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
13.2-RELEASE-p11
CBSD version ( cbsd version ): 
14.0.8

Just performed an upgrade of CBSD and now get the following when I attempt to start a jail:
jail: JailName: unknown parameter: allow.nfsd

If you can point me to where I can drop that parameter, I think that will function as a workaround. Thanks!

**Comment by mergar** [comment]
hmm, this option should not be available for FreeBSD 13 and has a corresponding check:

https://github.com/cbsd/cbsd/blob/ba4a39e598056e92dd6944d29e54ce3bef701306/tools/makejconf#L360

can you comment out the lines ( 360-367 ) in /usr/local/cbsd/tools/makejconf?

**Comment by GitHubinat0r** [comment]
I can't find the keywords and this might be a clue:
#!/usr/local/bin/cbsd
#v12.1.10
Did I miss an upgrade step for the past several releases???

I just found the latest version of the /usr/local/cbsd/tools/makejconf in the source code and replaced my version with it and everything works. I still have a copy of the old version if you wish to research what caused this failure.

**Comment by mergar** [comment]
this was recently fixed in the development branch and has not yet been released:  https://github.com/cbsd/cbsd/commit/f3444ec983225de41c253b29495d46cd1ed55121

@olevole new release ?)

**Comment by olevole** [comment]
Late to the party. That's right, this was fixed recently and has not yet been released. @mergar Thanks!
