### ISSUE TITLE
Looks like vulnerability

### ISSUE THREAD

**Issue by vlad-shabanov** [cbsd/cbsd#773]
Mandatory info for bug reports:
FreeBSD version ( uname -a ): all versions
CBSD version ( cbsd version ): 14.1.0, but also present in the current code

I dont want to publish it here. Can how can I submit the problem privately?

**Comment by olevole** [comment]
This does not appear to be a vulnerability, as information about it has been in the official documentation for over 10 years: https://www.bsdstore.ru/en/13.0.x/wf_jcreate_ssi.html

![image](https://github.com/user-attachments/assets/0a5f2f33-3a4f-4015-aada-37c971642fe9)

However, it is a good idea to remove the password completely in 14.1.1+
