### ISSUE TITLE
Unknown operator '|' when building CBSD from ports on FreeBSD 15

### ISSUE THREAD

**Issue by darbsh** [cbsd/cbsd#774]
Mandatory info for bug reports:

FreeBSD version: 
FreeBSD nasasaurus 15.0-CURRENT FreeBSD 15.0-CURRENT #0 main-n271646-f5ce3f4ef562: Mon Aug 12 19:09:27 UTC 2024     root@nasasaurus:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64

CBSD version:  
cbsd-14.1.0 from ports

I thought I'd give 15-CURRENT a try as a test host, and ran into an error when building from ports.

```
root@nasasaurus:~ # which make
/usr/bin/make
root@nasasaurus:~ # make -C /usr/ports/sysutils/cbsd
===>  Building for cbsd-14.1.0
make[1]: "/usr/ports/sysutils/cbsd/work/cbsd-14.1.0/bin/cbsdsh/Makefile" line 20: Unknown operator '|'
        in directory /usr/ports/sysutils/cbsd/work/cbsd-14.1.0/bin/cbsdsh
make[1]: Fatal errors encountered -- cannot continue
make[1]: stopped making "all" in /usr/ports/sysutils/cbsd/work/cbsd-14.1.0/bin/cbsdsh
*** Error code 1

Stop.
make: stopped making "all" in /usr/ports/sysutils/cbsd/work/cbsd-14.1.0
*** Error code 1

Stop.
make[1]: stopped making "/usr/ports/sysutils/cbsd/work/.stage_done.cbsd._usr_local" in /usr/ports/sysutils/cbsd
*** Error code 1

Stop.
make: stopped making "all" in /usr/ports/sysutils/cbsd
```

I didn't have any expectations considering CURRENT is unstable, but thought I'd report the error here anyway.

**Comment by darbsh** [comment]
It looks like this commit to bmake broke | and & in Makefiles.
https://github.com/NetBSD/src/commit/f7278694bb89e3a9223c47d9255c90d8120654af

**Comment by olevole** [comment]
The update will be sent to ports this weekend.

**Comment by olevole** [comment]
@darbsh https://cgit.freebsd.org/ports/commit/?id=e83b164736da2feb7aa2f03b212f48a6c4392751
