### ISSUE TITLE
Minor problem with linuxulator(ubintu) + jail

### ISSUE THREAD

**Issue by vlad-shabanov** [cbsd/cbsd#776]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD-15-CURRENT

CBSD version ( cbsd version ): 14.1.0

When I create linuxulator jail:
    sudo cbsd jcreate jname=JAILNAME jprofile=ubuntu_jammy allow_raw_sockets=1
and allow cbsd to fetch repo from dl.bsdstore.ru/img/...  it unlacks /usr/jails/basejail/base_amd64_amd64_jammy

```
$> ls -l /usr/jails/basejail/base_amd64_amd64_jammy
    ...
    lrwxrwxrwx   1 root wheel   7 Sep 23  2023 **lib** -> usr/lib
    ...
```

basejail has symlink 'lib' pointing to usr/lib

But 
```
$> ls -l /usr/jails/jails-data/JAILNAME-data/
   ...
   drwxr-xr-x   2 root wheel   2 Sep 23  2023 lib/
   ...

```
which has init/rw/... 

Jail is unable to start in this configuration.

The solution is 
```
cd ls -l /usr/jails/jails-data/JAILNAME-data/
mv lib/init/rw usr/lib/init/
rm -rf lib
ln -s usr/lib lib
```

**Comment by mekanix** [comment]
Installing linux jail through `debootstrap` produces this, so it's not strictly CBSD bug, but yes, it should work around it. Probably fixing a link after debootstrap finishes.

**Comment by olevole** [comment]
Unfortunately, I can't reproduce this behavior on the latest version of CBSD ( + FreeBSD 15.0-CURRENT) ;
Just in case, I updated ubuntu jammy tarbor (now: 22.04.5)

Please reopen if you see this issue on a new CBSD installation.
