### ISSUE TITLE
CBSD: Fetching inventory failed:

### ISSUE THREAD

**Issue by nopainnogainjoe** [cbsd/cbsd#78]
Hey,

I have a problem with some nodes. The error is: "CBSD: Fetching inventory failed:"
The node is added without a problem(ssh keys are in place) but when it comes to fetch the inventory from the remote node it fails. I think that is related to the fact that the local machine cannot get the sqlite file from the node

```
retr_db testnode
+ local '_rnode=testnode'
+ [ -z testnode ]
+ nodescp 'tryoffline=0' testnode:var/db/inv.testnode.sqlite /usr/jails/var/db/testnode.sqlite
+ [ 75 -eq 0 ]
+ echo -e '\033[0;35mCBSD: Fetching inventory failed: \033[0;32mtestnode\033[0m'
CBSD: Fetching inventory failed: testnode
+ retr_jdescr testnode
+ local '_rnode=testnode' _jname
+ [ -z testnode ]
+ [ ! -f /usr/jails/var/db/testnode.sqlite ]
+ return 0
+ retr_nodedescr testnode
+ local '_rnode=testnode' _files _i
+ [ -z testnode ]
+ [ ! -d /usr/jails/var/db/nodedescr ]
+ _files='descr role domain notes location'
+ nodescp 'tryoffline=0' testnode:node.descr /usr/jails/var/db/nodedescr/testnode.descr
+ chmod 0640 /usr/jails/var/db/nodedescr/testnode.descr
+ chown cbsd /usr/jails/var/db/nodedescr/testnode.descr
+ nodescp 'tryoffline=0' testnode:node.role /usr/jails/var/db/nodedescr/testnode.role
+ chmod 0640 /usr/jails/var/db/nodedescr/testnode.role
+ chown cbsd /usr/jails/var/db/nodedescr/testnode.role
+ nodescp 'tryoffline=0' testnode:node.domain /usr/jails/var/db/nodedescr/testnode.domain
+ chmod 0640 /usr/jails/var/db/nodedescr/testnode.domain
+ chown cbsd /usr/jails/var/db/nodedescr/testnode.domain
+ nodescp 'tryoffline=0' testnode:node.notes /usr/jails/var/db/nodedescr/testnode.notes
+ chmod 0640 /usr/jails/var/db/nodedescr/testnode.notes
+ chown cbsd /usr/jails/var/db/nodedescr/testnode.notes
+ nodescp 'tryoffline=0' testnode:node.location /usr/jails/var/db/nodedescr/testnode.location
+ chmod 0640 /usr/jails/var/db/nodedescr/testnode.location
+ chown cbsd /usr/jails/var/db/nodedescr/testnode.location
+ retr_fwcnt testnode
+ local '_rnode=testnode' _jname
+ [ -z testnode ]
+ [ ! -f /usr/jails/var/db/testnode.sqlite ]
+ return 0
+ /bin/rm -f /usr/jails/tmp/retrinv-log.24896
```

nlogin testnode works perfectly. 

What can I do to fix this thing?

**Comment by H1r0Sh1mA** [comment]
same issue here

**Comment by nopainnogainjoe** [comment]
Hey!

Any news with this bug?

Cheers!

**Comment by olevole** [comment]
Unfortunately still not yet. But i found bug with fd leaks. May be related to problem.  Please execute from the root:
~~~
fstat |grep cbsd |wc -l
~~~
If you see number greater then 20 - kill cbsdd process ASAP, old version have bug with fd leaks. Killing of cbsdd process not affects on existing jail/bhyve. And update CBSD to 10.3.3 version.
May be after server rebooting problem is gone. 

I can't reproduce issue, since I have only one FreeBSD server at the moment.

**Comment by nopainnogainjoe** [comment]
Hello, 

Even after updating CBSD 10.3.3 the active/open files are way above 150. 
On the old version 10.3.2_1 the open/active files are somewhere north of 300.000. 

I can't test the original bug at the moment but I'll let you know by tomorrow if it's fixed or not.

**Comment by olevole** [comment]
150 hmm, still big number. Can you check please tomorrow again this. at least, it should not increase

**Comment by H1r0Sh1mA** [comment]
after upgrade **fstat |grep cbsd |wc -l** returns 13 processes only. (this value is still consistent)
I will keep an eye on the situation and will report the result today later.

**Comment by nopainnogainjoe** [comment]
So over the night the numbers have increased slightly 207, 182, 154 and 191. I'll keep an eye on this.

**Comment by olevole** [comment]
@nopainnogainjoe still actual this ?)

**Comment by nopainnogainjoe** [comment]
Now the values are somewhere between 200 and 300. All the machines are running the latest cbsd version available in the ports system.

**Comment by olevole** [comment]
How about fetching inventory ?

**Comment by nopainnogainjoe** [comment]
That problem is long gone.

**Comment by olevole** [comment]
Cool.
