### ISSUE TITLE
updating from 14.1.0 to 14.1.2 breaks everything.

### ISSUE THREAD

**Issue by VVelox** [cbsd/cbsd#781]
Mandatory info for bug reports:

FreeBSD version ( uname -a ): FreeBSD nibbles0.vulpes.vvelox.net 13.3-RELEASE-p3 FreeBSD 13.3-RELEASE-p3 GENERIC amd64

CBSD version ( cbsd version ): 14.1.2

`cbsd bls` now shows no VMs.

**Comment by VVelox** [comment]
nc.inventory if it helps
```
nodename="nibbles0.vulpes.vvelox.net"
hostname="nibbles0.vulpes.vvelox.net"
nodeip="192.168.14.21"
nodedescr="(null)"
jnameserver="192.168.14.2,192.168.15.2"
nodeippool="192.168.12.0/24"
natip="(null)"
nat_enable="0"
fbsdrepo="1"
mdtmp="0"
repo="https://bsdstore.ru"
workdir="/storage/cbsd"
ipfw_enable="0"
fs="zfs"
zfsfeat="1"
jail_interface="auto"
ncpu="24"
physmem="136492703744"
memtype="(null)"
disks="cd0 da4 da1 da9 da3 da2 da0 da8 da7 da6 da5 ada1 ada0 nvd1 nvd0"
cpumodel="AMD Ryzen 9 7900 12-Core Processor "
cpufreq="3700"
kernhz="1000"
sched="ULE"
eventtimer="LAPIC(600) HPET(350) HPET1(350) HPET2(350) i8254(100) RTC(0)"
nics="igb0,igb1,igb2,igb3,bridge0,bridge1,wg0"
parallel="4"
stable="auto"
osrelease="13.3-RELEASE-p3"
hostarch="amd64"
vimage_feature="1"
racct="1"
sqlreplica="1"
domain="0"
platform="FreeBSD"
hammerfeat="0"
node_ip4_active="1"
node_ip6_active="0"
la="0.07 0.12 0.08"
is_virtual="physical"
freemem="126909739008"
statsd_bhyve_enable="1"
statsd_jail_enable="1"
statsd_hoster_enable="1"
cbsdver="14.1.2"
nodeip6pool="(null)"
nodeip6="(null)"
jail_feat="1"
xen_feat="0"
bhyve_feat="1"
mod_pkg_enabled="YES"
mod_bsdconf_enabled="YES"
mod_zfsinstall_enabled="YES"
```

**Comment by olevole** [comment]
"breaks everything" = "breaks bls" ? Or nothing works for you anymore ( jails, `cbsd jconstruct-tui`, `cbsd border`, `cbsd version`, .. ) ?

`bls` reads data from a SQLite3 database. Сan you check that the database contains data?

```
sqlite3 ~cbsd/var/db/local.sqlite "SELECT jname FROM jails WHERE emulator='bhyve'"
```


If the data exists, any error when you make a `cbsd initenv` command?
If data is missing, check the backup database in ~cbsd/var/db-XXXXXXX

Also, I would like to see the result for:

```
 /bin/sh -c 'env CBSD_DEBUG=1 cbsd bls 2>&1' | tee -a /tmp/xtrace_bls.txt
```

( please post /tmp/xtrace_bls.txt result )

**Comment by VVelox** [comment]
@olevole hmm... looks like it decided to change something during update...

Shows what is expected...

```
sqlite3 ~cbsd/var/db/inv.auto.sqlite "SELECT jname FROM jails WHERE emulator='bhyve'"
```

Does not...

```
sqlite3 ~cbsd/var/db/local.sqlite "SELECT jname FROM jails WHERE emulator='bhyve'"
```

was...

```
local.sqlite -> inv.auto.sqlite
```

now...

```
local.sqlite -> inv.nibbles0.vulpes.vvelox.net.sqlite
```

**Comment by olevole** [comment]
Hmm. Can you copy `inv.auto.sqlite` file into `inv.nibbles0.vulpes.vvelox.net.sqlite` yourself ? This will probably fix the problem.

And another interesting question for me - did you initialize cbsd in 'unattended mode' ?

E.g. `/usr/local/cbsd/sudoexec/initenv /usr/local/cbsd/share/initenv.conf` ?
I corrected the parameter with the 'auto' value in the latest version. This should not have any effect if you initialized cbsd manually

**Comment by VVelox** [comment]
Yeah. That fixed it.

**Comment by VVelox** [comment]
> Hmm. Can you copy `inv.auto.sqlite` file into `inv.nibbles0.vulpes.vvelox.net.sqlite` yourself ? This will probably fix the problem.
> 
> And another interesting question for me - did you initialize cbsd in 'unattended mode' ?
> 
> E.g. `/usr/local/cbsd/sudoexec/initenv /usr/local/cbsd/share/initenv.conf` ? I corrected the parameter with the 'auto' value in the latest version. This should not have any effect if you initialized cbsd manually

Nope. Ran `cbsd initenv` like normal post upgrade.

**Comment by olevole** [comment]
> 
> Nope. Ran `cbsd initenv` like normal post upgrade.

I meant the very first initialization: the 'auto' value appears only in initenv.conf sample ( /usr/local/cbsd/share/initenv.conf ). May be CBSD-REX ;) ?

**Comment by VVelox** [comment]
> > Nope. Ran `cbsd initenv` like normal post upgrade.
> 
> I meant the very first initialization: the 'auto' value appears only in initenv.conf sample ( /usr/local/cbsd/share/initenv.conf ). May be CBSD-REX ;) ?

First one? Honestly I forget. That was years ago.

**Comment by olevole** [comment]
Ok. Thanks for the report. I'll double check the latest changes.
