### ISSUE TITLE
Rexe command fails to complete its execution and hangs my terminal on hoster system

### ISSUE THREAD

**Issue by almmos** [cbsd/cbsd#782]
Mandatory info for bug reports:

**FreeBSD version ( uname -a ):** 
14.1-RELEASE-p5 FreeBSD 14.1-RELEASE-p5 GENERIC amd64

**CBSD version ( cbsd version ):** 
CBSD Project. Version 14.1.2

Hi there,

In order to better learn how to use **rexe** for some specific operations, as **root** on my node01 I tried to run, for testing purpose, the following command:
`cbsd rexe node=node02 cmd='date'`
or 
`cbsd rexe node=node02 date`

Every time I tried, the command fails to complete its execution, leaving my terminal unresponsive in some kind of infinite waiting state and the only option I have had, was to use the infamous **Ctrl C** to return to the CLI prompt.

I have tried again via **env DEBUG**, I have searched the code and I found that l[ine 327](https://github.com/cbsd/cbsd/blob/14.1.2/bin/rexe#L327) from bin/rexe file:
```
`${SSH_CMD} -oControlPath=${sshdir}/sockets/%r@%h:%p -t ${SSH_ARGS} ${TTOP} -C "/usr/local/bin/cbsd -c \"update_idle ${nodename}\"; ${THESCRIPT}"`
```
is the last line executed and where the execution hangs.

The above line of code use existing ssh connection to call the **cbsd shell** (/usr/local/bin/cbsd) builtin: **update_idle** on remote node named node02, using the **cbsd user**. We know that **cbsd user** is used because 2 lines above, the line 325 show us the SSH_ARGS with the option -l indicating our user:
```
`SSH_ARGS="-l ${cbsduser} -oBatchMode=yes -oStrictHostKeyChecking=no -oConnectTimeout=${connect_timeout} -q -oPort=${myport} -i ${mykey} ${myip}"`
```

As we [know that](https://github.com/cbsd/cbsd/issues/536#issuecomment-719478472) **cbsd must be run by root**, I don't know how to manage this.
Due to the fact that this remote call try to execute a builtin function, we cannot to individually add it to the cbsd_sudoers file.
As for testing and temporary workaround, I have added the full /usr/local/bin/cbsd to allowed commands in sudoers file and modified the call to execute via **sudo**. 
In this case the command finished flawless as suppose to do.

Please advice!

**Comment by almmos** [comment]
More information:

I have verified next commands on 2 different systems:
- on a hoster system with 14.1-RELEASE-p5 FreeBSD 14.1-RELEASE-p5 GENERIC amd64 and CBSD Project. **Version 14.1.0**
```
# su cbsd
$ cbsd -c version
```
the output is:
```
14.1.0
```
- on system with same 14.1-RELEASE-p5 FreeBSD 14.1-RELEASE-p5 GENERIC amd64, but with CBSD Project. **Version 14.1.2**
```
# su cbsd
$ cbsd -c version
```
the command fails to complete its execution and the terminal hangs
I am forced to use CtrlC to regain terminal control.

**Comment by olevole** [comment]
Hi! Thanks for reporting. Just for clarification: What does the command `cbsd node mode=list` show in your case ?

When `cbsd rexe` used it uses the `cbsd` user's (not root) to connect to the remote node.  

ps: the main idea of ​​connecting via SSH is to build a peer-to-peer network (when you can perform any actions with virtual environments (create/login/stop/start) on a remote node using a local installation). This approach has its pros and cons.
An alternative to building clusters is to use a broker and API: https://www.bsdstore.ru/en/broker_driven_sample_ssi.html + https://www.bsdstore.ru/en/cbsd_api_ssi.html

**Comment by almmos** [comment]
Hi!
Right now I have one cluster with 2 nodes, which I have already upgraded to the latest CBSD Version 14.1.2. 
On this one if I run **cbsd node mode=list** as root on node named bl91 I have the following output:
```
NODENAME  IP             PORT  KEYFILE                                                      STATUS     IDLE
bl92      192.168.50.33  22    /m2data/jails/.rssh/be14d40fba9fcbeaedf4ac76652f912f.id_rsa  Connected  6711
```
If I run the same command as cbsd user the terminal hangs.

More than that, trying to understand more I have run as **cbsd user** the following commands on the same hoster:
```
$ cbsd version
```
The output on terminal CLI is:
`14.1.2`
Running almost the same command but using the -c option like this:
```
$ cbsd -c version
```
The terminal hangs

I have another cluster with 3 nodes on CBSD Version 14.1.0. On this one all commands work as expected, including rexe.
On this other cluster (CBSD Version 14.1.0) both of this commands  `cbsd version` and `cbsd -c version` return the same result: `14.1.0`

What is the difference implemented by -c option?
Where can I find some documentation or information regarding this -c option?
Do you need more information from me?

**Comment by almmos** [comment]
Some more info.
On the 3 nodes cluster using CBSD Version 14.1.0 the output for **cbsd node mode=list** executed on bl04 hoster CLI is:
```
NODENAME  IP              PORT  KEYFILE                                                     STATUS     IDLE
bl02      192.168.50.201  22    /mdata/jails/.rssh/46ec61fe5da4298818220d0d1186e8f6.id_rsa  Connected  2333
bl03      192.168.50.202  22    /mdata/jails/.rssh/9014b5cd4d4ff3d6a221046ead6f8548.id_rsa  Connected  2333
```

On this cluster as **root** I can enter the cbsdsh shell and work from there, so for example command as **jls** show me the full list of jail containers from all 3 nodes in the cluster.
But **I can su to cbsd user** and from there I can enter the cbsdsh shell and in the same way I can execute **jls** and have the full listing returned to my terminal.

On the CBSD Version 14.1.2 cluster this is not working!!! Trying to su to cbsd user switch me to the cbsd user. But trying to enter cbsdsh shell freeze my terminal.

**Comment by almmos** [comment]
More details.
This is running cbsdsh shell as root:
```
root@hoster01:/home/almmos # cbsd -o
Current option settings
errexit         on
noglob          on
ignoreeof       on
interactive     on
monitor         on
noexec          on
stdin           on
xtrace          on
verbose         on
vi              on
emacs           on
noclobber       on
allexport       on
notify          on
nounset         on
privileged      off
trapsasync      on
physical        on
trackall        on
nolog           on
pipefail        on
root@hoster01:/var/empty # version
14.1.2
root@hoster01:/var/empty # pwd
/var/empty
root@hoster01:/var/empty # exit
root@hoster01:/home/almmos #
/usr/home/almmos
root@hoster01:/home/almmos #
```
Now we try to run cbsdsh shell as cbsd user:
```
root@hoster01:/home/almmos # su cbsd
cbsd@hoster01:/home/almmos $
cbsd@hoster01:/home/almmos $ cbsd -o
```
Here I was wrong! There is no freeze.
More exactly the cbsdsh shell is entered - I don't know how to properly describe this: I have no prompt! When I have entered some common shell command they were executed, see next:
```
cbsd@hoster01:/home/almmos $ cbsd -o
pwd
/var/empty
date
Thu Oct 24 17:34:21 EEST 2024
version
14.1.2
echo "on the next line I will try to use a cbsd specific command: like help"
on the next line I will try to use a cbsd specific command: like help
help
exit
exit
cbsd@hoster01:/home/almmos $
```
As you can see, if I use simple command like: **pwd**, **date**, **echo** and so on the system return a proper answer as expected.
Even when I use a cbsd specific command like: **version** I receive the proper answer.
But when I try to invoke the cbsd help, I don't see anything. I have typed: **exit**. First time nothing is to be seen. Second time the cbsdsh shell is exited.

I have tried also to run **jstart** command in the same condition and to check (using another connection) if this command is really executed somewhere in the background, but the related jail container is not started at all:
```
cbsd@hoster01:/home/almmos $ cbsd
version
14.1.2
carbon
carbon: not found
jstart cell2
exit
exit
cbsd@hoster01:/home/zillo $
```

As you can see from previous code, I have tried to use a non-existing command. I have used the word **carbon**. The cbsdsh shell returns a proper message regarding not finding the **carbon** command.
As we can see from my previous examples, the main function of cbsdsh shell is executed (the chdir is executed) and I suppose that the [cmdloop](https://github.com/cbsd/cbsd/blob/901259ae0d2724ecf756ba365f5715d41e1c35bf/bin/cbsdsh/main.c#L286) is entered and also can be exited by using **exit** builtin.

As for now I will need some help or direction and also I will really appreciate if somebody can confirm or infirm if this is happening on others system or is specific for my systems and my configs.

@olevole I will really appreciate your input, if you can find some time to take a look on this.

**Comment by olevole** [comment]
Thanks for the details. I haven't had time to check this one yet because I'm on vacation now. I'll definitely do it next week!

**Comment by olevole** [comment]
@almmos I think I found the source of the problem thanks to you. Apparently, https://github.com/cbsd/cbsd/blob/develop/bin/cbsdsh/input.c#L361  too silent when can't open file ( the problem starts with this line: https://github.com/cbsd/cbsd/blob/develop/bin/cbsdsh/main.c#L217 )

Problems opening this file: ~cbsd/nc.inventory which has 0400 permission. I don't think I did that that long ago.

May I ask you to change (temporary) perms for ~cbsd/nc.inventory and then check the execution of cbsd from the cbsd user? This problem does not apply to `rexe`:

e.g.:
```
chmod ~cbsd/nc.inventory
su - cbsd
cbsd
```

Please note that `cbsd initenv` will restore the original (bad) permission.

**Comment by olevole** [comment]
@almmos I suppose if you perform
```
chmod 0444 ~cbsd/nc.inventory
```

on remote host,  `cbsd rexe node=REMOTEHOST tryoffline=1 date` will work correctly.

**Comment by olevole** [comment]
Fix in /usr/local/local/cbsd/sudoexec/initenv - https://github.com/cbsd/cbsd/blob/develop/sudoexec/initenv#L920:
```
-- 	${CHMOD_CMD} 0660 ${dbdir}/inv.${nodename}.sqlite && ${CHOWN_CMD} ${cbsduser}:${cbsduser} ${dbdir}/inv.${nodename}.sqlite
++ 	${CHMOD_CMD} 0660 ${dbdir}/inv.${nodename}.sqlite ${workdir}/nc.inventory && ${CHOWN_CMD} ${cbsduser}:${cbsduser} ${dbdir}/inv.${nodename}.sqlite ${workdir}/nc.inventory
```

**Comment by almmos** [comment]
I can confirm that now it's working as expected for me. Thanks @olevole

**Comment by almmos** [comment]
@olevole Please take a look at this direct related issue:
```
hoster01:/home/almmos# ls -la ~cbsd/nc.inventory
-r--r--r--  1 root wheel 1355 Oct 25 13:00 /opt/jails/nc.inventory
hoster01:/home/almmos# service cbsdd restart
Starting cbsdd.
hoster01:/home/almmos# ls -la ~cbsd/nc.inventory
-rw-------  1 root wheel 1355 Oct 25 13:02 /opt/jails/nc.inventory
```
As you can see, if I restart cbsdd service, the mode related settings for nc.inventory file are reset to the wrong ones.
This is for restart service command, but I suppose that if this is fixed, it will fix the start command also - I think is the same place into code where this file settings is set (revert) to the faulty ones.
I think that this will also need your attention. 

Thank you very much for your support!

**Comment by mergar** [comment]
https://github.com/cbsd/cbsd/commit/007ddb5313aebd13a64d911def56661f52759185

Also relevant

**Comment by almmos** [comment]
You are right @mergar.

I have just set the proper mode for the file.
I didn't applied the patch on my system.

If I apply the patch the start and restart command for cbsdd service no longer revert the mode settings for nc.inventory file.

I will let this issue open for one more day, for a little more time for testing.
Thanks!
