### ISSUE TITLE
Need another pf.conf include

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#787]
The current `~cbsd/etc/pf.conf` permits to include custom pf rules using `~cbsd/etc/pfcustom.conf` (that's cool).
The problem is that this include is placed _BEFORE_ all NAT and REDIRECT rules managed by CBSD. So, trying to include any custom filter rule in `~cbsd/etc/pfcustom.conf` produces an error as follows:
`/jails/cbsd/etc/pfnat.conf:2: Rules must be in order: options, ethernet, normalization, queueing, translation, filtering`

So, I propose to add another include _AFTER_ all NAT rules managed by CBSD. Something like
`include "/jails/cbsd/etc/pfcustomflt.conf"`

Another suggestion is to add a symlink `/etc/pf.conf` to `~cbsd/etc/pf.conf` so all pf rules could be reloaded by simple
`service pf onereload`

The both proposed improvements are tested on my product server.

**Comment by olevole** [comment]
added with [this](https://github.com/cbsd/cbsd/commit/5ff227ca4ad1880f8ad2831ae7ae9d57626fcc19) commit
