### ISSUE TITLE
feature request: option for disable automatic bridging bhyve VMs

### ISSUE THREAD

**Issue by cleverfox** [cbsd/cbsd#97]
It would be great to have option for disable automatic TAP bridging for bhyve VMs.

**Comment by olevole** [comment]
Done in 11.0.4-rel: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213625

Keep in mind: at the moment, this options available only from
~~~
cbsd bconfig
~~~
menu ( not on bconstruct-tui stage - you need create VM first, than reconfigure network ):

**cbsd bconfig** ->
**bhyvenic** ->
**nicX** ->
**nic_parent** -> (set to disable)

Also, you can specify IP4/6 address for tap interfaces (from hoster-side, not in guest) via **nic_address**

Please feedback when you test it: in my testing (too small) everything was ok.

**Comment by cleverfox** [comment]
Everythig ok. Newly created machines working good. Machines created before update - not. I manually changed schema of table in sqlite (field added), and they become ok too.
